### ISSUE TITLE
Differences from the PECL version.

### ISSUE THREAD

**Issue by heygrady** [php-amqplib/php-amqplib#100]
I'm curious on the differences between this library and the PECL extension. It seems like there's a significant API overlap between the two.

It seems like a common pattern for pure PHP libraries to provide a fallback for the compiled versions if they exist. For instance, `Zend_Json` provides their custom interface but if a native JSON extensions exists, it uses that native library under the hood to increase performance. (I know that Zend Framework is old news, and that JSON is probably a much simpler API.)

I guess I have these questions:
- Is there something wrong with the PECL version that makes a pure PHP version more compelling (beyond the obvious portability advantage of a pure PHP version)?
- Are there any important performance differences between the two?
- Is there something preventing the pure PHP version from falling back to the PECL version if it exists? It seems like a reasonable addition to support both portability and performance.

I'm in a position where I can install the PECL version (and I assume it's faster) but I'll end up having to use the pure PHP version because that is what the [Symfony Bundle](https://github.com/videlalvaro/RabbitMqBundle) uses. I'm happy to be told I missed the documentation that addresses this.

**Comment by calcinai** [comment]
Stumbled across this looking for something else, I've just made a very basic wrap of php-amqplib for an API compatible with the PECL extension ([here](/calcinai/php-amqplib-bridge)).  Do you know if there's anything else around that might be better maintained?

**Comment by videlalvaro** [comment]
@calcinai what do you mean by 'better maintained'?

**Comment by calcinai** [comment]
I'm concerned that I'm implementing something that is (probably) already done? There's not a lot of point in me doing it if something more mature is out there…

**Comment by videlalvaro** [comment]
I haven't seen a bridge for both libraries; I have seen people asking for one
