### ISSUE TITLE
Fatal error: Uncaught Error: Class "PhpAmqpLib\Exchange\AMQPExchangeType" not found 

### ISSUE THREAD

**Issue by audas** [php-amqplib/php-amqplib#1000]
**Description**  
Exchange\AMQPExchangeType did not download with composer. I am not a builder of these types of libraries - but it looks like it is not in the distribution ?

**Comment by ramunasd** [comment]
Weird, just try again.
I don't see any issues from library side. If it happens again, please report to composer maintainers.

**Comment by audas** [comment]
Had to download latest version with specific number appended to composer.

 eg 

php-amqplib/php-amqplib:3.2.0
