### ISSUE TITLE
Broken pipe or closed connection

### ISSUE THREAD

**Issue by Funny-dot** [php-amqplib/php-amqplib#1005]
Fatal error: Uncaught PhpAmqpLib\Exception\AMQPConnectionClosedException: Broken pipe or closed connection in /www/wwwroot/cbs.com/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:234

composer version:
        "php-amqplib/php-amqplib": "^3.1",

my service is localhost;

![image](https://user-images.githubusercontent.com/27287970/173759668-e9a5afc2-1025-4203-aab0-c62d88c26647.png)

my codes:
```
include_once './vendor/autoload.php';

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('localhost', '5672', 'guest', 'guest',
    '/',false,'AMQPLAIN',null,'en_US',3,3,null,true,20);
$channel = $connection->channel();

$channel->queue_declare('hello', false, false, false, false);
$channel->basic_qos(null, 10, null);
$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'hello');

echo " [x] Sent 'Hello World!'\n";

$channel->close();
$connection->close();
```

**Comment by ramunasd** [comment]
please share exception stack trace

**Comment by Funny-dot** [comment]
> 请分享异常堆栈跟踪

It has been solved. It is a rabbitmq version problem. It is normal for me to lower one version.

**Comment by Funny-dot** [comment]
> please share exception stack trace

It has been solved. It is a rabbitmq version problem. It is normal for me to lower one version.
