### ISSUE TITLE
Set the path to librabbitmq install prefix [autodetect] : 

### ISSUE THREAD

**Issue by lianhuazi** [php-amqplib/php-amqplib#1006]
**Version(s) affected**: x.y.z
 docker Debian GNU/Linux 9  php5.6
**Description**  

pecl  -d with-librabbitmq-dir="/opt/rabbitmq-c-0.11.0/_install" install  amqp

root@95a02b74e90b:/var/www/html# pecl  -d with-librabbitmq-dir="/opt/rabbitmq-c-0.11.0/_install" install amqp
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading amqp-1.11.0.tgz ...
Starting to download amqp-1.11.0.tgz (108,493 bytes)
.........................done: 108,493 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Set the path to librabbitmq install prefix [autodetect] : 

why? pecl -D is fail?

**Comment by ramunasd** [comment]
wrong repo, you should ask at https://github.com/php-amqp/php-amqp
