### ISSUE TITLE
Sockets extension is not enabled 

### ISSUE THREAD

**Issue by des1roer** [php-amqplib/php-amqplib#1015]
www@ef0d8432969f:/var/www/service$ ./yii queue/listen -v

PHP Warning:  Sockets extension is not enabled in /var/www/service/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/SocketConstants.php on line 34

composer.json
```
"require": {
    "php": "~7.4",
    "ext-json": "*",
    "yidas/yii2-composer-bower-skip": "~2.0.5",
    "yiisoft/yii2": "~2",
    "ext-zip": "*",
    "yiisoft/yii2-queue": "^2.3",
    "enqueue/amqp-lib": "^0.10.9"
},
```

In Dockerfile

RUN docker-php-ext-install sockets

![image](https://user-images.githubusercontent.com/10970793/182765466-ea305b4c-7a08-428f-bf93-0625f7ba311d.png)

**Comment by ramunasd** [comment]
ext-sockets is within composer requirements, it's your responsibility to enable it
