### ISSUE TITLE
v3.3.0 heartbeat error

### ISSUE THREAD

**Issue by tlamy** [php-amqplib/php-amqplib#1029]
**Version(s) affected**: 3.3.0

**Description**  
After upgrading from 3.2.0 to 3.3.0 our consumers die on a regular basis. From our logs:
```
2022-10-04 10:27:45.588+0000➜{"name":"PhpAmqpLib\\Exception\\AMQPConnectionClosedException: Broken pipe or closed connection"}

2022-10-04 12:27:45 | missed heartbeats from client, timeout: 60s
2022-10-04 12:27:45 | 2022-10-04 10:27:45.587 [error] <0.14529.62> closing AMQP connection <0.14529.62> (10.42.5.160:56444 -> 10.42.8.124:5672):
```
(The first log line is from our PHP consumer, the latter ones from rabbitmq running with +02:00 timezone offset).

Connections are created using `$heartbeat` parameter set to 0, which worked properly with v3.2.0.

So it seems to me the client can no longer disable heartbeats by setting the parameter to 0?

**Comment by tlamy** [comment]
I even tried with $heartbeat set to 300 (since I may have really long consuming time for a message), and the server still closed the connection after 60 seconds.

I had to roll back to php-amqplib v3.2.0.

Version info:
RabbitMQ 3.8.16 on Erlang 23.3.4.1
PHP 8.0.24 (cli) (built: Sep 30 2022 23:48:52) ( NTS )

**Comment by dominicchinkh** [comment]
Hi @tlamy, the $heartbeat of 300 is really 300 microseconds.

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AbstractConnection.php#L672

**Comment by tlamy** [comment]
@dominicchinkh microtime(true) isn't microseconds.

> microtime(true) returns a float, which represents the current time in seconds since the Unix epoch accurate to the nearest microsecond.

**Comment by dominicchinkh** [comment]
> @dominicchinkh microtime(true) isn't microseconds.
> 
> > microtime(true) returns a float, which represents the current time in seconds since the Unix epoch accurate to the nearest microsecond.

@tlamy, you are right. I miss the PHP doc.
