### ISSUE TITLE
SIGUSR1 used instead of \SIGUSR1

### ISSUE THREAD

**Issue by OliverEspeter** [php-amqplib/php-amqplib#1038]
**Version(s) affected**: 3.4.0

**Description**  
The SIGHeartbeatSender is using `SIGUSR1`, what triggers the STRICT Policies of PHP:
"Use of undefined constant SIGUSR1 - assumed 'SIGUSR1' (this will throw an Error in a future version of PHP)"

**How to reproduce**  
Turn PHP to strict mode or catch strict warnings.

**Possible Solution**  
Use `\SIGUSR1` instead

**Additional context**

**Comment by ramunasd** [comment]
What is OS and PHP version?

**Comment by OliverEspeter** [comment]
Sorry...


root@28a026887323:/var/www# php -v
**PHP 7.2.24**-0ubuntu0.18.04.13 (cli) (built: Jul  6 2022 12:23:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.13, Copyright (c) 1999-2018, by Zend Technologies
root@28a026887323:/var/www# cat /etc/lsb-release 
**DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04**
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
root@28a026887323:/var/www#

**Comment by ramunasd** [comment]
SIGUSR1 constant is defined in pcntl extension. Have You enabled it?

All supported php versions has this constant, 7.2.24 as well:
https://github.com/php/php-src/blob/php-7.2.24/ext/pcntl/pcntl.c#L275
https://github.com/php/php-src/blob/php-7.3.33/ext/pcntl/pcntl.c#L273
https://github.com/php/php-src/blob/php-7.4.32/ext/pcntl/pcntl.c#L288
https://github.com/php/php-src/blob/php-8.0.25/ext/pcntl/pcntl.c#L125
https://github.com/php/php-src/blob/php-8.1.12/ext/pcntl/pcntl.c#L122

**Comment by OliverEspeter** [comment]
pcntl is enabled.

```
root@02bf1f87e800:/var/www# php -m
[PHP Modules]
amqp
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

root@02bf1f87e800:/var/www# 
```
