### ISSUE TITLE
amqplib connect mq error

### ISSUE THREAD

**Issue by wangziwen0216** [php-amqplib/php-amqplib#1040]
山鬼
16:14 (1小时前) 
收件人 rabbitmq-users
When i use amqplib to connect rabbitmq server,after a few while,the process is sleeping.
when i use strace -p pid , here is the information.
select(27, [26], [], [], NULL)          = 1 (in [26])

rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0

rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0

close(26)                               = 0

socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 26

fcntl(26, F_GETFL)                      = 0x2 (flags O_RDWR)

fcntl(26, F_SETFL, O_RDWR|O_NONBLOCK)   = 0

connect(26, {sa_family=AF_INET, sin_port=htons(PORT), sin_addr=inet_addr("IP")}, 16) = -1 EINPROGRESS (Operation now in progress)

poll([{fd=26, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 3000) = 1 ([{fd=26, revents=POLLOUT}])

getsockopt(26, SOL_SOCKET, SO_ERROR, [0], [4]) = 0

fcntl(26, F_SETFL, O_RDWR)              = 0

getpeername(26, {sa_family=AF_INET, sin_port=htons(PORT), sin_addr=inet_addr("IP")}, [128->16]) = 0

fcntl(26, F_GETFL)                      = 0x2 (flags O_RDWR)

fcntl(26, F_SETFL, O_RDWR|O_NONBLOCK)   = 0

getsockname(26, {sa_family=AF_INET, sin_port=htons(22714), sin_addr=inet_addr("IP")}, [128->16]) = 0

fcntl(26, F_GETFL)                      = 0x802 (flags O_RDWR|O_NONBLOCK)

setsockopt(26, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0

poll([{fd=26, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)

recvfrom(26, 0x562b5c370ad8, 7, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

any help is thankful!

**Comment by ramunasd** [comment]
More helpful would be debug output. Please define AMQP_DEBUG and then post output here. We cannot tell anything from stack trace.
