### ISSUE TITLE
Uncaught ErrorException: stream_socket_client(): unable to connect to ssl (Connection refused)

### ISSUE THREAD

**Issue by vol4ikman** [php-amqplib/php-amqplib#1044]
**composer:**
`{
    "require": {
        "php-amqplib/php-amqplib": "^2.8"
    }
}
`

**code:**
`define('CERTS_PATH', realpath(__DIR__ . '/lib/'));

	$ssl_opts = array(
		'cafile' 			=> CERTS_PATH . '/ca-cert.pem',
		'local_cert' 		=> CERTS_PATH . '/client-cert.pem',
		'local_pk' 			=> CERTS_PATH . '/client-key.pem',
		'verify_peer' 		=> true,
		'verify_peer_name' 	=> false,
	);

	require_once __DIR__ . '/lib/vendor/autoload.php';
	require('lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php');
	require('lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPSSLConnection.php');
	require('lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Message/AMQPMessage.php');
	
	$host        = ''; // ip goes here
	$user        = 'usesrname';
	$password    = 'password';
	$port        = 12021; // secured
       $connection   = new PhpAmqpLib\Connection\AMQPSSLConnection( $host, $port = 12021, $user, $password, $vhost = '/', $ssl_opts);
	var_dump($connection);
	die();
`

What am I missing?

thanks

**Comment by ramunasd** [comment]
Not enough info. Very likely connection params are wrong. Please enable debug mode and then try again.

**Comment by vol4ikman** [comment]
the full debug is

`<b>Fatal error</b>:  Uncaught ErrorException: stream_socket_client(): unable to connect to ssl://40.115.8.126:12021 (Connection refused) in /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:142
Stack trace:
#0 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(144): PhpAmqpLib\Wire\IO\StreamIO-&gt;cleanup_error_handler()
#1 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(208): PhpAmqpLib\Wire\IO\StreamIO-&gt;connect()
#2 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(192): PhpAmqpLib\Connection\AbstractConnection-&gt;connect()
#3 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(51): PhpAmqpLib\Connection\AbstractConnection-&gt;__construct('dooble_webporta...', 'AQpRpDKZdZ6BE8M', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0, 3)
#4 /home/solegre in <b>/home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php</b> on line <b>142</b><br />
`

**Comment by vol4ikman** [comment]
Connections params  is fine, because if I run it from PowerShell I do have a connection

**Comment by vol4ikman** [comment]
I do not understand why my issue was closed....

**Comment by ramunasd** [comment]
This issue was closed because there is no proof that something is wrong with library.
From Your stack trace we see error message "ssl://40.115.8.126:12021 (Connection refused)". It means PHP tried to open connection, but it failed.

 >   because if I run it from PowerShell I do have a connection

context is very important for SSL connections and obviously it is different in your shell
