### ISSUE TITLE
PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'request-queue' in vhost '/': received 'true' but current is 'false' in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:188

### ISSUE THREAD

**Issue by vol4ikman** [php-amqplib/php-amqplib#1046]
The error:
`<b>Fatal error</b>:  Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'request-queue' in vhost '/': received 'true' but current is 'false' in /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:188
Stack trace:
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel-&gt;channel_close()
#1 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(209): call_user_func()
#2 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(351): PhpAmqpLib\Channel\AbstractChannel-&gt;dispatch()
#3 /home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(652): PhpAmqpLib\Channel\AbstractChannel-&gt;wait()
#4 /home/solegreen/public_html/ajax.php(36): PhpAmqpLib\Channel\AMQPChannel-&gt;queue_declare()
#5 {main}
  thrown in <b>/home/solegreen/public_html/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php</b> on line <b>188</b><br />`

**Comment by vol4ikman** [comment]
the code:
`$connection   = new PhpAmqpLib\Connection\AMQPSSLConnection( $host, $port, $user, $password, $vhost = '/', $ssl_opts);
$channel = $connection->channel();
$channel->queue_declare('request-queue', false, true, false, false);
$message_content = '{"meter_id": "XXXXX","from": "2022-08-01T21:00:00Z","to": "2022-08-02T05:15:00Z"}';
$msg = new PhpAmqpLib\Message\AMQPMessage($message_content);
$channel->basic_publish($msg, '', 'request-queue');
$channel->close();
$connection->close();
`

**Comment by ramunasd** [comment]
You have created queue with param `durable` false some time ago. Now the same action but with different param `durable` cannot be processed. It is not allowed to change queue params. Please read error message carefully.
Closing as this is usage rather than library issue.
