### ISSUE TITLE
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE

### ISSUE THREAD

**Issue by ceresaconsultoria** [php-amqplib/php-amqplib#1053]
**Version(s) affected**: 3.10.7

**Description**  
AMQP Runtime exception stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 1046.  --enable-fd-setsize=2048 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date

**How to reproduce**  
Client PHP using Connection Recovery Cconsume example
https://github.com/php-amqplib/php-amqplib/blob/master/demo/connection_recovery_consume.php

**Possible Solution**  
first try to understand what the problem is 

**Additional context**  
Log

AMQP Runtime exception stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 1046.  --enable-fd-setsize=2048 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date.

**Comment by lukebakken** [comment]
https://github.com/php-amqplib/php-amqplib/search?q=FD_SETSIZE&type=issues

This has come up before, and is environment specific. I don't think there is much we can do about it. @ramunasd ?

**Comment by ramunasd** [comment]
@ceresaconsultoria Can You provide more info about PHP environment? Also, I see **Version affected** is not valid, we don't have version 3.10.7 :)
So in short, what we need - output of tests/phpinfo.php, PHP package source, whole script how to reproduce this issue.

**Comment by ceresaconsultoria** [comment]
PHP Version 7.4.22

System | Linux 64c431b0efb4 5.15.0-1023-aws #27~20.04.1-Ubuntu SMP Wed Oct 26 20:02:26 UTC 2022 x86_64
-- | --
Build Date | Aug 17 2021 13:13:00
Configure Command | './configure' '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pear' '--with-libdir=lib/x86_64-linux-gnu' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-gnu'
Server API | FPM/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /usr/local/etc/php
Loaded Configuration File | (none)
Scan this dir for additional .ini files | /usr/local/etc/php/conf.d
Additional .ini files parsed | /usr/local/etc/php/conf.d/devilbox-runtime-sendmail.ini, /usr/local/etc/php/conf.d/devilbox-runtime-timezone.ini, /usr/local/etc/php/conf.d/docker-php-ext-amqp.ini, /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini, /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini, /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini, /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini, /usr/local/etc/php/conf.d/docker-php-ext-dba.ini, /usr/local/etc/php/conf.d/docker-php-ext-enchant.ini, /usr/local/etc/php/conf.d/docker-php-ext-exif.ini, /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini, /usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini, /usr/local/etc/php/conf.d/docker-php-ext-gmp.ini, /usr/local/etc/php/conf.d/docker-php-ext-igbinary.ini, /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini, /usr/local/etc/php/conf.d/docker-php-ext-imap.ini, /usr/local/etc/php/conf.d/docker-php-ext-intl.ini, /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini, /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini, /usr/local/etc/php/conf.d/docker-php-ext-memcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini, /usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini, /usr/local/etc/php/conf.d/docker-php-ext-msgpack.ini, /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini, /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini, /usr/local/etc/php/conf.d/docker-php-ext-oci8.ini, /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_dblib.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_firebird.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_oci.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_sqlsrv.ini, /usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pspell.ini, /usr/local/etc/php/conf.d/docker-php-ext-rdkafka.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-shmop.ini, /usr/local/etc/php/conf.d/docker-php-ext-snmp.ini, /usr/local/etc/php/conf.d/docker-php-ext-soap.ini, /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini, /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini, /usr/local/etc/php/conf.d/docker-php-ext-solr.ini, /usr/local/etc/php/conf.d/docker-php-ext-sqlsrv.ini, /usr/local/etc/php/conf.d/docker-php-ext-ssh2.ini, /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvmsg.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvsem.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvshm.ini, /usr/local/etc/php/conf.d/docker-php-ext-tidy.ini, /usr/local/etc/php/conf.d/docker-php-ext-uploadprogress.ini, /usr/local/etc/php/conf.d/docker-php-ext-vips.ini, /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini, /usr/local/etc/php/conf.d/docker-php-ext-xlswriter.ini, /usr/local/etc/php/conf.d/docker-php-ext-xmlrpc.ini, /usr/local/etc/php/conf.d/docker-php-ext-xsl.ini, /usr/local/etc/php/conf.d/docker-php-ext-yaml.ini, /usr/local/etc/php/conf.d/docker-php-ext-zip.ini, /usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini, /usr/local/etc/php/conf.d/zzz-entrypoint-logfiles.ini
PHP API | 20190902
PHP Extension | 20190902
Zend Extension | 320190902
Zend Extension Build | API320190902,NTS
PHP Extension Build | API20190902,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, sqlsrv, ssh2.shell, ssh2.exec, ssh2.tunnel, ssh2.scp, ssh2.sftp, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters | zlib.*, convert.iconv.*, bzip2.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*


<h2 style="font-size: 20px; color: rgb(34, 34, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a name="module_amqp">amqp</a></h2>

Version | 1.10.2
-- | --

Configuration
amqp
Version	1.10.2
Revision	release
Compiled	Aug 18 2021 @ 01:05:30
AMQP protocol version	0-9-1
librabbitmq version	0.9.0
Default max channels per connection	256
Default max frame size	131072
Default heartbeats interval	0

amqp.auto_ack	0	0
amqp.cacert	no value	no value
amqp.cert	no value	no value
amqp.channel_max	256	256
amqp.connect_timeout	0	0
amqp.frame_max	131072	131072
amqp.global_prefetch_count	0	0
amqp.global_prefetch_size	0	0
amqp.heartbeat	0	0
amqp.host	localhost	localhost
amqp.key	no value	no value
amqp.login	guest	guest
amqp.password	guest	guest
amqp.port	5672	5672
amqp.prefetch_count	3	3
amqp.prefetch_size	0	0
amqp.read_timeout	0	0
amqp.rpc_timeout	0	0
amqp.sasl_method	0	0
amqp.timeout	no value	no value
amqp.verify	1	1
amqp.vhost	/	/
amqp.write_timeout	0	0

**Comment by ramunasd** [comment]
Thanks @ceresaconsultoria . The scripts You have provided is not usable. Missing config, some classes, unclear dependencies. You must minimize everything down to simple consumer, without any unrelated stuff.

BTW, Still missing info - library version and output of `tests/phpinfo.php`

Ideally we would like to get fullly working docker container(or compose) which always reproduce issue without additional efforts.

**Comment by agrobens** [comment]
each consumer runs in a container

I create with this command

docker run --restart always -d -v /home:/home --name {container name} devilbox/php-fpm:7.4-prod sh -c "/usr/local/bin/php {script path}"

"library version and output of tests/phpinfo.php"
> version of what exactly do you need?

**Comment by ceresaconsultoria** [comment]
each consumer runs in a container

I create with this command

docker run --restart always -d -v /home:/home --name {container name} devilbox/php-fpm:7.4-prod sh -c "/usr/local/bin/php {script path}"

> "library version and output of tests/phpinfo.php"
version of what exactly do you need?

**Comment by ceresaconsultoria** [comment]
problem seems to happen when consumer connects with rabbitmq to send data to another queue

I put a logger to see where it was giving error and check it out

in the code block that sends data to another queue is where the error pops

![image](https://user-images.githubusercontent.com/56128744/212754701-00acff45-a59c-46cd-82f8-ba87c82c0e18.png)

```php

//--

if($liProductDetails["tipo"] == 'atributo'){

    if($action->forceUpdateVariants){                
        CLI::write("-> Enviando ".count($liProductDetails["filhos"])." filhos para atualização");
        $logger->info("-> Enviando ".count($liProductDetails["filhos"])." filhos para atualização");
        
         //conect other queue, here get error
        $rabbitController->connectChannel('mdLojaIntegradaUpdateVariants');

        foreach($liProductDetails["filhos"] as $filho){
            $filhoIdArr = explode('/', $filho);
            $filhoId = end($filhoIdArr);
            
            //send message to queue
            $rabbitController->sameConnSendToQueue([
                "counter" => 1,
                "storeId" => $action->storeId,
                "inactiveItensZeroStock" => true,
                "flagSomenteValidos" => true,
                "variantId" => $filhoId
            ]);
        } 

        $rabbitController->closeChannel();
    }
}

```

**Comment by ramunasd** [comment]
I see error occurs when script tries to open a new connection. I guess Your script creates separate connection for each queue? If yes, then it's just a matter of time when PHP process reaches file descriptor(FD) or, in other words, connection limit.

You cannot keep unlimited amount of opened connections. There is always a limit, in Your case it's 1024.

So this is your application/setup issue. The library itself works fine.
If You need more help - use [discussions](https://github.com/php-amqplib/php-amqplib/discussions) or [dev group](https://groups.google.com/g/php-amqplib-devel).
