### ISSUE TITLE
Tests fail on PHP8.1

### ISSUE THREAD

**Issue by janmyszkier** [php-amqplib/php-amqplib#1055]
**Version(s) affected**: 3.4.0

**Description**  
The library does not support php 8.1 which is the oldest actively supported version at https://www.php.net/supported-versions.php

**How to reproduce**  

1. Run
```
git clone git@github.com:php-amqplib/php-amqplib.git
```

2. Edit `docker/php/Dockerfile` and change 
```
FROM php:7.1-cli
```
to
```
FROM php:8.1-cli
```

3. Run
```
docker-compose build
docker-compose up -d
docker-compose exec php php -v
docker-compose exec php composer install
docker-compose exec php php vendor/bin/phpunit
```

Output:
```
(...)
ERRORS!
Tests: 833, Assertions: 831, Errors: 73, Failures: 5, Skipped: 3.
```

**Possible Solution**  
Update tests / code to work with the docker image based on php8.1. Also make the docker image to use php8.1 by default.

**Additional context**  
none

**Comment by lukebakken** [comment]
We would welcome a PR to accomplish this. Thanks!

**Comment by ramunasd** [comment]
We support PHP8.1, for sure. There was discussions and fixes regarding it. We run automated tests using [github actions](https://github.com/php-amqplib/php-amqplib/actions/runs/3703508310/jobs/6275043656)

Moreover, I'm personally use docker for tests on different PHP versions and OS.

So I'm closing this while exact errors are unknown.

**Comment by janmyszkier** [comment]
@ramunasd What do you expect me to do here? create separate  73 issues about each error I get? I think it would be more reasonable to ask me to update the issue with more details than closing the issue. 
This isn't fixed, so shouldn't be closed.

**Comment by ramunasd** [comment]
@janmyszkier at least one error message with stack trace would be sufficient

**Comment by ramunasd** [comment]
BTW, You should run `docker-compose exec php composer update` instead of `docker-compose exec php composer install`
The difference here is that `install` does nothing if vendor packages were installed before, using another PHP version.
