### ISSUE TITLE
Does not pass `$config` parameter to AMQPSocketConnection using `AMQPConnectionFactory::create`

### ISSUE THREAD

**Issue by ssi-anik** [php-amqplib/php-amqplib#1076]
Other `Amqp*Connection` classes are being constructed with `$config` parameter passed down to the class. It's missing for `AMQPSocketConnection` class.

https://github.com/php-amqplib/php-amqplib/blob/5251da370b386d9822726aea97eafc17c95237f9/PhpAmqpLib/Connection/AMQPConnectionFactory.php#L76-L77

**Comment by ramunasd** [comment]
fixed in #1077

**Comment by ssi-anik** [comment]
@ramunasd any tentative timeline for the release of v3.5.2?
