### ISSUE TITLE
Newest version caused symfony/amqp-messenger amqp connection not working properly

### ISSUE THREAD

**Issue by miloszowi** [php-amqplib/php-amqplib#1111]
**Version(s) affected**: 2.0.0

**Description**  
Seems like the newest version of php-amqlip is causing connection to return null instead of bool upon ack in symfony messanger.
```
TypeError: Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned
```

**How to reproduce**  
- plain symfony app using symfony/amqp-messenger
- add simple message consuming
- try to consume (to trigger amqp connection) some message

**Possible Solution**  

**Additional context**

**Comment by ramunasd** [comment]
wrong repo, symfony transport use amqp extension - https://github.com/php-amqp/php-amqp
