### ISSUE TITLE
Wrong thrown `AMQPTimeoutException`-exception for heartbeat

### ISSUE THREAD

**Issue by BOPOH** [php-amqplib/php-amqplib#1118]
**Version(s) affected**: 3.5.4

**Description**  
Heartbeat sender combined with `$channel->wait_for_pending_acks(10);` after the sending is cause of `PhpAmqpLib\Exception\AMQPTimeoutException` exception with message `The connection timed out after 10 sec while awaiting incoming data` while the real time is around 0 seconds   
i.e. problem here is either a wrong error text or an unnecessary exception

**How to reproduce**  
Code to reproduce: [gist](https://gist.github.com/BOPOH/997b3b84a26414dc1d5f0f2db64ca187) - adapted version of https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher_with_confirms.php. Changed lines: 4, 12-19, 63, 66

**Additional context**  
PHP 8.2.9

**Comment by BOPOH** [comment]
related to the #1094:
- heartbeat signal interrupts the stream_select ([result is zero](https://github.com/php-amqplib/php-amqplib/blob/v3.5.4/PhpAmqpLib/Wire/IO/AbstractIO.php#L105))
- timeout is non-zero, so [$reader->wait() throws the exception](https://github.com/php-amqplib/php-amqplib/blob/v3.5.4/PhpAmqpLib/Wire/AMQPIOReader.php#L102)

**Comment by BOPOH** [comment]
Also, as far as I understood, it's a reason of SegFault (see #415 - yes, it's not fixed):
- enable heartbeat
- reconnect
- heartbeat signal occurs on the previous connection
- segfault

I'm not sure about the steps to reproduce, but we caught it several times when tried to reproduce the bug from the task

**Comment by ramunasd** [comment]
I think 2 seconds heartbeat is too low 🤔  Is there any real use case for a such low heartbeat intervals?

Can You reproduce the same when heartbeats aren't so frequent?

**Comment by lukebakken** [comment]
Team RabbitMQ _never_ recommends such a low heartbeat value - https://www.rabbitmq.com/heartbeats.html

10 seconds should be considered the minimum.

**Comment by BOPOH** [comment]
2 seconds is only to faster reproduce, real value is 1 minute. And yes, the same example reproduces the error even with the 1-minute timeout. But in this case you have to wait 30 seconds instead of 1 second.

**Comment by mruell** [comment]
Since we are facing the same issue I did a fix inspired by enqueues Socket Helper: https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-tools/SignalSocketHelper.php

**Comment by ramunasd** [comment]
@BOPOH can You test latest master?
