### ISSUE TITLE
ssl_protocol == null return $ssl_protocol parameter is deprecated

### ISSUE THREAD

**Issue by duhon** [php-amqplib/php-amqplib#1143]
When I try to create an object for the local server I get an error "$ssl_protocol parameter is deprecated...". Is this expected behavior? In many frameworks, such an error turns into exceptions, which prevents me create a connection to queue
```
$d = new \PhpAmqpLib\Connection\AMQPStreamConnection(
        'localhost',
        5672,
        'guest',
        'guest',
        '/',
        false,
        'AMQPLAIN',
        null,
        'en_US',
        3.0,
        3.0,
        null,
        false,
        0,
        0.0,
        null,
        null
    );
```
Version(s) affected: 3.6.0

**Comment by acelaya** [comment]
You can work around this by passing one less parameter. The intention of this deprecation warning is to announce the `ssl_protocol` parameter is deprecated, which is the penultimate one.

Since you are passing defaults anyway, you should be fine with this:

```php
$d = new \PhpAmqpLib\Connection\AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest',
    '/',
    false,
    'AMQPLAIN',
    null,
    'en_US',
    3.0,
    3.0,
    null,
    false,
    0,
    0.0,
    null,
    // null <- Get rid of this one and you won't get this deprecation warning
);
