### ISSUE TITLE
Connection option close_on_destruct doesn't work because of circular reference

### ISSUE THREAD

**Issue by Sn0wFox** [php-amqplib/php-amqplib#1144]
**Version(s) affected**: [3.5.4](https://github.com/php-amqplib/php-amqplib/releases/tag/v3.5.4), [3.6.0](https://github.com/php-amqplib/php-amqplib/releases/tag/v3.6.0) (and probably earlier as well)

**Description**  
`AbstractConnection` provides a way to close the amqp connection when the connection object is destroyed, namely `$close_on_destruct`.

However once the connection object has been used to connect, there is a circular reference preventing the destructor from running so the the underlying connection is not released until the php process dies (or until closed explicitly). This circular reference seems to come from [AbstractConnection.php#L257](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AbstractConnection.php#L257), where the `connect()` method does this:

```php
parent::__construct($this, 0);
```

**How to reproduce**  
Here is a minimal example showing the problem:

```php
class DemoCo extends \PhpAmqpLib\Connection\AbstractConnection {
    public function __construct()
    {
        // simulate the connect() method without the whole stuff
        \PhpAmqpLib\Channel\AbstractChannel::__construct($this, 0);
    }

    public function __destruct()
    {
        echo 'Destructing ' . self::class . PHP_EOL;
        parent::__destruct();
    }
}

$c = new DemoCo();
$c = null;
```

You will notice that the destructor log never shows up. If you comment out the `\PhpAmqpLib\Channel\AbstractChannel::__construct($this, 0);` bit in the constructor however, it will.

**Possible Solution**  

Can't think of one atm.

**Additional context**  

We first noticed this in a laravel worker, where a service performing some amqp stuff was registered as [a scoped singleton](https://laravel.com/docs/10.x/container#binding-scoped) instead of [a regular one](https://laravel.com/docs/10.x/container#binding-a-singleton).

The service was destructed after every job but its amqp connection wasn't, so we effectively reached the maximum connection on our test rabbit cluster until the worker was restarted.

This could become a pretty big issue pretty quick in some setups relying on `$close_on_destruct`, like with swoole or that kind of things where the php process doesn't die after each request.

**Comment by ramunasd** [comment]
That's not neccessary a bug. What if we change last lines of Your demo in this way:

```
$channel = (new DemoCo())->channel();
$channel->consume();
```

So channel object will keep reference to connection - it's absolutelly neccessary for operation, and destructor won't be called, even if You don't have variable for connection object.

We don't have automatic detection whether connection or channel object has references in code. And even if we would, then You would need to make sure that Your code does not left or leaked them somewhere.

I think easier and reliable way is just call `$connection->close();` and unset references afterwards. Simple and effective.

Always call `close()` if You don't need connection anymore!
