### ISSUE TITLE
Lazy stream connection leaks stream context resource causing file descriptor limit hit (FD_SETSIZE)

### ISSUE THREAD

**Issue by janedbal** [php-amqplib/php-amqplib#1152]
**Version(s) affected**: 
- 3.6.0

**Description**  
We are facing file descriptor limit hit in our CI causing failure in stream_select. This [has been reported multiple times](https://github.com/php-amqplib/php-amqplib/issues?q=is%3Aissue+is%3Aclosed+FD_SETSIZE). We found that the leaking descriptor is the stream-context used in [StreamIO::$context](https://github.com/php-amqplib/php-amqplib/blob/abee57c/PhpAmqpLib/Wire/IO/StreamIO.php#L16) when lazy connection is used. The context is created in constructor no matter if connection was lazy or not. And closing the connection does not help as `connection->close()` does not clear this context in such case.

The error is:
```
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1029.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
```

**How to reproduce**  

Fully reproduced in following PR:
- #1150

**Possible Solution**  

Fixed in following PR:
- #1151

**Comment by lukebakken** [comment]
Thank you for taking the time to investigate and fix this issue!

**Comment by ramunasd** [comment]
Issue was in another library, more info in PR comments
https://github.com/php-amqplib/php-amqplib/pull/1154#issuecomment-1905904826
