### ISSUE TITLE
 stream_set_blocking(): Argument #2 ($enable) must be of type bool, int given

### ISSUE THREAD

**Issue by sidigi** [php-amqplib/php-amqplib#1155]
**Version(s) affected**: 3.6.0

**Description**
Error in   

```
vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:142

▕         if ($this->canDispatchPcntlSignal) {
  ➜ 142▕             stream_set_blocking($this->sock, 0);
    143▕             stream_set_write_buffer($this->sock, 0);
    144▕             if (function_exists('stream_set_read_buffer')) {
    145▕                 stream_set_read_buffer($this->sock, 0);
    146▕             }
```

because of second parameter must be bool

```
function stream_set_blocking($stream, bool $enable): bool
{
}
```

**How to reproduce**  

```
<?php

declare(strict_types=1);

new AMQPStreamConnection(
                'localhost',
                5672,
                'guest',
                'guest'
            )
```

**Possible Solution**  

stream_set_blocking($this->sock, 0)
change to 
stream_set_blocking($this->sock, false)

**Additional context**

**Comment by ramunasd** [comment]
Thanks for pointing this out. Actually, this library is very old and was loose typed since first days. We can adjust some places but in overall we cannot promise strict typing. So please do not expect that.

BTW, which PHP version is this?

**Comment by sidigi** [comment]
PHP 8.2.14

**Comment by sidigi** [comment]
BTW It is only one place break the flow, after changes in vendor folder everything works fine
