### ISSUE TITLE
 DateTime::createFromFormat(): Argument #2 ($datetime) must be of type string, int given

### ISSUE THREAD

**Issue by sidigi** [php-amqplib/php-amqplib#1157]
**Version(s) affected**: 3.6.0
![Снимок экрана от 2024-02-05 14-55-45](https://github.com/php-amqplib/php-amqplib/assets/1765748/207dbb86-b05f-4834-be07-ddbd9d1a069b)

**Description**  
 DateTime::createFromFormat(): Argument #2 ($datetime) must be of type string, int given
vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPAbstractCollection.php:308

**How to reproduce**  
consume message from delayed queue

**Possible Solution**  
strict types:(

 $val = DateTime::createFromFormat('U', (string) $val);

**Additional context**

**Comment by ramunasd** [comment]
Which PHP version do You use?
Usually type casting is done automatically and we don't have strict type declaration in this library.
