### ISSUE TITLE
Warning: fwrite() expects parameter 1 to be resource, null given

### ISSUE THREAD

**Issue by BirknerAlex** [php-amqplib/php-amqplib#116]
Since today i've got a very strange error. We are using this lib together with Symfony 2.
This happens while opening the connection to the RabbitMQ server. This is the part of my controller:

$rabbitmqHost = $this->container->getParameter("rabbitmq_host");
$rabbitmqPort = $this->container->getParameter("rabbitmq_port");
$rabbitmqUser = $this->container->getParameter("rabbitmq_user");
$rabbitmqPassword = $this->container->getParameter("rabbitmq_password");
$rabbitmqVHost = $this->container->getParameter("rabbitmq_vhost");
$rabbitmqExchange = $this->container->getParameter("rabbitmq_exchange");

$this->conn = new AMQPConnection($rabbitmqHost, $rabbitmqPort, $rabbitmqUser, $rabbitmqPassword);
$this->vVhost = $rabbitmqVHost;
$this->exchange = $rabbitmqExchange;

The messaging works without problems. I can send und receive messages from the server, but this message appears in the error log from the webserver:

PHP Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: fwrite() expects parameter 1 to be resource, null given in PhpAmqpLib/Wire/IO/StreamIO.php line 61' in PhpAmqpLib/Wire/IO/StreamIO.php:61
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handle(2, 'fwrite() expect...', '', 61, Array)
#1 PhpAmqpLib/Wire/IO/StreamIO.php(61): fwrite(NULL, '??????????2????...')
#2 PhpAmqpLib/Connection/AbstractConnection.php(173): PhpAmqpLib\Wire\IO\StreamIO->write('??????????2????...')
#3 PhpAmqpLib/Connection/AbstractConnection.php(258): PhpAmqpLib\Connection\AbstractConnection- in PhpAmqpLib/Wire/IO/StreamIO.php on line 61

**Comment by Cyw1104** [comment]
I have the same error. Could you tell how to do the close of connections?
