### ISSUE TITLE
Connecting php-amqplib to rmohr/activemq docker image

### ISSUE THREAD

**Issue by AliIbrahim996** [php-amqplib/php-amqplib#1164]
I am getting this error while trying to use `AMQPStreamConnection`  to connect to ActiveMQ docker image 
`PhpAmqpLib\Exception\AMQPInvalidFrameException     Invalid frame type 65`
This error from the docker logs 

```
Connection attempt from non AMQP v1.0 client. AMQP,0,0,9,1
2024-02-22 13:24:44  WARN | Transport Connection to: tcp://192.168.65.1:32999 failed: org.apache.activemq.transport.amqp.AmqpProtocolException: Connection from the client using unsupported AMQP attempted
```
And these are my local env variables:
```
ACTIVEMQ_HOST=host.docker.internal
ACTIVEMQ_PORT=5672
ACTIVEMQ_USER=admin
ACTIVEMQ_PASSWORD=admin
ACTIVEMQ_QUEUE=activemqTest
```
 Seems like php-amqplib does not support AMQP v1.0

**Comment by ramunasd** [comment]
This lib never had support for AMQP1.0
