### ISSUE TITLE
feof() check in /Wire/IO/StreamIO::write() blocks connection

### ISSUE THREAD

**Issue by jjdunn** [php-amqplib/php-amqplib#1176]
**Version(s) affected**: 3.6.2
**PHP version**: 8.1.28  on Windows ( Dev: win10Pro / Prod: Windows Server 2019)
**RabbitMQ version**: 3.8.2

**Description**  
* we are upgrading from very old version of php-amqplib (2.6.1) to current version (3.6.2).
* our application connects to two separate RabbitMQ servers using the same library
  - connection to the first server works ok
  - connection to the second server fails in /Wire/IO/StreamIO::write() with generic error "Error: Broken pipe or closed connection"

* https://github.com/php-amqplib/php-amqplib/pull/791 introduced feof() check in write().  
    **removing feof() check allows connection to the server** and then our application works normally.

with AMQP_DEBUG enabled and feof() in write(), the failed connection gives not much information:
```
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 
```

**How to reproduce**  
As per above, it succeeds connecting to one server, but fails on the other. 
I cannot give confidential connection info....

**Additional context**  

see attached phpinfo.txt

**Comment by ramunasd** [comment]
Thanks for reporting, but this doesn't sound plausible. If `feof` is causing problems, then why it works for first connection? I'd say something is wrong with connection params or network. Maybe proxy in the middle has very low timeouts?

There was many changes between mentioned versions. It's better to upgrade in steps, to next minor version at once. And repeat only if all ok.

BTW, You forgot to share exception trace and php info. Closing while context is not clear.

**Comment by jjdunn** [comment]
thanks Ramunas for responding so quickly !

> If feof is causing problems, then why it works for first connection?

very good question!  I don't know. 

> I'd say something is wrong with connection params

here are the connection configurations:

```
// WORKING
'mq' => [
    'class' => 'YiiAMQP\Client',
    'connection' => [
        'host' => 'mq-portal-staging.dhamma.org',
        'port' => '5671', // amqps (secure)
        'vhost' => 'osa.dhammareg.applications.xml',
        'user' => 'drintegration',
        'password' => 'REMOVED',
        'connection_timeout' => 10, 
        'sslInfo' => [
            'capath' => 'C:\Program Files\Apache24\conf\dhammareg.ssl',
            'cafile' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\sf_bundle_2014_07.crt',
            'local_cert' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\STAR_dhammareg_dhamma_org-expNov2024.crt',
            'local_pk' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\11Oct2023-dhammareg.dhamma.org.key',
            'verify_peer' => false, 
            'verify_peer_name' => false,causes failure
        ],
    ],
]
```

```
// NOT WORKING
'mqsli' => [
    'class' => 'YiiAMQP\Client',
    'connection' => [
        'host' => 'mq-connect.dhamma.org.au',
        'port' => '5671',
        'vhost' => 'staging_vhost', 
        'user' => 'dhammareg-staging', 
        'password' => 'REMOVED',
        'sslInfo' => [
            'capath' => 'C:\Program Files\Apache24\conf\dhammareg.ssl',
            'cafile' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\sf_bundle_2014_07.crt',
            'local_cert' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\STAR_dhammareg_dhamma_org-expNov2024.crt',
            'local_pk' => 'C:\Program Files\Apache24\conf\dhammareg.ssl\11Oct2023-dhammareg.dhamma.org.key',
            'verify_peer' => false,
            'verify_peer_name' => false,
        ],
    ],
],
```

> You forgot to share exception trace and php info

I attached PHP info but somehow it didn't get attached.  Will attach phpinfo.txt and stack trace just before exception is thrown, next.

**Comment by jjdunn** [comment]
PHP info
[phpinfo.txt](https://github.com/php-amqplib/php-amqplib/files/15419440/phpinfo.txt)

Stack trace just before exception is thrown, with original code:
![stack-trace-on-feof-failure](https://github.com/php-amqplib/php-amqplib/assets/333222/586fdfb4-39f7-40b4-880f-3829e2d436bd)

**Comment by jjdunn** [comment]
p.s. I tried adding connectionTimeout = 10 but this did not help.

**Comment by ramunasd** [comment]
And You can confirm that without `feof()` it works fine?

**Comment by jjdunn** [comment]
> And You can confirm that without feof() it works fine?

yes, absolutely.  this code works:
```
        while ($written < $len) {
            // JJD 5/23/24 #5514 will not connect to SLI if feof() check is enabled.  why not ?
            //if (!is_resource($this->sock) || feof($this->sock)) {
            if (!is_resource($this->sock)) {
```

**Comment by jjdunn** [comment]
one more thing:  the RabbitMQ server/queue I'm trying to connect to had > 5,000 messages in queue.  I thought perhaps `feof() `might be affected by this.  So I emptied the queue by pulling all the messages, then tried to connect again with original code (`feof()` in place).  still does _not_ work.

**Comment by ramunasd** [comment]
Can You create a PR with the fix? I really would like to review working variant.
Please bear in mind, this fix should affect windows systems only.

**Comment by jjdunn** [comment]
> Can You create a PR with the fix?

https://github.com/php-amqplib/php-amqplib/pull/1177
