### ISSUE TITLE
first error message thrown by stream_socket_enable_crypto() is not propagated to caller

### ISSUE THREAD

**Issue by jjdunn** [php-amqplib/php-amqplib#1181]
**Version(s) affected**: 3.6.2
**PHP version**: 8.3.7
**RabbitMQ version**: 0.9.1

**Description**  
```stream_socket_enable_crypto()``` throws TWO errors if it cannot find the SSL certificate due to open_basedir restriction; but only the second of the two errors is propagated to the caller, making debugging more difficult than needed.

the first error is "stream_socket_enable_crypto(): open_basedir restriction in effect..." which is helpful. This is the real cause of the problem; but this error is NOT reported to the caller. it gets overwritten by the second error "unable to get real path of certificate file...." which is true; but not easy to debug

**How to reproduce**  
1. in php.ini, set open_basedir to a list of directories which includes the application, but does not include the path to SSL certificate and associated information (intermediate cert, keys, etc)
2. attempt to open an AMQPS connection
3. get the error "stream_socket_enable_crypto(): Unable to get real path of certificate file...."

**Possible Solution**  
\Wire\IO\AbstractIO::error_handler() should accumulate an array of errors (instead of just last_error); and ::throwOnError() would report the list of errors. I guess AbstractIO::last_error should be renamed as error_list or errors or similar. If you agree with this solution-design I would be happy to submit a PR...let me know.

**Additional context**  
this problem was not exposed in PHP 8.1.x and preceding versions

the open_basedir check when referencing local_cert and local_pk in was introduced in PHP 8.2:
https://www.php.net/ChangeLog-8.php
version 8.2.0:
Fixed bug https://github.com/php/php-src/issues/9310 (SSL local_cert and local_pk do not respect open_basedir).

see four attached screenshots:
1. stack trace at \Wire\IO\StreamIO::enableCrypto()
![stack-trace-1](https://github.com/php-amqplib/php-amqplib/assets/333222/5ecb88b5-53e8-4b61-a816-ab5a0ca86f14)

2. stack trace at \Wire\IO\StreamIO::error_handler()
![stack-trace-2](https://github.com/php-amqplib/php-amqplib/assets/333222/0429c29b-0303-442b-a454-55c97c1812d7)

3. StreamIO properties in first call to error_handler(), showing the error message which gets lost
![error-message-1-lost](https://github.com/php-amqplib/php-amqplib/assets/333222/a222f30f-4cf3-4648-8d29-b23b591ca8fd)

4. StreamIO properties in the second call to error_handler(), showing the less-valuable error message which is propagated to caller
![error-message-2-propagated](https://github.com/php-amqplib/php-amqplib/assets/333222/93e85c32-6dbd-465a-9f4c-1463f89c879b)

**Comment by ramunasd** [comment]
Thanks, this totally makes sense. There might be several warnings and all of them must be exposed for debug purposes. In addition those warnings could be printed out in debug mode.

**Comment by ramunasd** [comment]
My attempt in https://github.com/php-amqplib/php-amqplib/pull/1183

**Comment by jjdunn** [comment]
final commit from #1183 fixes this problem.  All exceptions are reported; and the final exception is no longer logged twice.

Thanks for your prompt attention to this problem !
