### ISSUE TITLE
FD_SETSIZE issue with PhpUnit10

### ISSUE THREAD

**Issue by Atul-glo35265** [php-amqplib/php-amqplib#1184]
**Summary**

I have upgraded PhpUnit in my application from PhpUnit9 to PhpUnit10.

In automation tests, we start getting below issue.

`Caused By: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1024.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
#0 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(410): PhpAmqpLib\Wire\IO\StreamIO->write()
#1 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(261): PhpAmqpLib\Connection\AbstractConnection->write()
#2 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(235): PhpAmqpLib\Connection\AbstractConnection->connect()
#3 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(71): PhpAmqpLib\Connection\AbstractConnection->__construct()
#4 /var/www/html/lib/internal/App/Framework/Amqp/Connection/Factory.php(44): PhpAmqpLib\Connection\AMQPStreamConnection->__construct()
#5 /var/www/html/lib/internal/App/Framework/Amqp/Config.php(160): App\Framework\Amqp\Connection\Factory->create()
#6 /var/www/html/lib/internal/App/Framework/Amqp/Config.php(173): App\Framework\Amqp\Config->createConnection()
#7 /var/www/html/lib/internal/App/Framework/Amqp/Exchange.php(84): App\Framework\Amqp\Config->getChannel()
#8 /var/www/html/lib/internal/App/Framework/MessageQueue/Publisher.php(95): App\Framework\Amqp\Exchange->enqueue()
#9 /var/www/html/lib/internal/App/Framework/MessageQueue/PublisherPool.php(89): App\Framework\MessageQueue\Publisher->publish()`

It is working fine with PhpUnit9 and starts appearing with PhpUnit10 only.

I just wanted to confirm, whether Is this issue coming because of php-amqplib incompatibility with PhpUnit10?
If No, please suggest some solution to fix the issue as we can't change the FD_SETSIZE value in our system.

**Comment by ramunasd** [comment]
In your tests, connections are opened but not closed, very likely because of references to connection object. That's why file descripor (FD) in other words - opened socket/connection limit is reached.
