### ISSUE TITLE
nack with requeue doesn't seem to set the redelivered flag to true 

### ISSUE THREAD

**Issue by FlaviuRadulescu** [php-amqplib/php-amqplib#1194]
I am trying to prevent a message from being delivered repeatedly. To do this, I am marking the message as "not acknowledged" (nack) with the "requeue" option set to true. I expect that when the message is redelivered, the isRedelivered() function will return true on the second attempt. However, this is not happening—isRedelivered() continues to return false even when the message is delivered again. Is this normal behavior? From what I've read, it seems that the redelivery flag should be set to true upon redelivery.

**Comment by ramunasd** [comment]
According to AMQP 0.9.1 complete reference [1]
```
The client MUST NOT rely on the redelivered field but should take it as a hint that the message may already have been processed. A fully robust client must be able to track duplicate received messages on non-transacted, and locally-transacted channels.
```

This library does not have any additional processing or tracking for delivered messages. Message properties are directly mapped from data frames.


All questions regarding rabbitmq itself should be asked in one of community resources - https://www.rabbitmq.com/contact#community-resources

[1] https://www.rabbitmq.com/amqp-0-9-1-reference
