### ISSUE TITLE
Call to undefined method PhpAmqpLib\Channel\AMQPChannel::consume()

### ISSUE THREAD

**Issue by DragonflyPhenom** [php-amqplib/php-amqplib#1196]
**Version(s) affected**: 2.8.0
**PHP version**: 8.0-fpm
**RabbitMQ version**: 3

**Description**  
I try do consumer service accord documentation.
But php get error on this line: 
try {
            $channel->consume();
        } catch (\Throwable $exception) {
            echo $exception->getMessage();
        }

Bcs: consume() method does not exist at channel;
PHPStorm highlight call this method too;

**How to reproduce**  
Just execute code from exmpl

**Possible Solution**  
Say new method for consuming or add ->consume() :)

**Comment by ramunasd** [comment]
This method available since version 3.2.0, older library version does not have this helper method.

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L1584
