### ISSUE TITLE
StreamIO::read loops infinitely if broker blocks producers

### ISSUE THREAD

**Issue by derekchan** [php-amqplib/php-amqplib#148]
We are using RabbitMQ as our broker, and using the default StreamIO in our producer clients. 

When the RabbitMQ server hits "low disk space watermark" it will block all producers (see https://www.rabbitmq.com/memory.html). The producer client will then loop infinitely in StreamIO::read. The correct behaviour for producer is to throw an Exception after timing out.

This had been fixed in commit 2661c3dde0df39cd107d4bd27520078f99917636 (which seemed to break consumers), and the change was later reverted (20d5007).

**Comment by lukebakken** [comment]
This will be addressed by fixes in `2.9.0`
