### ISSUE TITLE
basic_publish error with PThreads

### ISSUE THREAD

**Issue by henriqueoliveira** [php-amqplib/php-amqplib#164]
When calling basic_public inside a class that extends \Thread i got this error, if i just remove the extends \Thread from class it just works fine.

PHP Warning:  fwrite() expects parameter 1 to be resource, integer given in vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 65

PhpAmqpLib\Exception\AMQPRuntimeException: Error sending data in vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 66

Thanks

**Comment by januslo** [comment]
Any lucky for this issue? I meet this issue event two years later now.

**Comment by anuragdalia** [comment]
facing the namespace not found issue. anyone with a solution ?

**Comment by lukebakken** [comment]
Please provide a *complete* set of code to reproduce this and re-open this issue at that time.
