### ISSUE TITLE
 PhpAmqpLib\Connection\AMQPStreamConnection::getSocket is deprecated

### ISSUE THREAD

**Issue by atulatri** [php-amqplib/php-amqplib#166]
Hi,

Why  PhpAmqpLib\Connection\AMQPStreamConnection::getSocket is deprecated?

(it is being used in https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_consumer_non_blocking.php)

**Comment by laapsaap** [comment]
<?php
namespace PhpAmqpLib\Connection;

/**
 * Class AMQPConnection
 *
 * Kept for BC
 *
 * @deprecated
 */
class AMQPConnection extends AMQPStreamConnection
{
}


Well if the documentation isnt up to date, I can imagine it being confusing.. It confused me as well.
