### ISSUE TITLE
Unknown delivery tag 1.00000000

### ISSUE THREAD

**Issue by slepic** [php-amqplib/php-amqplib#180]
Hi, 
we encountered a randomly occuring error "'Server nack\'ed unknown delivery_tag 1.00000000" while waiting for pending acks after writing messages to a queue.
I figured out the problem is in use of bc function without their scale argument set. When provided $scale=0 to bc functions is Wire\AMQPReader::read_longlong everything turns out to be ok. For sure i recommend providing all bc function calls in the library with $scale=0

PS: this error only occured when channel->confirm_selected() was called first with either true or false argument.

**Comment by lukebakken** [comment]
Fixed by #254
