### ISSUE TITLE
Library can get stuck forever trying to read from the server

### ISSUE THREAD

**Issue by arnaud-lb** [php-amqplib/php-amqplib#184]
The library can get stuck forever trying to read from a [half-open connection](http://blog.stephencleary.com/2009/05/detection-of-half-open-dropped.html).

Half-open connections happen e.g. when the server's host crashes. In this event the client doesn't receive anything from the server, so it continues to assume that the connection is open. (If rabbitmq itself crashed, but not its host, the client would receive a TCP FIN packet from the host, and the connection would be closed on both sides.)

Reads on half-open connections never return, so attempting to read leads to wait forever.

StreamIO sets a read/write timeout on the socket [here](https://github.com/videlalvaro/php-amqplib/blob/00c2df2d3f2ceefcb4355cbd1a2f075cb74ff275/PhpAmqpLib/Wire/IO/StreamIO.php#L79), however the [read method](https://github.com/videlalvaro/php-amqplib/blob/00c2df2d3f2ceefcb4355cbd1a2f075cb74ff275/PhpAmqpLib/Wire/IO/StreamIO.php#L104) retries indefinitely (in case of timeout, fread() returns the empty string). 

Enabling KEEPALIVE helped to detect such connections in my case:

```
        $raw = socket_import_stream($this->sock);
        socket_set_option($raw, SOL_SOCKET, SO_KEEPALIVE, 1);
```

**Comment by lukebakken** [comment]
Fixed by #187 and inclusion of heartbeats in this library.
