### ISSUE TITLE
After creating a new AMQPConnection, calling getSocket() returns NULL

### ISSUE THREAD

**Issue by dkingofpa** [php-amqplib/php-amqplib#204]
This happens for v2.4.0 and master as of today.  However, it works on branch 091.

You can see this behavior throw php warnings from stream_select() by running https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_consumer_non_blocking.php

```
Warning: stream_select(): No stream arrays were passed in /Users/dking/Projects/test/vendor/videlalvaro/php-amqplib/demo/amqp_consumer_non_blocking.php on line 86

Call Stack:
    0.0003     240496   1. {main}() /Users/dking/Projects/test/vendor/videlalvaro/php-amqplib/demo/amqp_consumer_non_blocking.php:0
    0.5547    1362456   2. stream_select() /Users/dking/Projects/test/vendor/videlalvaro/php-amqplib/demo/amqp_consumer_non_blocking.php:86
```

**Comment by lukebakken** [comment]
I do not see this behavior when running `amqp_consumer_non_blocking.php` from `master`. Assuming that it has been fixed.
