### ISSUE TITLE
Exception uncaught when close() is called in the AMQPChannel destructor

### ISSUE THREAD

**Issue by jocel1** [php-amqplib/php-amqplib#209]
Hi,

When an exception occurs in the close() function called by the AMQPChannel destructor, a thrown exception is never caught :

exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with message 'Error sending data. Socket connection timed out' in /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Wire/IO/StreamIO.php:178
Stack trace:
#0 /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Connection/AbstractConnection.php(387): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#1 /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Connection/AbstractConnection.php(498): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#2 /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Channel/AbstractChannel.php(191): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Channel/AMQPChannel.php(200): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /home/Codizy-2.2.7/client/application/libs/php-amqplib-2.4.0/PhpAmqpLib/Channel/AMQPChannel.php(141): PhpAmqpLib\Channel\AMQPChannel->close()
#5 [internal function]: PhpAmqpLib\Channel\AMQPChannel->__destruct()

The following modification in the AMQPChannel destructor seems to fix the issue : 

```
public function __destruct()
{
    try {
        $this->close();
    } catch (\Exception $e) {
    }
}
```

Thanks,
  Jocelyn

**Comment by lukebakken** [comment]
Fixed by #195
