### ISSUE TITLE
AbstractChannel::wait() with timeout: why throw exception?

### ISSUE THREAD

**Issue by nickygerritsen** [php-amqplib/php-amqplib#211]
We are using php-amqplib in a project where we have a daemon running that, besides checking the AMQP data, should also do some other work regularly.

We can do this by adding a timeout variable to $channel->wait(). This works; however it will  throw an exception when the timeout occurs, which we then need to catch every time (we do not always receive data in the given timeout period).

I think this is a little strange, to always catch this. Is it an idea to at least have a way to disable this exception?

**Comment by shubhadip** [comment]
Even i have Same Issue.

**Comment by zakjan** [comment]
What is the current status of this issue?

I have a related problem: When catching the AMQPTimeoutException, so I can alternate with running other code, the channel is not closed correctly and it remains open until the process exits.

**Comment by videlalvaro** [comment]
If you have a sensible fix, then pelase send a PR @zakjan
