### ISSUE TITLE
How to retrieve the same message twice or more (without deleting it afterwards)?

### ISSUE THREAD

**Issue by exislow** [php-amqplib/php-amqplib#221]
How can I retrieve the same message from a queue more then once? The normal case is, if I have consumed the message, it will be deleted from the queue but I want to keep the message in the queue.

Is there a flag to disable delete after consuming or can I somehow redeliver it?

**Comment by nubeiro** [comment]
Is this still an issue?

**Comment by exislow** [comment]
Yes it is (in my opinion).

2016-02-15 9:18 GMT+01:00 Raúl Araya <notifications@github.com>:

**Comment by lukebakken** [comment]
If you are losing `nack`'d messages in an auto delete queue, most likely the queue has been deleted by RabbitMQ. Please re-read https://www.rabbitmq.com/queues.html

**Comment by rraveendrannair** [comment]
basicget can be used with ack flag = false
