### ISSUE TITLE
Duplicate messages being sent to High availability and non-ha queues on benchmark

### ISSUE THREAD

**Issue by whit1206** [php-amqplib/php-amqplib#226]
I setup rabbit on a cluster of 3 machines and used the benchmark code included in the 2.4.1 release to connect and make sure it publishes/consumes correctly. When I implement the basic high availability policy: [{"vhost":"/","name":"ha-all","pattern":"^ha\\.","definition":{"ha-mode":"all"},"priority":0}] and change the queue name in the bench mark producer and consumer to "ha.bench_queue", it creates the messages in both queues "ha.bench_queue" and "bench_queue" and you see the message counts go up by both. Running the consumer.php file correctly only takes them from the "ha.bench_queue" queue.

For some reason it duplicates the messages. I tried changing the name of the queue back to "bench_queue" and now the producer creates the messages in both queues again. Consumer acts correctly and only removes from the non-HA queue. Here is my complete policy file but the password hashes have been removed:

{"rabbit_version":"3.1.5","users":[{"name":"cwhitten","password_hash":"XXXX","tags":"administrator,monitoring,management,policymaker"},{"name":"croll","password_hash":"XXXX","tags":""}],"vhosts":[{"name":"/"}],"permissions":[{"user":"croll","vhost":"/","configure":".*","write":".*","read":".*"},{"user":"cwhitten","vhost":"/","configure":".*","write":".*","read":".*"}],"parameters":[],"policies":[{"vhost":"/","name":"ha-all","pattern":"^ha\\.","definition":{"ha-mode":"all"},"priority":0}],"queues":[{"name":"bench_queue","vhost":"/","durable":false,"auto_delete":false,"arguments":{}},{"name":"ha.bench_queue","vhost":"/","durable":false,"auto_delete":false,"arguments":{}}],"exchanges":[{"name":"bench_exchange","vhost":"/","type":"direct","durable":false,"auto_delete":false,"internal":false,"arguments":{}}],"bindings":[{"source":"bench_exchange","vhost":"/","destination":"bench_queue","destination_type":"queue","routing_key":"","arguments":{}},{"source":"bench_exchange","vhost":"/","destination":"ha.bench_queue","destination_type":"queue","routing_key":"","arguments":{}}]}

One last thing to note: if only the queue that its supposed to write to exists, it doesn't create the other one. It only writes to the other one if it already exists. Any idea why the messages are being sent to both queues? Thanks

**Comment by videlalvaro** [comment]
It seems to me that you bound both queues to the same exchange, right? If that's the case, then that's how RabbitMQ routing is supposed to work, and this has nothing to do with ha-queues or not.

Take a look here: http://www.rabbitmq.com/tutorials/amqp-concepts.html

**Comment by nubeiro** [comment]
Is this still an issue?
