### ISSUE TITLE
Transactions howto

### ISSUE THREAD

**Issue by gjuric** [php-amqplib/php-amqplib#228]
It would be really helpful if someone could provide a code sample on how to use transactions.

I was using it like this, but I am not sure if this is the correct way:

``` php
    // ... connect to AMQP broker and setup exchange, queue and bindings

    $channel->tx_select();

    $msg = new AMQPMessage("test message", array(
        'content_type' => 'text/plain',
        'delivery_mode' => 2)
    );

    $channel->basic_publish($msg, $exchange, $routingKey);
    $channel->tx_commit();
```

**Comment by videlalvaro** [comment]
@michaelklishin do you know of any library or test suite where we us transactions?

**Comment by lukebakken** [comment]
This code appears to be correct as per - https://www.rabbitmq.com/confirms.html#publisher-confirms

**Comment by gjuric** [comment]
@lukebakken the article you linked is talking about Publisher Confirms, this is not the same thing as  Transactions.

I think the code I posted is not 100% correct, I believe one should also wrap the pasted code inside the try-catch block, and do a `$channel->tx_rollback()` if an exception is thrown.

But since I am not 100% sure of how to confirm my thinking or make a test suite out of it I think that this issue should be left open.

If somebody wants to take a crack at it, I believe this is the relevant [specification](http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-transactions-v1.0.html#type-transaction-error).

**Comment by lukebakken** [comment]
From that paragraph:

> Using standard AMQP 0-9-1, the only way to guarantee that a message isn't lost is by using transactions -- make the channel transactional, publish the message, commit.

That is exactly what you are doing in the code. You're correct, there is no error handling which could be implemented as you suggest. The AMQP 0.9.1 spec document also has [this section](http://www.rabbitmq.com/amqp-0-9-1-quickref.html#class.tx).

Another transaction use-case is, like with a database, wait to commit until a batch of messages have been published, if they all must be published atomically.

**Comment by gjuric** [comment]
Guess I should have read that more carefully :) Thank you!

**Comment by lukebakken** [comment]
No problem!
