### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by bartfeenstra** [php-amqplib/php-amqplib#247]
The README refers to the documentation on the RabbitMQ website, but that was written for a previous version of the library and is no longer up to date (wrong class names, method parameters, etc.). I'm not sure what the best course of action is to fix this, but I thought I'd report it here so you're aware of the issue.

**Comment by videlalvaro** [comment]
Thanks, I will look into it and update the RabbitMQ docs

**Comment by michaelklishin** [comment]
Ugh, @videlalvaro if the docs on rabbitmq.com are out of date, I'd consider it to be a very high priority issue.

**Comment by videlalvaro** [comment]
@bartfeenstra would you mind elaborating on which methods have had their parameters changed? One thing we try pretty hard with this library is to not introduce API breaking changes.

The AMQPConnection class got deprecated, yes, but we never removed it, so the tutorials were still working.

In any case, I've updated the RabbitMQ docs to use the latest version of the library, plus the AMQPStreamConnection class: https://github.com/rabbitmq/rabbitmq-website/pull/55

**Comment by lukebakken** [comment]
Addressed by rabbitmq/rabbitmq-website#55
