### ISSUE TITLE
High cpu usage in newer versions of AbstractConnection

### ISSUE THREAD

**Issue by ptte** [php-amqplib/php-amqplib#258]
Let me start with saying that this isn't a bug, it's more of a feature request for backwards compatibility.

The AbstractConnection::__construct method had a different signature back in at least 2.0.0. It takes very different parameters after `$locale`.

One would expect that this would lead to old ways of initiating it would fail dramatically, but actually it works very well, without even throwing a notice, with some weird edge case exceptions that are very hard to trace to that specific point in the code.

If you call it with the old parameters, something that could look like this:

``` php
$this->connection = new Connection\AMQPConnection(
    $server->host,
    $server->port,
    $server->user,
    $server->password,
    $server->vhost,
    $server->insist,
    $server->login_method,
    $server->locale,
    $server->connection_timeout,
    $server->read_write_timeout,
    $server->context,
    $server->keepalive,
    $server->heartbeat
);
```

the effect I have seen is that CPU usage in channel::wait starts going to 100%

Seems like some versions of symfony with the plugins for rabbit have similar issues based on this http://stackoverflow.com/questions/27739815/amqp-consumer-loads-cpu-to-100 .

I just wanted to let y'all know and maybe it's possible adding something that throws an exception if it's called with the old signature.

Thanks for a great lib :)

**Comment by lukebakken** [comment]
Unable to reproduce using the following script, which was copied from `demo/amqp_consumer.php` and modified.

[amqp_consumer.php.txt](https://github.com/php-amqplib/php-amqplib/files/1639681/amqp_consumer.php.txt)
