### ISSUE TITLE
Alive consumer clarification

### ISSUE THREAD

**Issue by Wizofel** [php-amqplib/php-amqplib#276]
Hello,

I would like some further details on how a consumer (php script waiting to receive messages from a queue) stays alive and does not fall on execution timeout.

As far as i checked, there is not "set_time_limit(0)" command hidden anywhere in the library. 

Does this "heartbeat" and "keep the socket alive" thing do the trick? I cannot find any logical explanation, though i consider myself quite rookie on this.

Any help would be appreciated.

**Comment by matteosister** [comment]
it's a

``` php
while(true) {}
```



here it is: https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Channel/AbstractChannel.php#L354

**Comment by Wizofel** [comment]
Thank you for your response. What i fail to understand is why this endless loop overrides any "max_execution_time" set by the php.ini. Could you provide any further documentation and/or details?

**Comment by jonhattan** [comment]
FYI `max_execution_time` is 0 (i.e. unlimited) by default in php cli. Ref http://php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by nubeiro** [comment]
Is this still an issue? To me it looks like you got a valid solution for the problem.
