### ISSUE TITLE
Call to a member function getTimeout() on a non-object in PhpAmqpLib/Connection/AbstractConnection.php on line 522

### ISSUE THREAD

**Issue by michaa76** [php-amqplib/php-amqplib#285]
in multi process environment in one application of mine there is problem:
###
PHP Fatal error:  Call to a member function getTimeout() on a non-object in /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 522
###
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Projects/project-xyz/manager.php:0
PHP   2. X\Y\Z->run() /home/vagrant/Projects/project-xyz/manager.php:42
PHP   3. X\Y\Z->doStartProcess() /home/vagrant/Projects/project-xyz/src/X/Y/Z.php:60
PHP   4. X\Y\ZProcess->start() /home/vagrant/Projects/project-xyz/src/X/Y/Z.php:98
PHP   5. UnixProcess\AbstractUnix->start() /home/vagrant/Projects/project-xyz/src/X/Y/ZProcess.php:70
PHP   6. PhpAmqpLib\Connection\AbstractConnection->__destruct() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:0
PHP   7. PhpAmqpLib\Connection\AbstractConnection->safeClose() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:260
PHP   8. PhpAmqpLib\Connection\AbstractConnection->close() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:271
PHP   9. PhpAmqpLib\Connection\AbstractConnection->closeChannels() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:628
PHP  10. PhpAmqpLib\Channel\AMQPChannel->close() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:956
PHP  11. PhpAmqpLib\Channel\AbstractChannel->wait() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:174
PHP  12. PhpAmqpLib\Channel\AbstractChannel->next_frame() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:355
PHP  13. PhpAmqpLib\Connection\AbstractConnection->wait_channel() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:214
PHP  14. PhpAmqpLib\Connection\AbstractConnection->wait_frame() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:568
###

**Comment by nubeiro** [comment]
Is this still an issue?
Can you share more details if it is?
