### ISSUE TITLE
Read and write to multiple queues within one script

### ISSUE THREAD

**Issue by ehongyu** [php-amqplib/php-amqplib#293]
I created a unit test script that both reads and writes work queue messages to a rabbitmq service. It works perfectly fine if there is a single queue, but if there are more than one queues in the script, I sometimes saw strange behaviors of queue messages mixed up, e.g., the message from queue One will be picked up from queue Two. I used the faster basic_consume function here, and the error disappears if I switch to use basic_get function. Anyone has better idea of what happened?

**Comment by SuperStas** [comment]
HI @ehongyu what exchange type did you use?  Could be it "topic" or "direct" type, and messages are delivering by routing keys?

**Comment by ehongyu** [comment]
Thanks, @SuperStas. I believe it's "direct" because I essentially wrote it based on the Work Queue example code on the RabbitMQ website https://www.rabbitmq.com/tutorials/tutorial-two-php.html

**Comment by ehongyu** [comment]
Here is a simple process that I can repeat the error. The pseudo code looks like 

- publish a message to queue One
- publish a message to queue Two
- fetch a message from queue Two, and assert
- publish a message to queue One
- fetch a message from queue One, and assert
- fetch a message from queue Two, and assert. 

The last step threw an error. It is supposed to get an empty message here, but somehow the basic_consume API returns the message originally published to queue One.

**Comment by ehongyu** [comment]
Update: 

I implemented the same workflow using the RabbitMQ Java library, and it works correctly. Therefore, I suspect that something is wrong with this PHP lib.

**Comment by jesseforrest** [comment]
@ehongyu, this is the code being used for your `basicConsume($queue_name, $waiting_time)` method:

```
            if (!isset(self::$_queues[$queue_name])) {
                self::createQueue($queue_name);
            }

            if (!isset(self::$_queues_consumed[$queue_name])) {

                self::$_channel->basic_qos(null, 1, null);
                self::$_channel->basic_consume($queue_name, '', false, false, false, false, function ($msg) {
                    self::$_message = $msg->body;
                    $msg->delivery_info['channel']->basic_ack($msg->delivery_info['delivery_tag']);
                });
                self::$_queues_consumed[$queue_name] = true;

            }

            if (count(self::$_channel->callbacks)) {
                self::$_channel->wait(null, false, $waiting_time);
            }

            return self::$_message;
```

Is it okay that we are reusing 1 channel for multiple queues?  Could that be the issue?  Is it best practice to have 1 channel for many queues or 1 channel per queue?

**Comment by ehongyu** [comment]
I haven't seen any note in existing reference to prohibit clients from using multiple queues in one channel. My Java client did the same thing perfectly fine, while the php client only gave error in some edge cases.

I didn't post my code originally is because it involves lots of boiler plates. I am going to provide a strip-down version based on what @SuperStas emailed to me, so everybody can repeat it.

**Comment by videlalvaro** [comment]
Without the code to actually reproduce the error it's quite hard to help you debug the issue.

**Comment by ehongyu** [comment]
Here is the test code https://gist.github.com/ehongyu/84dc172d8855107ab42d
The output looks like:
```
---- Publish message 1
---- Publish message 2
---- Fetch message 2
string(5) "test2"
---- Publish message 1
---- Fetch message 1
string(5) "test1"
---- Fetch message 2
string(5) "test1"
```

And here is the original test code from @SuperStas : https://gist.github.com/SuperStas/f792b8ece120208e890d. His result is different, and the main difference is that
1) he used "direct" exchange, while my code used the default empty exchange
2) he used the while loop when calling the wait() function, while I used the if condition. 

If I switched to use the while loop while keeping the default empty exchange, the code will get stuck in the middle. See code: https://gist.github.com/ehongyu/d67fb391da805842e3be

BTW, here is my Java code https://gist.github.com/ehongyu/db8dcf7bd0824f806ab0

**Comment by nubeiro** [comment]
Is this still an issue for you?

**Comment by ehongyu** [comment]
I switched to use one queue per channel in my code, and the issue disappeared.

**Comment by lukebakken** [comment]
Consuming from multiple queues using the same channel is not supported in the AMQP spec. The fact that it works using the Java client is pure luck.
