### ISSUE TITLE
Nack not receiving when running demos

### ISSUE THREAD

**Issue by sendoav** [php-amqplib/php-amqplib#300]
I am running de amqp_publisher_with_confirms.php sample in parallel with de amqp_consumer.php sample. The messages are being transmitted but I am trying to differentiate the ACK and NACK responses changing from basic_ack to basic_nack, but I always get message from the ACK Handler

**Comment by dusan-ivanco** [comment]
I have this problem to. Any solution?

**Comment by lukebakken** [comment]
You should not see `basic.nack` messages in this scenario.

**Comment by ikodota** [comment]
I have this problem too.  

~~~php 
$msg->delivery_info['channel']->basic_nack($msg->delivery_info['delivery_tag'],false,false);
~~~

debug info:
~~~text

< 60,80:: Basic.ack
waiting for any method
waiting for a new frame
> 60,60: Basic.deliver
waiting for a new frame
waiting for a new frame
 [76393] consumer.services.product.demo:"bad"
< 60,120:: Basic.nack
< [hex]: 
0000  01 00 01 00 00 00 0D 00  3C 00 78 00 00 00 00 00   ........ <.x.....
0010  00 00 0C 00 CE                                     ....�

< 60,120:: Basic.nack
waiting for any method
waiting for a new frame
~~~
