### ISSUE TITLE
Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (113):

### ISSUE THREAD

**Issue by jayeshneema** [php-amqplib/php-amqplib#306]
I have installed rabbitMQ and trying to run first example (https://www.rabbitmq.com/tutorials/tutorial-one-php.html) of there official site, 
and when we wirte on terminal window: $ php send.php I am getting the following error:

PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (113): No route to host' in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:106
Stack trace:
#0 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(195): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(179): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(41): PhpAmqpLib\Connection\AbstractConnection->__construct('guest', 'guest', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#3 /opt/lampp/htdocs/rabbit/send.php(7): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('localhost', 5672, 'guest', 'guest')
#4 {main}
  thrown in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 106

**Comment by jayeshneema** [comment]
Hi 
If anyone who have experienced with this issues please send your words.

**Comment by northern** [comment]
I get the impression your server isn't running on localhost. However, this doesn't seem to be a bug with php-amqplib. Best to open a question on Stackoverflow [1] and don't forget to post your actual program code to give the issue a bit more context.

[1] http://stackoverflow.com

**Comment by jayeshneema** [comment]
ok I have tried to start server with following way:
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

php /usr/local/bin/composer

and use following to start server: 
$ invoke-rc.d rabbitmq-server start 

and getting the following result:
* Starting message broker rabbitmq-server                                                                                                                                                            start-stop-daemon: unable to set gid to 125 (Operation not permitted)
rm: cannot remove ‘/var/run/rabbitmq/pid’: Permission denied
invoke-rc.d: initscript rabbitmq-server, action "start" failed.

and when we trying to start server with sudo   $ sudo invoke-rc.d rabbitmq-server start
it results:

 * Starting message broker rabbitmq server                                                                                                                                                             * message broker already running


Now when we write  "$ php send.php" on terminal it again showing the fatal error:


PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (113): No route to host' in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:106
Stack trace:
#0 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(195): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(179): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(41): PhpAmqpLib\Connection\AbstractConnection->__construct('root', '', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#3 /opt/lampp/htdocs/rabbit/send.php(7): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('localhost', 5672, 'root', '')
#4 {main}
  thrown in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 106

**Comment by jayeshneema** [comment]
When we trying to start rabbitmq-server it show:
$ sudo invoke-rc.d rabbitmq-server start
[sudo] password for jayesh: 
 * Starting message broker rabbitmq server                                                                                                              
* FAILED - check /var/log/rabbitmq/startup_\{log, _err\}

Please send your help full comments Thanks

**Comment by jayeshneema** [comment]
Hello
I have fixed the issue by updated the file: /etc/rabbitmq/rabbitmq-env.conf

#example rabbitmq-env.conf file entries
#Rename the node
NODENAME=myhost
HOSTNAME=myhost
#Config file location and new filename bunnies.config
CONFIG_FILE=/etc/rabbitmq/rabbitmq.config
RABBITMQ_NODE_PORT=5672

**Comment by nubeiro** [comment]
So we can close this issue?

**Comment by juanrraider666** [comment]
rabbitmq-env.conf

**Comment by juanrraider666** [comment]
choco install rabbitmq
