### ISSUE TITLE
Why are we reconnecting in check_heartbeat method?

### ISSUE THREAD

**Issue by atulatri** [php-amqplib/php-amqplib#309]
In following code fragment (from StreamIO.php) we are reconnecting if server has gone away. Because of this process never terminates and keeps tying to reconnect.

Shouldn't we throw exception here instead of reopening socket again? 

AFAIK If TCP connection is closed, associated AMQP connection and channels are also closed. So simply reopening socket can not recreate AMQP connection.

```
protected function check_heartbeat()
    {
        // ignore unless heartbeat interval is set
        if ($this->heartbeat !== 0 && $this->last_read && $this->last_write) {
            $t = microtime(true);
            $t_read = round($t - $this->last_read);
            $t_write = round($t - $this->last_write);

            // server has gone away
            if (($this->heartbeat * 2) < $t_read) {
                $this->reconnect();
            }

            // time for client to send a heartbeat
            if (($this->heartbeat / 2) < $t_write) {
                $this->write_heartbeat();
            }
        }
    }
```

**Comment by c-datculescu** [comment]
Hello.

Most likely because after two missed heartbeats the server will consider the connection as failed and close it on its end. This would leave the client "connected" although it is not.

**Comment by dennis-hh** [comment]
We're having this exact issue. We use the server's proposed heartbeat value. Before even sending the heartbeat, check_heartbeat detects a "gone away", tries to reconnect and effectively kills all channels without establishing them again, rendering the worker in an unusable state.

**Comment by aleiphoenix** [comment]
`$this->last_read` is affecting `check_heartbeat` behavior here. When stuck in this reconnecting loop, `$this->last_read` is never updated, causing connection stuck in reconnecting loop.

Simply disconnect here  should do the trick.

```
// server has gone away
if (($this->heartbeat * 2) < $t_read) {
    // stop doing any reconnecting, just close itself.
    // $this->reconnect();
    $this->close();
}

// time for client to send a heartbeat
    if (($this->heartbeat / 2) < $t_write) {
    $this->write_heartbeat();
}
```

This, will lead into a `Broken pipe` error when writing anything further to this socket fd.

Just leave the reconnecting issue to outer codes. Or perhaps better missing heartbeat handling.

Reconnecting without recoverying any topology (this feature which is provided in Java client though) is NAIVE, IMNSHO.

**Comment by michaelklishin** [comment]
Partially addressed by https://github.com/php-amqplib/php-amqplib/pull/479.

**Comment by lukebakken** [comment]
#559 removed the reconnect call.
