### ISSUE TITLE
Add Changelog of major features and breaking changes

### ISSUE THREAD

**Issue by IMSoP** [php-amqplib/php-amqplib#315]
Please could you add a basic changelog file to the distribution. At the moment, there appears to be no record of the minimum version for new features, or breaking changes like this one: https://github.com/videlalvaro/php-amqplib/commit/1c4ae1c45d68be66e9e664d67d0cd72e91496f56 I have code which accesses message headers as an array, which fails under 2.6, because AMQPTable must be used explicitly.

While you're at it, the link to https://code.google.com/p/php-amqplib/ should be removed from the readme, since there's nothing useful there any more. :)

**Comment by IMSoP** [comment]
PS Apologies if there is actually a changelog somewhere, and I just failed to read it.

**Comment by videlalvaro** [comment]
Sadly I haven't had the discipline of producing a change log. That's totally my fault

I don't want to remove mentions to the original php-amqplib, since my work is based on theirs.

**Comment by IMSoP** [comment]
Ah, my mistake on the Google Code link, I was skim-reading in case there were references I'd missed.

**Comment by postalservice14** [comment]
Added a PR for the start of a changelog.  #317

**Comment by postalservice14** [comment]
Cool, so I think this can be closed.

**Comment by nubeiro** [comment]
Closing then, thanks a lot for starting the changelog :+1:
