### ISSUE TITLE
Memory exhausted in StreamIO.php

### ISSUE THREAD

**Issue by ruudk** [php-amqplib/php-amqplib#322]
I'm using version 2.6 of php-amqplib with the latest version of RabbitMqBundle and for weeks I run into a fatal memory exhausted error. It is trying to allocate 1.34 gigabyte in StreamIO.php on line 194.

I did a lot of debugging and research to find the issue causing this.

I use RabbitMQ 3.5.4 with the following RabbitMqBundle settings:
- keepalive: false
- heartbeat: 30
- read_write_timeout: 60
- Consumer argument: `--memory-limit=350`

My PHP has a memory limit of 500MB.

After every received message I do a memory cleanup and display the memory in use:

```
Oct 01 09:38:40 aws-pdf-web1 eventbus-2.log:  Auto cleanup, 59.5 mb in use.
Oct 01 09:53:21 aws-pdf-web1 eventbus-2.log:  Fatal error: Allowed memory size of 524288000 bytes exhausted (tried to allocate 1342177291 bytes) in /home/ticketswap/app/releases/20150930160705/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 194
```

As you can see, after receiving the last message it did nothing for 15 minutes and then failed.

Any thoughts what might cause this issue?

**Comment by videlalvaro** [comment]
maybe this is related to this? https://github.com/videlalvaro/php-amqplib/pull/319

**Comment by ruudk** [comment]
Just deployed that fix to production. The error normally occurs at night when there is less activity, so fingers crossed :)

**Comment by videlalvaro** [comment]
just merged it BTW

**Comment by bmcgavin** [comment]
Hi, hope this isn't considered derailing.

I've had the same error (specifically the number of bytes, 'trying to allocate 1342177291 bytes'), and found this link helpful in explaining what's going on : 

http://john.eckersberg.com/debugging-rabbitmq-frame_too_large-error.html

I think the protocol handling gets into an incorrect state if there's a networking problem. I've simulated this with a consumer (using AMQPStreamConnection) and iptables.

* Consumer starts with a heartbeat of 2 seconds
* Drop packets from the consumer to RMQ : iptables -A OUTPUT -p tcp --dport 5672 -j DROP
* Sleep 10 seconds
* Drop that rule to re-enable comms : iptables -D OUTPUT 1

Once comms are re-enabled, then the consumer successfully does a 3-way open and sends a heartbeat frame again. The broker responds with a connection start header ('AMQP' \0 \0 \9 \1) which leads to the allocation error as detailed above, and an immediate TCP RST packet. It also logs a 'bad_header' message. The consumer then reconnects and sends a method frame (type 0x01), and the broker again sends a connection start header and a RST. The consumer never manages to re-establish the link and the process needs to be restarted.

I think (and I may be wrong) that when the channel and connection are forced close (by the socket closing) then the client waits for a 20,41 or 10,51 message, but doesn't get either of them. Is there a way to force the connection back to the initial state once the connection is reset and no close_ok messages are received?

**Comment by postalservice14** [comment]
Did https://github.com/php-amqplib/php-amqplib/pull/372 fix this problem?

**Comment by bmcgavin** [comment]
@postalservice14 It definitely fixed my problem, yes.

As for the original one on the thread that I derailed, I can't comment.
