### ISSUE TITLE
Cannot change timeout on AbstractChannel->wait

### ISSUE THREAD

**Issue by garethwi** [php-amqplib/php-amqplib#330]
_Using version 2.5.x in composer_

We've been doing some stress testing at work, and one of those tests was to completely fill RabbitMQ with unacknowledged messages.  

When we do this, closing the connections hangs our script.  We've isolated this problem as follows:

The wait function in \PhpAmqpLib\Channel'AcstractChannel has a timeout parameter with a default setting of 0, which is called by the close function \PhpAmqpLib\Connection\AbstractConnection without passing a timeout parameter.

Is it possible to either add the ability to set a timeout, or maybe to change the default timeout to something less catastrophic?

Thanks.

**Comment by abreksa4** [comment]
@garethwi Looks like it can be set via a method parameter: https://github.com/php-amqplib/php-amqplib/blob/v2.5.2/PhpAmqpLib/Channel/AbstractChannel.php#L321

**Comment by lukebakken** [comment]
Closing as the two linked commits resolve the issue.
