### ISSUE TITLE
Lazy connections and `AMQPSocketConnection` 

### ISSUE THREAD

**Issue by mente** [php-amqplib/php-amqplib#331]
Hey guys,

From what I've noticed (according to benchmarks at least) using `AMQPSocketConnection` for producers 10x faster than stream implementation:

```
$ make benchmark
Publishing 4000 msgs with 1KB of content:
php benchmark/producer.php 4000
0.65707993507385
Consuming 4000:
php benchmark/consumer.php
Pid: 26125, Count: 4000, Time: 4.1040
Stream produce 100:
php benchmark/stream_tmp_produce.php 100
4.5005960464478
Socket produce 100:
php benchmark/socket_tmp_produce.php 100
0.53135895729065
```

I would like to test socket connection on our system but it lacks lazy connection in current implementation. Are there any reasons why `AMQPSocketConnection` class still doesn't support lazy connection? Except nobody actually implemented it :). Willing to help if that's the case.

**Comment by videlalvaro** [comment]
> Except nobody actually implemented it

that's the reason
