### ISSUE TITLE
Fatal error: Call to a member function send_channel_method_frame() on null

### ISSUE THREAD

**Issue by speller** [php-amqplib/php-amqplib#337]
Test code:

<?
// std connection routines

// check exchange exists
try {
	$this->channel->exchange_declare('tst.exchange2', 'topic', true);
	// exists - make something
} catch (\Exception $e) {
	// not exist
}
$this->channel->exchange_declare('tst.exchange2', 'topic', false, true, false);
?>

And on the last line we get the fatal error: 
Fatal error: Call to a member function send_channel_method_frame() on null

**Comment by postalservice14** [comment]
I've created a PR to throw an exception in this case rather than a fatal error: #358
