### ISSUE TITLE
When heartbeats parameter is greater than 0

### ISSUE THREAD

**Issue by Jekis** [php-amqplib/php-amqplib#352]
When heartbeats parameter is greater then 0 there is no signal dispatch

```
        if ($buf === '') {
            if ($this->canDispatchPcntlSignal) {
                pcntl_signal_dispatch();
            }
            continue;
        }
```

because `$buf` is always not empty

v2.5.2

**Comment by nubeiro** [comment]
Is this still an issue?

**Comment by Jekis** [comment]
Yes, it is!

Due to this issue the only way to stop the consumer process is to `kill -9` that prevents to terminate process properly.

**Comment by Enleur** [comment]
@Jekis just tried to reproduce on 2.5.2 version, works fine:

<img width="808" alt="screenshot 2016-02-12 21 55 57" src="https://cloud.githubusercontent.com/assets/858989/13010264/8f7b096e-d1d3-11e5-94c0-b169e0d0749b.png">

**Comment by Jekis** [comment]
I'm using this library within RabbitMQBundle. I will check one more time.

**Comment by nubeiro** [comment]
Please keep us updated, we are trying to clean up open issues.

**Comment by Jekis** [comment]
### Test 1

**Libs installed via composer:**

    "name": "videlalvaro/rabbitmq-bundle",
    "version": "v1.7.0",

    "name": "videlalvaro/php-amqplib",
    "version": "v2.5.2",

Run:

    php app/console rabbitmq:consumer my.consumer.name

Results:

When heartbeat = 0: process could be terminated with SIGTERM
When heartbeat = 1: process could be terminated with SIGQUIT or SIGKILL only


### Test 2

**Libs installed via composer:**

    "name": "videlalvaro/rabbitmq-bundle",
    "version": "v1.8.0",

    "name": "videlalvaro/php-amqplib",
    "version": "v2.6.1",

Run:

    php app/console rabbitmq:consumer my.consumer.name

Results:

When heartbeat = 0: process could be terminated with SIGQUIT or SIGKILL only
When heartbeat = 1: process could be terminated with SIGQUIT or SIGKILL only


### Test 3

**Libs installed via composer:**

    "name": "php-amqplib/rabbitmq-bundle",
    "version": "dev-master",

    "name": "php-amqplib/php-amqplib",
    "version": "v2.6.1",

Run:

    php app/console rabbitmq:consumer my.consumer.name

Results:

When heartbeat = 0: process could be terminated with SIGQUIT or SIGKILL only
When heartbeat = 1: process could be terminated with SIGQUIT or SIGKILL only

PS heartbeat changes were made in rabbitmqbundle configuration

**Comment by nubeiro** [comment]
Thanks for getting back. 
Please help me understand what do you mean when you say that "there is no signal dispatch".
I will try to check with the versions you sent, thanks a lot.

**Comment by Jekis** [comment]
> there is no signal dispatch

First time I found this issue I was trying to debug it. I found that `pcntl_signal_dispatch();` was never called when heartbeat is greater then 0

**Comment by lukebakken** [comment]
Please test with `2.8.0` RC1. I am closing stale issues.
