### ISSUE TITLE
Broken pipe or closed connection

### ISSUE THREAD

**Issue by winfan** [php-amqplib/php-amqplib#353]
thrown in /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 190
[2016-01-04 22:06:48 *15484.3]	WARN	zm_deactivate_swoole: Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:190
Stack trace:
#0 /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(336): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\x16\x00<\x00(\x00\x00\rD...')
#1 /data/www/Device/restApi/vendor/videlalvaro/php-amqpl
[2016-01-04 22:06:48 *15483.7]	WARN	zm_deactivate_swoole: Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:190
Stack trace:
#0 /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(336): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\x16\x00<\x00(\x00\x00\rD...')
#1 /data/www/Device/restApi/vendor/videlalvaro/php-amqpl
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /data/www/Device/restApi/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:190

**Comment by Enleur** [comment]
Seems that you rebooted a rabbitmq server

**Comment by manchicken** [comment]
You should probably handle closed connections, that's not an uncommon phenomenon.

**Comment by novaku** [comment]
@Enleur i have the same problem, and yes i have restart rabbitmq server, how do i remove this logs? every minutes the log file is increasing 2-4GB!!!!
Need your help here if you know the solution..

**Comment by Enleur** [comment]
@novaku I made Reconnect wrapper, that catches an exception, reconnects and retries the last operation. Works fine

**Comment by athlan** [comment]
@Enleur this budle is not well documented. Can you provide the solution, how to write such wrapper? Are you creating own command or using exiting functionality/events/interceptors?

**Comment by valerianpereira** [comment]
@novaku Can you share the snippet?

**Comment by SunnnyGohil** [comment]
hello @enleur 
can you share Reconnect wrapper created by you?

**Comment by vishal461** [comment]
Hello All I am facing the same problem when installing rabitmq on windows following error occured when I am trying to comment rabbitmq

Type: PhpAmqpLib\Exception\AMQPRuntimeException

Message: Broken pipe or closed connection

Filename: C:\xampp\htdocs\CodeIgniter\vendor\romainrg\codeigniter-php-amqplib\PhpAmqpLib\Wire\IO\StreamIO.php

**Comment by ebuildy** [comment]
I am facing this as well, I was connecting without username/password, fixed by using "guest" / "guest"

**Comment by dwiyudirayia** [comment]
> @enleur Can you share the snippet?

Do you have snippet how to handle that?
