### ISSUE TITLE
Release 2.6.0 issue

### ISSUE THREAD

**Issue by roelmonnens** [php-amqplib/php-amqplib#355]
When I require this tag in composer **_composer require videlalvaro/php-amqplib:2.6.0_**
or when I download release 2.6.0: https://github.com/videlalvaro/php-amqplib/archive/v2.6.0.zip

I don't get the [last commits](https://www.dropbox.com/s/r4295gvvhk28jmv/Screenshot%202016-01-08%2013.55.46.png?dl=0) made in that release.
There are no constants voor delivery-mode in AMQPMessage

Could somebody fix this or put me in the correct direction to fix it myself?

**Comment by postalservice14** [comment]
Master won't match the tag for v2.6.0.  You'll have to wait until a v2.6.1 release is cut.  Until that happens, you can run `composer require videlalvaro/php-amqplib:dev-master` as a workaround.

**Comment by nubeiro** [comment]
@postalservice14 https://github.com/php-amqplib/php-amqplib/compare/8a6e89ad46130eb365b7f57d313f2a795f5e3269...master changes in diff seem not to break anything.

**Comment by postalservice14** [comment]
I just release version `2.6.1` which should have the changes you need in it.  Thanks!
