### ISSUE TITLE
Find a new maintainer for the project

### ISSUE THREAD

**Issue by videlalvaro** [php-amqplib/php-amqplib#356]
As you might know, I'm leaving the company that makes RabbitMQ https://groups.google.com/forum/#!topic/rabbitmq-users/-byffkRnI2w, so I will have even less time to take care of this project. Therefore I'm opening this issue so the community helps with finding a new maintainer(s) for the project.

While I would like to have a stronger say on who should take care of the project, I would ask contributors and users to propose who you think would be a great candidate. Please comment on this issue and help find that person.

Besides from knowing PHP, you must be very familiar with at least these concepts: http://www.rabbitmq.com/tutorials/amqp-concepts.html

**Comment by ChristianRiesen** [comment]
I'd be very much interested in chiming in here for both the lib and the bundle.

**Comment by videlalvaro** [comment]
I must add that maintaining these libraries is far from "I want to quickly push the features I like", but it's about not breaking things for users first and foremost. With over 2MM downloads from packagist, this library is heavily used in the community, this means changing an API because someone doesn't like "snake case" vs. "camel case", it's a nono, unless you provide a migration path, and so on.

I don't want to scare anyone, and yes, I haven't been the best maintainer out there, but think twice before accepting the role of maintainer of a library.

**Comment by Enleur** [comment]
@fprochazka @ehberg @eexit @roihq you guys are most active contributors according to https://github.com/videlalvaro/php-amqplib/graphs/contributors?from=2010-09-12&to=2016-01-18&type=c

**Comment by videlalvaro** [comment]
@Enleur Thanks, I would ping @postalservice14 as well.

Also don't forget https://github.com/videlalvaro/RabbitMqBundle

**Comment by postalservice14** [comment]
@videlalvaro I'd be interested.  Maybe we can find some time to chat over Google Hangouts or Skype or something....

Also, where are you headed next career-wise?  Just curious...

**Comment by nubeiro** [comment]
I'm willing to help on the project.

**Comment by eexit** [comment]
Hello,

It is a real pleasure to help and contribute to this project but I don't feel comfortable enough with the low-level understanding of this library to accept this role. I'd much rather help contribute to a newer version of this piece of software where I could get easier and more gradually into it.

@videlalvaro Thanks for your work here and I hope I'll get to talk to you IRL in the future as you sneaked out during last PHP Forum ;)

**Comment by videlalvaro** [comment]
@postalservice14 @nubeiro @eexit we could find a balance between a couple of maintainers of course. Some people would need to understand the low level parts of the library related to networking and AMQP frame handling. The rest is mostly small bugs + stylistic changes and so on that people keep contributing

**Comment by nubeiro** [comment]
Hi, I'm willing to start working on issues and help with maintenance, I'm using RabbitMQ and this lib, so I think that's the least I can do to give back. I do like the idea of proposing most active contributors as maintainers.

**Comment by videlalvaro** [comment]
@nubeiro there's still this week to go and see what's the response from the community is, then we can decide who else is added as committer.

**Comment by postalservice14** [comment]
@videlalvaro I agree with the multiple maintainers idea.  I think it helps spread the load as well.

**Comment by seaneble** [comment]
I was rather shocked by this topic, but I'm glad your moving in the direction of a stable solution. As a pure "basic_consume()" instance (never contributed anything so far here) I can only agree that multiple maintainers would benefit the project and make it more dependent for everybody. Keep up the good work!

**Comment by RoyHP** [comment]
Good luck with the career move.

**Comment by mablae** [comment]
@videlalvaro Thanks for all work on this awesome lib. As you stated it is widely used. I hope it finds a good solution for future! Also good luck, whatever you're up to now. :heart:

**Comment by skirmis** [comment]
:+1:

**Comment by videlalvaro** [comment]
@ChristianRiesen @postalservice14 @nubeiro @eexit so, what do you guys think about becoming joint maintainers? Of course you will have to discuss how to collaborate, who merges what, and so on

**Comment by theintz** [comment]
If there is a junior position available, I'd gladly take that :)

**Comment by nubeiro** [comment]
I'm all in for working as a team. @videlalvaro : can you please check if https://github.com/videlalvaro/php-amqplib/blob/master/CONTRIBUTING.md is still valid? 
Should we add information about how project is maintained there? Or should we just create a pull request adding a MAINTAINERS.md doc?

**Comment by postalservice14** [comment]
@videlalvaro Works for me.

@nubeiro yeah, once we've been made maintainers, I think creating a MAINTAINERS.md file wouldn't be a bad idea.  I'm not sure the CONTRIBUTING.md file would need to be updated, unless there is something wrong with it.

**Comment by stevenscg** [comment]
@videlalvaro As others have said, thanks for all your great work on this library over the years! Good luck with the new post.

**Comment by DeRain** [comment]
@videlalvaro Thank you for this amazing library. I will be glad to help as co-developer/junior. Because i'm not very familiar with AMQP protocol.

**Comment by videlalvaro** [comment]
Based on feedback received on this issue, today I've added @postalservice14 and @nubeiro as collaborators with push access, I'd assume this gives the right to merge PRs?

In any case, the list of collaborators is not definitive, so if any of you thinks I've missed you, let me know, so I can add you there.

**Comment by videlalvaro** [comment]
Also once things become more active I can remove the "abandoned" tag from composer

**Comment by nubeiro** [comment]
good to know,  thanks a lot.

**Comment by videlalvaro** [comment]
@nubeiro please discuss as you go with @postalservice14 so you can start building up a good collaboration relationship

**Comment by postalservice14** [comment]
@videlalvaro great thanks!  I can merge...

@nubeiro and @videlalvaro I've created a new github organization called `php-amqplib`, so the new project would become `php-amqplib\php-amqplib`.  I think it might be a good idea to transfer this repo to that organization so it is pulled off your personal github account.  Makes it easier to adjust maintainers and collaborators for open source projects.

What do you guys think of that?

**Comment by videlalvaro** [comment]
makes sense for me

**Comment by nubeiro** [comment]
Count me in ;)

**Comment by videlalvaro** [comment]
@postalservice14 do I have admin rights on this org? I'm ready to do the transfer

**Comment by postalservice14** [comment]
@videlalvaro yeah, you and @nubeiro should have admin rights...  Are you not able to make the transfer?

**Comment by postalservice14** [comment]
@videlalvaro can you update packagist to point to this new repo?  Not sure if there is a way to keep the old one abandoned and point people to the new one or not?  The transition for people might be a little rough unfortunately. :-/

**Comment by pierrre** [comment]
Will you move https://github.com/videlalvaro/RabbitMqBundle to this new organization?

**Comment by videlalvaro** [comment]
@postalservice14 @nubeiro what are your packagist user names?

**Comment by postalservice14** [comment]
@videlalvaro mines `postalservice14`

**Comment by nubeiro** [comment]
@videlalvaro mine is nubeiro

**Comment by postalservice14** [comment]
Okay, I think we may be good now.   Base on the suggestions here: https://github.com/composer/packagist/issues/47#issuecomment-130599468

I've marked the old package on packagist as abandoned and pointed to the new package `php-amqplib/php-amqplib`.  @nubeiro you are added as a maintainer of that as well.

I think that wraps up the migration...  Am I missing anything?

**Comment by pierrre** [comment]
@postalservice14 yes, https://github.com/videlalvaro/RabbitMqBundle still uses `videlalvaro/php-amqplib`

**Comment by videlalvaro** [comment]
@postalservice14 why did you do that? I had already changed the URL of the videlalvaro package on packagist

**Comment by videlalvaro** [comment]
@postalservice14 oh, so I get it, packagist doesn't change the actual package URL

**Comment by videlalvaro** [comment]
@postalservice14 can you add me on the new package as well on packagist?

**Comment by videlalvaro** [comment]
@pierrre the bundle is going through a similar process now, I've asked the volunteers for their confirmation before adding them as maintainers, then we should do a similar move

**Comment by postalservice14** [comment]
@videlalvaro yeah, you got it.

**Comment by videlalvaro** [comment]
Thanks, I think we can close this issue then?

**Comment by videlalvaro** [comment]
BTW, please, without much fuss and fights, let's add a CoC to the project? what do you think?

**Comment by postalservice14** [comment]
@videlalvaro yeah we can close it.  I've invited you to a Gitter chatroom where @nubeiro and I are talking about what are plans are for the package.  Let's chat about CoC there as well....
