### ISSUE TITLE
StreamIO doesn't call restore_error_handler when an error occurs

### ISSUE THREAD

**Issue by gcalore** [php-amqplib/php-amqplib#378]
As the title says, in the `StreamIO::connect` method, if something wrong happens when calling `stream_socket_client`, an exception is thrown and the `restore_error_handler` is never called.

This means that if there's a problem when connecting, and I don't want to terminate the application but continue with the normal flow of things, the custom error handler will pick up anything from that point onwards instead of the error handlers you might have defined in your application.

Luckily `AMQPSocketConnection` doesn't use custom error handlers, so I ended up using that.

I have no idea atm of what could be the solution to this problem, but I thought at least to report it.

**Comment by postalservice14** [comment]
As far as I can tell, it is being called.  If the custom error handler returns null, this one gets called: https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L132

If the custom error handler doesn't return null and throws an exception, this one get's called: https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L318

Am I missing something?

**Comment by gcalore** [comment]
Maybe I am missing something. I'm pretty sure the library handler was picking up errors from the application I'm working on, but maybe something else is going on. I'll double-check later and let you know.

**Comment by postalservice14** [comment]
Are you using the latest version of php-amqplib?

**Comment by gcalore** [comment]
I'm using version 2.6.1, on PHP 5.6.18.

I've been looking at this again, I didn't notice the call inside the error_handler, my bad. But the problem is still there.

I've been debugging this with invalid connection parameters (I simply turned off my rabbitmq server), and I see that the restore call inside the handler is executed as it should be, but somehow it still goes inside the error handler again during the same request with a completely unrelated error. It's like the restore function is completely ignored... my impression is that it's some odd php behaviour.

I wrote some code to test this outside my application, just in case:
https://gist.github.com/gcalore/3c5c67e140734ee89e5c

Try running `test.php` with a running RabbitMQ server that accepts the credentials set in the file, and then run it with the server turned off.

**Comment by postalservice14** [comment]
Interesting, looks like the `restore_error_handler` isn't working when called from the error handler itself.  I have a fix.  Just running it through some tests now...  Thanks for the catch.

**Comment by postalservice14** [comment]
PR is open, any chance you can make sure it fixes your issue? https://github.com/php-amqplib/php-amqplib/pull/379

**Comment by gcalore** [comment]
Yes, the try-catch thing you added seems to do the trick :+1:
