### ISSUE TITLE
memory leaks on rpc-fetch event

### ISSUE THREAD

**Issue by mshallop** [php-amqplib/php-amqplib#385]
Hi - 

I have a production app where my consumers (aka brokers) are persistent apps that consume requests from various clients.  

I've got a couple PHP classes I wrote for instantiating a new broker client and publishing a request and consuming the subsequent response.  They're pretty simple class clients that are just wrappers around slightly-expanded demo code.  But they work.

I've been doing some testing where I submit a fetch request to my read-broker (my brokers are somewhat crud-based) and I'm able to reproduce a memory leak consistently in the persistent application.  If I run the same operation, using just the class-instantiation code for my framework, basically performing the exact same work/queries, but without traveling through the amqp-layer, I get zero bytes leaked.

This was brought up because a new client, under node.js, just pounded the system with 1,800 concurrent requests and the whole node blew itself senseless as a result.  We spun-down his request to about 40 queries and were seeing the leaks accumulating as a function of the amount of data being returned.  With 40 queries executing sequentially, leaks were consistent at about 67M lost per run.

If I refactor the query, 1 query returning 40 records, the leak is reduced significantly to about 0-200K per request.

When I look the process memory map for the broker, I see an anon-process accumulating the leak in the same increments reported by /proc/pid/status -- but, interestingly, the anon memory location is in the low-order 8-bytes of the address dump probably because anon is swap (not file) backed so it's being managed by the swapd:

Address           Kbytes Mode  Offset           Device    Mapping
0000000000400000    8144 r-x-- 0000000000000000 008:00005 php5
0000000000df3000     644 r---- 00000000007f3000 008:00005 php5
0000000000e94000      52 rw--- 0000000000894000 008:00005 php5
0000000000ea1000     116 rw--- 0000000000000000 000:00000   [ anon ]
**000000000195f000    9768 rw--- 0000000000000000 000:00000   [ anon ]**
00007f6b3485a000      44 r-x-- 0000000000000000 008:00005 libnss_files-2.19.so
00007f6b34865000    2044 ----- 000000000000b000 008:00005 libnss_files-2.19.so
00007f6b34a64000       4 r---- 000000000000a000 008:00005 libnss_files-2.19.so
00007f6b34a65000       4 rw--- 000000000000b000 008:00005 libnss_files-2.19.so

run the broker-request a few (3-4) times (returns 134 short records of containing about 10 fields each) in about 0.15 seconds...

Address           Kbytes Mode  Offset           Device    Mapping
0000000000400000    8144 r-x-- 0000000000000000 008:00005 php5
0000000000df3000     644 r---- 00000000007f3000 008:00005 php5
0000000000e94000      52 rw--- 0000000000894000 008:00005 php5
0000000000ea1000     116 rw--- 0000000000000000 000:00000   [ anon ]
**000000000195f000   10536 rw--- 0000000000000000 000:00000   [ anon ]**
00007f6b3485a000      44 r-x-- 0000000000000000 008:00005 libnss_files-2.19.so
00007f6b34865000    2044 ----- 000000000000b000 008:00005 libnss_files-2.19.so
00007f6b34a64000       4 r---- 000000000000a000 008:00005 libnss_files-2.19.so
00007f6b34a65000       4 rw--- 000000000000b000 008:00005 libnss_files-2.19.so

Now, I know PHP is not supported to be persistent blah-blah-blah but it is in this app.  In the past, I've reduced the leaks to minimal consumption by forking off the events and writing the return datasets to shmem.  This worked great.

However, in this new deployment, I have events in AWS which need to publish their own requests back to a second data-center -- meaning that I can't use the fork() paradigm because the event forks, then at some point, a new request is published to the remote location, dies, and it takes-down the parent on close().  (Known issue.)

Nothing I'm seeing in the libs show pconnect() being invoked which is the work-around for this issue.  Would be nice to be able to pass this back as an option when instantiating the AMQP object.  Oh, also, I'm using AMQPSSLConnection in my brokers.

Anyway, I'm going to see if I can't fork() deeper in the framework stack, when I'm making the remote request, so as to perhaps have the memory leak discarded on SIGCLD.

I can make my code stubs available to you if you like.  Not sure how/what/if you'd want to proceed.

Thanks!

--mike

**Comment by mshallop** [comment]
I'm trying to compensate for the leakage by using pcntl_fork() at the event level in my broker-code. 

The event forks a child which makes no additional amqp requests, just processes data. However, when the child dies and the parent resumes processing, the SIGCLD is closing the parent's AMQPSSL connection:

[13-Apr-2016 15:36:30 America/Los_Angeles] PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:207
Stack trace:
#0 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(149): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#1 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(508): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel( in /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 207

Googling the issue (I made a reference in the OP about this being a "known" issue) recommends that you use pconnect() so that the connection persists across SIGCLD.

**Comment by lukebakken** [comment]
If you'd like to provide a complete example that reproduces this memory leak, please do so and re-open this issue. Thank you!

**Comment by mshallop** [comment]
Nah.  I've mitigated the issue with a code work-around that limits the number of events an RPC child-daemon broker will process before I kill it off... 

FWIW, I use a combination of RPC and Simple queues, both of which sit atop of my framework class instantiation stack.  RPC queues **always** leak while the Simple queues just keep going forever with 0-bytes leaked.  I was hoping moving to PHP7 would also mitigate the leakage but nope.

Best!

**Comment by lukebakken** [comment]
Great thanks for letting us know.
