### ISSUE TITLE
AMQPLazyConnection not working

### ISSUE THREAD

**Issue by lulco** [php-amqplib/php-amqplib#390]
I am trying to create AMQPLazyConnection and AMQPChannel

```
$connection = new \PhpAmqpLib\Connection\AMQPLazyConnection();
$channel = new \PhpAmqpLib\Channel\AMQPChannel($connection);
```

But I get an error:
`Call to a member function debug_method_signature1() on null` on AbstractConnection.php line 480:

```
$this->debug->debug_method_signature1($method_sig);
```

I think the problem is that $debug is initialized in method connect() of AbstractConnection on the line 200 as part of Channel construct:

```
parent::__construct($this, 0);
```

And this is too late.

**Comment by postalservice14** [comment]
Yeah, if you do it that way, you'll need to connect before creating a new `AMQPChannel` object.

A better way (and I think the way it's documented) is to create channels like this:

```php
$connection = new \PhpAmqpLib\Connection\AMQPLazyConnection();
$channel = $connection->channel();
```

**Comment by lulco** [comment]
Thank you very much, I was trying to create Channel without calling connect() method, but now I see it is not possible.

**Comment by prolic** [comment]
The connect method is protected and therefore cannot be called from outside.
