### ISSUE TITLE
stream_socket_client fails to connect to RabbitMQ SSL listener on PHP 5.5.34

### ISSUE THREAD

**Issue by oldpeculier** [php-amqplib/php-amqplib#394]
I set up 2 servers.  One server (A) is running a NGINX site on HTTPS, a Rabbitmq server on an SSL listener and has PHP 5.5.34 installed.  The second server (B) just has PHP 5.5.9 installed.  Using the code further down below, I run the following tests:

1) From server A connect to Server A HTTPS endpoint - Connects
2) From server A connect to Server A AMQP endpoint - Fails (SSL: Connection reset by peer)
3) From server B connect to Server A AMQP endpoint - Connects

I used the same remote IP (public address) and certificates in all tests. The only difference is the version of PHP that the sample code is running on.

It appears something between 5.5.9 - 5.5.34 might have caused stream_socket_client to offend RabbitMQ?

While, this isn't an issue that you all are responsible for (and I probably should have delivered this via some other mechanism), I did feel it was a matter you'd be interested in and I welcome any suggestions, feedback, and/or attempts to duplicate.  The workaround for me is to stay at 5.5.9 for now.

``` php
<?php
$cafile = "/path/to/ca";
$host = "1.1.1.1";
$port = "5671";
//$port ="443";
$context = stream_context_create(array('ssl'=>array('cafile'=>$cafile, 'verify_peer'=>true)));
$sock = stream_socket_client("ssl://".$host.":".$port,$errno,$errstr,10,STREAM_CLIENT_CONNECT,$context);
if ($sock) {
  echo "CONNECTED!\n";
  //$path = "/";
  //fputs($sock,"GET ".$path." HTTP/1.1\r\nhost: localhost\r\nAccept:*/*\r\n\r\n");
  //echo fread($sock,8192);
  //fclose($sock);
} else {
  echo "$errno - $errstr\n";
}
?>
```

**Comment by michaelklishin** [comment]
Having RabbitMQ logs would help immensely with investigating this.

**Comment by oldpeculier** [comment]
Sure.  Here is the RabbitMQ log messages generated on connection attempts using PHP installed from the ondrej/ppa repo. (Which installs 5.5.35; it was updated this morning).  As a note, this issue can more accurately be described as; *stream_socket_client fails to connect to RabbitMQ SSL listener on PHP installs from ondrej/ppa repository*.
```
=CRASH REPORT==== 4-May-2016::15:27:51 ===
  crasher:
    initial call: tls_connection:init/1
    pid: <0.229.0>
    registered_name: []
    exception exit: {function_clause,
                        [{tls_v1,enum_to_oid,
                             [28],
                             [{file,"tls_v1.erl"},{line,404}]},
                         {ssl_handshake,
                             '-dec_hello_extensions/2-blc$^1/1-0-',1,
                             [{file,"ssl_handshake.erl"},{line,1653}]},
                         {ssl_handshake,
                             '-dec_hello_extensions/2-blc$^1/1-0-',1,
                             [{file,"ssl_handshake.erl"},{line,1653}]},
                         {ssl_handshake,dec_hello_extensions,2,
                             [{file,"ssl_handshake.erl"},{line,1653}]},
                         {tls_handshake,decode_handshake,3,
                             [{file,"tls_handshake.erl"},{line,182}]},
                         {tls_handshake,get_tls_handshake_aux,3,
                             [{file,"tls_handshake.erl"},{line,153}]},
                         {tls_connection,next_state,4,
                             [{file,"tls_connection.erl"},{line,454}]},
                         {gen_fsm,handle_msg,7,
                             [{file,"gen_fsm.erl"},{line,505}]}]}
      in function  gen_fsm:terminate/7 (gen_fsm.erl, line 622)
    ancestors: [tls_connection_sup,ssl_sup,<0.206.0>]
    messages: []
    links: [<0.209.0>]
    dictionary: [{ssl_manager,ssl_manager}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 735
  neighbours:

=SUPERVISOR REPORT==== 4-May-2016::15:27:51 ===
     Supervisor: {local,tls_connection_sup}
     Context:    child_terminated
     Reason:     {function_clause,
                     [{tls_v1,enum_to_oid,
                          [28],
                          [{file,"tls_v1.erl"},{line,404}]},
                      {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
                          [{file,"ssl_handshake.erl"},{line,1653}]},
                      {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
                          [{file,"ssl_handshake.erl"},{line,1653}]},
                      {ssl_handshake,dec_hello_extensions,2,
                          [{file,"ssl_handshake.erl"},{line,1653}]},
                      {tls_handshake,decode_handshake,3,
                          [{file,"tls_handshake.erl"},{line,182}]},
                      {tls_handshake,get_tls_handshake_aux,3,
                          [{file,"tls_handshake.erl"},{line,153}]},
                      {tls_connection,next_state,4,
                          [{file,"tls_connection.erl"},{line,454}]},
                      {gen_fsm,handle_msg,7,
                          [{file,"gen_fsm.erl"},{line,505}]}]}
     Offender:   [{pid,<0.229.0>},
                  {name,undefined},
                  {mfargs,{tls_connection,start_link,undefined}},
                  {restart_type,temporary},
                  {shutdown,4000},
                  {child_type,worker}]
```
I set up a repo with a script that will reproduce the issue.  First, launch an ubuntu-14.04 image from Amazon (I tested in us-west-1).  After logging in to your new ubuntu instance, you can run the following linux commands to generate the issue I'm describing.
```bash
sudo apt-get -fy install git
git clone https://github.com/oldpeculier/issue-394.git
cd issue-394
./test.sh # This will install php (5.5.9) from the default repos
```
The script above will install and configure a RabbitMQ server and connect via stream_socket_client to the server without issue.  Then re-run the script with the command `ondrej` to generate the failure scenario.
```bash
./test.sh ondrej  # This will install php (5.5.35) and other packages from ondrej/ppa.
```
You can rerun `./test.sh` after this failure and it will work fine, again.

I would be interested if you get the same behavior.

**Comment by lukebakken** [comment]
The `tls_v1,enum_to_oid` error is well-known. For instance, see [this issue](https://github.com/ruby-amqp/bunny/issues/303#issuecomment-100334906). You don't specify which version of Erlang you are using, but I suspect it is `R16B03`. Please upgrade.
