### ISSUE TITLE
AbstractConnection connect function take 0.25 seconds to execute

### ISSUE THREAD

**Issue by alanyuen** [php-amqplib/php-amqplib#395]
`
$a = \microtime(true);

$host = $this->x_open($this->vhost, '', $this->insist);

echo \microtime(true) - $a;
`

Is it long execute time?

**Comment by lukebakken** [comment]
Both the stream and socket interfaces support the `tcp_nodelay` option, which should address this. If you are using the stream interface, it requires PHP 7.1+ and the next version of this library (or, use `master`)
