### ISSUE TITLE
AMQPChannel::queue_declare() always returns 0 messages

### ISSUE THREAD

**Issue by knikulov** [php-amqplib/php-amqplib#403]
I have found that AMQPChannel::queue_declare() always tells that queue contains 0 messages, even it does not. I can put messages to queue and read them, but can't count them.

my example code:
```
<?php
        define('IN_SCRIPT', null);
        require_once __DIR__ . "/config.php";
        require_once SWVS_ROOT_DIR . "/php/secmon_wvs_common.php";
        require_once SWVS_ROOT_DIR . "/php/amqplib/vendor/autoload.php";

        $queue = "secmon_wvs_scan";

        $connection = new \PhpAmqpLib\Connection\AMQPStreamConnection( SWVS_AMQP_HOST, SWVS_AMQP_PORT, SWVS_AMQP_USER, SWVS_AMQP_PASS, SWVS_AMQP_VHOST );
        $channel = $connection->channel();

        list($name, $jobs, $consumers) = $channel->queue_declare($queue, TRUE, TRUE, FALSE, FALSE);
        echo $name . " " . $jobs . " " . $consumers . PHP_EOL;

        $channel->close();
        $connection->close();
?>
```

rabbitmqctl output:
```
$ sudo rabbitmqctl list_queues
secmon_wvs_scan	39
```

**Comment by zengkun100** [comment]
```php
$response = $this->channel->queue_declare($queue_name, true, true, false, false);
echo $response[1];
```

**Comment by knikulov** [comment]
Looks like here is a lot of magic.

**Comment by knikulov** [comment]
This works not always. Can't understand where the problem is.

**Comment by knikulov** [comment]
$ sudo rabbitmqctl list_queues
Listing queues ...
secmon_wvs_scan	54

$ php ~/secmon_wvs/php/number.php 


Array
(
    [0] => secmon_wvs_scan
    [1] => 0
    [2] => 1
)
0

file "number.php"
``
<?php

        define('IN_SCRIPT', null);
        require_once __DIR__ . "/config.php";
        require_once SWVS_ROOT_DIR . "/php/secmon_wvs_common.php";
        require_once SWVS_ROOT_DIR . "/php/amqplib/vendor/autoload.php";

        $queue = "secmon_wvs_scan";

        $connection = new \PhpAmqpLib\Connection\AMQPStreamConnection( SWVS_AMQP_HOST, SWVS_AMQP_PORT, SWVS_AMQP_USER, SWVS_AMQP_PASS, SWVS_AMQP_VHOST );
        $channel = $connection->channel();

        $asdasd = $channel->queue_declare($queue, TRUE, TRUE, FALSE, FALSE);
        print_r($asdasd);
        echo $asdasd[1] . PHP_EOL;

        $channel->close();
        $connection->close();
?>
``

**Comment by knikulov** [comment]
I rewrote this example in python and got the same result. Looks like it's not php-amqplib problem.

**Comment by knikulov** [comment]
Solution is in using `basic_get` instead of `basic_consume`. It looks like `rabbitmq-server` contains a bug (or an undocumented feature) making him to return zero message count when there are registered consumers.

**Comment by videlalvaro** [comment]
It's not a bug. Message count for queue declare is about ready messages.
This means messages that have been sent to consumers and are pending an ack
are not accounted for. Whenever you need to find out if something is a bug
or not, check the AMQP spec.

**Comment by knikulov** [comment]
Can I force the server to stop sending messages while waiting for consumer to return an ack?

**Comment by videlalvaro** [comment]
re: ack, read about basic_qos on the RabbitMQ docs
