### ISSUE TITLE
Memory Leak with confirm_select(false)

### ISSUE THREAD

**Issue by mfreedman** [php-amqplib/php-amqplib#406]
When publishing with confirm_select(false) memory increases until it runs out.  With nowait = true memory does not increase.  This occurs on basic_publish along with batch_basic_publish.

**Comment by lukebakken** [comment]
I can't reproduce using the attached code - memory use by the `php` process remains constant.

[amqp_publisher_with_confirms_mandatory.php.txt](https://github.com/php-amqplib/php-amqplib/files/1637097/amqp_publisher_with_confirms_mandatory.php.txt)
