### ISSUE TITLE
Get Unack'd Message Count From Consumer Side?

### ISSUE THREAD

**Issue by mfreedman** [php-amqplib/php-amqplib#407]
When initially starting a consumer, and using a prefetch of 20, the prefetch fills up and $channel->getMethodQueue() is available to see the messages pending.  

Once that queue drops to 0, it never seems to populate again even though there are unack'd messages stored with the consumer.

Maybe I'm misunderstanding the protocol or something, but aren't these unack'd messages already on the consumer?

**Comment by lukebakken** [comment]
Please re-open this if you can produce a small code sample to demonstrate your issue. The following statements aren't clear -

> Once that queue drops to 0

I'm assuming "that queue" is the queue returned by `getMethodQueue`. How are you reading the messages there?

> it never seems to populate again

RabbitMQ won't deliver more messages until the first 20 are ack'd, if you have the consumer configured for manual acknowledgements.
