### ISSUE TITLE
StreamConnection does not time out

### ISSUE THREAD

**Issue by prolic** [php-amqplib/php-amqplib#408]
I have the following scenario:

Push 5 messages to a queue, and try to consume 10.

When using php amqp extension, I receive an exception like: "Consumer timeout exceed".

When using php-amqplib SocketConnection, I receive an exception like: "Error reading data. Received 0 instead of expected 7 bytes". I can catch that and turn into a more readable exception.

When using php-amqplib StreamConnecton, I do not receive any Exception, the consumer just hangs forever, which is highly undesired.

**Comment by Xedecimal** [comment]
I believe the issue you are having is in StreamIO::read($len) that says

`$this->select(null, null);`

This goes down to 

stream_select($read, $write, $except, null, null);

Finally you'll see that 

![image](https://cloud.githubusercontent.com/assets/99204/23525904/f48cc8d4-ff44-11e6-9927-2d2f92343cc8.png)

and voila, frozen processes for all!

**Comment by lukebakken** [comment]
Please see #423. If you could test out that patch, it would be very helpful. Thanks!

**Comment by lukebakken** [comment]
Assuming this has been addressed by #423 and will ship in `2.8.0`. Please test an RC that will be available this week.
