### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by dopesong** [php-amqplib/php-amqplib#411]
Message from future?

https://github.com/php-amqplib/php-amqplib#new-maintainers-2016-10-02

**Comment by angelxmoreno** [comment]
rofl, was just about to point this out

**Comment by michaelklishin** [comment]
Given that the new maintainer is from a country that uses the YYYY-MM-DD format, #417 is not a solution and to me at least seems to be a jerk move. Either use an unambiguous date format or I will close this.
