### ISSUE TITLE
StreamIO can wait for data indefinitely

### ISSUE THREAD

**Issue by velvetcat** [php-amqplib/php-amqplib#416]
We face the situation when this piece of code in `StreamIO::read()`:

```
               if ($this->canDispatchPcntlSignal) {
                    // prevent cpu from being consumed while waiting
                    if ($this->canSelectNull) {
                        $this->select(null, null);
                        pcntl_signal_dispatch();
                    } else {
                        usleep(100000);
                        pcntl_signal_dispatch();
                    }
                }
```

hangs when the connection is broken. It blocks at `select(null, null)` so it is even unable to check the heartbeat.

Please consider introducing something like `$this->select(0, 100000);`

**Comment by cwdt** [comment]
You could reproduce this issue by running a consumer without the "AMQP_WITHOUT_SIGNALS" constant and disabling your network connection.

**Comment by lukebakken** [comment]
Assuming that #423 fixes this. Please test `2.8.0` RC1 that will be available this week.
