### ISSUE TITLE
"Invalid Frame Type" on PHP 7

### ISSUE THREAD

**Issue by azngeek** [php-amqplib/php-amqplib#421]
Hello, i get some strange errors which i do not understand. 

```
Warning: unpack(): Type C: not enough input, need 1, have 0 in /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 194

Call Stack:
    0.0400     367536   1. {main}() /var/www/share/dev/htdocs/.modman/blabla/src/shell/rabbitmq_consumer_products.php:0
    0.1100     816064   2. PhpAmqpLib\Connection\AMQPStreamConnection->__construct(???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???) /var/www/share/dev/htdocs/.modman/blabla/src/shell/rabbitmq_consumer_products.php:67
    0.1200     882360   3. PhpAmqpLib\Connection\AbstractConnection->__construct(???, ???, ???, ???, ???, ???, ???, ???, ???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php:50
    0.1200    1237352   4. PhpAmqpLib\Connection\AbstractConnection->connect() /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:180
    2.3700    1407984   5. PhpAmqpLib\Channel\AbstractChannel->wait(???, ???, ???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:205
    2.3700    1408416   6. PhpAmqpLib\Channel\AbstractChannel->next_frame(???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:328
    2.3700    1408416   7. PhpAmqpLib\Connection\AbstractConnection->wait_channel(???, ???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:217
    2.3700    1408416   8. PhpAmqpLib\Connection\AbstractConnection->wait_frame(???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:555
    4.6700    1408448   9. PhpAmqpLib\Wire\AMQPReader->read_octet() /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:511
    5.1900    1408480  10. unpack(???, ???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:194


Fatal error: Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: Invalid frame type  in /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 514

PhpAmqpLib\Exception\AMQPRuntimeException: Invalid frame type  in /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 514

Call Stack:
    0.0400     367536   1. {main}() /var/www/share/dev/htdocs/.modman/blabla/src/shell/rabbitmq_consumer_products.php:0
    0.1100     816064   2. PhpAmqpLib\Connection\AMQPStreamConnection->__construct(???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???, ???) /var/www/share/dev/htdocs/.modman/blabla/src/shell/rabbitmq_consumer_products.php:67
    0.1200     882360   3. PhpAmqpLib\Connection\AbstractConnection->__construct(???, ???, ???, ???, ???, ???, ???, ???, ???) /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php:50
    0.1200    1237352   4. PhpAmqpLib\Connection\AbstractConnection->connect() /var/www/share/dev/htdocs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:180
```

So any one got a hint for me? Do i need some additional php libraries?

**Comment by lettierimarco** [comment]
#438

**Comment by chrisnoden** [comment]
having same problem with PHP7.1. Having no problems connecting using another AMQP client. Server is RabbitMQ v3.6.5

**Comment by anedisi** [comment]
also have problems with PHP 5.6.29-1+deb.sury.org~precise+1 and rabbit 3.6.5
rolling back to php5.5 works

**Comment by MatthewKingDev** [comment]
Ran into the same issue after deploying to a live box, turns out I had missed some extensions, highlighted when running composer update. This is on PHP7.1 but will apply to all versions. One of the following is needed:

php7.1-intl
php7.1-mbstring
php7.1-bcmath
php7.1-curl

I also updated to dev-master which may have resolved.

**Comment by kathiedart** [comment]
On my end, I get the same when using master too:

2017-03-08T16:42:15+00:00 ERR (3): PId:2551-PHP-API--PhpAmqpLib\Exception\AMQPRuntimeException-*#*-Invalid frame type -*#*-/Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php-*#*-514-*#*-#0 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#1 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 0)
#2 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#3 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(205): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /Volumes/api.dwt/src/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(50): PhpAmqpLib\Connection\AbstractConnection->__construct('u', 'p', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 5)
#6 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Dao/Rabbit/Exchange.php(98): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('h', '5672', 'u', 'p', '/', false, 'AMQPLAIN', NULL, 'en_US', 10, 10, NULL, true, 5)
#7 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Dao/Rabbit/Exchange.php(114): Common\Dao\Rabbit\Exchange->_createConnection(true)
#8 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Dao/Rabbit/Exchange.php(168): Common\Dao\Rabbit\Exchange->_getReadConnection()
#9 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Dao/Rabbit/Exchange.php(65): Common\Dao\Rabbit\Exchange->_getReadChannel()
#10 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Message/Abstract.php(202): Common\Dao\Rabbit\Exchange->__destruct()
#11 /Volumes/api.dwt/src/php/vendor/dwt/commonCode/src/php/Common/Gateway/QueryBuild.php(84): Common_Message_Abstract->send()
#12 /Volumes/api.dwt/src/php/modules/api/controllers/QueryController.php(418): Common_Gateway_QueryBuild->save(Object(Common_Model_QueryBuild))
#13 /Volumes/api.dwt/src/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Api_QueryController->indexAction_POST()
#14 /Volumes/api.dwt/src/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction_POS...')
#15 /Volumes/api.dwt/src/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Common_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#16 /Volumes/api.dwt/src/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#17 /Volumes/api.dwt/src/php/Bootstrap.php(126): Zend_Application_Bootstrap_Bootstrap->run()
#18 /Volumes/api.dwt/src/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Bootstrap->run()
#19 /Volumes/api.dwt/src/php/application.php(28): Zend_Application->run()
#20 /Volumes/api.dwt/src/public/index.php(1): require('/Volumes/api.dw...')
#21 {main}

**Comment by MatthewKingDev** [comment]
Have you tried composer update? It will report which PHP extensions you're missing.

**Comment by kathiedart** [comment]
Personally have no missing extensions

**Comment by sterichards** [comment]
I am having this issue but **only** when attempting to connect to Amazon MQ

I can run a local RabbitMQ server and using php-amqplib, there is no issue connecting

Local RabbitMQ runs on port 5671

Amazon MQ runs on port 5672

I don't understand what is causing my issue at all

**Comment by AnrDaemon** [comment]
> I am having this issue but **only** when attempting to connect to Amazon MQ
> 
> I can run a local RabbitMQ server and using php-amqplib, there is no issue connecting
> 
> Local RabbitMQ runs on port 5671
> 
> Amazon MQ runs on port 5672
> 
> I don't understand what is causing my issue at all

Having same issue connecting to TLS enabled AMQP server with 3.4.0 lib. Investigating.

**Comment by mkdesignn** [comment]
@AnrDaemon Any luck? I have the same issue but i couldn't resolve it. I'm using laravel + vladimir-yuldashev/laravel-queue-rabbitmq
And when trying to run the command to listen to i'm seeing this error from php side
`Invalid frame type 21`
And from the rabbitMq Server logs i can see this 
```
<0.710.0> TLS server: In state hello at tls_record.erl:564 generated SERVER ALERT: Fatal - Unexpected Message
<0.710.0>  - {unsupported_record_type,65}
```

**Comment by AnrDaemon** [comment]
No luck. Got dragged away, but I have a point to check for you, if you are interested.
Is your certificate contains server name in CN, or only in subjectAltName (DNS:…)?
