### ISSUE TITLE
Channel::waitForConfirm waits timeout per message instead of total

### ISSUE THREAD

**Issue by prolic** [php-amqplib/php-amqplib#428]
When I am in confirm select mode and I send 1000 messages, and give wait timeout = 2, this means it should wait 2 seconds. But the current implementation is wrong and waits 2 seconds per message!

**Comment by prolic** [comment]
ping @michaelklishin

**Comment by michaelklishin** [comment]
@prolic please provide a code example, that's too little information to work with.

While publishing is entirely asynchronous in the protocol, it's not necessarily "wrong" for clients to require timeouts to be per-operation.

**Comment by prolic** [comment]
First of all, this behaviour is not consistent with php-amqp extension.

A code example is maybe too much, just follow the simple use case:

1. publish 1000 messages
2. wait 2 secs for confirmation

- I don't want to wait 2 secs per message, as this would make up to 2000 secs, which is way too long.
- I also don't want to wait 0.002 secs/message, as I don't care how long a specific message needs, I want the block to success within 2 secs.

**Comment by prolic** [comment]
If you want timeout per operation, send a single message and wait for confirmation. It's not reasonable to send 1000 messages and wait for timeout of a single operation.

**Comment by michaelklishin** [comment]
@prolic please post a code example of what you are trying to do. This library is not driven by API choices in the `php-amqp` extension.

While I understand that waiting for a batch at a time is much more efficient, we will not make API changes based on a couple of sentences and a blanket statement that something is "wrong".

**Comment by michaelklishin** [comment]
GitHub code search returns [no results for `waitForConfirm` in this repository](https://github.com/php-amqplib/php-amqplib/search?utf8=%E2%9C%93&q=waitForConfirm&type=).

**Comment by prolic** [comment]
```
$channel->confirm_select();
$channel->basic_publish(new AMQPMessage('foo'), 'test-exchange');
$channel->basic_publish(new AMQPMessage('bar'), 'test-exchange');
$channel->wait(null, false, 2);
```

Does this help?

**Comment by michaelklishin** [comment]
`Channel::wait_for_pending_acks_returns` seems to [do just what you are looking for](https://github.com/php-amqplib/php-amqplib/blob/b7b677d046a9735e0ad940d649feaf38d58c866c/demo/amqp_publisher_with_confirms_mandatory.php#L69).

[Its docs](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L1356) seem to confirm this.

I'm not very familiar with how continuations and confirms are implemented in this client but `Channel::wait` seems to be a generic method that performs an operation with a timeout (in which case it cannot support batching due to protocol semantics).

**Comment by michaelklishin** [comment]
@hairyhum @nubeiro please correct me if I'm wrong ^^^.

**Comment by prolic** [comment]
I will test this tomorrow and let you know.

**Comment by prolic** [comment]
works like a charm, my bad

**Comment by michaelklishin** [comment]
Thank you for reporting back.
