### ISSUE TITLE
iconv_strlen(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by vitorsdcs** [php-amqplib/php-amqplib#433]
I just did a clean install of a Lumen/Laravel application running on PHP 7 inside a Docker container, and added php-amqplib 2.6.3 as a dependency. I'm also running RabbitMQ 3.6.5 inside Docker.

Whenever I attempt to establish a connection with RabbitMQ, I get the following error:

ErrorException in Mbstring.php line 338:
iconv_strlen(): Detected an illegal character in input string
in Mbstring.php line 338
at Application->Laravel\Lumen\Concerns{closure}('8', 'iconv_strlen(): Detected an illegal character in input string', '/var/www/html/vendor/symfony/polyfill-mbstring/Mbstring.php', '338', array('s' => '�', 'encoding' => 'ASCII'))
at iconv_strlen('�', 'ASCII') in Mbstring.php line 338
at Mbstring::mb_strlen('�', 'ASCII') in bootstrap.php line 31
at mb_strlen('�', 'ASCII') in StreamIO.php line 237
at StreamIO->read('7') in AMQPReader.php line 149
at AMQPReader->rawread('7') in AMQPReader.php line 106
at AMQPReader->read('7') in AbstractConnection.php line 508
at AbstractConnection->wait_frame('0') in AbstractConnection.php line 555
at AbstractConnection->wait_channel('0', '0') in AbstractChannel.php line 217
at AbstractChannel->next_frame('0') in AbstractChannel.php line 328
at AbstractChannel->wait(array('10,10')) in AbstractConnection.php line 205
at AbstractConnection->connect() in AbstractConnection.php line 180
at AbstractConnection->__construct('guest', 'guest', '/', false, 'AMQPLAIN', null, 'en_US', object(StreamIO), '0') in AMQPStreamConnection.php line 50
at AMQPStreamConnection->__construct('rabbitmq', '5672', 'guest', 'guest') in QuizController.php line 18
at QuizController->store(object(Request))
at call_user_func_array(array(object(QuizController), 'store'), array(object(Request))) in Container.php line 507
at Container->call(array(object(QuizController), 'store'), array()) in RoutesRequests.php line 593
at Application->callControllerCallable(array(object(QuizController), 'store'), array()) in RoutesRequests.php line 559
at Application->callLumenController(object(QuizController), 'store', array(true, array('uses' => 'App\Http\Controllers\QuizController@store'), array())) in RoutesRequests.php line 533
at Application->callControllerAction(array(true, array('uses' => 'App\Http\Controllers\QuizController@store'), array())) in RoutesRequests.php line 501
at Application->callActionOnArrayBasedRoute(array(true, array('uses' => 'App\Http\Controllers\QuizController@store'), array())) in RoutesRequests.php line 486
at Application->handleFoundRoute(array(true, array('uses' => 'App\Http\Controllers\QuizController@store'), array())) in RoutesRequests.php line 383
at Application->Laravel\Lumen\Concerns{closure}() in RoutesRequests.php line 636
at Application->sendThroughPipeline(array(), object(Closure)) in RoutesRequests.php line 389
at Application->dispatch(null) in RoutesRequests.php line 334
at Application->run() in index.php line 28

I don't know if that helps, but this is the complete output of the $buffer variable inside StreamIO's read() function:

� �capabilitiesF�publisher_confirmstexchange_exchange_bindingst basic.nacktconsumer_cancel_notifytconnection.blockedtconsumer_prioritiestauthentication_failure_closetper_consumer_qostdirect_reply_totcluster_nameSrabbit@b9ae20f5142e copyrightS.Copyright (C) 2007-2016 Pivotal Software, Inc.informationS5Licensed under the MPL. See http://www.rabbitmq.com/platformS Erlang/OTPproductSRabbitMQversionS3.6.5PLAIN AMQPLAINen_US�

Could these special characters be causing the issue? How can I get rid of them?

I've already tried increasing heartbeat, timeout, etc, but nothing works.

**Comment by gectus** [comment]
I have the same problem 8(

**Comment by gectus** [comment]
`[2016-08-24 13:18:26] lumen.ERROR: ErrorException: iconv_strlen(): Detected an illegal character in input string in /var/www/heaven11-storage/vendor/symfony/polyfill-mbstring/Mbstring.php:338
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'iconv_strlen():...', '/var/www/heaven...', 338, Array)
#1 /var/www/heaven11-storage/vendor/symfony/polyfill-mbstring/Mbstring.php(338): iconv_strlen('\x01\x00\x00\x00\x00\x01\xE5', 'ASCII')
#2 /var/www/heaven11-storage/vendor/symfony/polyfill-mbstring/bootstrap.php(31): Symfony\Polyfill\Mbstring\Mbstring::mb_strlen('\x01\x00\x00\x00\x00\x01\xE5', 'ASCII')
#3 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(237): mb_strlen('\x01\x00\x00\x00\x00\x01\xE5', 'ASCII')
#4 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(149): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#5 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#6 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(508): PhpAmqpLib\Wire\AMQPReader->read(7)
#7 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#8 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 0)
#9 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#10 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(205): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#11 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#12 /var/www/heaven11-storage/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(50): PhpAmqpLib\Connection\AbstractConnection->__construct('****', '****', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#13 /var/www/heaven11-storage/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/VladimirYuldashev/LaravelQueueRabbitMQ/Queue/Connectors/RabbitMQConnector.php(22): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('172.17.42.2', '5672', '****', '****', '/')
#14 /var/www/heaven11-storage/vendor/illuminate/queue/QueueManager.php(155): VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector->connect(Array)
#15 /var/www/heaven11-storage/vendor/illuminate/queue/QueueManager.php(135): Illuminate\Queue\QueueManager->resolve('rabbitmq')
#16 /var/www/heaven11-storage/vendor/illuminate/queue/Worker.php(147): Illuminate\Queue\QueueManager->connection('rabbitmq')
#17 /var/www/heaven11-storage/vendor/illuminate/queue/Console/WorkCommand.php(125): Illuminate\Queue\Worker->pop('rabbitmq', NULL, 0, 3, 0)
#18 /var/www/heaven11-storage/vendor/illuminate/queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', NULL, 0, 128, false)
#19 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#20 /var/www/heaven11-storage/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#21 /var/www/heaven11-storage/vendor/illuminate/console/Command.php(169): Illuminate\Container\Container->call(Array)
#22 /var/www/heaven11-storage/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/heaven11-storage/vendor/illuminate/console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/heaven11-storage/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/heaven11-storage/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/heaven11-storage/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/heaven11-storage/vendor/laravel/lumen-framework/src/Console/Kernel.php(76): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/heaven11-storage/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}  
`

**Comment by gectus** [comment]
https://github.com/symfony/polyfill/issues/72

**Comment by anhducbkhn** [comment]
I have same pb :|

**Comment by vitorsdcs** [comment]
I created a [pull request on symfony/polyfill](https://github.com/symfony/polyfill/pull/74) but for some reason the tests are failing. However it solved this problem. If you want a quick fix, try using my fork [vitorsdcs/polyfill](https://github.com/vitorsdcs/polyfill)

**Comment by barmat** [comment]
The polyfill library has a drop in replacement for PHP's `mbstring` extension which is used if it's not installed. If you're able to install it, it should workaround this error.

**Comment by lukebakken** [comment]
Closing - please see @barmat's [workaround](https://github.com/php-amqplib/php-amqplib/issues/433#issuecomment-256239247).
