### ISSUE TITLE
Missing bcmath while installing package using official docker php:5.6 image

### ISSUE THREAD

**Issue by gornostal** [php-amqplib/php-amqplib#436]
# Steps to reproduce:

* `docker run --rm -it php:5.6-fpm bash`
*  Run in container:  
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
php composer-setup.php && \
php -r "unlink('composer-setup.php');"
```
* `./composer.phar require php-amqplib/php-amqplib`

# Actual result:
```
Using version ^2.6 for php-amqplib/php-amqplib
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/php-amqplib v2.6.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/php-amqplib v2.6.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/php-amqplib v2.6.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for php-amqplib/php-amqplib ^2.6 -> satisfiable by php-amqplib/php-amqplib[v2.6.0, v2.6.1, v2.6.2, v2.6.3].


Installation failed, deleting ./composer.json.
```

The official PHP image is based on debian:jessie. 
I couldn't find how to install bcmath extension there. According to the Internet bcmath should be built into `php5`. Source: http://askubuntu.com/a/416875/64612
The same error occurs in Alpine container.

Please advise.

**Comment by alenn-m** [comment]
I have the same problem

**Comment by zf2timo** [comment]
Is the extension installed? Post the output of `php -m`, please.

**Comment by gornostal** [comment]
Extension is not installed.

```
[PHP Modules]
Core
ctype
curl
date
dom
ereg
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

```

**Comment by alenn-m** [comment]
Same here:
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
json
libxml
mbstring
mcrypt
memcached
mongodb
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by zf2timo** [comment]
As you can see, it is required by [php-amqplib](https://github.com/php-amqplib/php-amqplib/blob/a4a77c2e855c36a095a8ae2caa3774e26d72f23c/composer.json#L28). So you have to install it.

**Comment by gornostal** [comment]
I found a solution.
bcmath can be installed with by command inside a container: `docker-php-ext-install bcmath`.
Found here https://github.com/docker-library/php/issues/75

**Comment by angelmsccm** [comment]
Try to install bcmath by "sudo apt-get install php-bcmath" ;) 
It worked for me :)

**Comment by iftikharahmed** [comment]
> I found a solution.
> bcmath can be installed by running this command inside a container: `docker-php-ext-install bcmath`.
> Found here [docker-library/php#75](https://github.com/docker-library/php/issues/75)

This worked for me

**Comment by ramunasd** [comment]
docker dev container as example https://github.com/php-amqplib/php-amqplib/blob/master/docker/php/Dockerfile

**Comment by mohamedhafezqo** [comment]
> I found a solution.
> bcmath can be installed by running this command inside a container: `docker-php-ext-install bcmath`.
> Found here [docker-library/php#75](https://github.com/docker-library/php/issues/75)

Thanks :D

**Comment by ysidro** [comment]
on my case it's install 
`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

[Zend Modules]

`
