### ISSUE TITLE
Documentation on handling exceptions related to network errors/failures/partitions

### ISSUE THREAD

**Issue by kanishkdudeja** [php-amqplib/php-amqplib#439]
Is there are documentation I can refer to on how I can/should handle exceptions related to network errors/failures/partitions and possibly on how I can recover the connections once the code is able to detect it?

**Comment by lukebakken** [comment]
The [RabbitMQ documentation](https://www.rabbitmq.com/partitions.html) has a section on [network partitions](https://www.rabbitmq.com/partitions.html). As for this library, as of version [`2.7.0`](https://github.com/php-amqplib/php-amqplib/releases/tag/v2.7.0) heartbeat checking will detect connection errors and will attempt retries. If that does not meet your needs, please re-open this issue with a specific example showing why not. Thanks!
