### ISSUE TITLE
PHP Notice:  fwrite(): send of 6206 bytes failed with errno=11 

### ISSUE THREAD

**Issue by viavorskii** [php-amqplib/php-amqplib#441]
Hello everybody.

Does anybody know what can be a reason of this problem.
I updated lib to the latest version but the problem is still there. 
Number of messages in the queue is  about 5000.

From log file:
"stderr": "PHP Notice:  fwrite(): send of 6206 bytes failed with errno=11 Resource temporarily unavailable in /srv/www/mtc/releases/20160908171340/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 65[37;41m                                                   [39;49m[37;41m  [PhpAmqpLib\Exception\AMQPTimeoutException]      [39;49m[37;41m  Error sending data. Socket connection timed out  [39;49m[37;41m                                                   [39;49m[32mimport:daemon:handler:start [39m[32m<bundle>[39m[32m [39m[32m<handler>[39mPHP Notice:  fwrite(): send of 19 bytes failed with errno=11 Resource temporarily unavailable in /srv/www/mtc/releases/20160908171340/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 65"

**Comment by blaaat** [comment]
I have exactly the same problems; suddenly large messages or large batches get this exception. 
Started when I updated to 2.6.3 (was on 2.5.2 before)

**Comment by blaaat** [comment]
After a lot of searching in the codebase; this apears to solve the problem for me: 

`	define('AMQP_WITHOUT_SIGNALS', true);
`

**Comment by lingorus** [comment]
$channel->basic_qos(0, 400, false);
It helped me.

**Comment by FractalizeR** [comment]
My code had a problem of creating a second amqp connection and trying to reuse a channel with the same id as was used by the first connection (channel number 1). This also caused fwrite errors when sending data.

**Comment by michaelklishin** [comment]
@FractalizeR channels are scoped per connection. Channel number is very likely a red herring in your case.

**Comment by michaelklishin** [comment]
There can be a lot of different reasons for failing socket writes. We cannot suggest much without a way to reproduce and clear evidence that something in the library is the root cause.
