### ISSUE TITLE
class not found  what's the matter 

### ISSUE THREAD

**Issue by brighten01** [php-amqplib/php-amqplib#442]
Fatal error: Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found in D:\
work\public\amqp_consumer.php on line 9

Call Stack:
    0.0000     242200   1. {main}() D:\work\public\amqp_consumer.php:0

**Comment by zf2timo** [comment]
It looks like you're autoloader isn't loaded/configured properly.

**Comment by brighten01** [comment]
thank you,it must be installed by composer yet!

发自我的 iPhone
