### ISSUE TITLE
php ext-bcmath required

### ISSUE THREAD

**Issue by helloEson** [php-amqplib/php-amqplib#447]
The production environment hosts may does not have bc-mach extension installed.
Could you please update this requirement to Readme.md file?

`# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for php-amqplib/php-amqplib v2.6.3 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
`

**Comment by mente** [comment]
AFAIK this is needed only for php7

**Comment by bouke-nederstigt** [comment]
Actually just ran into this problem as well.
The php 5.6 version from https://launchpad.net/~ondrej/+archive/ubuntu/php  does not include the bcmath and mbstring extensions by default. Without them it's not possible to run composer.

**Comment by nubeiro** [comment]
Readme is already updated in master branch.

**Comment by pixelgaurav** [comment]
the requested PHP extension bcmath is missing from your system
