### ISSUE TITLE
Benchmarking: stream vs socket vs extension

### ISSUE THREAD

**Issue by mente** [php-amqplib/php-amqplib#449]
Hello,

I've created a detailed [benchmark project](https://github.com/mente/php-amqp-benchmark) to compare php-amqplib performance with different options and amqp-ext as comparison.

3 questions:
* why socket connection is so much faster than stream connection?
* if socket connection is comparable to amqp-ext - why it gains so little support inside of the library and bundle?
* does it make sense to include such kind of benchmarks into php-amqplib upstream? It would be easier to detect regressions in performance

**Comment by mente** [comment]
> why socket connection is so much faster than stream connection?

Found an answer - socket connection is using `TCP_NODELAY`. Btw same [has landed](https://bugs.php.net/bug.php?id=46360) for stream connection in php 7.1 . Makes sense to update as well

**Comment by mirfilip** [comment]
What about the third bullet? It really makes sense to include perf test in the package itself, maybe even chain it to CI.

**Comment by mente** [comment]
I lack feedback here to be able to contribute. If at least one  maintainer appears here to say "yes, we would like to have it" then I will invest into PR
