### ISSUE TITLE
Not able to connect to the rabbitmq server via an aws load balancer with SSL

### ISSUE THREAD

**Issue by akang1** [php-amqplib/php-amqplib#451]
I have been trying to connect to my rabbitmq server with SSL through the AWS’s elastic load balancer but i am getting the following error:

Error reading data. Received 0 instead of expected 7 bytes

When I monitor the traffic on the rabbitmq server and look at the LB’s logs, no traffic gets through to the rabbit server nor to the LB.

Here is the code I am using.

```
<?php
require_once 'composer/vendor/autoload.php';
header('Content-type: text/plain');

$port = '5671';
$user = 'rabuser';
$password = 'rabpw';
$sslIp = 'rabbit-server.com';
$ip = 'rabbit-server.com';

$sslOptions = array ();

define('AMQP_DEBUG', true);

echo 'rand: ' . rand() . "\n";
try {
 echo 'connected to SSL connection' . "\n";
 $sslConnection = new \PhpAmqpLib\Connection\AMQPSSLConnection($sslIp, $port, $user, $password);
 $sslConnection->close();
}
catch (Exception $e) {
  echo "error" . "\n";
  echo $e->getMessage() . "\n";
}
?>
```

I did not set "sslOptions” since it can use the trusted certificate on the machine I am running this on (at least that is what I think but I could be wrong)

Any help/advice is much appreciated.

PS. when i use curl on the https/ssl port, i get the correct SSL/certificate response. I really believe that the load balancer is set up correctly with the certificate and the problem is due to the way I am using the library.

**Comment by michaelklishin** [comment]
There is a TLS troubleshooting guide on rabbitmq.com and you have already posted this to rabbitmq-users. Please stick to using the mailing list for questions.

**Comment by michaelklishin** [comment]
So you haven't provided `sslOptions` (or set anything related to TLS as far as I can tell with my limited PHP experience), not sure if that should be done or not but on rabbitmq-users you claim that this is a client library bug.
