### ISSUE TITLE
how consumer will pick high priority msg at first ?????

### ISSUE THREAD

**Issue by saravana91mobiles** [php-amqplib/php-amqplib#452]
publisher.php

$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();

$channel->queue_declare('mytestq', false, true, false, false, ['x-max-priority' => ['I', 25]]);

for($t=0;$t<10;$t++)
{	
$data = "test".$t;
$msg = new AMQPMessage($data,
                        array('delivery_mode' => 2, 'priority' => $t) # make message persistent
                      );
$channel->basic_publish($msg, '', 'mytestq');
echo " [x] Sent ".$data."'\n";
}

$channel->close();
$connection->close();

consumer.php

$channel = $connection->channel();
$channel->queue_declare('mytestq', false, true, false, false, array('x-priority' => array('I', 5)) );
echo ' [*] Waiting for messages. To exit press CTRL+C', "\n";
$callback = function($msg) {
    echo " [x] Received ", $msg->body, "\n";
};
$channel->basic_consume('mytestq', '', false, true, false, false, $callback);

i pushed 10 msg with different priorities ... but how can i get in consumer ???? pls help me ??

**Comment by michaelklishin** [comment]
Consumer doesn't have control over what gets delivered to it first, RabbitMQ does. Consumer simply subscribes for deliveries and that's it.

**Comment by michaelklishin** [comment]
On an unrelated note, 25 priorities is an overkill. Values no greater than 5 or 10 is what team RabbitMQ recommends.

**Comment by michaelklishin** [comment]
If your question really is "why can't I see any priority-based delivery", that's because when there is a consumer online, messages are delivered to it immediately without delaying. See [Priority Queues documentation guide](http://www.rabbitmq.com/priority.html) which lists consumer interaction and limitations.

**Comment by saravana91mobiles** [comment]
yes my question is - why can't I see any priority-based delivery??

as per http://www.rabbitmq.com/priority.html

we cant see the priority-based delivery  but it will happen automatically when the Que size is bigger ???
