### ISSUE TITLE
Unable to install via Composer

### ISSUE THREAD

**Issue by steveWinter** [php-amqplib/php-amqplib#454]
When I try to require this package using composer I seem to end up in a circular reference issue between the old and new packages:

```
Steves-MacBook-Pro-3:rabbitMQ SteveWinter$ composer require php-amqplib/php-amqplib
Using version ^2.6 for php-amqplib/php-amqplib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
```

Looking at the composer.json file in the repo it seems to correctly named, but I can't get composer to install it. Any ideas?

**Comment by zf2timo** [comment]
It looks like you have the package `videlalvaro/php-amqplib` in your composer.json. You should remove it.

**Comment by steveWinter** [comment]
Doh...!! thanks for the rely, you were quite correct. Apologies for wasting your time.

**Comment by zf2timo** [comment]
You're welcome.
