### ISSUE TITLE
Is the master branch ready for production?

### ISSUE THREAD

**Issue by wvdweij** [php-amqplib/php-amqplib#457]
I'm sorry if I'm asking a trivial question but do you use the master branch in production environments? I've tried various times to use 2.6.3 in production but I keep running into some performance issues. Last issue is probably resolved with #435. But for now I'm still on 2.4.1.

I really would like to switch because the master and newer versions have some significant changes but I'm a little bit afraid to switch to the master branch for my production environment. Could someone give me advise on this matter?

**Comment by Fogush** [comment]
Is there any news on this?

**Comment by michaelklishin** [comment]
There is only one valid answer for this: try it for yourself, in your actual environment.
