### ISSUE TITLE
Default Payload size 

### ISSUE THREAD

**Issue by hellracer** [php-amqplib/php-amqplib#465]
I have a very basic publisher code with JSON data as a message payload, it seems like there's a a message capped that the library is imposing that I can't really see, could anyone shed some light on this please to triage the issue, the publisher code look something like this.

function queueMessage($mobileno,$message,$port,$gwip){
        try {
                $exchange = 'router';
                $queue = 'Incoming';
                $connection = new AMQPStreamConnection(HOST, PORT, USER, PASS, VHOST);
                $channel = $connection->channel();
                $channel->queue_declare($queue, false, true, false, false);
                $channel->exchange_declare($exchange, 'direct', false, true, false);
                $channel->queue_bind($queue, $exchange);
                $msgcode = array("mobile" => $mobileno,"message" => $message,"port" => $port,"gwip" => $gwip);
                $msg = json_encode($msgcode);
                //$message = new AMQPMessage($msg, array('content_type' => 'text/plain', 'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT));
                $message = new AMQPMessage($msg);
                $channel->basic_publish($message, $exchange);
                $channel->close();
                $connection->close();
                return true;
        } catch(Exception $e) {
                return false;
        }
}

**Comment by hellracer** [comment]
The problem i'm experiencing is if the message I ingest in the queue is small enough the code above works expectedly but, when the message is quite large then there's no error or something it's just that the message was not ingest in Queue

**Comment by michaelklishin** [comment]
Your code publishes then closes the connection. It has a false assumption that when `basic_publish` returns all data was received and processed by the broker. That is not necessarily the case. Use [Publisher Confirms](http://www.rabbitmq.com/confirms.html).

**Comment by hellracer** [comment]
Hi Michaelklishin,

Did you mean this? I'll just execute wait_for_pending_acks method before closing the connection? thanks!

$channel->basic_publish($message, $exchange);
$channel->wait_for_pending_acks(); 
$channel->close();
$connection->close();

**Comment by hellracer** [comment]
After reading the docs regarding Publisher confirms that code now look like this
function queueMessage($mobileno,$message,$port,$gwip){
        try {
                $exchange = 'router';
                $queue = 'Incoming';
                $connection = new AMQPStreamConnection(HOST, PORT, USER, PASS, VHOST);
                $channel = $connection->channel(); /* Publisher Confirm Mode */
                $channel->queue_declare($queue, false, true, false, false);
                $channel->confirm_select();
                $channel->exchange_declare($exchange, 'direct', false, true, false);
                $channel->queue_bind($queue, $exchange);
                $msgcode = array("mobile" => $mobileno,"message" => $message,"port" => $port,"gwip" => $gwip);
                $msg = json_encode($msgcode);
                //$message = new AMQPMessage($msg, array('content_type' => 'text/plain', 'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT));
                $message = new AMQPMessage($msg);
                $channel->basic_qos(0, 400, false);
                $channel->basic_publish($message, $exchange);
                $channel->wait_for_pending_acks_returns(); /* Mandatory */
                $channel->close();
                $connection->close();
                return true;
        } catch(Exception $e) {
                return false;
        }
}

I adjust the mode to publisher confirm but still the problem remains, thanks in advance for anyone who's going to chime in :)

**Comment by hellracer** [comment]
Ok this is non issue, I refactor my code against Michael suggestion and it's working now
