### ISSUE TITLE
RabbitMQ Consumer not working

### ISSUE THREAD

**Issue by taqiofficial** [php-amqplib/php-amqplib#466]
I am using RabbitMq in my symfony app, The Producer is successfully sent messages to rabbitmq but somehow consumer is not working. 

I run below command, 

    sudo rabbitmqctl list_queues messages name
    Listing queues ...
    2014 notification.notification.create

I have both test and prod server, Initially error was Signature verification issue, So i regenerate signautre and resinstall rabbitmq on Test server. It was solved. then i tried same on prod server but it didn't work.

I see there are two logs files in /var/log/rabbitmq `ssl.log` and `test.log`

    tail -f test.log
    
    accepting AMQP connection <0.10580.12> (127.0.0.1:53668 -> 127.0.0.1:5672)
    
    =INFO REPORT==== 15-Feb-2017::08:59:00 ===
    closing AMQP connection <0.10580.12> (127.0.0.1:53668 -> 127.0.0.1:5672)
    
    =INFO REPORT==== 15-Feb-2017::12:29:07 ===
    accepting AMQP connection <0.14663.15> (127.0.0.1:38318 -> 127.0.0.1:5672)
    
    =INFO REPORT==== 15-Feb-2017::12:29:07 ===
    closing AMQP connection <0.14663.15> (127.0.0.1:38318 -> 127.0.0.1:5672)
    
    and tail -f ssl.log
    
    Supervisor: {<0.542.0>,rabbit_channel_sup_sup}
         Context:    shutdown_error
         Reason:     shutdown
         Offender:   [{nb_children,1},
                      {name,channel_sup},
                      {mfargs,{rabbit_channel_sup,start_link,[]}},
                      {restart_type,temporary},
                      {shutdown,infinity},
                      {child_type,supervisor}]

**Comment by michaelklishin** [comment]
I don't understand what you are trying to do. The logs shows 2 successful connections, at least one of which disconnected immediately. There is nothing related to SSL in the log, the "ssl.log" you are tailing is the rabbitmq-sasl.log and what you see there isn't a reason for concern, nor it is related to TLS.

**Comment by taqiofficial** [comment]
@michaelklishin Publisher is sending the messages to the queue as you can see `2014` messages. but it is not distributing the messages to consumers.

**Comment by michaelklishin** [comment]
@taqiofficial that's still too little information to work with. Consider posting your code and a terminal session that demonstrates what happens when you start your consumer and what is logged by RabbitMQ.
