### ISSUE TITLE
PHP 7.1 has asynchronous signal handling

### ISSUE THREAD

**Issue by dzuelke** [php-amqplib/php-amqplib#468]
See https://wiki.php.net/rfc/async_signals

Basically, in 7.1+, the `pcntl_signal_dispatch()` call in the loop is no longer necessary.

**Comment by ramunasd** [comment]
I had this idea in my head for a long time. At the first glance it looks like opportunity to get rid of some code and rely purely on PHP internals. But there is two gotchas:
- what if async signals are disabled? and they are by default. In this case signal handling could work only in asynchronous manner and only if explicitly enabled.
- it's always better to dispatch signals only in specific time moments, before or after callback, but not in the middle of execution. Then we can be sure that signal handler wont break any internals.

This is the reasons why I want to leave signal handling as it is now. Eveyrone can choose what works best, either synchronous or asynchronous signals. More options is always better.
