### ISSUE TITLE
Is it time for a new release?

### ISSUE THREAD

**Issue by therosco** [php-amqplib/php-amqplib#469]
It's been almost a year since the previous release.

Do you mind to collect all these patches and fixes happened during this time under a new shining release?

**Comment by crashev** [comment]
Also wonder when will be new version. Old stopped working properly with latest 3.6.7 version of Rabbitmq

**Comment by michaelklishin** [comment]
@crashev you are making claims with no evidence provided (in #472). Please stop it, collect logs and really investigate what's going on.

**Comment by michaelklishin** [comment]
FTR, the issue was with Erlang/OTP R16B03 and 17.x compatibility that was broken in 3.6.7. [3.6.8 is already out](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_8).

**Comment by crashev** [comment]
@michaelklishin Thanks for information. Everything works just fine with rabbitmq 3.6.8, sorry to bother You here without deeper checking :)

**Comment by nubeiro** [comment]
@michaelklishin so we can close this issue?

**Comment by therosco** [comment]
Has new version been released yet?

**Comment by nubeiro** [comment]
If you refer to php-amqplib, not yet.

**Comment by therosco** [comment]
Ok then, let the issue be open until php-amqplib would be released.

**Comment by michaelklishin** [comment]
@nubeiro we will close it after the GA release.

FTR, @nubeiro @hairyhum and I have an RC of 2.6.4 planned very soon (a couple more PRs need a bit of massaging).

**Comment by michaelklishin** [comment]
@nubeiro @hairyhum both PRs I had in mind for the next release are now merged.

Should we tag an RC? Should it be a `2.6.4` or `2.7.0`? Given the number of changes I'd suggest the latter, even if we don't technically have any breaking changes.

**Comment by hairyhum** [comment]
There is a new behaviour in SocketIO, so I think it should be `2.7.0`. And there should be an RC because of this new behaviour.

**Comment by michaelklishin** [comment]
Yes, there will be an RC. The question was really "should we tag it now".

**Comment by michaelklishin** [comment]
@nubeiro I think we can tag a `2.7.0-rc1`. The volume of changes alone is a good enough reason to jump to `2.7.0`. Would you agree? Can you please tag it this time (you've mentioned over email that there is a certain tag name pattern that Packageist expects)?

**Comment by nubeiro** [comment]
Agreed, I will tag with 2.7.0-rc1 then.

**Comment by nubeiro** [comment]
See #486, I've done my best to include most relevant changes.

**Comment by nubeiro** [comment]
New release is done, flagged as pre-release in github:
- https://github.com/php-amqplib/php-amqplib/releases/tag/v2.7.0-rc1

**Comment by michaelklishin** [comment]
@nubeiro @hairyhum it's been a month of RC-ing. Should we tag `2.7.0` final? :) Do we want to move to `2.8.0` or are there reasons to go to `3.0.0` for the next cycle?

**Comment by hairyhum** [comment]
@michaelklishin  @nubeiro We should definitely tag 2.7.0.

**Comment by nubeiro** [comment]
Great news, let me do it this week.

El dc., 5 jul. 2017 , 09:30, Daniil Fedotov <notifications@github.com> va
escriure:

**Comment by HonzaMac** [comment]
@nubeiro what about this week?

**Comment by michaelklishin** [comment]
I've merged a small PR earlier today. Should we do a `2.7.0 RC2` first (and wait for a week or so?)

@nubeiro @hairyhum I'm happy to tag it if you agree. Otherwise we can go all in and release `2.7.0` this week :)

**Comment by acasademont** [comment]
Any news on the final release? ^^

**Comment by michaelklishin** [comment]
I haven't gotten any response, so proceeded to tag `v2.7.0` and updated the change log.
