### ISSUE TITLE
[question]Broken pipe or closed connection

### ISSUE THREAD

**Issue by kike91** [php-amqplib/php-amqplib#471]
Hi,

I readed all issues of php-amqplib about "Broken pipe or closed connection" and I can't find a solution.  I cant make a success conection with this :

`$connection = new AMQPStreamConnection('host', port, 'user', 'pass', '/vhost');`

I always get a: 
```
[PhpAmqpLib_Exception_AMQPRuntimeException]  
  Broken pipe or closed connection
```

From my terminal with: `amqp-get -u amqp://myUser:myPass@myHost:myPort/myVhost --queue=.. `I get the items without problem. But not with php-amqlib.

What could i do? I've spend 3 days in this

**Comment by kike91** [comment]
The problem was the "/" of the host

**Comment by lawrence615** [comment]
Hello @kike91, 

What did you mean the problem was "/" of the host?

Am facing the same issue.

**Comment by enriquepery** [comment]
I had to remove '/' in host field
