### ISSUE TITLE
Messages longer than $frame_max are not framed correctly?

### ISSUE THREAD

**Issue by andreisusanu** [php-amqplib/php-amqplib#483]
Hello!

I have a middleware application where notifications are being received (xml) and sent to processors in a RabbitMQ exchange. When the xml content is too large, the message is published incomplete.

Checking **AbstractConnection.php**, we have:

`$payload = mb_substr($body, $position, $this->frame_max - 8, 'ASCII');`

where
`protected $frame_max = 131072;`

This means all messages over 131072 - 8 will be incompletely published, causing unwanted behaviors.

**Questions:**

1. What is the reason on this limitation?
2. Is it possible to set a higher limit?

Thanks!

**Comment by andreisusanu** [comment]
Help!

**Comment by Tobur** [comment]
@andreisusanu change your code to send only identifier by this identifier get data(your xml) from storage which you use. No reason to send all data.

**Comment by andreisusanu** [comment]
I have no storage in the middleware, so I cannot send just the storage ID. I need to sent the entire message as it is.

As temporary solution I am compressing the message contents when publishing.

```
// Compress message
$compressedString = base64_encode(gzcompress($string, 9));
```

On worker side I am decompressing the message content
```
// Uncompress message
$decompressedString = gzuncompress(base64_decode($compressedString));

```

I would like to have the option to set a custom frame_max value in the library.

Thanks!

**Comment by makasim** [comment]
I was able to send base64 encoded images via RabbitMQ and PHP AMQP extension. So It is not a limitation of neither AMQP nor RabbitMQ.

**Comment by michaelklishin** [comment]
RabbitMQ or client libraries do not care what the payload is, it's just a stream of bytes. Payloads are split into multiple frames (of ~ 128 kB by default) by client libraries and RabbitMQ. It could be that this client does not do that :(

Here's how [Bunny does it](https://github.com/ruby-amqp/amq-protocol/blob/master/lib/amq/protocol/client.rb#L164), for example.

**Comment by hairyhum** [comment]
@andreisusanu I cannot reproduce it on my machine. I've modified the `testSendFile` in `FileTransferTest` to create messages of 10MB and it works fine. I also can publish big messages by hand using `php -a` repl.
Are you sure you don't have [message truncation](https://github.com/php-amqplib/php-amqplib#truncating-large-messages) configured? You can check if messages have `AMQPMessage::$is_truncated` flag set to true.

**Comment by lukebakken** [comment]
Closing due to lack of response.
