### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by nubeiro** [php-amqplib/php-amqplib#485]
I am missing a roadmap in this project. 
I'd like feedback on the following ideas (in no specific order):

- Supported PHP versions
Current PHP versions are 5.6.x, 7.0.x and 7.1.x. I would drop support for deprecated PHP versions. 

- Increasing unit test coverage
There have already been contributions that increase code coverage support. It´s not that I am aiming for 100% but rather that I'd like to play _safe_ when refactoring. 

Please feel free to add your comments below.

**Comment by jgimeno** [comment]
I agree on the coverage.

**Comment by aramonc** [comment]
@nubeiro for the version support, would you leave the latest stable as a version branch for those that need it or do like Guzzle & create a new namespace? I'm thinking it would be nice to have the current stable still around for at least another year, without support, to give people time to migrate.

**Comment by michaelklishin** [comment]
I 👎 new namespaces, it becomes impossible to document decently once you have two libraries in one.

Using branches (e.g. `2.6.x-stable`) is perfectly reasonable and what most other client libraries do.

**Comment by nubeiro** [comment]
@aramonc I'm not sure I understand. Current version 2.6.3 has already been around for a year. 
As long as tags are available on repository, you can always have composer install a specific version, can't you?

I would not use an additional namespace. The fact that we move on and produce new releases does not imply people not being able to use older versions.

**Comment by aramonc** [comment]
That's perfect, by current stable I meant which ever is the last current stable when the new version goes live. 

Honestly didn't know what version it's been on or how long it's been around for. Most of the projects I've used it on have already had this lib in the composer.json by the time I start working on them. :smile:

**Comment by lukebakken** [comment]
Closing since this issue has not had activity in almost two years, and keeping long-running issues open isn't productive. Keep an eye on the [`3.0.0` milestone](https://github.com/php-amqplib/php-amqplib/milestone/1) and if you have suggestions they are best submitted as pull requests. Thank you.
