### ISSUE TITLE
Should we pass int or float for timeout in `wait_for_pending_acks_returns` and `wait_for_pending_acks` ?

### ISSUE THREAD

**Issue by prashanthviva** [php-amqplib/php-amqplib#487]
Looks like the functions `wait_for_pending_acks` and `wait_for_pending_acks_returns` allow `float` value for `timeout`. However, all the docs mention `int $timeout`. 

Is this just a typo in the docs or should we not pass `float` for timeout. 
My use-case is to set a timeout of about `500ms` when calling `wait_for_pending_acks_returns`.

**Comment by michaelklishin** [comment]
As far as I can tell [the value is in seconds](https://github.com/php-amqplib/php-amqplib/blob/c3ed1406c25688740e6fb40ad2717611e47b54dd/PhpAmqpLib/Channel/AMQPChannel.php#L1382) but ultimately will be [split into seconds and microseconds](https://github.com/php-amqplib/php-amqplib/blob/b7b677d046a9735e0ad940d649feaf38d58c866c/PhpAmqpLib/Helper/MiscHelper.php#L37).

So you should be able to use floats but integers are also fine.
