### ISSUE TITLE
"Invalid frame type" when connecting from Slim

### ISSUE THREAD

**Issue by kevinmlong** [php-amqplib/php-amqplib#488]
Hi,

We're using php-amqplib to connect to RabbitMQ to serve as an event-bus of sorts. This has been working great where we have implemented it. We just started to implement it in our API part of our code (it uses Slim) and it seems that it's causing those routes to return 500 response codes. 

- The implementations of the queue services work fine when not wrapped in a Slim endpoint.
- Additionally, commenting out the code that uses the queue services causes the endpoints to work as intended (minus the queue stuff)

Any suggestions on where to start and what might be causing this, would be greatly appreciated!

**Comment by michaelklishin** [comment]
@kevinmlong please post relevant portions of your code and the full stack trace.

**Comment by kevinmlong** [comment]
@michaelklishin - here are the relevant parts with some items obfuscated

**Stack Trace**
```
#0 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection-&gt;wait_frame(0)
#1 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection-&gt;wait_channel(0, 0)
#2 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel-&gt;next_frame(0)
#3 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(205): PhpAmqpLib\Channel\AbstractChannel-&gt;wait(Array)
#4 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection-&gt;connect()
#5 <source-route>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection-&gt;__construct(<username>, <password>, '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#6 <source-route>/utilities/admin/SlackHelper.php(23): PhpAmqpLib\Connection\AMQPStreamConnection-&gt;__construct('localhost', <port>, <username>, <password>)
```

**Code Implementation**
```php
$app->get('/endpoint/here', function ($request, $response, $args) {
        // Do some stuff
        $slackHelper = SlackHelper::create();
}
```
In SlackHelper::create() we call the following to create and store a connection to later use to publish a message to the queue
```php
$this->connection = new AMQPStreamConnection('localhost',<port>,<username>,<password>);
```

**Comment by michaelklishin** [comment]
There is no line mentioning "Invalid frame type". Was it obfuscated or where does it come from?

I don't know anything about Slim but the code looks OK except that it creates a shared piece of state (`$this->connection`) that multiple requests then share. It's certainly not uncommon to see issues that stem from that in many languages/clients/Web frameworks.

What is in server logs?

**Comment by kevinmlong** [comment]
@michaelklishin - apologies. here is some more.

<h1>Slim Application Error</h1>
        <p>The application could not run because of the following error:</p>
        <h2>Details</h2>
        <div>
            <strong>Type:</strong> PhpAmqpLib\Exception\AMQPRuntimeException
        </div>
        <div>
            <strong>Message:</strong> Invalid frame type
        </div>
        <div>
            <strong>File:</strong> <source-root>/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
        </div>
        <div>
            <strong>Line:</strong> 514
        </div>
        <h2>Trace</h2>
       ...the stack above...

**Comment by michaelklishin** [comment]
Assuming this is with 2.6.3, [it's this line](https://github.com/php-amqplib/php-amqplib/blob/v2.6.3/PhpAmqpLib/Connection/AbstractConnection.php#L514).

A payload received in response (from RabbitMQ) does not start with a value that encodes a frame type. By far the most efficient way of investigating such issues is [taking a traffic capture with Wireshark](https://www.rabbitmq.com/amqp-wireshark.html) and inspecting server logs.
Since you have two versions of a service that you are comparing, doing so for both of them and comparing is also a good idea.

**Comment by geggleto** [comment]
@kevinmlong I would suspect that there is a problem with your messages. Slim handles all errors and will catch things you normally wouldn't expect which is why it "appears" to work fine outside of the framework.

I would suggest adding monolog to your domain items to see exactly what is going on.

**Comment by kevinmlong** [comment]
@geggleto - it's failing on the constructor before we even send (publish) any messages.

**Comment by kevinmlong** [comment]
Alright...there actually aren't any problems at all. We're using a docker as a test box (simulates the app/web server) and the docker didn't have required php extension (php-mbstring and php-bcmath). Having those installed fixed everything. 🤦
