### ISSUE TITLE
pcntl SIGHUP Consumer restart not working in demo

### ISSUE THREAD

**Issue by wtorsi** [php-amqplib/php-amqplib#489]
Hi,
Maybe I do something wrong, but after sending signal for restarting consumer using demo code (amqp_consumer_signals.php), the script stops catching other signals but restarts correctly, only 

I'm not familiar with backstage code. 
So, do you know why this happens?

**Comment by ramunasd** [comment]
So problem here is that after SIGHUP new wait() loop is started inside signal handler function. It means new signal cannot be dispatched while previous handler function is not finished.
