### ISSUE TITLE
Return listener not called

### ISSUE THREAD

**Issue by alexethomas** [php-amqplib/php-amqplib#490]
[returns_test_case.php.txt](https://github.com/php-amqplib/php-amqplib/files/1055344/returns_test_case.php.txt)
Don't seem to see AMQPChannel::basic_return called when a message is unrouted.
Checked 2.7.0-rc1 and 2.6.2
Reproducer attached

**Comment by lukebakken** [comment]
Please see the attached: [returns_test_case-fixed.php.txt](https://github.com/php-amqplib/php-amqplib/files/2882079/returns_test_case-fixed.php.txt)

Your script exits before the handler has a chance to be called.
