### ISSUE TITLE
AbstractChannel calling protected methods on AbstractConnection child instances

### ISSUE THREAD

**Issue by gregl83** [php-amqplib/php-amqplib#494]
Looks like `wait_channel`, `send_channel_method_frame`, and `prepare_channel_method_frame` are protected methods.

```
    public function next_frame($timeout = 0)
    {
        // ...
        return $this->connection->wait_channel($this->channel_id, $timeout);
    }
    protected function send_method_frame($method_sig, $args = '')
    {
        // ...
        $this->connection->send_channel_method_frame($this->channel_id, $method_sig, $args);
    }
    protected function prepare_method_frame($method_sig, $args = '', $pkt = null)
    {
        return $this->connection->prepare_channel_method_frame($this->channel_id, $method_sig, $args, $pkt);
    }
```

**Comment by lukebakken** [comment]
I suspect that this is allowed due to the fact that `AbstractConnection` extends `AbstractChannel`. Whether or not that relationship makes sense, I won't comment on here.

**Comment by charlieman** [comment]
Wouldn't it be ok if the abstract methods were added to the `AbstractChannel` class?

    abstract protected function wait_channel($channel_id, $timeout);
    abstract protected function send_channel_method_frame($channel, $method_sig, $args, $pkt);
    abstract protected function prepare_channel_method_frame($channel, $method_sig, $args, $pkt);

I can send a pull request if this seems alright. It's not a big problem, I just don't like seeing the red squigly lines in my IDE :smile:
