### ISSUE TITLE
publish/subscribe on mqtt with RabbitMQ

### ISSUE THREAD

**Issue by cirovargas** [php-amqplib/php-amqplib#496]
Hi

I've installed RabbitMQ with mqtt and webservice mqtt plugins.

How i can pub/sub with the php-amqplib? Anyone have tryed this?

My flow is:  user browser <> mqtt RabbitMQ amqtp <> web application

**Comment by michaelklishin** [comment]
This library implements [AMQP 0-9-1](http://www.rabbitmq.com/getstarted.html), not MQTT. If you want specifically MQTT, there is no shortage of MQTT tutorials on the Web, including for PHP. If you don't care what the protocol is, see [RabbitMQ tutorials](http://www.rabbitmq.com/getstarted.html) that use this client.

Web MQTT plugin is meant to be used by JavaScript clients, not PHP.

**Comment by cirovargas** [comment]
Hi @michaelklishin 

The point is:

I have a RabbitMQ instance with the MQTT plugin, i have a mqtt producer/consumer and an AMQP producer/consumer too (using php-amqplib on the symfony RabbitMqBundle)

The RabbitMQ documentation says that all MQTT topics works on the amq.topic exchange.

Right

My situation:

MQTT consumer/producer subscribed on /topic/test  topic
AMQP consumer on amq.topic exchange, on route key .topic.test (i dont know about this but rabbit replace / for . on mqtt topics)


AMQP consume MQTT messages: OK
AMQP produce message to MQTT: NOT
MQTT to MQTT: OK
AMQP to AMQP: OK

My mqtt pub/sub is a JS client (tested in some)
My AMQP pub/sub ith the php/symfony

**Comment by michaelklishin** [comment]
@cirovargas the problem is not in the client. MQTT and AMQP 0-9-1 use different topic segment separators, that's why you see slashes replaced with dots. It is something done by the server, not this client. When two different protocols interoperate, you sometimes can avoid scenarios like this.
I will clarify this in the MQTT client docs.

Adjusting your topics should be sufficient, e.g. instead of `/a/b/c` try `a/b/c`.

Speaking of interoperability, interoperability between AMQP 0-9-1 and STOMP is usually more straightforward. You get access to more AMQP 0-9-1 features because STOMP is extensible and flexible in nature, MQTT much less so. So while it's not necessary to get the flow you want, consider using [STOMP over WebSockets](http://www.rabbitmq.com/web-stomp.html) unless you really have to use MQTT on the browser end.

**Comment by cirovargas** [comment]
@michaelklishin my producer on php-amqplib is using point and slashes

```
producers:
        search_driver:
            connection:       default
            exchange_options: {name: 'amq.topic', type: topic}
            queue_options:    {name: '.topic.test', routing_keys: ['.topic.test', '/topic/test']}
    consumers:
        search_driver:
            connection:       default
            exchange_options: {name: 'amq.topic', type: topic}
            queue_options:    {routing_keys: ['.topic.test', '/topic/test']}
            callback:         pr.consumer.search_driver
```

but the MQTT consumer dont show de message, on the Rabbit panel show .topic.test and /topic/test messages

**Comment by michaelklishin** [comment]
@cirovargas sorry I don't know how to interprete `queue_options` in the producer section but ".topic.test" for a routing key seems like a misunderstanding of how topic routing works. Please take a look at [Tutorial 5](http://www.rabbitmq.com/tutorials/tutorial-five-php.html) if that part is unclear.

I outlined where the mismatch that affects message routing is, please take it from here.

**Comment by cirovargas** [comment]
@michaelklishin I understood everything, but I still can't make it work.

See, using the lib (with no bundle, that's works):

```
require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();

$channel->exchange_declare('amq.topic', 'topic', true,true,true);

$routing_key = isset($argv[1]) && !empty($argv[1]) ? $argv[1] : 'topic.test';
$data = implode(' ', array_slice($argv, 2));
if(empty($data)) $data = "Hello World!";

$msg = new AMQPMessage($data);

$channel->basic_publish($msg, 'amq.topic', $routing_key);

echo " [x] Sent ",$routing_key,':',$data," \n";

$channel->close();
$connection->close();
```

**Comment by cirovargas** [comment]
OH MY FUCKING GOD

Hey @michaelklishin , sorry

its a bundle bug,

The publisher configs are not passed to the class on call it

fuck, lost 3 days on it
