### ISSUE TITLE
OpenSSL error - decryption failed or bad record mac

### ISSUE THREAD

**Issue by akang1** [php-amqplib/php-amqplib#497]
When connecting to a AWS load balancer using SSL/TLS, after 60 seconds, I keep on getting the following error from our app server.

SSL operation failed with code 1. OpenSSL Error messages:
error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac in /var/www/exzact/composer/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 0

I've tried to increase the timeout setting on the AWS load balancer but this did not resolve it.

This is dropping the connection to rabbit abruptly and killing the consumer and the app server is not able to send an ACK back to rabbit, therefore the msgs never get consumed/get removed from the queue.

Has anyone come across this issue and if so, resolved it?

**Comment by lukebakken** [comment]
If you are able to provide instructions and/or code (and certificates) that consistently reproduce this, please re-open this issue.
