### ISSUE TITLE
Can we specify multiple hosts while creating AMQPConnection ?

### ISSUE THREAD

**Issue by gauravgargtech** [php-amqplib/php-amqplib#498]
We have set-up a HA cluster with 2 nodes and thinking to add 2 hosts addresses in RABBITMQ_SERVER_HOSTNAME, Is it possible in this library.

                self::$connection = new AMQPConnection(RABBITMQ_SERVER_HOSTNAME, RMQ_PORT, RMQ_USER_NAME, RMQ_PASSWORD);

Can we have constant "RABBITMQ_SERVER_HOSTNAME" = 'host01,host02';

and both these hosts have same Port and username/password combinations ...

**Comment by michaelklishin** [comment]
As far as I can tell, it isn't. For initial connection, it should be a fairly easy feature to add (connection recovery is a different story). Feel free to look into a pull request.
