### ISSUE TITLE
Producer time consuming

### ISSUE THREAD

**Issue by chaiyanlin** [php-amqplib/php-amqplib#503]
I did an ab test yesterday. And I found out producer send a msg to mq-server could cost over 500ms. And I have no idea about this issue, any suggestions?

**Comment by makasim** [comment]
if producer performance is something critical for you try amqp extension https://github.com/pdezwart/php-amqp. It has to be way faster.

**Comment by chaiyanlin** [comment]
@makasim thank you for your reply, I was curious...when I read the [php-amqp specific examples](https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/php-amqp), is it the same class when we use the RabbitMQ C library? In fact, I have already use the c extenstion directly, but there was nothing good...

**Comment by makasim** [comment]
Honestly, 500ms per message sounds completely weird even for php-amqplib. According to this [benchmark](https://github.com/jakubkulhan/bunny) it has to be around 1.3ms per message

**Comment by chaiyanlin** [comment]
@makasim I do agree with you, would you mind take a look at my produer code?
`
...
public static function send($queue, $msg) {
    
    $config = self::bootstrap();
    $connection = new AMQPSocketConnection(
      $config['host'],
      $config['port'],
      $config['user'],
      $config['password'],
      $config['vhost'],
      false,
      'AMQPLAIN',
      null,
      'en_US',
      3,
      true
    );
    $channel = $connection->channel();
    $channel->queue_declare($queue, false, false, false, false);
    $message = new AMQPMessage($msg);
    $channel->basic_publish($message, '', $queue);
    $channel->close();
    $connection->close();
  }
`
