### ISSUE TITLE
How to correctly declare message body content encoding?

### ISSUE THREAD

**Issue by andrefigueira** [php-amqplib/php-amqplib#505]
Hello,

Firstly, thank you very much for all the hard work that goes into this library! Hopefully I'll be able to contribute in some way.

So I have recently had to implement compression on the messages we're putting into rabbit due to the sheer volume we're dealing with in order to save on bandwidth. Currently, I've placed a content_encoding header in the `AMQPMessage` properties, as defined on the property definitions.

e.g. 

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Message/AMQPMessage.php#L29

However, the `AMQPMessage` itself, contains a public property for `content_encoding` also and event includes a getter for it, `getContentEncoding` however there does not seem to be any parity between the property definitions of the `AMQPMessage` and the the `content_encoding` property, and I'm unsure which is the "correct" place to put my header, if it's the property in the `AMQPMessage` accessible via the getter already available, would there be any objection to the addition of a setter?

For reference, here is the `AMQPMessage` definition for the content_encoding

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Message/AMQPMessage.php#L24

Thanks again, hope this makes sense.

**Comment by michaelklishin** [comment]
Can you please post your code? This client uses a single message abstraction for both publishers and consumers, so in some cases the publisher must set properties but in others they already come from the server.

**Comment by michaelklishin** [comment]
Closed because I close all issues that are questions. You can still leave comments ;)

**Comment by andrefigueira** [comment]
@michaelklishin  Sure! here it is:

```
try {
            $messageContent = json_encode($messageContent);
            $messageProperties = [
                'delivery_mode' => $this->getDeliveryMode(),
            ];

            if (false === $messageContent) {
                throw new JsonEncodingException(
                    'Failed to encode the producer message into JSON: ' . json_last_error_msg()
                );
            }

            $compressionAdapter = $this->getCompressionAdapter();

            if (null !== $compressionAdapter) {
                // here you can see I'm just assigning it as a property
                $messageProperties['content_encoding'] = $compressionAdapter->getName();

                $messageContent = $compressionAdapter->compress($messageContent);
            }

            $message = new AMQPMessage($messageContent, $messageProperties);

            $message->set('application_headers', new AMQPTable($headers));

            $this->channel->basic_publish($message, $this->getExchangeName(), $this->getRoutingKey());
        } catch (Exception $e) {
            throw new QueuePublishException('Failed to publish to RabbitMQ', $e->getCode(), $e);
        }
```

This is the code my producer is using, I'm trying to see the best way now for my consumer to have access to it, so was originally going to use something along the lines of:

```
$properties = $message->get_properties();

// with some checking to make sure the property exists...
$contentEncoding = $properties['content_encoding'];
```

Then base my work after from this variable, but having seen that the AMQPMessage has the getter, I'd rather use:

```
$contentEncoding = $message->getContentEncoding();
```

I know I could simply do the following in order to use the getter, but I'd rather publicly available method rather than using the property directly.

```
$message->content_encoding = 'gzip';
```

But then again all depends on the intended usage for it :)

Thanks for the speedy reply!

**Comment by TodoshiTakato** [comment]
Any activity on this topic yet? When will we be able to set 'content_encoding' of message? Or when will you implement the setter?

**Comment by lukebakken** [comment]
@TodoshiTakato you can set and get `content_encoding` with the code as it is. Please do the following if you'd like further assistance-

* Start a discussion here - https://github.com/php-amqplib/php-amqplib/discussions
* Describe what you're trying to do, and how the library is not working as you expect.
* Share your code in a git repository that I can clone and run to see what you're trying to accomplish. You **MUST** make your code runnable to save me the time of doing that.
