### ISSUE TITLE
Create new connection and channel every time in API case?

### ISSUE THREAD

**Issue by chaiyanlin** [php-amqplib/php-amqplib#506]
I was wondering that should I create a new connection & channel every time during client calling my api?
My personal opinion is we shouldn't. So here is what I did:
1. All Mq-msg will be saved into a redis queue: $redis->rPush($msg);
2. Create a php-cli task that keep connection and channel connecting,  and this task will keep trying to get message from the redis queue: $redis->lPop(); Once the task get a new message from the queue, it will directly send the message to the mq-server.

The idea behind all of this is we don't have a connection pool, and creating new connection & channel will cost much time.

My question is what is the best way to do this? Thx！

**Comment by makasim** [comment]
What problem do you want to solve by using redis as midleware? 

http api is stateless hence both redis and rabbitmq connections are being re-created in each request. you still have to connect to redis. 

Does the time spend on establishing a connection is that big? You might have other stuff that consumes far bigger time resources  (doctrine for example).

**Comment by chaiyanlin** [comment]
Creating connection cost over 300ms during ab test. I'm using lithium framework, but I'm pretty sure there is nothing to do with doctrine.



发自我的 iPhone
> 在 2017年8月28日，上午1:54，Maksim Kotlyar <notifications@github.com> 写道：
> 
> doctrine

**Comment by michaelklishin** [comment]
If you can reuse a connection (and channel), you definitely should. Pretty much all messaging protocols, including AMQP 0-9-1, assume this. It's not always realistic in case of PHP, however.

**Comment by Valantir007** [comment]
@chaiyanlin did you solve this problem?

**Comment by chaiyanlin** [comment]
@Valantir007 

Here is my solution, if you are running your code on php-fpm mode, and you are facing high concurrence case，then just don't use php-amqplib, it is a pure php lib, it cannot maintain a persistent connection for you，you can simply verify my point via running an ab test, and during the test, if you can use netstat you'll found a lot of TCP connection shows `TIME_WAIT`.

So I suggest using [amqp ext](http://pecl.php.net/package/amqp), C extension provides `pconnect` feature, every php-fpm process can maintain a persistent connection~

**Comment by Valantir007** [comment]
@chaiyanlin

Very thanks for your reply.
How you think - this package is good to use in this case?

https://github.com/pdezwart/php-amqp

**Comment by chaiyanlin** [comment]
@Valantir007 

I think this lib is fine. BTW, what framework are you using ?

**Comment by Valantir007** [comment]
Zend Expressive

**Comment by KnowerBoye** [comment]
Okay so I have a question. 
I'm using cloudamqp's little lemur plan. 
The limit  on connections is 20. 
Does that mean if my api get's 20 simultaneous request at a go that counts as 20 connections ?

**Comment by lukebakken** [comment]
@KnowerBoye I suggest asking CloudAMQP support.

Also, see this comment -
https://github.com/php-amqplib/php-amqplib/issues/506#issuecomment-419651579

And this project -
https://github.com/cloudamqp/amqproxy
