### ISSUE TITLE
check_heartbeat in write() at StreamIO

### ISSUE THREAD

**Issue by materkov** [php-amqplib/php-amqplib#507]
I see that check_heartbeat method is called at read() and select() methods. Why it is not called in the begining at write()?

My current problem: 
I have one long task (for example, this task takes 1 min, and heartbeat interval is 10 second). After this task finished, I need to write another message to inform others that the task was finished. But connection at this moment already broken, so it seems reasonable to reconnect at this moment. As for now, there is an error:
```
PHP Fatal error:  Uncaught ErrorException: fwrite(): send of 145 bytes failed with errno=104 Connection reset by peer in /code/current/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:281
Stack trace:
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/code/f659f3efc...', 281, Array)
#1 /code/current/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(281): fwrite(Resource id #32, '\x01\x00\x01\x00\x00\x00"\x00<\x00(\x00\x00\x19t...', 8192)
#2 /code/current/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00"\x00<\x00(\x00\x00\x19t...')
#3 /code/current/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(368): PhpAmqpLib\Connection\Abstract in /code/current/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 281
```

PS: php-amqplib/php-amqplib v2.6.3

**Comment by boryashkin** [comment]
It seems like SreamIO's reconnect() method can't work at all. First thing you see after it runs - `{bad_header,<<8,0,0,0,0,0,0,206>>}` in rabbitMQ logs

**Comment by materkov** [comment]
Yes, that's true. It looks like there is no good way to keep long-running connections from PHP. 
Another option is to write some "wrapper listener" in another language (Python, Go), and then call regular PHP CLI command to actually do the job.

**Comment by boryashkin** [comment]
I found out [the way](https://github.com/php-amqplib/php-amqplib/blob/e2a5074a096b3e9b9819964341c561dce5412be2/PhpAmqpLib/Connection/AbstractConnection.php#L250) it works fine;
But v2.6 have [this bug](https://github.com/php-amqplib/php-amqplib/pull/479) when it works wrong, trying to reconnect going from [here](https://github.com/php-amqplib/php-amqplib/blob/ba9468b08b5ff90859ef5069a6b9a70bcdd98fa1/PhpAmqpLib/Wire/IO/StreamIO.php#L200) to [here](https://github.com/php-amqplib/php-amqplib/blob/ba9468b08b5ff90859ef5069a6b9a70bcdd98fa1/PhpAmqpLib/Wire/IO/StreamIO.php#L225) in infinite loop throuth [this line](https://github.com/php-amqplib/php-amqplib/blob/ba9468b08b5ff90859ef5069a6b9a70bcdd98fa1/PhpAmqpLib/Wire/IO/StreamIO.php#L342) where it breaks

**Comment by sadok-f** [comment]
@boryashkin how did you resolve this issue? 
I tried to overwrite the `write` function and add a reconnect method if there's a exception, but I got another error:
```
[2017-10-16T10:36:49.828+00:00] main.ERROR: Uncaught Exception PhpAmqpLib\Exception\AMQPProtocolConnectionException: "CHANNEL_ERROR - expected 'channel.open'" at /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php line 666 {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPProtocolConnectionException(code: 504): CHANNEL_ERROR - expected 'channel.open' at /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:666)"} []
```

And my rabbitmq server show this error:
```
rabbitmq_1        | =INFO REPORT==== 16-Oct-2017::10:36:49 ===
rabbitmq_1        | connection <0.2756.0> (172.18.0.5:48906 -> 172.18.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1        |
rabbitmq_1        | =ERROR REPORT==== 16-Oct-2017::10:36:49 ===
rabbitmq_1        | Error on AMQP connection <0.2756.0> (172.18.0.5:48906 -> 172.18.0.2:5672, vhost: '/', user: 'guest', state: running), channel 1:
rabbitmq_1        | operation basic.ack caused a connection exception channel_error: "expected 'channel.open'"
```

my code block is:
```php
 /**
     * @param $data
     *
     * @throws \Exception
     */
    public function write($data)
    {
        try {
            $this->debug->debug_hexdump($data);
            $this->getIO()->write($data);
        } catch (\Exception $e) {
            $connectionAttempts = 0;
            $this->setIsConnected(false);
            while ($connectionAttempts < self::MAX_ATTEMPTS && !$this->isConnected()) {
                $connectionAttempts++;
                $this->reconnect();
            }
            if (!$this->isConnected()) {
                throw new \ErrorException($e->getMessage());
            }
        }
    }
```

**Comment by boryashkin** [comment]
@sadok-f I did not, to be honest. Just moved to v2.7 where the issue with the inifinite loop was fixed.
 It seems to be more stable, but consumers (daemons) are still hangs from time to time. But without RabbitMQ errors.

I think that the reconnection logic should be happened on [that](https://github.com/php-amqplib/php-amqplib/issues/444) kind of level

**Comment by sadok-f** [comment]
@boryashkin Thank you for your response, I fixed the issue by adding the channel creation after ` $this->reconnect();`, also I have to bind the topics again to the queue and bind the consumer as well.
so my code will be like:
```php
$connectionAttempts++;
$this->reconnect();
 $channel = $this->channel();
 $channel->queue_bind(...,...);
 $channel->basic_consume(...,...);

```

**Comment by boryashkin** [comment]
@sadok-f I have the same algorythm :) but i didn't posted it, assuming you'll find it out.

Btw, it still hangs up somtimes (loosing tcp connection and infinetely waiting) (couple times in 2 month)

**Comment by sadok-f** [comment]
@boryashkin we still experimenting PHP as long-running process, there's a plan to switch to Go as a worker and call a php-fpm each message received, but we need to see how PHP perform now.

**Comment by gnovotny** [comment]
I think the check_heartbeat method should be made public so it can be called manually by a long-running worker to keep the connection alive. My current solution is to call duplicate code from the write_heartbeat method after every database transaction in my consumer, working well so far.

**Comment by rbro** [comment]
I am running into a similar issue where I have a long-running process and would like to manually call check_heartbeat every so often.  Could check_heartbeat be made public?

**Comment by michaelklishin** [comment]
Those who feel that `check_heartbeat` should be made public (with some extra comments explaining why that's the case) should submit a PR.

**Comment by rbro** [comment]
@gnovotny Not sure if this is something you have run into, but when I call the check_heartbeat method in a loop, it eventually stops calling write_heatbeat because $this->last_read stays the same, which means it eventually calls reconnect.  Are you seeing that too?  Not sure if this has any side effects, but if I call read(0) in a loop instead of check_heartbeat, then it seems to get around it and update $this->last_read after each call.

**Comment by lukebakken** [comment]
#520

**Comment by lukebakken** [comment]
Please see the discussion in #617. Considering this issue closed due to lack of activity.
