### ISSUE TITLE
Where to find API docs?

### ISSUE THREAD

**Issue by speller** [php-amqplib/php-amqplib#513]
For example, I'm searching for explanation for the AMQPStreamConnection constructor params. No links, no docs anywhere. Could you help please or provide a link?

**Comment by michaelklishin** [comment]
API docs are not published anywhere as far as I know. If you have suggestions about services that can host API documentation, we would consider them (something [similar to this](http://www.rubydoc.info/github/ruby-amqp/bunny)).

**Comment by andrefigueira** [comment]
@michaelklishin I'd recommend https://readthedocs.org really good and used by a lot of open source projects to host documentation

**Comment by Ilyes512** [comment]
I am surprised there is no documentation of the api.

Another option is to use the static pages option of Github: https://pages.github.com/

**Comment by JouzaLoL** [comment]
API docs would be awesome!

**Comment by lukebakken** [comment]
@JouzaLoL - http://php-amqplib.github.io/php-amqplib/
