### ISSUE TITLE
How i can publish a bytes array?

### ISSUE THREAD

**Issue by giovannyreyeso** [php-amqplib/php-amqplib#514]
Hi, its possible publish a bytes array?, i have a class from protobuf (Google) and i cant found how publish a message (array bytes)

**Comment by andrefigueira** [comment]
Could you not gzip it?

**Comment by giovannyreyeso** [comment]
I don't think so . Because the AMPQMessage only can send a string message

**Comment by andrefigueira** [comment]
Yeah and the griped content is essentially that I’m using gzip myself on publish compress on consume decompress

**Comment by giovannyreyeso** [comment]
But my consumer is write in Java and use parse from array bytes. Have a example of gzip ?

**Comment by michaelklishin** [comment]
@giovannyreyeso gzip [de]compression and PHP and Java have nothing to do with this library. Consider taking this elsewhere.

**Comment by michaelklishin** [comment]
By [producing a string out of a byte array](https://stackoverflow.com/questions/5473011/how-can-i-convert-array-of-bytes-to-a-string-in-php). If anyone wants to contribute a helper publish method that consumes byte arrays, feel free to submit a PR. In other clients (Java, .NET) it is usually the other way around: strings must be converted to byte arrays, and there are helpers that take strings or byte buffers.
