### ISSUE TITLE
Unknown delivery_tag 2 with publisher confirms

### ISSUE THREAD

**Issue by andrefigueira** [php-amqplib/php-amqplib#515]
Hello!

Just wondering if someone would be able to help with the issue I'm getting when I enable publisher confirms, I am consistently receiving the following error:

```
Server ack'ed unknown delivery_tag "2"
```

I cannot see what I've got wrong as it's just using publisher confirms, as retrieved from the demo folder of the project. Is it possibly a bug?

Thanks in advance.

**Comment by michaelklishin** [comment]
We cannot tell as you haven't provided enough information to work with. Consider posting a complete way to reproduce.
