### ISSUE TITLE
Agree on a set of shared interfaces

### ISSUE THREAD

**Issue by Nyholm** [php-amqplib/php-amqplib#524]
I've recently started to research the AMQP libraries that exists in the PHP land. I know that there are discussions in FIG to create a PSR and discussion in Symfony about creating another AMQP library. 

I've seen discussions in #500 and #499. I like the idea of ***an interop organization*** that will work as a "community driven PSR". Much like HTTPlug was used in the community before the PSR was drafted. I'm sure the maintainers know the value if interchangeability and the stability shared interfaces will bring, so I do not intend to repeat it here. 

I'm not sure I agree with the implementation in #500 but I think the purpose was sound. 

Questions: 
1) Could you see that your existing classes in `php-amqplib` will implement the interfaces in `queue-interop` and/or `amqp-interop` within a reasonable future?
2) Could we all work together to make sure `queue-interop` and `amqp-interop` is as perfect as they can be prior a future PSR? 

Since the maintainers and the active contributors here are very knowledgeable with queues it would be great to have your input.

**Comment by michaelklishin** [comment]
We explained our position in #500. Our goal is to develop a quality RabbitMQ client. An interface for `queue-interop` should be a separate library from this one.

I personally have seen a lot of unified interface for X attempts, especially in the messaging space. Once they get past the common denominator stage they hit a wall, which is: different protocols have different features and even if the difference doesn't seem major at first, that's where their strengths come in.
