### ISSUE TITLE
Incorrect Password Encoding/Escaping

### ISSUE THREAD

**Issue by geggleto** [php-amqplib/php-amqplib#525]
Hello,

I ran into an issue when deploying a project to production. Our WWW servers could not connect to our rabbit exchange using a complicated password. `Ln1V3#'C0oA1{FFB9l_IwBv9hmfSw8PZ?]SdU';isy~th6CDdbFDHzp4Hr=3oYsk`

Regenerating the password using only Ascii Characters solved the problem. Given the nature of the issue I didn't have time to dig deeper into exactly what characters were causing the problem.

**Comment by lukebakken** [comment]
I can't reproduce this. Here is what I did:

* Create a test user with the password you provide:

```
$ rabbitmqctl add_user 'php-amqplib-525' 'Ln1V3#'\''C0oA1{FFB9l_IwBv9hmfSw8PZ?]SdU'\'';isy~th6CDdbFDHzp4Hr=3oYsk'
Adding user "php-amqplib-525" ...

$ rabbitmqctl authenticate_user 'php-amqplib-525' 'Ln1V3#'\''C0oA1{FFB9l_IwBv9hmfSw8PZ?]SdU'\'';isy~th6CDdbFDHzp4Hr=3oYsk'
Authenticating user "php-amqplib-525" ...
Success

$ rabbitmqctl set_permissions 'php-amqplib-525' '.*' '.*' '.*'
Setting permissions for user "php-amqplib-525" in vhost "/" ...
```

* Modified [the demo configuration] as follows:

```php
define('HOST', 'localhost');
define('PORT', 5672);
define('USER', 'php-amqplib-525');
define('PASS', "Ln1V3#'C0oA1{FFB9l_IwBv9hmfSw8PZ?]SdU';isy~th6CDdbFDHzp4Hr=3oYsk");
define('VHOST', '/');
```

* Run a demo. Transcript is attached, showing success: [php-amqplib-525-transcript.txt](https://github.com/php-amqplib/php-amqplib/files/1633157/php-amqplib-525-transcript.txt)
