### ISSUE TITLE
Is this library still actively supported?

### ISSUE THREAD

**Issue by bvanmeggelen** [php-amqplib/php-amqplib#526]
Quite simple, is this library still actively being supported? Reasons for asking is that I'm running into
a few issues and although I can easily fix them and make a PR for it, it would be nice if it's even going to be looked at. There are a few pending PR's from other people, but it seems a bit quiet since September last year. 
Please let me know, because so far this library is doing a great job.

**Comment by lukebakken** [comment]
Members of the RabbitMQ team try to keep on top of this library as time permits. I have brought up your question with the team to see if we can find some time to catch up.

**Comment by michaelklishin** [comment]
Please submit the PRs. A good PR with tests and problem definition, especially one that you've tested in production systems, can be reviewed very efficiently.

**Comment by lukebakken** [comment]
@bvanmeggelen I am getting `2.7.1-rc1` ready at the moment. If you have fixes that can land in `2.7.1`, a PR (or PRs) would be welcome. Thanks.

**Comment by lukebakken** [comment]
OK. If you have time to test `2.7.1-rc1`, we would appreciate it. I have quite a few issues in the [`2.7.1` milestone](https://github.com/php-amqplib/php-amqplib/milestone/2) to deal with before `2.7.1` will be released.
