### ISSUE TITLE
A weird thing about heartbeat config

### ISSUE THREAD

**Issue by pjyong** [php-amqplib/php-amqplib#531]
Hi, I have one question about heartbeat. I create AMQPStreamConnection instance and set keepalive=true,heartbeat=1, then sleep(5) and send message to RabbitMQ, it shows me "failed with errno=104 Connection reset by peer".

So I only change above code heartbeat=0, no matter sleep(5) or sleep(1800), the error never show up and the message is sent successfully.

That's weird, Someone can explain this?

Thanks very much

**Comment by michaelklishin** [comment]
Consider posting questions to rabbitmq-users and providing a code snippet. The value of 0 [disables heartbeats](http://www.rabbitmq.com/heartbeats.html), therefore even if something blocks all I/O activity (e.g. a sleep strategically placed), RabbitMQ won't consider this to be a reason to close the connection.
