### ISSUE TITLE
Packageist errors

### ISSUE THREAD

**Issue by lukebakken** [php-amqplib/php-amqplib#533]
@videlalvaro reported getting this over and over:

> The videlalvaro/php-amqplib package of which you are a maintainer has
> failed to update due to invalid data contained in your composer.json.
> Please address this as soon as possible since the package stopped updating.

I don't have access to Packageist to diagnose. @videlalvaro or @michaelklishin - can you give me access?

**Comment by videlalvaro** [comment]
@lukebakken what's your username on packagist?

**Comment by lukebakken** [comment]
I just created an account my username is `lukebakken`

**Comment by videlalvaro** [comment]
@lukebakken I added you as admin

**Comment by lukebakken** [comment]
Thanks, I'll see what's up tomorrow

**Comment by lukebakken** [comment]
@videlalvaro - I don't see anything in the Packagist UI indicating an error with `composer.json`. Could you attach one of the emails you received to this issue?

**Comment by lukebakken** [comment]
I found composer/packagist#292 and ran `composer validate`, which found an issue in the file.

Fixed by d5673e3c3714ea21e743942087b95662a99aef63
