### ISSUE TITLE
Windows + IIS - Without Composer

### ISSUE THREAD

**Issue by mlhkr** [php-amqplib/php-amqplib#536]
Hi,
How can I use this library without composer on windows + IIS?
I try different ways but all fails. Also check for:
https://github.com/php-amqplib/php-amqplib/issues/99 but the code for autoload.php doesn't work.

Can you please help me about this?

**Comment by lukebakken** [comment]
Hello,

In order for us to help out, you must provide information:

* Windows version, IIS version
* How is PHP installed on Windows?
* What have you tried? How does it fail? Please provide exact commands used and output attached as files.
* Please clarify what " Also check for: #99 but the code for autoload.php doesn't work" means. What did you try? What did you observe?

**Comment by mlhkr** [comment]
Hi,
Windows 10 x64
IIS 10.0.16299.15
PHP 7.1.13 x64 NTS Installed AS FASTCGI on IIS

Since I'm on windows platform and hard to use composer here need to use include commands in php to solve this. But unfortunately the library hasn't got autoload.php or something like that. I try to directly load files manually like:

```
<?php
include_once "PhpAmqpLib/Connection/AMQPStreamConnection.php";
include_once "PhpAmqpLib/Message/AMQPMessage.php";

$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();
```
But now I'm getting:
Fatal error: Class 'PhpAmqpLib\Connection\AbstractConnection' not found in ...\PhpAmqpLib\Connection\AMQPStreamConnection.php on line 6

So stuck here, can you please help me about this or library itself somehow designed to run on linux only?

Thanks

**Comment by mlhkr** [comment]
Sorry accidentally closed...

**Comment by lukebakken** [comment]
Thanks for the information. I strongly suggest that you get composer working on Windows. There appear to be several guides online for installing it, such as this:

http://webdevzoom.com/how-to-install-composer-on-windows/
