### ISSUE TITLE
 Fatal error:  Uncaught exception 

### ISSUE THREAD

**Issue by avishake** [php-amqplib/php-amqplib#538]
Hi,
I have a problem. My code was working fine. But  now I have a error like this. I didn't understand the problem.
My code is:

    $queue_name=$db_name.'_bounce';
    $channel->queue_declare($queue_name, false, true, false, false);
    $callback = function($msg){
        //Do some calculation with data
    }
    $channel->basic_qos(null, 1, null);
    $channel->basic_consume($queue_name, '', false, false, false, false, $callback);
	while(count($channel->callbacks)) {
		$channel->wait();
	}
Below is the full error which I found while run the code.  
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Excepti
on\AMQPBasicCancelException' in C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AMQPChannel.php:881
Stack trace:
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_cancel_from_server(Object(PhpAmqpLib\Wire\AMQPReader))
#1 C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('60,30', '\x1Famq.ctag-Fr3Lm...', NULL)
#3 C:\xampp\htdocs\isend\blog\cron\rmq_to_es.php(100): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 {main}
  thrown in C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AMQPChannel.php on line 881

Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPBasicCancelException' in C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AMQPChannel.php:881
Stack trace:
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_cancel_from_server(Object(PhpAmqpLib\Wire\AMQPReader))
#1 C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('60,30', '\x1Famq.ctag-Fr3Lm...', NULL)
#3 C:\xampp\htdocs\isend\blog\cron\rmq_to_es.php(100): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 {main}
  thrown in C:\xampp\htdocs\isend\blog\cron\lib\PhpAmqpLib\Channel\AMQPChannel.php on line 881

**Comment by IMSoP** [comment]
`basic_cancel` or `basic.cancel` is a message type in AMQP; according to the [documentation on the RabbitMQ site](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.cancel):

> It may also be sent from the server to the client in the event of the consumer being unexpectedly cancelled (i.e. cancelled for any reason other than the server receiving the corresponding basic.cancel from the client). This allows clients to be notified of the loss of consumers due to events such as queue deletion.

Your stack trace suggests that this is what has happened in this case: the I/O channel has received this message and processed it with `AMQPChannel->basic_cancel_from_server`.

So for some reason, your connection is being cancelled at the server end.
