### ISSUE TITLE
php53 compatibility Wire/IO/StreamIO.php

### ISSUE THREAD

**Issue by korrident** [php-amqplib/php-amqplib#539]
This part of code it'snt compatible with php5.3 
in PhpAmqpLib/Wire/IO/StreamIO.php
$this->context = stream_context_create([
                    "socket" => [
                        "tcp_nodelay" => true
                    ]
                ]);

replace [] by array() please

**Comment by korrident** [comment]
`
From 2bd161d3f5e64c733922bea66e6aaa1ba937e34b Mon Sep 17 00:00:00 2001
From: Vincent KERDRAON <v.kerdraon@servicemagic.eu>
Date: Wed, 7 Feb 2018 15:31:09 +0100
Subject: [PATCH] Fix #539 php53 compatibility Wire/IO/StreamIO.php

---
 PhpAmqpLib/Wire/IO/StreamIO.php | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/PhpAmqpLib/Wire/IO/StreamIO.php b/PhpAmqpLib/Wire/IO/StreamIO.php
index e724431..bfe8011 100644
--- a/PhpAmqpLib/Wire/IO/StreamIO.php
+++ b/PhpAmqpLib/Wire/IO/StreamIO.php
@@ -89,11 +89,11 @@ class StreamIO extends AbstractIO
         if (is_null($this->context)) {
             // tcp_nodelay was added in 7.1.0
             if (PHP_VERSION_ID >= 70100) {
-                $this->context = stream_context_create([
-                    "socket" => [
+                $this->context = stream_context_create(array(
+                    "socket" => array(
                         "tcp_nodelay" => true
-                    ]
-                ]);
+                    )
+                ));
             } else {
                 $this->context = stream_context_create();
             }
--
libgit2 0.26.0


`

**Comment by korrident** [comment]
see pull-request https://github.com/php-amqplib/php-amqplib/pull/540

**Comment by lukebakken** [comment]
@korrident @IMSoP - just so you know, PHP 5.3 is no longer officially supported or tested by this project. We're happy to accept future PRs to keep support going, but please try to get them in during the RC phase of the next release. This will probably be the only time we tag a release just for 5.3 support.

**Comment by IMSoP** [comment]
I think it's reasonable to drop 5.3 support at this point, and adjusting the minimum PHP version in the composer.json (and readme) in 2.8.0. I believe that way, people still using composer under 5.3 will automatically be left on the old version. The reason this bug was rather disruptive was that a routine `composer update` pulled in the incompatible version.

**Comment by lukebakken** [comment]
@korrident @IMSoP - https://github.com/php-amqplib/php-amqplib/releases/tag/v2.7.2

**Comment by korrident** [comment]
@IMSoP @lukebakken  thx very much.
Migration to PHP5.6 is planned in our project.
I aggree with @IMSoP about dropping PHP5.3 support AND changing the composer json accordingly.
