### ISSUE TITLE
Getting really often "Connection reset by peer"

### ISSUE THREAD

**Issue by goetas** [php-amqplib/php-amqplib#546]
Hi! 
More than a bug, this is a request for help. I saw other similar issues in the repo, but all of them look somehow different. 

Im getting very often (every ~100 consumed messages) `[ErrorException]   fwrite(): send of 21 bytes failed with errno=104 Connection reset by peer`

On the client the stack trace is: 
```
Exception trace:
 PhpAmqpLib\Wire\IO\StreamIO->error_handler() at n/a:n/a
 fwrite() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:294
 PhpAmqpLib\Wire\IO\StreamIO->write() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:338
 PhpAmqpLib\Connection\AbstractConnection->write() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:459
 PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:230
 PhpAmqpLib\Channel\AbstractChannel->send_method_frame() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:748
 PhpAmqpLib\Channel\AMQPChannel->basic_ack() at /var/www/app/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php:195
 OldSound\RabbitMqBundle\RabbitMq\Consumer->handleProcessMessage() at /var/www/app/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php:134
 OldSound\RabbitMqBundle\RabbitMq\Consumer->processMessageQueueCallback() at /var/www/app/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php:179
 OldSound\RabbitMqBundle\RabbitMq\Consumer->processMessage() at n/a:n/a
 call_user_func() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:986
 PhpAmqpLib\Channel\AMQPChannel->basic_deliver() at n/a:n/a
 call_user_func() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:202
 PhpAmqpLib\Channel\AbstractChannel->dispatch() at /var/www/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:340
 PhpAmqpLib\Channel\AbstractChannel->wait() at /var/www/app/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php:88
 OldSound\RabbitMqBundle\RabbitMq\Consumer->consume() at /var/www/app/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php:90
 OldSound\RabbitMqBundle\Command\BaseConsumerCommand->execute() at /var/www/app/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/app/vendor/symfony/console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /var/www/app/vendor/symfony/framework-bundle/Console/Application.php:84
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/app/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/app/vendor/symfony/framework-bundle/Console/Application.php:72
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/app/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/app/bin/console:36
```

On the rabbitqm server I also have messages as this for each "connection reset" on the client:
```
=ERROR REPORT==== 16-Feb-2018::13:27:35 ===
closing AMQP connection <0.21550.1> (10.0.1.163:60922 -> 10.0.1.95:5672):
{inet_error,enotconn}
```

I tried to run the client in debug mode, butt apparently there are no "weird" errors...

```
< 60,80:: Basic.ack
waiting for any method
waiting for a new frame
> 60,60: Basic.deliver
waiting for a new frame
waiting for a new frame
< 60,80:: Basic.ack
< [hex]: 
0000  01 00 01 00 00 00 0D 00  3C 00 50 00 00 00 00 00   ........ <.P.....
0010  00 00 5D 00 CE                                     ..].�

< 60,80:: Basic.ack
waiting for any method
waiting for a new frame
> 60,60: Basic.deliver
waiting for a new frame
waiting for a new frame
< 60,80:: Basic.ack
< [hex]: 
0000  01 00 01 00 00 00 0D 00  3C 00 50 00 00 00 00 00   ........ <.P.....
0010  00 00 5E 00 CE                                     ..^.�

!! The ERROR happens here here....

< 20,40:: Channel.close
< [hex]: 
0000  01 00 01 00 00 00 0B 00  14 00 28 00 00 00 00 00   ........ ..(.....
0010  00 00 CE                                           ..�

< 20,40:: Channel.close
< [hex]: 
0000  01 00 01 00 00 00 0B 00  14 00 28 00 00 00 00 00   ........ ..(.....
0010  00 00 CE                                           ..�

< 10,50:: Connection.close
< [hex]: 
0000  01 00 00 00 00 00 0B 00  0A 00 32 00 00 00 00 00   ........ ..2.....
0010  00 00 CE                                           ..�

< 20,40:: Channel.close
< [hex]: 
0000  01 00 01 00 00 00 0B 00  14 00 28 00 00 00 00 00   ........ ..(.....
0010  00 00 CE                                           ..�

< 10,50:: Connection.close
< [hex]: 
0000  01 00 00 00 00 00 0B 00  0A 00 32 00 00 00 00 00   ........ ..2.....
0010  00 00 CE                                           ..�
```

The rabbitmq server and the php client are physically on the same instance. 
The rabbitmq server is a dockerized  rabbitmq and same is the php client.
The docker-daemon is in swarm mode. Ive tried also disabling the routing mesh, but no differences.

The only "uncommon" issues is that this "weird" error happens when there are many queued messages on the server (200k).
Should be no performance issues as the instance has 32GB ram an 8 CPUs...
Client are not using SSL...
Same happens using stream or socket connections.

Tried also a simple rabbitmq restart, but no differences.

Anybody had similar issues?

**Comment by lukebakken** [comment]
This is clearly an issue with networking, most likely due to Docker. Somehow the TCP connection is being abnormally terminated. If you can reproduce this issue without using Docker, please re-open it and let us know.

I suggest doing a search using the string `docker "connection reset by peer"`. Here is one instance of a similar issue that turned out to be IP address collision related - https://serverfault.com/a/848157/227908

**Comment by goetas** [comment]
Interesting detail I've found. When keeping the prefetch count low (10) the problem does not occur. High prefetch (100) triggers this weird behavior. Apparently the amount of consumers does not matter (tried with 1-40 consumers)

**Comment by lukebakken** [comment]
Can you reproduce this without using Docker?

**Comment by goetas** [comment]
hmm, that will be hard as the whole stack is based on it. in case i get more details will comment again.

Thanks for the fast feedback!

**Comment by lukebakken** [comment]
No problem. What's happening is that during a batch of acknowledgements a write to the socket fails because the connection is reset. The only culprit I can think of is something to do with docker networking.

**Comment by goetas** [comment]
> The only culprit I can think of is something to do with docker networking.

me too!

**Comment by goetas** [comment]
Look an issue related to networking of the cloud provider we were using. When we moved to a different one, the issue just disappeared

**Comment by fchris82** [comment]
Just for future, if anybody else find this issue. I used docker, but the "solution" was independent from it.
Here are details what might be the problem: https://stackoverflow.com/a/36114095/1476819 
These two changes solved my problem:
- Adding this before calling `basic_consume`. It sets `prefetch_count` to 1 instead of "infinity".
```php
$channel->basic_qos(null, 1, null);
$channel->basic_consume(...);
```
- I'm not sure that it is necessary too but I have changed from `no_ack` to `ack`. Here scroll down to *Message acknowledgment* title: https://www.rabbitmq.com/tutorials/tutorial-two-php.html

I have done these changes at the same time, and now it works with docker.

**Comment by GeorgII-web** [comment]
I have deleted 1sec delay in a consumer loop and "Connection reset by peer" disappears.
In a Rabbit logs I got rows like connected/disconnected one by one then delay was in a consumer.
Think the problem is in too many reconnections.
I have moved "logic" from consumer and make it work as fast as it can.
So, now I have 1 connection for a hundreds messages in Rabbit logs.
Hope it helps
