### ISSUE TITLE
Error handling of connection issues

### ISSUE THREAD

**Issue by alcohol** [php-amqplib/php-amqplib#548]
We are experiencing a lot of connection issues in our producers:

```
ErrorException: fwrite(): send of 4904 bytes failed with errno=32 Broken pipe in /var/www/releases/20180215.171914-0f7de52165c0802209ab06585cca303b360dd065/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:285
```

In the `write` method of `StreamIO` we can see that a custom error handler is used: https://github.com/php-amqplib/php-amqplib/blob/dfd3694a86f1a7394d3693485259d4074a6ec79b/PhpAmqpLib/Wire/IO/StreamIO.php#L256-L305

On closer inspection, however, we can see that this error handler does not handle the above case, and thus returns an `\ErrorException`: https://github.com/php-amqplib/php-amqplib/blob/dfd3694a86f1a7394d3693485259d4074a6ec79b/PhpAmqpLib/Wire/IO/StreamIO.php#L307-L336

This means that the `\ErrorException` bubbles up into `write` inside `AbstractConnection`, where unfortunately this is not handled and thus the connection is never set to `is_connected = false`: https://github.com/php-amqplib/php-amqplib/blob/dfd3694a86f1a7394d3693485259d4074a6ec79b/PhpAmqpLib/Connection/AbstractConnection.php#L333-L346

How should we go about handling / dealing with this?

**Comment by alcohol** [comment]
Also, would you be open to changing the type of exception returned from the custom error handling to a local namespaced one? That way it is easier to determine where the exception originated from.

**Comment by lukebakken** [comment]
@alcohol we'd be happy to accept a PR with a fix for this.

**Comment by alcohol** [comment]
I am not sure what you would consider an appropriate fix though? I am not intimately familiar with your library. I have been debugging it a lot only lately, as we've frequently been having issues. But they could just as well originate from misconfiguration on our clusters, or in the RabbitMqBundle that we use which is built on top of this library.

In regards to changing the Exception type, would this be considered a BC breaking change? If we extend it from the native \ErrorException it would still match any existing catch statements. Is that an acceptable solution?

**Comment by lukebakken** [comment]
@alcohol apologies for getting back to you so late.

I would like to get a fix for this in the upcoming `2.9.0` release. A broken pipe is an unrecoverable connection exception, so I assume that `AMQPRuntimeException` should be thrown.

**Comment by lukebakken** [comment]
@alcohol thanks!

**Comment by alcohol** [comment]
On closer inspection at the code in its current state, it looks like the original issue should no longer occur. The `\ErrorException` thrown by the `cleanup_error_handler()` method is now turned into a `AMQPRuntimeException` (this was not the case when I first opened this issue). The `write()` method of the `AbstractConnection` does catch this type and marks the connection as disconnected.

**Comment by alcohol** [comment]
#564 and some other cleanup PR's pretty much solved this. I'll close this issue :-)

**Comment by lukebakken** [comment]
Thanks @alcohol !
