### ISSUE TITLE
Whoops, looks like something went wrong. (1/1) ErrorException getimagesize(): send of 18 bytes failed with errno=104 Connection reset by peer

### ISSUE THREAD

**Issue by alabadi93** [php-amqplib/php-amqplib#551]
# **in ShowController.php (line 283)**
--
at HandleExceptions->handleError(8, 'getimagesize(): send of 18 bytes failed with errno=104 Connection reset by peer',

**Comment by lukebakken** [comment]
This isn't nearly enough information to file an issue.

**Comment by alabadi93** [comment]
Hi bro @lukebakken9 
This is  she my problem
 What information should I list?
 Do you have other instructions?
