### ISSUE TITLE
stream_select() ErrorException FD_SETSIZE

### ISSUE THREAD

**Issue by dixromos98** [php-amqplib/php-amqplib#552]
Hi,

I am receiving the following error during the publish to the queue

```
[object] (ErrorException(code: 0): stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.\nIt is set to 1024, but you have descriptors numbered at least as high as 1094.
\n --enable-fd-setsize=2048 is recommended, but you may want to set it\nto equal the maximum number of open files supported by your system,\nin order to avoid seeing this error again at a later date. at php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:420
```

The error says that I am trying to do stream_select() with a file descriptor larger than 1024 (as high as 1094) which is the default for Linux systems.

Any idea as to why the error is occurring and do you know any techniques I can use to avoid it from happening again?

**Comment by lukebakken** [comment]
I ran [a search](https://www.google.com/search?q=%22You+MUST+recompile+PHP+with+a+larger+value+of+FD_SETSIZE%22) that produced a wide variety of information about this error, which is PHP-specific and not related to this library.

**Comment by christianmeller** [comment]
Hi, I'm receiving the same error with v2.7.2 and php 7.1. When i downgrade the library back to v2.7.0 everything works like expected.

**Comment by dixromos98** [comment]
By minimizing the FD_SIZE in our Linux system development environment we manage to make it work as well. The issue for use occurs when we do stream_select() with a file descriptor larger than 1024 and as @lukebakken this is a PHP related issue. Unfortunately i can't downgrade and reproduce this because we did a lot of work to bring the system FD_SIZE down so we can continue development. But  stream_select() will eventually fail if you exceed FD_SIZE more than 1024?
