### ISSUE TITLE
SOCKS Proxy between RMQ and client

### ISSUE THREAD

**Issue by NaeiKinDus** [php-amqplib/php-amqplib#558]
I am trying to access a RabbitMQ broker installed on an external server from an enterprise network server requiring us to use a SOCKS proxy.
I can't for the life of me find a way to make my client successfully connect to it.

Using the basic AMQPStreamConnection I hit a "Cannot access tcp://<whatever>" and if I switch to an AMQPSocketConnection (I'm not even sure that's supposed to change anything in my case) and some putenv() for `http_proxy` and  `https_proxy`, I get "Error Connecting to server (115): Operation now in progress".

Any help / pointers would be greatly appreciated.

**Comment by lukebakken** [comment]
This client does not directly support SOCKS proxies. I suggest using a tunneling solution.
