### ISSUE TITLE
Queue declare not timing out

### ISSUE THREAD

**Issue by programster** [php-amqplib/php-amqplib#561]
When creating a connection to RabbitMQ, an exception will be thrown within 3 seconds if the server cannot be connected to unless the default `$connection_timeout = 3.0` and `$read_write_timeout = 3.0` defaults are overridden to something else.

Unfortunately, these timeouts don't seem to effect how long the application will block for when trying to run a queue_declare operation on a queue that is currently undergoing a large purge operation. The declare call appears to wait indefinitely until the purge has completed.

```
// create the connection, this will throw exception within 3 seconds if cannot connect.
$connection = new \PhpAmqpLib\Connection\AMQPStreamConnection(
    $host, 
    $port, 
    $user, 
    $password
);

print "creating channel: " . time() . "<br>";
$this->m_channel = $connection->channel();

// declare the queue, this will hang forever if a large purge operation is happening.
$this->m_channel->queue_declare(
    $queueName,
    $passive = false,
    $durable = true,
    $exclusive = false,
    $auto_delete = false,
    $nowait = false, 
    $arguments = null,
    $ticket = null
);
```

Is there some other way of writing this code so that I can gracefully capture an exception if the declare operation is taking longer than 3 seconds? I would rather just bail out in such situations and try to recover in some other way, such as using a different queue, or using something other than RabbitMQ if possible. 

I had tried setting nowait to true, but that just resulted in any operations being made asynchronous and the app would get past that line in the code, but the app never stop/end because it was still waiting on RabbitMQ.

I had initially made [a pull request](https://github.com/php-amqplib/php-amqplib/pull/560#issuecomment-382686007) that would pass through a timeout to the declare's internal call to `wait()`, but did not realize the other consequences this would have for people who may wish for the connection to persist, and are switching between various queues.

**Comment by lukebakken** [comment]
Please set the `$channel_rpc_timeout` value in your connection, which will get passed to your channel. This should accomplish what you want. If not, please report back here.
