### ISSUE TITLE
Multihost connection

### ISSUE THREAD

**Issue by ed-fruty** [php-amqplib/php-amqplib#570]
As I see, it was a good thing added by this [commit](https://github.com/php-amqplib/php-amqplib/commit/0ec26a6bb546e6984dc3ed7bc293bb000d17ef16) for multihost connection.

Сould you please orient, when this feature will be released ?

**Comment by lukebakken** [comment]
I expect to release `2.8.0` RC1 this week. Please test it and follow up if you find issues.
