### ISSUE TITLE
can't throw fwrite() error immediately

### ISSUE THREAD

**Issue by luozhijiang** [php-amqplib/php-amqplib#578]
When the rabbitmq client connects to the server and sends a message to the server, I actively shut down the rabbitmq server service. The fwrite method can continue to write successfully and cannot throw an exception, such as "send of 89 bytes failed with errno=32 Broken pipe" Such an error; so I know that processing these messages is really successful. The final result is that some messages are missing.

**Comment by lukebakken** [comment]
This may be addressed by changes in `master` over the past few months. Please give the current code a try, or wait for the upcoming `2.8.0` RC1 release and test that. If you still see the issue, follow up here.
