### ISSUE TITLE
Connecting to Red Hat JBOSS

### ISSUE THREAD

**Issue by slloyd88** [php-amqplib/php-amqplib#580]
Do you have an example of consuming from Red Hat JBOSS queue?  
when I try I get the following:

Error: Uncaught AMQPConnectionException: Library error: unexpected method received - Potential login failure.

**Comment by lukebakken** [comment]
Hello -

I think in this case the easiest way to diagnose what's up would be for you to do a packet capture on port 5672. Wireshark has an AMQP parser which will show what is being exchanged. If you'd like to compress the capture and attach it in your comment, I can check it out.

**Comment by slloyd88** [comment]
[debug.zip](https://github.com/php-amqplib/php-amqplib/files/2198033/debug.zip)

Here is the TCPdump pcap file. I will work on a wireshark file...

**Comment by slloyd88** [comment]
[wireshark.zip](https://github.com/php-amqplib/php-amqplib/files/2198103/wireshark.zip)
Here is the wireshark capture

**Comment by lukebakken** [comment]
@slloyd88 - you can see in the 6th packet that the server is responding with an AMQP 1.0.0 header. This library supports version 0.9.1 of the AMQP protocol.
