### ISSUE TITLE
Please add support for AMQP 1.0

### ISSUE THREAD

**Issue by slloyd88** [php-amqplib/php-amqplib#583]
Can you please add support for AMQP 1.0?  Redhat JBOSS is using AMQP 1.0 and thus I am unable to connect.

**Comment by makasim** [comment]
AMQP 1.0 is a completely different protocol.  It wont be added here. 

It would be good if [amqp qpid](https://qpid.apache.org/) project bring php extension support back

**Comment by slloyd88** [comment]
I asked the amqp qpid forum and they said that PHP was not being maintained well enough so they dropped PHP support.

**Comment by makasim** [comment]
yeah I know, that would be great if they could reconsider. Time has changed.

**Comment by slloyd88** [comment]
One more question/clarification.  If AMQP 1.0 is completely different then does that imply that this library will become obsolete too?  I assume stuff will migrate to use the latest AMQP specs.

**Comment by makasim** [comment]
As long as RabbitMQ supports AMQP 0.9.1 the library will live.

**Comment by slloyd88** [comment]
It looks like RabbitMQ is also moving to 1.0
https://github.com/rabbitmq/rabbitmq-amqp1.0

**Comment by lukebakken** [comment]
RabbitMQ is not "moving" to AMQP 1.0, there is only a plugin to add support.

As mentioned before, AMQP 1.0 is a completely different protocol. It is not "better" than 0.9.1 and there is not nearly as much support or use of it at this time. 1.0 may never be as popular as 0.9.1.

**Comment by pimjansen** [comment]
@lukebakken and all involved. Maybe it is time to reconsider this now after 6 years?

1.0 is being widely adopted and also RabbitMQ is using it.

I think it would be the time to support or both or make different implementations (depending on the diff and complexity)

**Comment by lukebakken** [comment]
@pimjansen it is unlikely that this library will support AMQP 1.0 unless someone who _pays_ for RabbitMQ support requests it.

If someone could point out the source code for AMQP QPID for PHP, maybe we could start with that.

**Comment by dercoder** [comment]
> AMQP 1.0 becomes a core protocol
> [AMQP 1.0 is now a core protocol](https://www.rabbitmq.com/blog/2024/08/05/native-amqp) that is always enabled. Its plugin is > now a no-op that only exists to simplify upgrades.
> 
> The AMQP 1.0 implementation is also significantly more efficient: its peak throughput is [more than double than that of 3.13.x](https://www.rabbitmq.com/blog/2024/08/21/amqp-benchmarks)

https://www.rabbitmq.com/docs/whats-new

![Image](https://github.com/user-attachments/assets/ea9371fd-c4b8-45df-9bc2-0309c1475fa8)

**Comment by lukebakken** [comment]
@dercoder - you may or may not be aware that AMQP 1.0 is a _completely different_ protocol than AMQP 0.9.1, and, as such, would be an enormous undertaking for this project. Nobody from the community has stepped up to add support, and no RabbitMQ customers are interested that I'm aware of.
