### ISSUE TITLE
where is the function "AMQPStreamConnection::create_connection()"

### ISSUE THREAD

**Issue by karliehgf** [php-amqplib/php-amqplib#586]
I installed the 2.7.2 version by composer, but can't find the AMQPStreamConnection::create_connection() when I tryed to connecting the cluster of mq servers.
then I found the function in the master branch.

**Comment by lukebakken** [comment]
`master` != `2.7.2`. This function will be available in the next release (`2.8.0`)

**Comment by karliehgf** [comment]
ths
