### ISSUE TITLE
Connecting RMQ with multiple host connection 

### ISSUE THREAD

**Issue by venugopal8** [php-amqplib/php-amqplib#588]
Thanks for providing sample for multiple host connection.
But i am trying to connect to RMQ with multiple host with this library but i am getting an Call to undefined method PhpAmqpLib\Connection\AMQPStreamConnection::create_connection() while calling

$connection = AMQPStreamConnection::create_connection([
    ['host' => HOST, 'port' => PORT, 'user' => USER, 'password' => PASS, 'vhost' => VHOST],
    ['host' => HOST, 'port' => 5678, 'user' => USER, 'password' => PASS, 'vhost' => VHOST]
],
[]);

if i use like below i am getting missing argument error message.

$connection = new AMQPStreamConnection([
    ['host' => HOST, 'port' => PORT, 'user' => USER, 'password' => PASS, 'vhost' => VHOST],
    ['host' => HOST, 'port' => 5678, 'user' => USER, 'password' => PASS, 'vhost' => VHOST]
],
[]);

Can you please help me on this.

Thanks

**Comment by mayesto** [comment]
I have the same problem. This function is available on the master branch. You probably use v2.7.2 which has not this function.

**Comment by lukebakken** [comment]
I really am trying to get a `2.8.0` release candidate available this week. Keep an eye out and give it a try. Thanks.
