### ISSUE TITLE
Use swoole to generate multi-process channel errors

### ISSUE THREAD

**Issue by bimoQi** [php-amqplib/php-amqplib#592]
I use swoole to generate multiple processes, all processes share the same connection, each process uses a secondary connection to generate a different channel, but the operation is wrong.

`process_pid:52081  time:2018-08-11 06:04:27  recv: using channel_id: 1

process_pid:52082  time:2018-08-11 06:04:27  recv: using channel_id: 2
< 20,10:: Channel.open
< [hex]:
0000  01 00 02 00 00 00 05 00  14 00 0A 00 CE            ........ ....<CE>

< 20,10:: Channel.open
waiting for 20,11
waiting for a new frame

process_pid:52081  time:2018-08-11 06:04:27  recv: < 20,10:: Channel.open
< [hex]:
0000  01 00 01 00 00 00 05 00  14 00 0A 00 CE            ........ ....<CE>

< 20,10:: Channel.open
waiting for 20,11
waiting for a new frame

process_pid:52082  time:2018-08-11 06:04:27  recv: PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: Invalid frame type 0 in /private/var/www/data-collector/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:523
Stack trace:`

If each process is assigned a separate connection, there is no problem.

Trouble to solution my doubts
thanks！thanks

**Comment by lukebakken** [comment]
> If each process is assigned a separate connection, there is no problem

Great, thank you for letting us know. Sharing a connection with swoole is a recipe for disaster.
