### ISSUE TITLE
Unacknowledged Messages after Consumer basic_cancel

### ISSUE THREAD

**Issue by ArtisticPhoenix** [php-amqplib/php-amqplib#593]
When calling basic_cancel from a consumer it leaves Unacknowledged messages.

A few details

- Queue is blocking using $channel->wait()
- Prefetch is 1 (the smallest I can set)
- Consumers can call basic_cancel on a queue they are consuming from
- Consumers pull from multiple queues

```
   Debug::dump($this->getAmqpChannel()->getMethodQueue());
   $this->getAmqpChannel()->basic_cancel( $tag );
   Debug::dump($this->getAmqpChannel()->getMethodQueue());
```

Output

```
  array()
 // RunCommand: basic_cancel this works fine consumer forgets queue except ->
  array(1){
    [0] => array(3){
        [0] => string(5) "60,60",
        [1] => string(114) "amq.ctag-D9om-gD_cPevzeon52zpig\0\0\0\0\0\0\0\0\0G{queuename}",  //{queuename} is the name of the queue, which is based on clients information I cant share (such as their name)
       [2] => object(PhpAmqpLib\Message\AMQPMessage)#0 (9) {
            ["DELIVERY_MODE_NON_PERSISTENT":constant] => int(1),
            ["DELIVERY_MODE_PERSISTENT":constant] => int(2),
            ["body":public] => string(1358647) "{ ... "correlation_id":32,"max_correlation_id":38}"
            ["body_size":public] => int(135864),
            ["is_truncated":public] => bool(false),
            ["content_encoding":public] => null,
            ["propertyDefinitions":protected static] => array(14){ ... }
            ["delivery_info":public] => array(0){},
            ["prop_types":protected] => array(14){ ... }
      }
    }
```

Calling cancel removes the callback for that queue, so messages cannot be processed even though the min prefetch of 1 adds a message after that.

Things I have tried, 

 - calling `basic_nack` is not possible as there is no `delivery_info` in the above information

 - setting no prefetch is not possible, prefetch 0 (the default) fetches all messages

 - using multiple channels on the connection (so the channel could be closed after cancel) is not possible or practical when using blocking because 

`
      while(count($channel->callbacks)) {
             $channel->wait(null, false, $this->_queueInterval);
       }
`

Makes no sense if `$channel` is an array.  Besides that then you wind up calling wait on channels that are closed etc.

This happens every time I call basic cancel on a worker that persists after the call, and example is a consumer pulling messages from multiple queues, have the worker call cancel on one of the queues while there is messages left in the queue, and you will get {n} unacknowledged messages where {n} = the prefetch count.

**Comment by lukebakken** [comment]
I suggest tracing the TCP connection to see what is happening. Since you don't provide a way to reproduce this I can only guess at what is happening. If you acknowledge a message before calling `basic_cancel` I'm pretty sure RabbitMQ is going to deliver the next message before processing the cancel request.

If a way to reproduce this can be provided, I'll give it a try. Thanks.
