### ISSUE TITLE
My api connected to rabbitmq

### ISSUE THREAD

**Issue by Valantir007** [php-amqplib/php-amqplib#594]
I have that system:
client -> service api -> rabbitmq
I do one connection to rabbit per request to api but system is not efficient. Should I keep the connection up? If should I, how can I do that?

**Comment by lukebakken** [comment]
Long-running connections with PHP depend on how you are running your PHP program. If it is within a web server, most likely the connections will be created and torn down on each request. I recommend researching what other PHP projects do to implement long-running connections - maybe you can use ideas from those.
