### ISSUE TITLE
Trying to track down a bug causing a random crash

### ISSUE THREAD

**Issue by hinch** [php-amqplib/php-amqplib#598]
Hi,

I'm trying to track down what appears to be a random failure/crashing of one of my queue workers.  Its a fairly simple php script that subscribes to a rabbit channel and processes items as they're pushed into the queue.  No black magic or fancyness.  The issue I have is that the worker randomly crashes, for example it worked fine for 2 months then died and I had to restart it, then it worked fine for a couple of weeks then it died and needed restarting again.  Now its died 3 days back to back now and every time I just need to restart it.  The error is below and gives me basically no useful information as far as I can see its just like it dies when reading the channel.  I think the error below is slightly misleading as I don't know how you can possibly have the get() function for one iteration and not have it the next its not like the code is mutating mid loop.

I've put the basics of the code below (all it does is send an sms via AWS so i've cut out most of the crap but left the basic aws structure in there incase it is conflicting etc (however unlikely that may be)

Any guidance or suggestions would be much appreciated.

**Code**
```
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('localhost', 5672, 'user', 'pass');
$channel = $connection->channel();
$channel->queue_declare($queueid , false, true, false, false);

$callback = function ($msg) {
try {
			$snsresult = $sns->publish([
				'Message' => "here's your sms", // REQUIRED
				'MessageAttributes' => [
					'AWS.SNS.SMS.SenderID' => [
						'DataType' => 'String', // REQUIRED
						'StringValue' => 'Bob'
					],
					'AWS.SNS.SMS.SMSType' => [
						'DataType' => 'String', // REQUIRED
						'StringValue' => 'Transactional' // or 'Promotional'
					]
				],
				'PhoneNumber' => $msg
			]);			
			$msg_id = $result->get('MessageId');
		} catch (Exception $e) {
			$snsresult['@metadata']['statusCode'] = 0;//override object to show failure
		}
}
$msg->delivery_info['channel']->basic_ack($msg->delivery_info['delivery_tag']);
};
$channel->basic_qos(null, 1, null);
$channel->basic_consume($queueid , '', false, false, false, false, $callback);
while (count($channel->callbacks)) {
	if (file_exists("/queueworkers/stop.txt")) break; 
	$channel->wait();
}
$channel->close();
$connection->close();
```

**Error**
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on array in /www/https/queueworkers/worker.php:247
Stack trace:
#0 [internal function]: {closure}(Object(PhpAmqpLib\Message\AMQPMessage))
#1 /www/https/store/lib/PhpAmqpLib/Channel/AMQPChannel.php(997): call_user_func(Object(Closure), Object(PhpAmqpLib\Message\AMQPMessage))
#2 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#3 /www/https/store/lib/PhpAmqpLib/Channel/AbstractChannel.php(210): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#4 /www/https/store/lib/PhpAmqpLib/Channel/AbstractChannel.php(348): PhpAmqpLib\Channel\AbstractChannel->dispatch('60,60', '\x1Famq.ctag-QKGGc...', Object(PhpAmqpLib\Message\AMQPMessage))
#5 /www/https/queueworkers/worker.php(304): PhpAmqpLib\Channel\AbstractChannel->wait()
#6 {main}
  thrown in /www/https/queueworkers/worker.php on line 247
```

**Comment by lukebakken** [comment]
I'm assuming it is this line throwing the Error:

```
$msg_id = $result->get('MessageId');
```

In order for that to be raised, `$result` must contain an array instead of the expected object instance. I recommend debugging the contents of the `$result` variable to ensure it contains what you expect.
