### ISSUE TITLE
Problem width mbstring.internal_encoding and mbstring.func_overload 

### ISSUE THREAD

**Issue by tcz** [php-amqplib/php-amqplib#6]
We have found a problem which causes the client library not work under some circumstances.

If the PHP INI settings below are set the the indicated values, the client library refuses to finish the handshake.

```
mbstring.internal_encoding => UTF-8
mbstring.func_overload => 2
```

It's most likely because to implement the binary protocol you take advantage of string functions excessively.
We got around the problem by callign ini_set each time we access the library, something like this:

```
$original_internal_encoding = ini_get( 'mbstring.internal_encoding' );
ini_set( 'mbstring.internal_encoding', null );

// Call the php-amqp

ini_set( 'mbstring.internal_encoding', $original_internal_encoding );
```

...but this is quite inconvenient. Do you think this problem could be addressed inside the library? 

Thank you!

**Comment by postalservice14** [comment]
Is this still an issue?  Want to confirm before I look into it...  Thanks!

**Comment by lukebakken** [comment]
See #5, and the fact that the `mb_` functions are used by this library. Closing.
