### ISSUE TITLE
Feature Request: Allow overriding of LIBRARY_PROPERTIES

### ISSUE THREAD

**Issue by madrussa** [php-amqplib/php-amqplib#603]
It would be really useful to override the library properties. If it used a method call instead of a self call then it can be overloaded so it may return more information. Even changing the self call to a static call would allow it to be overwritten. https://github.com/php-amqplib/php-amqplib/blob/3edc3941dd79c46253e2d179b03d9bcbc1e8a98d/PhpAmqpLib/Connection/AbstractConnection.php#L215

This would be especially useful when debugging connections as the information property could be populated with server information, or the platform including the PHP version. 

AbstractConnection
```php
public function getLibraryProperties()
{
    return static::$LIBRARY_PROPERTIES;
}
```

MyCustomConnection
```php
public function getLibraryProperties()
{
    return array_merge(parent::getLibraryProperties(), [
        'platform'    => ['S', 'PHP ' . phpversion()],
        'information' => ['S', env('SERVER') . ' :: ' . $this->getCallee()]
    ];
}
```

Late static binding was introduced in PHP 5.3 so it won't changed the requirements. Also it is an internal call currently so no public API's will be broken / changed.

**Comment by lukebakken** [comment]
Sure, submit a PR with a test. Thanks!

**Comment by lukebakken** [comment]
Implemented by #606

**Comment by hex7c0** [comment]
hey @madrussa thanks for this snippet.
you have a typo in your example :)

```php
public function getLibraryProperties()
{
    return array_merge(parent::getLibraryProperties(), [
        'platform'    => ['S', 'PHP ' . phpversion()],
        'information' => ['S', env('SERVER') . ' :: ' . $this->getCallee()]
    ]);
}
```

**Comment by lukebakken** [comment]
@hex7c0 if there is code to change in this repository, please submit a pull request!
