### ISSUE TITLE
Call protected function outside class

### ISSUE THREAD

**Issue by a-bekzat** [php-amqplib/php-amqplib#604]
`abstract class AbstractChannel
{
....
    public function next_frame($timeout = 0)
    {
        $this->debug->debug_msg('waiting for a new frame');

        if (!empty($this->frame_queue)) {
            return array_shift($this->frame_queue);
        }

        return $this->connection->wait_channel($this->channel_id, $timeout);
    }`

But function wait_channel is protected

**Comment by lukebakken** [comment]
@ramunasd thank you for the clarification.
