### ISSUE TITLE
AMQPStreamConnection $connection_timeout - milliseconds or seconds?

### ISSUE THREAD

**Issue by marcinrosinski** [php-amqplib/php-amqplib#616]
Hi there,

Can you please advise if timeout option for AMQPStreamConnection is in milliseconds or seconds?

Tried finding inside classes but it doesn't say it anywhere.

Thanks,
/Marcin

**Comment by lukebakken** [comment]
The value is in seconds ... having a [3ms default](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPStreamConnection.php#L34-L35) doesn't make much sense 😄

**Comment by marcinrosinski** [comment]
Hi Luke, thanks but if its in seconds them its 3sec not millisecond as its set as 3.0 under __construct()

Can you please confirm?
