### ISSUE TITLE
Undefined constant SOCKET_EAGAIN in Windows

### ISSUE THREAD

**Issue by MaxwellZY** [php-amqplib/php-amqplib#619]
I have found a compatibility bug at \PhpAmqpLib\Wire\IO\StreamIO.php line 88：

```php
self::$ERRNO_EQUALS_EAGAIN = 'errno=' . SOCKET_EAGAIN;
```
I checked the PHP source code, the SOCKET_EAGAIN constant is referred from EAGAIN, but cannot be accessed in Windows (EWOULDBLOCK instead in Windows). Thus the program would crash due to this undefined constant. Please kindly check whether defined SOCKET_EAGAIN before use it, or replace it by SOCKET_EWOULDBLOCK, also it's an alias for SOCKET_EAGAIN in Linux.

```php
// patch type1:
self::$ERRNO_EQUALS_EAGAIN = 'errno=' . (defined('SOCKET_EAGAIN') ? SOCKET_EAGAIN : SOCKET_EWOULDBLOCK);

// patch type2:
self::$ERRNO_EQUALS_EAGAIN = 'errno=' . SOCKET_EWOULDBLOCK;
```

**Comment by lukebakken** [comment]
If you have time, a pull request would be appreciated. Thanks!

**Comment by nifrasismail** [comment]
When I hardcode the value for this, it is working for me 

```
        self::$ERRNO_EQUALS_EAGAIN = 'errno=' . SOCKET_EAGAIN;
        self::$ERRNO_EQUALS_EWOULDBLOCK = 'errno=' . SOCKET_EWOULDBLOCK;
        self::$ERRNO_EQUALS_EINTR = 'errno=' . SOCKET_EINTR;
```

**Comment by nifrasismail** [comment]
I fixed this issue by enabling the socket ext  in php

**Comment by M0H3N** [comment]
@nifrasismail  
How did you enable socket ext ?

**Comment by nifrasismail** [comment]
from your `php.ini` uncomment this 

;extension=php_sockets.dll
