### ISSUE TITLE
Connection remains  isConnected === true while  AMQPHeartbeatMissedException is thrown

### ISSUE THREAD

**Issue by programmer512** [php-amqplib/php-amqplib#627]
php-amqplib version: 2.8.1

I noticed that AbstractConnection::is_connected remains  equal to "true" while we have an exception 
 AMQPHeartbeatMissedException("Missed server heartbeat") which is thrown from AbstractIO::check_heartbeat()

This happens because neither AMQPHeartbeatMissedException and AMQPRuntimeException are never catched during AbstractIO::read operation;

And as a result we can have a FATAL error inside __destruct because we try to close connection there (AbstractConnection::close()) but got exception  "Broken pipe or closed connection". Or it could have any other bad consequences 

Best Regards

**Comment by lukebakken** [comment]
Could we get a pull request to fix this? Thank you.

**Comment by lukebakken** [comment]
Fixed by #659

**Comment by programmer512** [comment]
@lukebakken  thank you for fix.
But my problem was inside check_heartbeat() function which is called from   StreamIO::read() method, not from AbstractIO::select(),  and this exception "AMQPHeartbeatMissedException" is thrown from there

 public function read($len)
    {
        $this->check_heartbeat();

**Comment by ramunasd** [comment]
@programmer512 AMQPHeartbeatMissedException is expected behaviour and warns You about incorrect application behaviour - consumer spends too much time on task without checking connection aliveness.
This exception is is handled in some methods, probably not in all possible places. Can You share a stack trace?

**Comment by programmer512** [comment]
yes. exactly. i competently agree with you.  Task taking too much time and as a result we have this behavior. (throw AMQPHeartbeatMissedException) but i believe it should be handled correctly, connection should be marked as is_connected=== false. Incorrect way only in that we do not mark is_connected as false. will share soon trace

**Comment by programmer512** [comment]
i checked out using this commit:
f8300127bb4b7d1490746e9459329a4b55961dd1
Trace is:
AbstractIO:: check_heartbeat()
 AbstractIO::select() 
AMQPReader::wait()
AMQPReader::rawread() 
AMQPReader::read() 
AbstractConnection::wait_frame()
AbstractConnection::wait_channel()
AbstractChannel::next_frame()
AbstractChannel:wait()

**Comment by ramunasd** [comment]
Thanks!
So AbstractIO::check_heartbeat() is closing socket before exception:
https://github.com/php-amqplib/php-amqplib/blob/f8300127bb4b7d1490746e9459329a4b55961dd1/PhpAmqpLib/Wire/IO/AbstractIO.php#L139

AbstractConnection::wait_frame() catch it and performs unconditional close here:
https://github.com/php-amqplib/php-amqplib/blob/f8300127bb4b7d1490746e9459329a4b55961dd1/PhpAmqpLib/Connection/AbstractConnection.php#L571

So all flags should be reset on any connection exception. Is there anything else we can do here?

**Comment by programmer512** [comment]
@ramunasd , @lukebakken  thank you very much
You are completely right. I did not notice that inside AbstractConnection::wait_frame there is a catch for AMQPConnectionClosedException. So no problem then. Everything is clear and correct from my side.
Sorry for disturbing you because of misunderstanding
