### ISSUE TITLE
Connection is aborted without Exception

### ISSUE THREAD

**Issue by fooger** [php-amqplib/php-amqplib#639]
Hello. I use php-amqplib v2.7.0 and yesterday I had very strange situation:
My consumer script worked fine about 5 months (without rebooting). Yesterday, I saw, last jobs are not not processed. When i go to the RabbitMQ admin panel (RabbitMQ management), I saw that are no active connections. When I go to terminal, and looked to the script status - that are working good, in "waiting" state, i.e. script not trigger any Exception/Fatal error, when connection is broken. After this, I did some tests for active consumer script:
1) I kill connection in RabbitMQ admin panel
2) I turn off/block network connection when script is working

and every time I got an Fatal error.
What could happened? Any ideas/recommendations?
Thank you very much!

**Comment by lukebakken** [comment]
Without more information, like log entries from RabbitMQ and your script, or a way to reproduce this, there's not much I can suggest.

I suggest asking this on the [`rabbitmq-users` mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). Be **sure** to provide this information:

* RabbitMQ, Erlang, PHP and operating system versions
* Logs from RabbitMQ (attach as a file)
* Any other logs or output (attach as a file)
* "every time I got an Fatal error" - what error, exactly?
