### ISSUE TITLE
[2.7,2.8] StreamIO force protocol "ssl" (hardcoded)

### ISSUE THREAD

**Issue by Cyrille37** [php-amqplib/php-amqplib#641]
Hi,

For some reason (system update or ...) our Php RabbitMQ consumers stopped to work. While searching a solution I've found that forcing [`StreamIO::protocol`](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L117) value to "tls" in place on "ssl" make all consumers work again.

But this change is not a option, it's a hardcoded value.

Here the piece of code in [`StreamIO::protocol`](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L117) constructor :
```
        if (is_null($this->context)) {
            // tcp_nodelay was added in 7.1.0
            // ...
        } else {
            $this->protocol = 'ssl';
        }
```

Php version: PHP 7.1.26
Php ssl configuration :
```
$ php -i|grep ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
openssl
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
```

**Comment by lukebakken** [comment]
I would be happy to review a pull request to fix this. It would be even better to know what version of PHP you're using, and how you have TLS configured.

**Comment by Cyrille37** [comment]
@lukebakken I've updated the issue description with some php information.

**Comment by lukebakken** [comment]
Please test the `php-amqplib-641` branch in your environment.
