### ISSUE TITLE
在哪里能设置 x-expires呢，在不修改库代码的情况下

### ISSUE THREAD

**Issue by hkui** [php-amqplib/php-amqplib#644]
现在在delayMessage方法里有设置

**Comment by lukebakken** [comment]
> Now there is a setting in the delayMessage method.

I don't understand your question, sorry.

**Comment by lukebakken** [comment]
Please see this:

https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_message_headers_snd.php
