### ISSUE TITLE
如何判断 channel->basic_publish 是否成功？

### ISSUE THREAD

**Issue by denept** [php-amqplib/php-amqplib#646]
如何判断 channel->basic_publish 是否成功？

**Comment by lukebakken** [comment]
> How can I tell if channel->basic_publish is successful?

Please do not use GitHub issues for questions. Instead, ask on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

You should enable publisher confirms. Please see the [RabbitMQ documentation](https://www.rabbitmq.com/confirms.html), then [this code](https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher_with_confirms.php)

**Comment by denept** [comment]
@lukebakken Thank you!
