### ISSUE TITLE
Undefined constant SOCKET_EAGAIN in Windows

### ISSUE THREAD

**Issue by MaxwellZY** [php-amqplib/php-amqplib#664]
Undefined constant SOCKET_EAGAIN in Windows #619

**Comment by ramunasd** [comment]
Hi @MaxwellZY, thanks for reporting. Probably my fault in latest changes where error handler use that constant directly. In Your case I would suggest to define that costant. It's easy like that
```
if (!defined('SOCKET_EAGAIN')) {
    define('SOCKET_EAGAIN', 11);
}
```

I think we can add that check in next minor release.

**Comment by lukebakken** [comment]
@MaxwellZY - could you please confirm that #668 fixes this in your environment? I don't have a Windows env to test at the moment.

**Comment by lukebakken** [comment]
[`2.9.1` is released](https://groups.google.com/d/topic/rabbitmq-users/ks4kk-raJAw/discussion)
