### ISSUE TITLE
stream_select(): unable to select [4]: Interrupted system call (max_fd=5)

### ISSUE THREAD

**Issue by bigdaddymax** [php-amqplib/php-amqplib#670]
After upgrading to 2.8.1 we get the ocasional following exceptions:

> Fatal error: Uncaught ErrorException: stream_select(): unable to select [4]: Interrupted system call (max_fd=5) in /opt/www/sbwell.com/library/PhpAmqpLib/Wire/IO/StreamIO.php on line 474

It looks like the reason for this exception is the recent change in _error_handler()_ function, in particular the way how specific warning is detected: #615 

In previouse versions it was simple search for "**Interrupted system call**" substring.

Now it is looking for "**errno=4**":

```php
        self::$ERRNO_EQUALS_EINTR = 'errno=' . SOCKET_EINTR;      
        
        // stream_select warning that it has been interrupted by a signal - EINTR
        if (strpos($errstr, self::$ERRNO_EQUALS_EINTR) !== false) {
```
The trick is that the real error string (in our case) does not contain "errno=XXX" substring at all:

> stream_select(): unable to select [4]: Interrupted system call (max_fd=5)

I am not sure if the format of the error string depends on the OS or PHP version, we use PHP 7.1 and CentOS 6.10

**Comment by ramunasd** [comment]
Hi @bigdaddymax , this was fixed in version v2.9.0, please check.

**Comment by lukebakken** [comment]
Assuming fixed in the latest version. If evidence to the contrary is provided, we will re-open.

**Comment by liuyong888** [comment]
> Assuming fixed in the latest version. If evidence to the contrary is provided, we will re-open.

Hi, I ran into this problem with 2.9.1
