### ISSUE TITLE
 Error Wrong parameters for PhpAmqpLib\Exception\AMQPRuntimeException([string $message [, long $code [, Throwable $previous = NULL]]])

### ISSUE THREAD

**Issue by rapkey** [php-amqplib/php-amqplib#671]
I got the following error, what does it mean?

Error Wrong parameters for PhpAmqpLib\Exception\AMQPRuntimeException([string $message [, long $code [, Throwable $previous = NULL]]])

**Comment by ramunasd** [comment]
Hi @rapkey , there are several places where this exception can be thrown. Can You provider more detailed example or stack trace?

**Comment by lukebakken** [comment]
@rapkey we would really like to fix this for version `2.9.2`. Could you please provide the information that @ramunasd requested?

**Comment by lukebakken** [comment]
@rapkey please provide the requested information. We plan on releasing version `2.9.2` with a fix for this, but can't continue without more information.

**Comment by lukebakken** [comment]
I checked all the places where `AMQPRuntimeException` and its derived classes are instantiated and I can't see where this originates. Assuming that it is fixed in the latest version.
