### ISSUE TITLE
Broken pipe connection

### ISSUE THREAD

**Issue by loicdev** [php-amqplib/php-amqplib#679]
Hello, i use php-amqplib version 2.8.0 in 4 projects and very often i had this error on all my consumers at the same time : 
```
Broken pipe or closed connection at /usr/local/src/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:222
```
That refert to: 
https://github.com/php-amqplib/php-amqplib/blob/v2.8.0/PhpAmqpLib/Wire/IO/StreamIO.php#L222

Can i have a explanation about what does it mean and how to prevend it ? 
Thanks in advance

**Comment by lukebakken** [comment]
Perhaps the connection has been closed, but there isn't enough information here to diagnose. Please let us know what AMQP broker you are using (RabbitMQ? What version?) and what the broker logs at the time the exception is thrown.

If this information is provided and a bug or other actionable work for `php-amqplib` is found, I will re-open this issue. Thanks.

**Comment by nicopenaredondo** [comment]
@loicdev  have you managed to find a solution on this ?
