### ISSUE TITLE
Consider adding re-connection handling

### ISSUE THREAD

**Issue by schmittjoh** [php-amqplib/php-amqplib#68]
I'm wondering whether you have thought about adding some logic for handling re-connects?

Especially for longer running processes, there is always the possibility that the rabbitmq server is temporarily unavailable which would be good to handle a bit more gracefully than just throwing an exception.

Do you think such logic would belong to this library, or should rather be in a different place?

**Comment by lukebakken** [comment]
I believe that the heartbeat and re-connection changes to this library have implemented what was requested here. Closing.

**Comment by videlalvaro** [comment]
@lukebakken Hi, I kept seeing today that you where closing PRs and branches which is great. Have you seen what's going on at packagist?

I keep receiving emails with this error message:

```
The videlalvaro/php-amqplib package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.
```

**Comment by lukebakken** [comment]
That's news to me. Do you want to open a new issue to track it instead of commenting here?

**Comment by videlalvaro** [comment]
I didn't know where to report so I just replied to one of the many emails I've been getting this week from github telling me some issues have been closed :D

**Comment by lukebakken** [comment]
@videlalvaro please see #533
