### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by AnarbekB** [php-amqplib/php-amqplib#680]
Error in demo file demo/amqp_consumer.php:83 line

> // Loop as long as the channel has callbacks registered
while ($ch->is_consuming()) {
    $channel->wait();
}

use $channel instead of $ch

**Comment by lukebakken** [comment]
We would be happy to accept a pull request to fix this, thanks.

**Comment by AnarbekB** [comment]
https://github.com/php-amqplib/php-amqplib/pull/681
