### ISSUE TITLE
stream_socket_client(): unable to connect to tcp://

### ISSUE THREAD

**Issue by AmberLavigne** [php-amqplib/php-amqplib#682]
ErrorException: stream_socket_client(): unable to connect to tcp://: (Failed to parse address ":") in vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:141

**Comment by ramunasd** [comment]
Hi @AmberLavigne, seems Your configuration is wrong. You must provide valid hostname/ip address. AFAIK ipv6 is not supported by this lib.
