### ISSUE TITLE
High CPU usage after 2.9.0 release.

### ISSUE THREAD

**Issue by umbrella-artem-seryak** [php-amqplib/php-amqplib#686]
After 2.9.0 was released we noticed a significant spike in the CPU usage in our project.

Investigation proved the problem was with the php-amqplib package, which we do not use directly, but it is used by [bschmitt/laravel-amqp](https://github.com/bschmitt/laravel-amqp) [here](https://github.com/bschmitt/laravel-amqp/blob/master/src/Consumer.php#L73). From our side, the usage of `bschmitt/laravel-amqp` is basically limited to the usage of their `consume` method.

So what happens is `laravel-amqp` calls `wait` method from `php-amqplib`(https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AbstractChannel.php#L334), which after https://github.com/php-amqplib/php-amqplib/pull/642 was merged throws an `AMQPNoDataException` in case timeout is disabled (instead of patiently waiting for a data as happens in case timeout is set to `0`). And in this particular case timeout is disabled because of a non-blocking action (https://github.com/php-amqplib/php-amqplib/pull/642/files#diff-195c265ed9a66166715118df34df6ea3R339).

After `AMQPNoDataException` is thrown, the process repeats. `bschmitt/laravel-amqp` calls `wait` method, again and again, resulting in an endless loop.

It is hard to tell for me what is the solution here, but since there is a specific PR which caused this I felt like you guys might have a better idea. Obviously, removal of this lines:

```
        // timeouts must be deactivated for non-blocking actions
        if (true === $non_blocking) {
            $timeout = null;
        }
```

Solves the issue, but I am not aware of the reasoning behind them.

**Comment by ramunasd** [comment]
Hi @umbrella-artem-seryak, if You are using non blocking `wait()` then You must take care of some some delays between calls.
We don't want to enable timeouts for non-blocking `wait()` because it simply makes no sense.
So either use blocking mode or catch that exception and add delays.
