### ISSUE TITLE
stream_socket_client unable to connect (Unknown error) - OpenSSL 1.0 vs 1.1

### ISSUE THREAD

**Issue by Cyrille37** [php-amqplib/php-amqplib#687]
Hello

A working configuration stopped to work with the error "stream_socket_client unable to connect (Unknown error)".

The other side sysadmin tell me that is because they using RabbitMQ and OpenSSL 1.0 and my side using OpenSSL 1.1. Do you agree with this potential reason ?

Thanks a lot.

```
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPIOException: stream_socket_client():
 unable to connect to tls://xxx-xxx.com:5671 (Unknown error)
in .../rabbitmq_tester/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:109
Stack trace:
#0 .../rabbitmq_tester/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(213): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 .../rabbitmq_tester/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(197): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 .../rabbitmq_tester/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(69): PhpAmqpLib\Connection\AbstractConnection->__construct('dwh_pro...', 'XxXx...', 'dwh_pro...', false, 'AMQPLAIN', NULL, 'fr_FR', Object(PhpAmqpLib\Wire\IO\StreamIO), 60, 3, 0)
#3 .../rabbitmq_tester/vendor/ in .../rabbitmq_tester/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 109
```

**Comment by ramunasd** [comment]
Hi @Cyrille37, very likely it is secure connection problem and both sides cannot complete negotiation process. Unfortunally there is no easy way to debug this case.
Have You tried to use `ssl` instead of `tls` as protocol? Also, there is several other options which might have impact, check it out - https://www.php.net/manual/en/context.ssl.php

**Comment by lukebakken** [comment]
Please follow the troubleshooting steps here: https://www.rabbitmq.com/troubleshooting-ssl.html

Working TLS configurations don't suddenly stop - did something change?

If you'd like to continue discussing this issue, please do so on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list, providing the following information:

* RabbitMQ, Erlang, PHP and `php-amqplib` versions
* Log files from RabbitMQ, or at least log entries for this connection event.

Thanks

**Comment by Cyrille37** [comment]
ok, thanks.
