### ISSUE TITLE
report error inqueue_declare

### ISSUE THREAD

**Issue by BlackDogLi** [php-amqplib/php-amqplib#692]
My code:
```
$con = new AMQPStreamConnection('127.0.0.1', 5672, 'guest', 'guest');
        $channel = $con->channel();
        $channel->queue_declare('study_notice', false, true, false, false, ['x-queue-mode' => 'lazy']);
        $callback = function ($msg) {
            echo $msg->body;
        };
        $channel->basic_consume('study_notice', '', false, true, false, false, $callback);

        while(count($channel->callbacks)) {
            $channel->wait();
        }
        $channel->close();
        $con->close();
```

error: 
![image](https://user-images.githubusercontent.com/29592417/58087718-bb3b3600-7bf3-11e9-9d5c-d68152130266.png)

**Comment by ramunasd** [comment]
@BlackDogLi usually You cannot change queue options, they always must be same. Unless queue was deleted before declaring using different options.
Closing because this is not library problem.

**Comment by BlackDogLi** [comment]
I try delete the queue, and run my code.There is no x-queue-mode in the queue info after create the queue.
I try print the $arguments on the function queue_declare,it echo [].I do not find the problem!
