### ISSUE TITLE
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE

### ISSUE THREAD

**Issue by monsieurchico** [php-amqplib/php-amqplib#693]
Hello, 

I known there already are closed issues on the subject but I encounter this error on one of my project. I tried to downgrade the version to 2.7.0 and it worked.

But it's not really a reliable solution.... 

May be a retry system could be implemented ? 

My stack : 
- php 7.1.28 (docker alpine version)
- symfony 4.2
- swarrot bundle

The full error :

> [2019-05-22 11:23:38] app.ERROR: Uncaught exception of type PhpAmqpLib\Exception\AMQPIOWaitException {"exception_message":"stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.\nIt is set to 1024, but you have descriptors numbered at least as high as 1610.\n --enable-fd-setsize=2048 is recommended, but you may want to set it\nto equal the maximum number of open files supported by your system,\nin order to avoid seeing this error again at a later date.","class":"PhpAmqpLib\\Exception\\AMQPIOWaitException","code":0,"file":"/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:89","app_code":"INTERNAL_SERVER_ERROR"} []

**Comment by ramunasd** [comment]
Hi @monsieurchico , can You try latest version with disabled `tcp_nodelay` ? I think #517 is the only one change which can cause this type of error.

**Comment by monsieurchico** [comment]
How can I disable tcp_nodelay ?

**Comment by ramunasd** [comment]
```
$context = stream_context_create();
$connection = new AMQPStreamConnection($host, $port, $user, $password, $vhost, false, 'AMQPLAIN', null, 'en_US', 3, 130, $context);
```

**Comment by monsieurchico** [comment]
Is there a way to do it in swarrot ?

**Comment by ramunasd** [comment]
@monsieurchico please ask there :)

**Comment by lukebakken** [comment]
Assuming addressed by @ramunasd 's comment [here](https://github.com/php-amqplib/php-amqplib/issues/693#issuecomment-494806389).

**Comment by ym2048** [comment]
@monsieurchico

**Comment by ym2048** [comment]
@lukebakken

**Comment by ym2048** [comment]
@monsieurchico 
we also downgrade the version to 2.7.0,  is that you final solution?

**Comment by ramunasd** [comment]
@ym2048 can You prepare example on how to reproduce this issue?

**Comment by ym2048** [comment]
@ramunasd

**Comment by ramunasd** [comment]
@ym2048 So in which sapi you get this error? CLI or CGI?
I guess there is something wrong in Your client code. You either spinning up too much processes or each process opens too much connections. Single process single connection consumes only one file descriptor.

More context:
https://bugs.php.net/bug.php?id=69637
https://bugs.php.net/bug.php?id=37025

**Comment by gitsrc** [comment]
Centos operating system can try to adjust the LimitNPROC parameter of systemd or kernel。
# Specifies the maximum number of processes
LimitNPROC=4096

**Comment by bizmate** [comment]
> ```
> $context = stream_context_create();
> $connection = new AMQPStreamConnection($host, $port, $user, $password, $vhost, false, 'AMQPLAIN', null, 'en_US', 3, 130, $context);
> ```

Just to confirm, your suggestion of disabling  tcp_nodelay  is to pass value 130 as the ``_$read_write_timeout_ argument?
