### ISSUE TITLE
FATAL ERROR: Call to a member function send_content() on null

### ISSUE THREAD

**Issue by andreagualandi** [php-amqplib/php-amqplib#698]
I got this error while i'm using the AMPQChannel's class method `channel->basic_publish(...)`. It's rare. But sometimes, for unkown reasons, it happen that the rabbit connection is closed in the middle of the php request. So at code's line 1163: `$this->connection->send_content(` spawn the fatal error because `connection` is null. Maybe is better to check if `isset($this->connection) before using it. And if is not set throw an handable exception. In that way i can catch that exception and retry to connect rabbit.

**Comment by ramunasd** [comment]
Indeed, write oprations must check connection aliveness, if crucial exceptions were ignored :)

**Comment by lukebakken** [comment]
Fixed by #701
