### ISSUE TITLE
[Question] php-amqplib reuse connection

### ISSUE THREAD

**Issue by josep1122** [php-amqplib/php-amqplib#702]
Hi, i working in php system and i have to send many messages and I noticed that when opening a connection this delay between 1 ~ 2 seconds, which is too much for me, so I need to know if it is possible to reuse the connections with php-amqplib and AMQPSSLConnection

**Comment by lukebakken** [comment]
> I need to know if it is possible to reuse the connections with php-amqplib and AMQPSSLConnection

It is, it depends on how you are running your script (`php` directly vs web server). You should also look at [this project](https://github.com/cloudamqp/amqproxy).

In the future, please use the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list for questions. Thanks.
