### ISSUE TITLE
Long running producer -- can send messages to queues already declared, but can't declare new queues

### ISSUE THREAD

**Issue by skeets23** [php-amqplib/php-amqplib#703]
I have a "producer" that's supposed to be always running, but it seems that after a day or so, it is still able to send messages to queues it has previously declared, but when trying to declare a new queue, it blows up with:

```
'PhpAmqpLib\Exception\AMQPHeartbeatMissedException' with message 'Missed server heartbeat' in /php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:140
```

I thought that the heartbeat was only for consumers (since there's no place to check for heartbeats on producers)? Is it a bug that the heartbeat is being checked when I'm not a "consumer"?

Or is it that my script also becomes a "consumer" when I declare a queue, because it needs to "consume" feedback from the server that the queue is ready for use or something?

The way it's currently set up, what work-around could I use periodically to check if `queue_declare` would blow up if it was run, so that when I do need to run `queue_declare` it doesn't blow up unexpectedly?

I'm using `AMQPSSLConnection` on the most recent version (2.9.2), and `$connection->isConnected()` is returning `true` the whole time. Heartbeat is set to 15 seconds.

**Comment by lukebakken** [comment]
I don't have any ideas - @ramunasd ?

If you could provide code to reproduce this, that's about the best way we can try to fix it.

**Comment by ramunasd** [comment]
Hi @skeets23 , from official documentation[1]:
> Any traffic (e.g. protocol operations, published messages, acknowledgements) counts for a valid heartbeat

So it really does not matter are You consuming or producing messages, heartbeats must be sent/received if they are enabled.
In Your case I would recommend to increase heartbeat timeout or disable it at all. 15 seconds is quite short interval to keep up and very likelly it is causing false positives[2]. Otherwise, use some very smart technique (threads, async, ticks) to trigger heartbeat check every `heartbeat timeout / 2 seconds` [1].

[1] https://www.rabbitmq.com/heartbeats.html
[2] https://www.rabbitmq.com/heartbeats.html#false-positives

**Comment by skeets23** [comment]
15 seconds does seem pretty short, but for consumers, I've been pretty successful with this time frame (very low false positives) on 200+ locations over the past several months.

I traced the error back a little bit, and I see the issue now. While declaring new queues checks the heartbeat, and sends / receives when needed, sending messages with `basic_publish` does not check the heartbeat or send / receive the heartbeat. So that explains why I was able to continue sending messages, but not able to declare new queues.

So it may be considered a bug that sending messages doesn't check / read / write heartbeats.

Of course, if you're not guaranteed to send a message more often than the heartbeat timeout, it wouldn't be enough to only check for heartbeats when sending messages, so perhaps it's not a bug. I could see it interpreted either way. I suppose it's not worth changing, since that would definitely be a breaking change.

I believe (please correct me if I'm wrong) that calling this occasionally would be a valid way to check / read / write heartbeats:

$connection->wait(null, true);

**Comment by ramunasd** [comment]
As for now, yes, `wait()` function can handle all pending messages.
In next minor release there will be a new dedicated function for that `$connection->checkHeartBeat()`.
