### ISSUE TITLE
Warning for SOCKET_EWOULDBLOCK not defined

### ISSUE THREAD

**Issue by nicola883** [php-amqplib/php-amqplib#705]
Hi.
It seems that constant SOCKET_EWOULDBLOCK is never defined.
Therefore, a warning message is raised:
`Warning: Use of undefined constant SOCKET_EWOULDBLOCK - assumed 'SOCKET_EWOULDBLOCK' (this will throw an Error in a future version of PHP) in /sun/server/composer-libs/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 78`

**Comment by lukebakken** [comment]
This is probably similar to #619 and I'm sure the fix is similar. It would be great to get a pull request to fix this. Thanks!

**Comment by ramunasd** [comment]
Hi @nicola883, are You sure sockets extension is enabled and You can connect to broker?
Can You share PHP and OS version?

**Comment by bravist** [comment]
```bash

root@3bcfd2276a9a:/var/www/zhanye# php -v
PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
root@3bcfd2276a9a:/var/www/zhanye# php -m|grep sockets
sockets
root@3bcfd2276a9a:/var/www/zhanye# php -m|grep bcmath
bcmath
root@3bcfd2276a9a:/var/www/zhanye#


```


i used laradock, but same problem with me

**Comment by ramunasd** [comment]
thanks @bravist, I see there is different script paths in issue body and your previous comment, maybe the reason is that sockets extension is not enabled only for web server?

**Comment by bravist** [comment]
> thanks @bravist, I see there is different script paths in issue body and your previous comment, maybe the reason is that sockets extension is not enabled only for web server?

yes, you are right.  


if run CLI mode, no problem. but only for web server.


so, how can i slove it?

**Comment by ramunasd** [comment]
I see You use ubuntu so this tutorial should help
https://tecadmin.net/enable-disable-php-modules-ubuntu/
