### ISSUE TITLE
Broken pipe or closed connection

### ISSUE THREAD

**Issue by dercoder** [php-amqplib/php-amqplib#706]
Hi,

currently i am using the php-amqp extension but i want to switch to php-amqplib library.
With the php extension, my connection is working but with this library i get this error message:
`Broken pipe or closed connection` (with and without ssl).

The server is some external service so i dont have any possibility to get the log files.
The service dont use passwords, only username.

php-amqplib version: `2.9.2`
php version: `7.2.17`
rabbitmq version: `3.7.14`

my php code:
```php
$connection = new AMQPSSLConnection($host, 5672, $user, null, $vhost);
```

```
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
> 10,10: Connection.start
Start from server, version: 0.9, properties: capabilities=(publisher_confirms=1, exchange_exchange_bindings=1, basic.nack=1, consumer_cancel_notify=1, connection.blocked=1, consumer_priorities=1, authentication_failure_close=1, per_consumer_qos=1, direct_reply_to=1), cluster_name=rabbit@xxxxx, copyright=Copyright (C) 2007-2019 Pivotal Software, Inc., information=Licensed under the MPL.  See https://www.rabbitmq.com/, platform=Erlang/OTP 21.3.4, product=RabbitMQ, version=3.7.14, mechanisms: PLAIN, AMQPLAIN, locales: en_US
< 10,11:: Connection.start_ok
< [hex]: 
0000  01 00 00 00 00 01 0E 00  0A 00 0B 00 00 00 F3 07   ........ ......ó.
0010  70 72 6F 64 75 63 74 53  00 00 00 07 41 4D 51 50   productS ....AMQP
0020  4C 69 62 08 70 6C 61 74  66 6F 72 6D 53 00 00 00   Lib.plat formS...
0030  03 50 48 50 07 76 65 72  73 69 6F 6E 53 00 00 00   .PHP.ver sionS...
0040  03 32 2E 39 0B 69 6E 66  6F 72 6D 61 74 69 6F 6E   .2.9.inf ormation
0050  53 00 00 00 00 09 63 6F  70 79 72 69 67 68 74 53   S.....co pyrightS
0060  00 00 00 00 0C 63 61 70  61 62 69 6C 69 74 69 65   .....cap abilitie
0070  73 46 00 00 00 8C 1C 61  75 74 68 65 6E 74 69 63   sF...Œ.a uthentic
0080  61 74 69 6F 6E 5F 66 61  69 6C 75 72 65 5F 63 6C   ation_fa ilure_cl
0090  6F 73 65 74 01 12 70 75  62 6C 69 73 68 65 72 5F   oset..pu blisher_
00A0  63 6F 6E 66 69 72 6D 73  74 01 16 63 6F 6E 73 75   confirms t..consu
00B0  6D 65 72 5F 63 61 6E 63  65 6C 5F 6E 6F 74 69 66   mer_canc el_notif
00C0  79 74 01 1A 65 78 63 68  61 6E 67 65 5F 65 78 63   yt..exch ange_exc
00D0  68 61 6E 67 65 5F 62 69  6E 64 69 6E 67 73 74 01   hange_bi ndingst.
00E0  0A 62 61 73 69 63 2E 6E  61 63 6B 74 01 12 63 6F   .basic.n ackt..co
00F0  6E 6E 65 63 74 69 6F 6E  2E 62 6C 6F 63 6B 65 64   nnection .blocked
0100  74 01 08 41 4D 51 50 4C  41 49 4E 00 00 00 00 05   t..AMQPL AIN.....
0110  65 6E 5F 55 53 CE                                  en_USÎ

< 10,11:: Connection.start_ok
waiting for 10,20, 10,30
waiting for a new frame
closing input
closing socket
closing input
closing socket
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPConnectionClosedException: Broken pipe or closed connection in /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:170
Stack trace:
#0 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(165): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#1 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(107): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(548): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(604): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(233): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 0)
#5 /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/Abstra in /home/ec2-user/test/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 170
```

**Comment by lukebakken** [comment]
> The server is some external service so i dont have any possibility to get the log files.

Try testing your code with your own instance of RabbitMQ.

Only use `AMQPSSLConnection` if you really are using TLS. If you can get a packet capture with Wireshark that may be helpful.

If additional information is provided that points to a bug in this library, I will re-open this issue.

**Comment by dercoder** [comment]
Hi,

i created my own rabbitmq server and i found the bug. Its because the password is empty (the user has no password).

So i tried to connect with $pass as `null`, `''` and `false`. The issue alway happens.

```php
define('AMQP_DEBUG', true);

$host = 'localhost';
$port = 5672;
$username = 'test';
$password = null;
$virtualHost = '/test/1234';

$connection = new AMQPStreamConnection($host, $port, $username, $password, $virtualHost);
```

**Comment by lukebakken** [comment]
What is logged by RabbitMQ?

**Comment by dercoder** [comment]
```
2019-07-02 22:28:32.796 [error] <0.21785.1303> closing AMQP connection <0.21785.1303> (127.0.0.1:51990 -> 127.0.0.1:5672):
{handshake_error,starting,0,{amqp_error,syntax_error,"AMQPLAIN auth info [] is missing LOGIN or PASSWORD field",'connection.start_ok'}}
```

**Comment by lukebakken** [comment]
So this library needs to set a `null` or empty password correctly in the connection message. Thank you for the report. If you have time to fix it, that would be great. I may not have time until next week.

**Comment by dercoder** [comment]
Yes i think to. You are welcome. I would like to help you but i am not so familiar with this protocols. Sorry

**Comment by ramunasd** [comment]
I see credentials are sent only when both user and password not empty
https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AbstractConnection.php#L185
Should be easy to fix but tests must be added.

**Comment by ramunasd** [comment]
@dercoder since versions `3.6.15` and `3.7.3` blank password is not allowed [1]. In such case RabbitMQ outputs something like:
```
Error on AMQP connection <0.1608.0> (172.19.0.4:43480 -> 172.19.0.2:5672, state: starting):
rabbitmq_1  | AMQPLAIN login refused: user 'test_77371115' attempted to log in with a blank password, which is prohibited by the internal authN backend. To use TLS/x509 certificate-based authentication, see the rabbitmq_auth_mechanism_ssl plugin and configure the client to use the EXTERNAL authentication mechanism. Alternatively change the password for the user to be non-blank.
```

So we can throw descriptive exception here. It is expected behaviour?

[1] https://www.rabbitmq.com/passwords.html#passwordless-users

**Comment by dercoder** [comment]
@ramunasd but i tried this without password with version `3.7.14` and it worked.
As i described in my first comment, i try to connect to an external provider which uses the same version and users without passwords. I also switched back to the amqp php extension and its working fine without password. So maybe the passwordless users are deprecated but they are still supported.

Please take a look at this screeenshot:

![rabbitmq](https://user-images.githubusercontent.com/1737685/62045198-0d589300-b205-11e9-916f-2e1aa2dd4f81.png)

**Comment by ramunasd** [comment]
@dercoder php extension use auth method `PLAIN` which is different from default legacy `AMQPLAIN`. I see this library does not support SASL based auth methods and connection with blank password is not possible.
I would say it is not a bug, but rather missing feature. Please reopen this as feature request with descriptive title. Thanks.

**Comment by dercoder** [comment]
No matter. I will just use the PHP extension.

**Comment by bhupendravgroup** [comment]
This is due to the permssion issue while connecting with rabbitmq

create a user in rabbitmq using below command
rabbitmqctl add_user username password
set this user as admin
rabbitmqctl set_user_tags username administrator
you will see that this user does not have any permission
rabbitmqctl list_user_permissions username
Assign this user all permssions
rabbitmqctl set_permissions -p / username "^username -." "." ".*"

**Comment by bhupendra-mehra** [comment]
This is due to the permssion issue while connecting with rabbitmq

1. create a user in rabbitmq using below command
rabbitmqctl add_user username password
2. set this user as admin
 rabbitmqctl set_user_tags username administrator
3. you will see that this user does not have any permission
 rabbitmqctl list_user_permissions username
4. Assign this user all permssions
 rabbitmqctl set_permissions -p / username "^username -." "." ".*"

It works for me, Best of Luck

**Comment by dercoder** [comment]
It maybe works when you are the owner of the rabbitmq server ;)
We need to access an external server.

I use the php extension since 2 years and its working fine

**Comment by MrMaximus** [comment]
For me the problem was simply that the connection object was outliving the timeout so trying to interact with the channel after timeout resulted in this error. Now I create a new connection for a task and then close it afterwards
