### ISSUE TITLE
Is Channel access by reference a possibility?

### ISSUE THREAD

**Issue by durandster** [php-amqplib/php-amqplib#707]
I'm currently implementing a wrapper around this library to bring it into our generic connector framework. We encountered an issue whereby we were referencing the channel via the connection class on multiple occasions and realised the channel we were being returned was a copy and not the actual channel initially set up. So, for example, this is from a basic receive example:

```
echo " [*] Waiting for messages. To exit press CTRL+C\n";                        
                                                                                
$callback = function ($msg) {                                                    
    echo ' [x] Received ', $msg->body, "\n";                                     
};                                                                               
                                                                                 
$connection->channel()->basic_consume(
    'hello', '',
    false, true, false, false,
    $callback
);

while (count($connection->channel()->callbacks)) {                               
    $connection->channel()->wait();                                              
} 
```

The above **will not work** because the channel() call returns a copy of the channel object each time - operations on it are essentially operations on different objects.

Generally this is not obvious in the example code because generally the channel object is retrieved into it's own variable and thereafter all operations are done on that copy. For example:

```
$channel = $connection->channel();
$channel->doThis();
$channel->doThat();
```

I think either a small note about this should be placed somewhere or reference access granted to the channel object so that reading of the code represents the actions taking place. Just pointing this out. Not quite sure what to do about this. It won't be obvious to some people.

I'm now storing the initial channel object separately and referencing that copy directly.  I assume this is fine because it's more in line with the examples.

**Comment by ramunasd** [comment]
You are right, this method always returns new channel, not only new object, but also new rabbitmq channel. From documentation[1]:
> Some applications need multiple logical connections to the broker. However, it is undesirable to keep many TCP connections open at the same time because doing so consumes system resources and makes it more difficult to configure firewalls. AMQP 0-9-1 connections are multiplexed with channels that can be thought of as "lightweight connections that share a single TCP connection".

There is no separate methods to get new/existing channels. You must either keep reference or pass channel id to this method to get existing one.

[1] https://www.rabbitmq.com/channels.html
