### ISSUE TITLE
why php alway quit

### ISSUE THREAD

**Issue by panshuangqing** [php-amqplib/php-amqplib#708]
when i use  $channel->basic_consume($queueName, $consumerTag, false, false, false, false, array($this, 'process_message')); and          while ($channel->is_consuming()) {
            $channel->wait();
        }  I want  block always but  about  20 seconds  php script quit

**Comment by ramunasd** [comment]
@lukebakken I think it's time to introduce github issue template :)

**Comment by ramunasd** [comment]
@panshuangqing please create another ticket using bug report template/
