### ISSUE TITLE
Connection timeout disguised as missed server heartbeat

### ISSUE THREAD

**Issue by Naktibalda** [php-amqplib/php-amqplib#713]
I have a cronjob running every 5 minutes which connects to RabbitMQ.
Occationaly it fails after a few seconds with `PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPHeartbeatMissedException' with message 'Missed server heartbeat'` in php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:609

https://github.com/php-amqplib/php-amqplib/blob/v2.9.2/PhpAmqpLib/Connection/AbstractConnection.php#L609

I did some debugging and the message of original exception  is `The connection timed out after 3 sec while awaiting incoming data`, but heartbeat condition passes, because `$this->last_frame` is null.
I would rather get a connection timeout message than misleading missed heartbeat message,

**Comment by lukebakken** [comment]
Fixed by #716
