### ISSUE TITLE
UNIX only SOCKET_* constants trigger E_NOTICE on Windows

### ISSUE THREAD

**Issue by RyAndrew** [php-amqplib/php-amqplib#723]
**Version(s) affected**: 2.9.1 and up?

**Description**
When rabbit server closes connection on windows platform, I get PHP_NOTICE error raised instead of correct AMQPConnectionClosedException exception thrown.
error:
php-amqplib-2.9.1\PhpAmqpLib\Wire\IO\SocketIO.php(176):
PHP  E_NOTICE Error (8)! Use of undefined constant SOCKET_EPIPE - assumed 'SOCKET_EPIPE'

see php docs: https://www.php.net/manual/en/sockets.constants.php
_The following constants are **only available on UNIX-like platforms**. Each constant is only defined if their equal is available on the platform._

All of the SOCKET_* constants used in the error handling fall into this "Unix Only" category.

Failing on this block:
Wire/IO/StreamIO.php
```
$code = $this->last_error['errno'];
switch ($code) {
case SOCKET_EPIPE: // This is line 176
case SOCKET_ENETDOWN:
case SOCKET_ENETUNREACH:
case SOCKET_ENETRESET:
case SOCKET_ECONNABORTED:
case SOCKET_ECONNRESET:
case SOCKET_ECONNREFUSED:
case SOCKET_ETIMEDOUT:

```

**How to reproduce**  
On windows platform run this code and stop your rabbit service during the sleep() period:

```
$connection = new AMQPSocketConnection($server, $port, $username, $password);
$channel = $connection->channel();
$msg = new AMQPMessage("test");
sleep(20); //STOP THE RABBIT SERVICE NOW!
$channel->basic_publish($msg, '', $queue);
```

**Possible Solution**  
instead of using SOCKET_ constants for non unix switch to self::$SOCKET_ERR_* type constants maybe

**Additional context**

**Comment by ramunasd** [comment]
@RyAndrew could You please share output of script `tests/phpinfo.php` ?

**Comment by RyAndrew** [comment]
Attached is the requested output from test/phpinfo.php
[phpinfo.html.txt](https://github.com/php-amqplib/php-amqplib/files/3463915/phpinfo.html.txt)
I saved as .html but doesn't like html attachments so it is renamed to .txt

Thanks for the quick fix!!
