### ISSUE TITLE
Heartbeat problem when the consumer consume a message for too long

### ISSUE THREAD

**Issue by Kangkeizai** [php-amqplib/php-amqplib#725]
We are using the default heartbeat settings: 60S. 
When a message is delivered to the consumer and the consumption time exceeds 2 to 3 heartbeats, the server will actively disconnect the connection. 
The log shows: missed heartbeats from client, timeout: 60s.
How can I keep the connection alive?

**Comment by ramunasd** [comment]
- increase heartbeat timeout
- disable it
- use ticks to periodically check heartbeat as described https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp_lib.md#long-running-task-and-heartbeat-and-timeouts
