### ISSUE TITLE
How to set connection name ?

### ISSUE THREAD

**Issue by younessadmi** [php-amqplib/php-amqplib#728]
Hi there, 
I'm using php-amqplib 2.9.2 and I was looking for setting the connection name so that I'm not getting the IP:PORT in the RabbitMQ Management tool.

It would be useful to be able to identify the RabbitMQ client by its connection name.

Do you have any advice to give me up ?

**Comment by ramunasd** [comment]
At the moment it is possible by altering public static variable `AbstractConnection::$LIBRARY_PROPERTIES` and settings additional key `connection_name` with value `array('S', 'my connection name')`.
In the future this will be changed so do not expect to work it correctly.

**Comment by younessadmi** [comment]
Hi, thank you for the answer. I've made the following modification and it works like a charm so far.

```
public function __construct($hosts)
    {
        // add the connection_name
        $currentHost = gethostname();
        AMQPLazyConnection::$LIBRARY_PROPERTIES['connection_name'] = array('S', $currentHost);
        $this->connection = AMQPLazyConnection::create_connection($hosts);
        $this->channel = $this->connection->channel();
    }
```

**Comment by i3bepb** [comment]
Pull request with solution  #1035
