### ISSUE TITLE
Use v2.9~2.10, the CPU will 99% when waiting for new messages. v2.8 has no such problem.

### ISSUE THREAD

**Issue by imbin** [php-amqplib/php-amqplib#729]
**Version(s) affected**: 2.9.* ~ 2.10.*

**Description**  

When upgrade php-amqplib  to v2.9 or 2.10 , php artisan run a rabbitmq consumer, cpu 99%.

And v2.8 has no such problem.

![image](https://user-images.githubusercontent.com/2072389/63506777-ca8a9200-c508-11e9-824c-8a7ddbde6165.png)

**How to reproduce**  

Laravel 5.7

my composer.json, main fields:
```json
{
"require": {
        "php": "^7.1.3",
        "aws/aws-sdk-php-laravel": "~3.0",
        "bschmitt/laravel-amqp": "^2.0",
        "cache/filesystem-adapter": "^1.0",
        "codedge/laravel-fpdf": "^1.3",
        "cviebrock/laravel-elasticsearch": "^3.4",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "illuminate/redis": "^5.7",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "microsoft/bingads": "v0.12.0.3",
        "php-amqplib/php-amqplib": "^2.0",
        "phpoffice/phpspreadsheet": "^1.6",
        "phpseclib/phpseclib": "~1.0",
        "predis/predis": "^1.1",
        "tymon/jwt-auth": "1.*@rc"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    }
}
```
```shell
php artisan xxx_consumer
```

when open debug mode:
```php
define('AMQP_DEBUG', true);
```
run php artisan , can see always print:
```
waiting for any method
waiting for a new frame
waiting for any method
waiting for a new frame
waiting for any method
waiting for a new frame
```

**Possible Solution**  

**Additional context**

**Comment by lukebakken** [comment]
Please provide a source code archive or GitHub repository that I can clone, and provide _exact_ instructions on how to set up and run the code to see this issue.

We appreciate the report but we do not have the time to try and guess how to reproduce this issue. If you would like this fixed quickly, please provide something that is very easy for me to run.

More than likely this is due to how the `php-amqplib` library is being used.

Thank you.

**Comment by imbin** [comment]
Thank you for reply.
I has push a demo repository:
https://github.com/imbin/amqplib-demo

It is a simple laravel project, and i add a consumer demo. The CPU is still 99%.

**Comment by lukebakken** [comment]
Thank you. I will try to get to this within the next week or so.

**Comment by lukebakken** [comment]
Please see [this pull request](https://github.com/imbin/amqplib-demo/pull/1)

I don't know why it appears you have copied the Consumer code from `Bschmitt\Amqp` instead of using it directly, but that code has not been correctly updated for this library.

**Comment by imbin** [comment]
Great!!! 
Consumer code copied from Bschmitt\Amqp wants to reuse a single connection.
