### ISSUE TITLE
isConnected remains true while AMQPConnectionClosedException is thrown

### ISSUE THREAD

**Issue by kauanslr** [php-amqplib/php-amqplib#730]
**Version(s) affected**: 2.10.0

**Description**  
So, basically i have a worker that make some RPC calls to do the jobs.
I've bind the connection to application container and every time i call the connection from container it check `isConnected` and do the `reconnect`.

```laravel
public function getConnection()
{
    $connection = $this->app->make('CAmqp.connection');
    $connection->isConnected() ?: $connection->reconnect();
    return $connection;
}
```
after some time, the socket is closed (I don't know why) and if i call the `getConnection`
 and do anything it just throw a `AMQPConnectionClosedException`.

This behavior is correct to `isConnected` method?

**How to reproduce**  
1. Create a connection and stay it connected
2. Close the socket, i've used this step by step: https://superuser.com/a/668155
3. Using the connection at step 1 call the `isConnected` method, and it'll return `true`
4. Try to do anything using the broke connection.

**Comment by lukebakken** [comment]
Hello and thanks for using `php-amqplib`. Yes, this is a function of how TCP works and the method you use to close your socket. The only way to know a socket is closed is to try to do something with it. `isConnected()` just checks the _last known_ socket state.
