### ISSUE TITLE
Cannot create a durable queue

### ISSUE THREAD

**Issue by BlackZork** [php-amqplib/php-amqplib#731]
Hi,

I am using rabbitmq:3.7-management docker image and php-amaqplib 2.8.0.
I am unable to create durable queue. Code:

```
            $connection = new AMQPStreamConnection($this->rabbitHost, $this->rabbitPort, $this->rabbitUser, $this->rabbitPass);
            $channel = $connection->channel();
            $queue_name = 'myqueue';
            $channel->queue_declare($queue=$queue_name, $durable=TRUE, $autodelete=FALSE);
```
This returns errors:
```
Fatal error: Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException: NOT_FOUND - no queue 'myqueue' in vhost '/' in /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php on line 188

( ! ) PhpAmqpLib\Exception\AMQPProtocolChannelException: NOT_FOUND - no queue 'myqueue' in vhost '/' in /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php on line 188
```

When I set durable to FALSE then queue is created.
I can also send messages to durable queue created from web interface.

Any idea why I cannot create a durable queue?

**Comment by ramunasd** [comment]
Hello @BlackZork ,
looks like You came from python world where You can specify function arguments in any order. But this is not true in PHP world. Also, You don't need to do something like `$queue=$queue_name`, just pass variables in correct order and everything will be ok.

Here is demo https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher.php#L22
