### ISSUE TITLE
basic_publish and memory alarms

### ISSUE THREAD

**Issue by rbro** [php-amqplib/php-amqplib#743]
I hope you can help with this question.  I have more details below, but my question is: is there a way to have basic_publish be synchronous and return an error if a message wasn't delivered?  More details:

I ran into an issue where my RabbitMQ server hit a memory alarm.  When that happened, my php-fpm connections started building up and not closing which caused my php-fpm max_children to be reached.  I see there is a new option channel_rpc_timeout to close those connections so they don't hang.

Even with that option, I noticed that the basic_publish calls were not throwing any errors and my code was continuing as if all was working.

How can basic_publish be called so that it waits until the message is sent or an error occurs?

For example, I ran this to cause a memory alarm:
```
rabbitmqctl set_vm_memory_high_watermark 0
```

Then if I run the below script, it continues execution and hangs at the end unless I set the new option for channel_rpc_timeout, but even if I set that, I still don't know which calls worked and which didn't.

How can I tell if basic_publish is successful or not?  For example, what if the 1st call to basic_publish worked, but the last 3 didn't?  Can basic_publish be synchronous so that it returns a success/error and doesn't just continue executing code as if all was successful?

Thank you for your help.

```
<?php
require_once __DIR__.'/vendor/autoload.php';

$connection = new \PhpAmqpLib\Connection\AMQPStreamConnection('localhost', 5672, 'guest', 'guest', '/');

$channel = $connection->channel();

$channel->queue_declare('task_queue1', false, true, false, false);

$channel->basic_publish(new PhpAmqpLib\Message\AMQPMessage('Test Message'), '', 'task_queue1');
$channel->basic_publish(new PhpAmqpLib\Message\AMQPMessage('Test Message'), '', 'task_queue1');
$channel->basic_publish(new PhpAmqpLib\Message\AMQPMessage('Test Message'), '', 'task_queue1');
$channel->basic_publish(new PhpAmqpLib\Message\AMQPMessage('Test Message'), '', 'task_queue1');

echo 'Sent';
```

**Comment by ramunasd** [comment]
Please take a look at https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher_with_confirms.php
Basically You can `wait_for_pending_acks()` after each published message.

**Comment by rbro** [comment]
@ramunasd - thanks, I tried causing the memory alarm as I listed above, and ran amqp_publisher_with_confirms.php, but it seems to hang on the ```wait_for_pending_acks()``` line.  I also tried setting ```channel_rpc_timeout```, but it still hangs.  Is there a way to have the callback be called when the server has a memory alarm?

**Comment by ramunasd** [comment]
AMQP protocol does not define such things as "memory alarms". You must monitor Your services with dedicated software.
Take a look at function `wait_for_pending_acks($timeout = 0)`. You can set timeout which is by default 0 (infinity). Try to set several seconds and catch `AMQPTimeoutException`, which is clear sign that something is wrong with Your broker.

**Comment by rbro** [comment]
@ramunasd - thanks, I caught the AMQPTimeoutException, but my script still hangs on shutdown - example is below.  The exit line never exits.  Is this where I need to also use ```channel_rpc_timeout```?  Is there a way to cancel the pending messages after the AMQPTimeoutException is caught, so that my script exits immediately?

I tried clearing the memory alarm while in the channel_rpc_timeout period, and the message is still sent.  That is a little misleading as then a AMQPTimeoutException is thrown, which indicates the message wasn't sent, but the message is still sent.  Thanks again for your help.

```
try
{
	$channel->wait_for_pending_acks(3);
}
catch (\Exception $e)
{
	echo 'Error: '.$e->getMessage();

	exit; // this line hangs forever
}
```

**Comment by ramunasd** [comment]
Looks like You are doing something wrong in general.

Are You publishing very large messages? If yes, then You must use another storage and stop using rabbitmq for them, as it always keeps message bodies in memory.
Can Your consumers clear all queues in 3 seconds? If not, then You must increase pending ack timeout.
Have You tried lazy queues? It works very well for huge/heavy queues with slow consumers as only part of messages is kept in memory.

I cannot help You with something else, cause You are not providing code, configuration examples, stack traces, nor rabbit logs.

**Comment by ramunasd** [comment]
I see there is another approach. This library supports blocked connection notifications[1].
You can define callbacks whenever broker stops accepting new messages `set_connection_block_handler()` and clears out `set_connection_unblock_handler()`. However, it's up to You how blocking delay will be implemented on publisher side. It can be simple `wait()` loop until `connection.unblocked` callback.

[1] https://www.rabbitmq.com/connection-blocked.html

**Comment by rbro** [comment]
Thanks, I'm still running into the same problem using set_connection_block_handler().  I found a possible workaround, but it's not really straightforward.

I am not looking for help for avoiding a memory alarm or how to set-up my RabbitMQ server or queues.

What I am asking for help with is if my RabbitMQ server has a memory alarm, and at the same time my PHP script using php-amqplib tries to queue a message, how can my PHP script know if that message was queued or not, and if there is a memory alarm, how can my PHP script cancel sending that message to the server.

I am running on CentOS 7, and I installed the rabbitmq-server RPM provided on https://www.rabbitmq.com.  I am using the default configuration provided by the RPM.  I did not edit any RabbitMQ config files.

From my tests and your help from above, I can catch the AMQPTimeoutException when this happens, but even though the AMQPTimeoutException was thrown, the message still seems to be waiting for the server to come back, so if the memory alarm clears during that time, the message is still sent even though there was an AMQPTimeoutException thrown.  This creates an issue for me since from my PHP script, I have no way to know if the message was sent.

I am looking for a way to completely cancel the message after the AMQPTimeoutException is thrown.

The workaround I found is to close the connection with the server as soon as the AMQPTimeoutException is thrown.  It doesn't seem like the right solution, but it seems to fix it.

To reproduce the issue:
- run this to cause a memory alarm:
```rabbitmqctl set_vm_memory_high_watermark 0```
- run below script.  In 5 seconds, the text "wait_for_pending_acks timeout" will appear on the screen, but the script will not exit for another 20 seconds (channel_rpc_timeout * 2).
- during those 20 seconds, if you run this to clear the memory alarm:
```rabbitmqctl set_vm_memory_high_watermark 0.4```
- the message will be sent to the server even though the AMQPTimeoutException was thrown, and the PHP script already exited.

For the workaround:
- uncomment this line in the script:
```$connection->custom_close();```
- and run this again to cause a memory alarm:
```rabbitmqctl set_vm_memory_high_watermark 0```
- and then run the script.  The text "wait_for_pending_acks timeout" will appear on the screen in 5 seconds, and the script will immediately exit.  The message is not sent to the server.

Closing the server connection directly was the only way I found to completely cancel the message and prevent php-amqplib from trying to send it.

Is there another way the message can be cancelled when the AMQPTimeoutException is thrown?

Thanks again for your help.

```
<?php
require_once __DIR__.'/vendor/autoload.php';

use \PhpAmqpLib\Connection\AMQPStreamConnection;
use \PhpAmqpLib\Message\AMQPMessage;
use \PhpAmqpLib\Exception\AMQPTimeoutException;

class rabbitmq extends AMQPStreamConnection
{
	public function custom_close()
	{
		$this->close_input();
		$this->close_socket();
	}
}

$connection = new rabbitmq('localhost', 5672, 'guest', 'guest', '/', false, 'AMQPLAIN', null, 'en_US', 10, 10, null, false, 0, 10, null);

$channel = $connection->channel();

$channel->queue_declare('task_queue1', false, true, false, false);

$channel->confirm_select();

$channel->basic_publish(new AMQPMessage('Test Message'), '', 'task_queue1');

try
{
	$channel->wait_for_pending_acks(5);
}
catch (AMQPTimeoutException $e)
{
	echo "wait_for_pending_acks timeout\n";

	//$connection->custom_close();

	echo "message not sent\n";
	exit;
}

echo "message sent\n";
exit;
```

**Comment by ramunasd** [comment]
> run below script. In 5 seconds, the text "wait_for_pending_acks timeout" will appear on the screen, but the script will not exit for another 20 seconds (channel_rpc_timeout * 2).

That's because library is trying to close connection properly by sending special packets. You can disable that by calling `$connection->set_close_on_destruct(false);`.

In general we cannot detect what is exactly wrong with broker if it is not responding. Even if You get timeout on read operation does not mean that connection is broken and You won't get response in next couple seconds. This behaviour is acceptable for long running workers but not good for short web request, indeed.
