### ISSUE TITLE
shell_exec(): Unable to execute ''

### ISSUE THREAD

**Issue by NGY198888** [php-amqplib/php-amqplib#756]
**Version(s) affected**:2.10

**Description**  

 $message = new AMQPMessage($messageBody, array('content_type' => 'text/plain', 'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT));
  $this->channel->basic_publish($message,``,$this->queue);

Sometimes, there will be a bug in the method basic_publish, prompting shell exec(): unable to execute ''. I don't know why. Please give me some advice

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by ramunasd** [comment]
Read the PHP docs `backtick operator`. Please use simple quotes unless You want execute some shell code.

**Comment by NGY198888** [comment]
> Read the PHP docs `backtick operator`. Please use simple quotes unless You want execute some shell code.

Oh, I didn't notice the problem caused by symbols. Thank you very much for your answer!
