### ISSUE TITLE
Heartbeat do not working if loses connection

### ISSUE THREAD

**Issue by sergeyquancy** [php-amqplib/php-amqplib#762]
**Version(s) affected**: 2.11.0

**Description**  

We have unstable consumers under phpamqplib.

**How to reproduce**  

1) Rise consumer with heartbeat=60
2) Disconnect internet connection.
3) Waiting for 120 sec. 
4) RabbitMQ 3.8.0 close consumer, but phpamqplib consumer still working and do not recover connection.

**Possible Solution**  

phpamqplib MUST monitoring heartbeat.

**Additional context**  

We try to use amqptools (console) and python piko - these libs working good.

**Comment by ramunasd** [comment]
@sergeyquancy can you please provide consumer example?

**Comment by sergeyquancy** [comment]
```#!/usr/bin/php
<?php

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/config.php';

use PhpAmqpLib\Connection\AMQPStreamConnection;

$connection = new AMQPStreamConnection(RMQ_HOST, RMQ_PORT, RMQ_USER, RMQ_PASS, RMQ_VHOST, false, 'AMQPLAIN', null, 'en_US', 3.0, 3.0, null, true, 60);
$channel = $connection->channel();
$channel->confirm_select();
$channel->queue_declare(RMQ_QUEUE, false, true, false, false);

echo ' [*] Waiting for messages. To exit press CTRL+C', "\n";

$callback = function($msg) {
    echo " [x] Received ", $msg->body, "\n";

    // TODO

};

$channel->basic_consume(RMQ_QUEUE, '', false, true, false, false, $callback);

print date('c') . ' ' . 'Selected random timeout: ' . $timeout . PHP_EOL;

try {
    while (count($channel->callbacks))
        $channel->wait(null, false, 86400 );
} catch(Exception $e) {
    print date('c') . ' reboot by timeout.' . PHP_EOL;
}

$channel->close();
$connection->close();
```

**Comment by ramunasd** [comment]
Please use lower wait timeout and everything will be ok. There is no way at the moment to check heartbeat while consumer is blocked mode.
