### ISSUE TITLE
Incorrect documentation for AMQPMessage constructor (and others)

### ISSUE THREAD

**Issue by passcod** [php-amqplib/php-amqplib#769]
**Version(s) affected**: 2.11.0

The documentation here: https://php-amqplib.github.io/php-amqplib/classes/PhpAmqpLib.Message.AMQPMessage.html shows the constructor's signature as:

```php
__construct(array $properties, array $propertyTypes = null)
```

while the code (and examples at RabbitMQ) show instead:

```php
__construct($body = '', $properties = array())
```

This is extremely confusing, and I wonder if the class reference documentation is at all accurate / can be relied on. At a glance, it looks like most constructors for other classes are also incorrect.

**Comment by lukebakken** [comment]
This is the source for `AMQPMessage`'s constructor: [link](https://github.com/php-amqplib/php-amqplib/blob/d05ed93d7dd76e946430f8a2269ed3a4876acbca/PhpAmqpLib/Message/AMQPMessage.php#L44-L52).

I just re-built the docs and pushed the `gh-pages` branch. I'm not sure why the HTML documentation doesn't match what is in the source code. If you click on the documentation for `__construct`, you can see this error:

```
Warning: count(): Parameter must be an array or an object that implements Countable in phar:///home/lbakken/development/php-amqplib/php-amqplib/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1293 Warning: count(): Parameter must be an array or an object that implements Countable in phar:///home/lbakken/development/php-amqplib/php-amqplib/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1293
```

I suspect the documentation is not being built correctly by `phpDocumentor`. @ramunasd ... any ideas?

@passcod this is open source software. Patches or other assistance to resolve this would be greatly appreciated.

**Comment by ramunasd** [comment]
This is related to template issue - https://github.com/phpDocumentor/phpDocumentor/issues/1496
It is possible to switch to another similar and error free `clean` template. Is that ok?

**Comment by lukebakken** [comment]
Please, switch away!
