### ISSUE TITLE
support pseudo-simultaneous channel processing

### ISSUE THREAD

**Issue by wyrfel** [php-amqplib/php-amqplib#77]
The library is currently unable to simultaneously process messages for different channels on the same connection. E.g. say you want a worker that listens on a job message queue (consumer1) as well as a management queue (to receive messages that trigger it to reconfigure itself, shutdown, etc.) (consumer2) and you want to have each consumer use their own channel.

Such a setup is currently impossible due to the nature of AbstractConnection::wait_channel().

Ironically, it seems this can be easily mitigated by modifying that method to always call wait() on any messages for other channels:

``` php
    protected function wait_channel($channel_id, $timeout = 0)
    {
        while (true) {
            list($frame_type, $frame_channel, $payload) = $this->wait_frame($timeout);
            if ($frame_channel == $channel_id) {
                return array($frame_type, $payload);
            }

            // we introduce a check if the channel still exists since we now have
            // potential for other code to interfere
            if (isset($this->channels[$frame_channel])) {
              // Not the channel we were looking for.  Queue this frame
              //for later, when the other channel is looking for frames.
              array_push($this->channels[$frame_channel]->frame_queue,
                         array($frame_type, $payload));

              // Always invoke a 'sub-wait()' causing the according channel to process
              // the just queued frame and call us again
              $this->channels[$frame_channel]->wait();
            }
        }
    }
```

This potentially results in a somewhat ugly call chain, but should be safe due to the frame- and method queueing mechanisms in AbstractChannel.

Of course in a larger refactoring effort this could be done a lot cleaner, but this solution should work without modifying AbstractChannel and hence doesn't require people to change their code.

**Comment by lukebakken** [comment]
See #121. This may be implemented at some point in the future if the need arises, or a pull request is submitted.
