### ISSUE TITLE
Socket connection failed on server and it's working on localhost

### ISSUE THREAD

**Issue by seemagebandnut** [php-amqplib/php-amqplib#770]
**Version(s) affected**: x.y.z

**Description**  

**How to reproduce**  

<html>
    <head>
		
        <title>ZK Test</title>
    </head>
    
    <body>
<?php
   echo phpinfo();

    include("zklib/zklib.php");
    
    $zk = new ZKLib("192.168.1.201",4370);
   
    $ret = $zk->connect();
	if ($ret === false) {
    $errorcode = socket_last_error();
    $errormsg = socket_strerror($errorcode);
    
    die("Couldn't create socket: [$errorcode] $errormsg");
}

	
    sleep(1);
    if ( $ret ): 
        $zk->disableDevice();
        sleep(1);
		
    ?>
        
   
        
        <table border="1" cellpadding="5" cellspacing="2">
            <tr>
                <th colspan="6">Data Attendance</th>
            </tr>
            <tr>
                <th>Index</th>
                <th>UID</th>
                <th>ID</th>
                <th>Status</th>
                <th>Date</th>
                <th>Time</th>
            </tr>
            <?php
            $attendance = $zk->getAttendance();
            sleep(1);
            while(list($idx, $attendancedata) = each($attendance)):
                if ( $attendancedata[2] == 14 )
                    $status = 'Check Out';
                else
                    $status = 'Check In';
            ?>
            <tr>
                <td><?php echo $idx ?></td>
                <td><?php echo $attendancedata[0] ?></td>
                <td><?php echo $attendancedata[1] ?></td>
                <td><?php echo $status ?></td>
                <td><?php echo date( "d-m-Y", strtotime( $attendancedata[3] ) ) ?></td>
                <td><?php echo date( "H:i:s", strtotime( $attendancedata[3] ) ) ?></td>
            </tr>
            <?php
            endwhile
            ?>
        </table>
        

    <?php

        sleep(1);
        $zk->disconnect();
    endif
?>
    </body>
</html>

**Possible Solution**  

**Additional context**

**Comment by ramunasd** [comment]
If it's working in your local env, then very likely it's configuration problem. Cannot tell more from your example.

**Comment by seemagebandnut** [comment]
Can u tell me what configuration is required because i m not getting this what more steps need to do on server in settings. because i didnt do anything on local  php settings.

**Comment by lukebakken** [comment]
> Can u tell me what configuration is required

We can't because we don't know _anything_ about your environment. If you're using RabbitMQ, please see [the documentation](https://rabbitmq.com)

**Comment by seemagebandnut** [comment]
I am using AWS cloud with ubuntu OS platform and you can see PHP info configuration here http://3.133.73.57/socket/dnaextrim-php_zklib-8b46116/zktest.php
