### ISSUE TITLE
Publisher confirms

### ISSUE THREAD

**Issue by somnaderi** [php-amqplib/php-amqplib#774]
Apologies if there's documentation on this and I haven't found it. And maybe this is a basic problem that requires basic PHP knowledge that I'm just being obtuse about.

But I can't seem to figure out how publisher confirms are supposed to work with this library. I've looked at the demo code, but it only appears to cover a simple case of being able to print messages in response to ack/nacks. Without some sort of context passed into the callback (or global variables), I don't seem to be able to do things like curating/clearing my list of messages awaiting acks. I also can't really do anything to trigger initiating a redelivery should the publishing return a nack.

The tutorial on the RabbitMQ site only has a couple language examples and PHP isn't one of them. Maybe publish confirms aren't really supported with this library beyond the basic use case...? (which is fine, of course, since I get that the library is maintained by volunteers... would just like to know)

Would really appreciate it if someone could point me in the right direction.

**Comment by ramunasd** [comment]
Callable can be several things, like public methods from your handler class, which obviously has its own context, take a look at https://www.php.net/manual/en/language.types.callable.php
Also You can use anonymous function with inherited variables like here https://www.php.net/manual/en/functions.anonymous.php#example-167

Anyways, this is not library related issue.

**Comment by somnaderi** [comment]
Ah -- thank you. Wasn't aware of PHP's use/inherited variables. Makes a lot more sense this way.
