### ISSUE TITLE
AMQPStreamConnection gives error "The connection timed out after 3 sec while awaiting incoming data" sometimes

### ISSUE THREAD

**Issue by francis-li** [php-amqplib/php-amqplib#780]
We are using v2.11.

When instantiating AMQPStreamConnection, we frequently encounter the following error: "The connection timed out after 3 sec while awaiting incoming data". When we use AMQPConnection, this error no longer appears. To be clear, we were able to acquire connections SOME of the time using AMQPStreamConnection. But it also frequently gives us the aforementioned error. Using AMQPConnection, the error never appears.

Looking at the code, we noticed that AMQPConnection simply extends AMQPStreamConnection. As such we're a little confused as to why we are seeing this difference. Any insight would be appreciated.

**Comment by ramunasd** [comment]
`AMQPConnection` is completely same as `AMQPStreamConnection`, it means problem is in environment. Without knowing anything about your stack and configuration we can't tell what is wrong. Please see https://raw.githubusercontent.com/php-amqplib/php-amqplib/master/.github/ISSUE_TEMPLATE/1_Bug_report.md and resubmit issue with more info on this.
