### ISSUE TITLE
minor release has return type BC breaks

### ISSUE THREAD

**Issue by sudevva** [php-amqplib/php-amqplib#781]
**Version(s) affected**: 2.11.0 and greater

**Description**  
changes in https://github.com/php-amqplib/php-amqplib/commit/1252cfbab6342dd36f5c5f1af70b6085bfcf60f8 has bc breaks as type system does not allow to return int when return type is string.
Also it is bad practice to return multiple types in one method such as string|int
for example read_longlong method of AMQPReader class

**How to reproduce**  
For example write a simple function 
```
    function getDeliveryTag(\PhpAmqpLib\Message\AMQPMessage $amqpMessage): ?string
    {
        return $amqpMessage->delivery_info['delivery_tag'];
    }
```
And we got:  "Return value of getDeliveryTag() must be of the type string or null, int returned"

**Possible Solution**
Such changes must be made in major release or preserve types as it was before.

**Comment by ramunasd** [comment]
Delivery tag is integer, always.

**Comment by sudevva** [comment]
It was always a string for a while, before that commit
![image](https://user-images.githubusercontent.com/10704835/74738531-ca711200-525f-11ea-9c99-9f92b73b6fb4.png)

**Comment by sudevva** [comment]
Please reopen this issue

**Comment by lukebakken** [comment]
@sudevva - we would be happy to review a pull request with a fix for this issue (including tests). Right now we're considering the previous behavior to be a bug.
