### ISSUE TITLE
consumer can't recieve any message after 2 hours idle without exception

### ISSUE THREAD

**Issue by ellenus** [php-amqplib/php-amqplib#786]
**environment:**
- centos7
- php 7.2
- rabbitmq 3..8.3
- php-amqplib 2.11.1

I have a long running consumer, when it keep recieving message everything is fine. 
but when it complete all messages and idle more than two hours, it won't get any message anymore.
nothing show in server error,
no exceptions,
the process is alive,
connection and channel status is active (see from web console)

hungting for this silent problem for 2+days.
until I downgrade to v2.9 everything work smoothly.

is it a issue cause by heartbeat timeout?

code:
```php
$connection = new AMQPStreamConnection(RMQ_HOST, RMQ_PORT, RMQ_USER, RMQ_PASS);
$channel = $connection->channel();
$channel->queue_declare('queue_name', false, true, false, false);
$channel->basic_qos(null, 1, null);

$callback = function ($msg){
	$logger->info($msg->body);

    $msg->delivery_info['channel']->basic_ack($msg->delivery_info['delivery_tag']);
};

$channel->basic_consume('queue_name', '', false, false, false, false, $callback);

while (count($channel->callbacks)) {
	try {
		$channel->wait();

    } catch (Exception $e) {
		$logger->error((string) $e);

		exit;
    }
}
```

**Edit**
upload my rabbitmq log (barely nothing though...)
some short time connection is my producers
[rabbitmqlog.zip](https://github.com/php-amqplib/php-amqplib/files/4441959/rabbitmqlog.zip)

**Comment by lukebakken** [comment]
Please compress and attach your RabbitMQ log file from the same time period. Thank you.

**Comment by ramunasd** [comment]
@ellenus by default `$channel->wait();` does not have set any timeouts and will wait indefinitely until next network frame. After some time(30 seconds in your case) broker will close connection due to missing activity - no message nor heartbeats.

All You need is slightly change the loop, something like that:
```
while ($channel->is_consuming()) {
    try {
        $channel->wait(null, false, 10);
    } catch (AMQPTimeoutException $e) {
        $connection->checkHeartBeat();
        continue;
    } catch (Exception $e) {
        $logger->error((string) $e);
        exit;
    }
}
```

Here you either keep connection alive using heartbeats or get exception if connection gets closed.

**Comment by ellenus** [comment]
@ramunasd 
try your solution but really didn't help. :(
consumer hang still.

I thought the message might be sent.(because the Unacked number is correct)  just my callback function not been triggered?

any idea?

![2020-04-09_16-29-25](https://user-images.githubusercontent.com/5111667/78875439-783eb700-7a80-11ea-8583-ffe879e9f3a5.jpg)

**Comment by ramunasd** [comment]
@ellenus callback function cannot be not triggered, that whould be serious bug and everyone would face it. Here it looks like some weird network problems.
Can you enable debug mode and submit it here? Just add `define('AMQP_DEBUG', true);` to your script.

**Comment by ellenus** [comment]
@ramunasd 
I add `define('AMQP_DEBUG', true);`
and just see bunch of 'waiting for a new frame'
this log keep show even after my consumer is hang.

[error_20200410.log](https://github.com/php-amqplib/php-amqplib/files/4459811/error_20200410.log)
'

**Comment by ellenus** [comment]
sorry, does anyone try my scenario. cause I can reproduce it 100% time.
and this issue doesn't exist when I am under version 2.9
it's hard to believe it's only my "network problem".

**Comment by ramunasd** [comment]
It is clearly visible from your log that consumer did everything fine. Can you try other environment, vagrant, docker or anything else we could use to reproduce this issue?
Also, your log does not match provided example :|

**Comment by ellenus** [comment]
finally find the problem.
turn out the stream connection got closed by system
[similar situation on pika](https://github.com/zulip/zulip/pull/12711)

shorten the tcp keepalive timeout and turn on the keepalive parameter can solve this. 
`new AMQPStreamConnection(RMQ_HOST, RMQ_PORT, RMQ_USER, RMQ_PASS, .... , $keepalive = true);`

@ramunasd 's suggestion can also effect, if you set heartbeat > 0.
