### ISSUE TITLE
why php-amqplib not support persistent connection？

### ISSUE THREAD

**Issue by ym2048** [php-amqplib/php-amqplib#788]
Persistent connection will save the cost of establish connection，why doesn‘t php-amqplib use persistent connection?

**Comment by ramunasd** [comment]
Thank You for the question. The reason is that unlike the http or in general rest endpoints, AMQP connection is statefull. It means, that each connection has it's own not sharable parameters and context.

**Comment by ym2048** [comment]
@ramunasd
