### ISSUE TITLE
Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPConnectionClosedException' with message 'FRAME_ERROR - type 2, first 16 octets

### ISSUE THREAD

**Issue by Stehos** [php-amqplib/php-amqplib#789]
Hi Guys, I am trying to use this library in one of the old projects where we use PHP Version 5.5.9-1ubuntu4.14 but I receive the following error:

Warning: pack(): Type J: unknown format code in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 215

Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPConnectionClosedException' with message 'FRAME_ERROR - type 2, first 16 octets = <<0,60,0,0,22,0,2,46,55,50,102,48,97,56,97,97>>: {invalid_frame_end_marker, 91}(0, 0)' in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:745 Stack trace: #0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader)) #1 /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(216): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader)) #2 /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '???FRAME_ERROR ...', NULL) #3 /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(666): PhpAmqpLib\Channel\Ab in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 745

Already tested in the docker container with PHP Version 7.2.2 and everything looks good.

Please do you have any ideas what can be done for easy fix?

Thanks for your advice.

**Comment by lukebakken** [comment]
Thanks for using this library. This is the error:

`Warning: pack(): Type J: unknown format code`

PHP version 5.5.9 is not supported. 5.6.3 is the minimum version.

**Comment by Stehos** [comment]
@lukebakken Thank you for your fast reply. Do you think that this warning causes the fatal error? Thank you.
