### ISSUE TITLE
Rabbit goes to infinite wait in OpenVPN

### ISSUE THREAD

**Issue by srebbsrebb** [php-amqplib/php-amqplib#790]
**Version(s) affected**: ^2.9.0

**Description**  
RabbitMQ consumer doesn't detect a broken OpenVPN connection

**How to reproduce**  
1. Install the rabbit broker and an OpenVpn server on server A
2. Connect Server B via OpenVPN to server A
3. Setup a consumer on server B and point to the broker on A via VPN
4. Start the consumer
5. Stop the VPN server on A
=> the consumer won't detect the broken connection

**Possible Solution**  
Not a real solution but the exact lines where the issue comes from.

Commit: 242db8072cb46f3da79e76300140a6e152d04d37
Check PhpAmqpLib/Wire/AMQPReader.php:129
$sec is set to null there to wait indefinitely. Seems to be done by intention. Anyway, exactly this breaks it in PhpAmqpLib/Wire/IO/SocketIO.php:239 when using OpenVPN. If OpenVPN comes back up too late, the connection won't work anymore and is stuck in the infinite wait.

Producers also don't detect the broken VpnConnection anymore. They were working at least in v2.8.0

**Comment by ramunasd** [comment]
Thanks @srebbsrebb , so does rabbit(?) or client falls into infinite wait?
I assume this is expected behaviour for blocking connections without timeout 🤷 
Can You try exactly same consumer with timeout? AMQPTimeoutException isn't bad outcome, just catch it and repeat.

**Comment by srebbsrebb** [comment]
Hey @ramunasd , the client (php-amqplib) goes to infinite wait.
I have a timeout configured, which is 4 seconds.
The seems to be:
There are several methods trying to do a polling with by using the default timeout 0 instead of the configured timeout (4). In v2.8.0 this worked, cause the 0 caused an instant return which showed no changes in the socket / stream.
=> php-amqplib was able to detect the missing heartbeat.

Now the 0 timeout causes an infinite wait. Instant polling is not working anymore but still used in a lot of places.

**Comment by ramunasd** [comment]
@srebbsrebb 0 means no timeout, for polling please use `null` or 2nd parameter should be `true`.

**Comment by srebbsrebb** [comment]
Thank you very much for your effort @ramunasd 
Unfortunately the problem still exists, even if your answer is correct.
The timeout is configured to a value bigger than 0.

I am using the php-amqplibs in combination with the rabbitmq-bundle for symfony.
Independent of the configured timeout, rabbitmq-bundle does a wait on the Channel with timeout 0. In the past php-amqplibs returned null from inside the wait in that case. Now it waits infinite.

Even if the channel->wait() would be called with a timeout bigger than 0, rabbitmq-bundle would restart the consumer, cause the AMQPTimeoutException thrown in the wait is not catched.

If it is called with null as timeout, there is an infinite polling which burns the cpu.

For me it looks like the rabbitmq-bundle is not fully compatible with phpamqplibs ^2.9.0
With phpamqplibs ^2.8.0 the heartbeat detects the broken vpn correctly. So I downgrade for now.

Any further ideas are welcome.

**Comment by ramunasd** [comment]
I would recommend to You switch from old and unsupported RabbitMqBundle to php-enqueue. Unfortunally we don't have access to first library, thus no one from old company can help.
