### ISSUE TITLE
Heartbeat Frame waits indefinitely when firewall is reset on the application server and fails to throw the Missed heartbeat exception.

### ISSUE THREAD

**Issue by bharathmurthy** [php-amqplib/php-amqplib#792]
**Version(s) affected**: 2.11.0

**Description**  
We have RabbitMQ server setup on one server and consumers are run in different application server. We have enabled the heartbeat on the client by doing this and when calling the **wait** method no timeout is set.
`                
$this->amqp_connection = new AMQPConnection(AMQP_HOST, AMQP_PORT, AMQP_USER, AMQP_PASS, AMQP_VHOST, false, 'AMQPLAIN', null, 'en_US', 600, 600, null, false, 300);
`
`
$channel = $this->amqp_connection->channel();
`
`
$channel->basic_consume($this->queue, $this->consumer_tag, false, false, false, false, array($this, 'processMessage'));
`
`
while (count($channel->callbacks)) {
    $channel->wait(null, false);
}
`
and then at some point in time when we are required to do some firewall changes and the firewall is reset from the amqplib debug logs we can see the consumer is stuck in a state indefinitely waiting for the heartbeat frame to come back from the server. But it'll never receive it as all the TCP connections were flushed/reset during the firewall reset.
 
**How to reproduce**  
1. Start a consumer with heartbeat enabled.
2. Once the consumer is started and starts receiving the heartbeat reset the firewall in the app server where the consumers are running.
3. You should be experiencing that no Missed heartbeat exception is thrown by the library.

**Possible Solution**  
After trying to debug the code found this part is where its sitting and waiting for the heartbeat frame forever.
https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/AMQPReader.php#L133

**Additional context**  
Please let me know if you need anything else and will try to provide it ASAP. If you can fix this issue that'll greatly help us to detect dead tcp connections and reconnect to server automatically hence avoiding any outages!
Thanks in advance.

Cheers,
Kumar

**Comment by lukebakken** [comment]
Please re-try with version `2.11.2`, the latest. Thank you.

**Comment by bharathmurthy** [comment]
Hi @lukebakken , Thanks for the response. I tried with 2.11.2 and still same behavior. Can you please suggest what else can I try ? 
Also the current workaround I now have is instead of setting the $sec=null in here [https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/AMQPReader.php#L133](url) I have hardcoded it to same as the connection timeout which is 600s. This results in me getting a Missed server heartbeat exception thrown in about 10mins when the firewall is reset. Please suggest what will the side effects of me setting the $sec to 600s (10mins). 
Thanks.

**Comment by ramunasd** [comment]
@bharathmurthy it's a common mistake to use timeout=0. Please set 3rd parameter for method `wait()` and it will change `select()` timeout. As a consequence you will get AMQPTimeoutException or AMQPHeartbeatMissedException after some time.
You can follow example:
https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_message_headers_recv.php#L46
Just adjust timeout value to your needs - how fast you want to detect broken connection.

**Comment by bharathmurthy** [comment]
@ramunasd Thanks for the response. I tried out your suggestion and it works like a charm!! Thanks a lot for the suggestion. Have a great week!

Cheers,
Kumar
