### ISSUE TITLE
use rabbitmq with plugin rabbitmq_delayed_message_exchange issue

### ISSUE THREAD

**Issue by BigmasterU** [php-amqplib/php-amqplib#795]
if I want to delay_message,how to pass params?some codes like this:
                $channel->exchange_declare($this->exchange,
                        'x-delayed-message',
                        false,
                        false,
                        false,
                        false,
                        false,
                        ['x-delayed-type'=>['s','topic']]
                    );
                    $msg = new AMQPMessage($message,['headers'=>['x-delay'=> 1000]]);
is this ok?
but some exception happened

**Comment by ramunasd** [comment]
Please check example at https://github.com/php-amqplib/php-amqplib/blob/master/demo/delayed_message.php
