### ISSUE TITLE
Persistent connections

### ISSUE THREAD

**Issue by galmok** [php-amqplib/php-amqplib#797]
**Description**  
PHP supports a feature called persistent connections, which are TCP connections that survive from one invocation of the script to the next, if certain conditions are met. Using this with php-amqplib would be great as it could allow the AMQPConnection to be reused.

It would require the library to use pfsockopen and its related send/receive method (fread, fwrite, feof). This might not be a problem.

**Example**  
The usage of thise library would need a option on AMQPConnection to specify if a persistent connection is to be used or not. The remaining use would be as today, except there would be no large delay opening the AMQPConnection (50ms on my development machine, i.e. very slow).

**Comment by ramunasd** [comment]
AMQP connection is stateful. It means that each connection has it's own context - enabled features, negotiated timeouts and etc. Main reason why it takes so long to connect is several TCP rountrips, persistent connection does not solve this problem at all.
Please look at https://github.com/cloudamqp/amqproxy as potential solution to this problem.
