### ISSUE TITLE
TLS connection example needed in readme

### ISSUE THREAD

**Issue by diphuaji** [php-amqplib/php-amqplib#801]
In the readme there is nowhere to see how to set up a secure connection.

There needs to be a section on how to do that.

**Comment by lukebakken** [comment]
Thanks for using `php-amqplib`.

I did the following internet search - https://www.google.com/search?q=php-amqplib+TLS

These are from the top hits:

https://github.com/cloudamqp/php-amqplib-ssl-example

https://github.com/cloudamqp/php-amqplib-ssl-example

https://lornajane.net/posts/2016/connect-to-rabbitmq-from-php-over-amqps

We would gladly review and accept a pull request that takes information from the internet and updates the README in this project. Thanks!

**Comment by lukebakken** [comment]
@diphuaji if you'd like, take this PR and turn it into an example -

https://github.com/php-amqplib/php-amqplib/pull/777

Please be sure to follow the comments left by @ramunasd

**Comment by diphuaji** [comment]
@lukebakken yeah I can do that.

**Comment by ramunasd** [comment]
You can find working demo here https://github.com/php-amqplib/php-amqplib/blob/master/demo/ssl_connection.php
Please let me know if something is missing.
