### ISSUE TITLE
NullClasses for testing

### ISSUE THREAD

**Issue by D4rkMindz** [php-amqplib/php-amqplib#802]
**Description**  
I'm using php-amqplib for quite some time and now my PM wants me to create some tests.
We're using a cloud AMQP solution. So there is no option to use this Rabbit MQ instance for testing purposes.
So is there any option to replace the AMQPStreamConnection with e.g. a NullAMQPConnection?
I tried to create those classes within my project, but the setup is too complicated (too many Classes that are dependent on each other).

This "Problem" might be solved by creating some Interfaces (like a ConnectionInterface which is then implemented by The AMQPStreamConnection).

**Example**  
I'll create a PR, just give me some time.

**Comment by lukebakken** [comment]
In general, you should be testing with RabbitMQ in place (integration tests) when your code interacts with this library. If you need to have messaging in your unit tests, you should have your own abstraction layer. I don't believe that to be the responsibility of this library and I'm hesitant to take on more code to maintain.

It is _extremely_ simple to run RabbitMQ as part of your integration tests - much easier than having a database in place, for instance.

@ramunasd what do you think?

**Comment by ramunasd** [comment]
@D4rkMindz
Well, this does not look like real problem. Have You ever heard about mocking frameworks?

> This "Problem" might be solved by creating some Interfaces

Why You are not proposing solution which could fully solve the "problem"? The reasoning "might" sounds a little be weird :|
