### ISSUE TITLE
when I want to use publish_batch in confirm

### ISSUE THREAD

**Issue by easytoeasy** [php-amqplib/php-amqplib#806]
**Description**  

Hello Daniel, I have encapsulated my own batch sending method based on **publish_batch** and enabled the sender confirmation mechanism. But when I sent several batches of data to possibly different queues before AMQP was closed, I would report an error, such as 'Server ack' Ed unknown delivery_tag ', but I only had to change one of the **confirm_select** of AMQPChannel to not report an error. Such as code:
``` PHP
If ($this - > next_delivery_tag = = 0)
     $this - > next_delivery_tag = 1;
```
I know that because I wanted to **confirm_select** to count **next_delivery_tag** from 1 each time I sent a batch message, but at present, this variable **next_delivery_tag** will keep increasing until the end of sending, which caused my mistake. Is there any danger if I change the way I write it? I really hope you can take time out of your busy schedule to catch a glimpse of my problem. Thank you very much!

**Example**  

      for ($i=1; $i<=100; $i++) {
            $jobs[] = new CountJob([
                'count' => $i
            ]);
            
            if ($i % 10 == 0) {
                Yii::$app->easyQueue->publish($jobs); //publish_batch and confirm_select 
                $jobs = [];
            }
        }

**Comment by easytoeasy** [comment]
”Daniel“ in this I means ”大牛“，In China it means very very smart。

**Comment by ramunasd** [comment]
This does look like wrong library usage rather than bug.
Please submit code example of how to reproduce bug or functional test.

**Comment by easytoeasy** [comment]
I tried to write a demo under the php-amqplib/php-amqplib/demo , the code is as follows:
```php
<?php

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

include(__DIR__ . '/config.php');

$t = new Test();

$msgs = [];
for ($i = 1; $i <= 100; $i++) {
    $msgs[] = $i;
    if ($i % 10 == 0) {
        $t->publish($msgs);
        $msgs = [];
    }
}

class Test
{
    private $connection;
    /** @var \PhpAmqpLib\Channel\AMQPChannel */
    private $channel;

    private $queueName1 = 'queue1';
    private $queueName2 = 'queue2';
    private $exchangeName = 'exchange';
    private $routingKey1 = 'routing1';
    private $routingKey2 = 'routing2';

    public function __construct()
    {
        $this->open();
        $this->bind();
    }

    public function bind()
    {
        $this->channel->queue_declare($this->queueName1);
        $this->channel->queue_declare($this->queueName2);
        $this->channel->exchange_declare($this->exchangeName, 'direct');

        $this->channel->queue_bind($this->queueName1, $this->exchangeName, $this->routingKey1);
        $this->channel->queue_bind($this->queueName2, $this->exchangeName, $this->routingKey2);
    }

    public function publish($messages)
    {
        foreach ($messages as $msg) {
            $msg = new AMQPMessage($msg);
            $routingKey = 'routing' . mt_rand(1, 2);
            $this->channel->batch_basic_publish($msg, $this->exchangeName, $routingKey);
        }
        $this->publishBatch();
    }

    public function publishBatch()
    {
        $this->channel->set_ack_handler(function (AMQPMessage $payload) {
            echo 'ack:' . $payload->getBody() . PHP_EOL;
        });

        $this->channel->set_nack_handler(function ($payload) {
            echo 'nack:' . $payload->getBody() . PHP_EOL;
        });

        $this->channel->confirm_select();
        $this->channel->publish_batch();
        $this->channel->wait_for_pending_acks();
    }

    public function open()
    {
        $this->connection = new AMQPStreamConnection(HOST, PORT, USER, PASS, VHOST);
        $this->channel = $this->connection->channel();
    }

    public function close()
    {
        if (!$this->channel) return;
        $this->channel->close();
        $this->connection->close();
    }

    public function __destruct()
    {
        $this->close();
    }
}
```
when I edit the AMQPChnnel::confirm_select as code :
```php
public function confirm_select($nowait = false)
    {
        list($class_id, $method_id, $args) = $this->protocolWriter->confirmSelect($nowait);

        $this->send_method_frame(array($class_id, $method_id), $args);

        if ($nowait) {
            return null;
        }

        $this->wait(array(
            $this->waitHelper->get_wait('confirm.select_ok')
        ), false, $this->channel_rpc_timeout);
        if ($this->next_delivery_tag == 0) // where I’m edit
            $this->next_delivery_tag = 1;
    }
```
and then run the code the result is exactly what I expected: "ack:0 ack:1 ... ack:100"
Then I comment out my changes and get an error：
ack:0 ack:1 ... ack:10
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: Server ack'ed unknown delivery_tag "19"

Now I do not know why this is so, I hope to get your answer, thank you！

**Comment by xiaoproject** [comment]
try :

$this->channel->confirm_select();  ==>    __construct()

**Comment by xuzhenjun130** [comment]
\PhpAmqpLib\Channel\AMQPChannel::confirm_select()， 只运行一次，就不会报错了

你这代码明显， 循环遍历多次，多次运行confirm_select() 了
```php
for ($i = 1; $i <= 100; $i++) {
    $msgs[] = $i;
    if ($i % 10 == 0) {
        $t->publish($msgs);
        $msgs = [];
    }
}
```
confirm_select() 每次都会重置 next_delivery_tag = 1， 你循环运行多次，就会导致next_delivery_tag 累加不了
```php
public function confirm_select($nowait = false)
    {
        list($class_id, $method_id, $args) = $this->protocolWriter->confirmSelect($nowait);

        $this->send_method_frame(array($class_id, $method_id), $args);

        if ($nowait) {
            return null;
        }

        $this->wait(array(
            $this->waitHelper->get_wait('confirm.select_ok')
        ), false, $this->channel_rpc_timeout);
        $this->next_delivery_tag = 1;
    }

```

@easytoeasy

**Comment by ramunasd** [comment]
Method `$channel->confirm_select();` must be called before methods `basic_publish()` or `batch_basic_publish()` methods. The library does not keep references to messages which were published or "batched" before so called "confirmation mode".
