### ISSUE TITLE
Allow user to connect only with a username and empty password

### ISSUE THREAD

**Issue by tinodj** [php-amqplib/php-amqplib#808]
Hi, 

this line:
https://github.com/php-amqplib/php-amqplib/blob/31c6ec8425e7bcbde1f649b5296b00de9e6c86eb/PhpAmqpLib/Connection/AbstractConnection.php#L195

should be fixed into: 
```if ($user) {```

since a user should be able to authenticate with an empty password. 

This way it gives just a strange message: "The
   connection timed out after 3 sec while awaiting incoming data in ..." which is actually wrong login, and it took some debugging from my side to identify where exactly the problem is.

**Comment by lukebakken** [comment]
Thanks for taking the time to report this. Does using the empty string work as an empty password?

**Comment by ramunasd** [comment]
Passwordless[1] auth is supported only with external authentication methods. Later isn't supported by this library. Unless You use pretty old rabbitmq version.

[1] https://www.rabbitmq.com/passwords.html#passwordless-users

**Comment by tinodj** [comment]
well - if password is an empty string, this evaluates to false in php, therefore the condition if ($user and $password) is false.

**Comment by tinodj** [comment]
> Passwordless[1] auth is supported only with external authentication methods. Later isn't supported by this library. Unless You use pretty old rabbitmq version.

This is what I am getting as a response from the server: 
platform=Erlang/OTP 22.3.2, product=RabbitMQ, version=3.8.3, mechanisms: AMQPLAIN, PLAIN, locales: en_US

On this server password-less authentication works just fine, after myself fixing the above mentioned issue.

**Comment by tinodj** [comment]
I still believe you should handle this in else - and report exception if you don't support password to be empty. Nonetheless, I don't know why would you limit it here, rather I would return the message from the server - if it can't authenticate with empty password. I strongly argue that this if here should be changed and an option to the user should be given.

**Comment by ramunasd** [comment]
@tinodj would be nice to get PR from You, with all functional tests please :)
