### ISSUE TITLE
Debug in some cases is not working - possible fix - line 29 in DebugHelper

### ISSUE THREAD

**Issue by tinodj** [php-amqplib/php-amqplib#809]
Hi, please change this: 

https://github.com/php-amqplib/php-amqplib/blob/31c6ec8425e7bcbde1f649b5296b00de9e6c86eb/PhpAmqpLib/Helper/DebugHelper.php#L29
to:
``` define('STDOUT', fopen('php://output', 'w'));``` 

It makes things easier when using php-fpm. Output is logged directly on screen, while php://stdout is discarded by default configurations. 

This is how php-fpm is configured by default: 
```
; Redirect worker stdout and stderr into main error log. If not set, stdout and
; stderr will be redirected to /dev/null according to FastCGI specs.
; Note: on highloaded environement, this can cause some delay in the page
; process time (several ms).
; Default Value: no
;catch_workers_output = yes
```

so it sends everything to /dev/null.

However, for debugging purposes it is much better option writing to a file instead on output.

**Comment by lukebakken** [comment]
Please open a pull request with this change and provide a way for us to verify it. Thanks!
