### ISSUE TITLE
Add support for publisher confirmations

### ISSUE THREAD

**Issue by josegonzalez** [php-amqplib/php-amqplib#81]
It's a pretty useful feature, and my initial dig-through the codebase doesn't show me how I can implement this. The basics would be as follows (I think):

```
<?php
// Add the following to `AMQPChannel`
  function confirm_select($nowait = true, $callback = null):
    '''
    Set this channel to use publisher confirmations.
    '''
    $nowait = $nowait && $this->allow_nowait() && !$callback;

    $this->_msg_id = 0;
    $this->_last_ack_id = 0;
    list($class_id, $method_id, $args) = $this->protocolWriter->confirmSelect($nowait);

    $this->send_method_frame(array($class_id, $method_id), $args);

    if (!$nowait) {
      $this->select_callbacks[] = $callback;
      $this->wait(
        $this->waitHelper->get_wait('confirm.select_ok')
      )
    }
  }

  function confirm_select_ok($method_frame) {
    $callback = array_pop($this->select_callbacks);
    $callback();
  }
```

I _think_ this is sort of what is needed, though I am not quite sure whether the callback stuff is correct. I translated the code from [here](https://github.com/agoragames/haigha/blob/master/haigha/connections/rabbit_connection.py), if it matters.

I'd be happy to work through this with anyone who has any idea as to how this works!

**Comment by lukebakken** [comment]
This has been implemented since this issue was opened. Closing.
