### ISSUE TITLE
Adding exception handling for better user experience

### ISSUE THREAD

**Issue by tinodj** [php-amqplib/php-amqplib#810]
This line 
https://github.com/php-amqplib/php-amqplib/blob/31c6ec8425e7bcbde1f649b5296b00de9e6c86eb/PhpAmqpLib/Channel/AMQPChannel.php#L1029

might get replaced with 
```
            if (is_callable($this->callbacks[$consumer_tag])) {
                call_user_func($this->callbacks[$consumer_tag], $message);
            }else{
                throw new AMQPInvalidArgumentException(sprintf('%s is not callable.',var_export($this->callbacks[$consumer_tag], true)));
            }
```
for better user experience.

**Comment by lukebakken** [comment]
Would you mind checking if there are other places this could apply and open a pull request with a test to address them? Thank you.

**Comment by ramunasd** [comment]
@tinodj callback check in this place would hurt performance, it's better to check it before assignment, in method `basic_consume()`

**Comment by tinodj** [comment]
> @tinodj callback check in this place would hurt performance, it's better to check it before assignment, in method `basic_consume()`

I agree - you are right.
