### ISSUE TITLE
Setting x-ha-policy from client side is not longer available since version 3.0

### ISSUE THREAD

**Issue by seroleinic** [php-amqplib/php-amqplib#811]
There is an example in demo file amqp_ha_consumer.php, which describes how to set HA mirroring queues via arguments declaration. 
In RabbitMQ 3.0, queue mirroring is no longer controlled by the x-ha-policy argument when declaring a queue. Your applications can continue to declare this argument, but it won't cause queues to be mirrored. Instead you can declare one or more policies which control which queues are mirrored, and how.

**Comment by lukebakken** [comment]
We would welcome a pull request to fix the demo file. Thanks!
