### ISSUE TITLE
Publishing not happend after publishing to non-existent exchange

### ISSUE THREAD

**Issue by stepanets** [php-amqplib/php-amqplib#823]
**Version(s) affected**: 2.11.3

**Description**  
After publishing to non-existent exchange publishing to existent exchange not happens without any exceptions. The only exception is thrown on `$channel->close()`

**How to reproduce**  
```php
$connection = new AMQPSocketConnection('rabbit', 5672, 'guest', 'guest');

$ch = $connection->channel();
$ch->exchange_declare('existent', AMQPExchangeType::DIRECT);
$ch->queue_declare('queue');
$ch->queue_bind('queue', 'existent', 'test');

$ch->basic_publish(new AMQPMessage(), 'existent', 'test'); // this message will be published
$ch->basic_publish(new AMQPMessage(), 'non-existent', 'test'); // next messages will NOT published
$ch->basic_publish(new AMQPMessage(), 'existent', 'test'); 
$ch->basic_publish(new AMQPMessage(), 'existent', 'test');
```
![изображение](https://user-images.githubusercontent.com/2420662/91705377-0f7ae700-eba7-11ea-9943-35ddaf52b561.png)

**Comment by ramunasd** [comment]
The client(library) does not know which exchanges doest exist and wich don't. I'm pretty sure broker returns some error frames about attempts to publish to non existing exchange but library does not wait for them. This method is optimized for speed and there is no read operations in there.
I would recommend calls to `$channel->wait(null, true)` after publishing to suspicious exchanges or You can enable [confirm mode](https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher_with_confirms.php)

**Comment by stepanets** [comment]
However publishing to the existen exchacnge should works, but it doesn't after publishing to non-existent one.

**Comment by ramunasd** [comment]
From documentation [1] 

    The client MUST NOT attempt to publish a content to an exchange that does not exist. Error code: not-found

Right after attempt a broker close channel and it becomes unusable. You will get error frame but your script must wait for it exclusivelly.

Something like that:
```
try {
    $channel->basic_publish(new AMQPMessage(), 'non-existent', 'test');
    $channel->wait(null, true);
} catch (AMQPProtocolException) {
    $channel = $connection->channel();
}
```


[1] https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish.exchange

**Comment by limingxinleo** [comment]
https://github.com/hyperf/hyperf/issues/3801
