### ISSUE TITLE
descriptors, not using other nodes

### ISSUE THREAD

**Issue by aa6my** [php-amqplib/php-amqplib#824]
Hi,

from what i know it should be automatically using the other node for `descriptors` . But my case

![image](https://user-images.githubusercontent.com/7272163/91836403-4e7b6c00-ec7d-11ea-82b4-77dd082d8b3f.png)

and here the client connection

![image](https://user-images.githubusercontent.com/7272163/91836586-94d0cb00-ec7d-11ea-8795-eeffb646070a.png)

Anything configuration that i missed ?

**Comment by ramunasd** [comment]
This library does not distribute load over all configured connections, additional configs are being used as fallbacks if previous connection fails.

**Comment by aa6my** [comment]
> This library does not distribute load over all configured connections, additional configs are being used as fallbacks if previous connection fails.

Thank you for your feedback
