### ISSUE TITLE
Install with php 7.4.10

### ISSUE THREAD

**Issue by dodo1708** [php-amqplib/php-amqplib#833]
**Version(s) affected**: 2.12.0

**Description**  
I'm trying to get the package running under php 7.4.10. Always getting this error:

  Problem 1
    - Installation request for php 7.4 -> satisfiable by php[7.4].
    - php-amqplib/php-amqplib v2.12.0 conflicts with php[7.4].
    - Installation request for php-amqplib/php-amqplib ^2.12 -> satisfiable by php-amqplib/php-amqplib[v2.12.0].

It's running inside a docker container, image used: php:7.4.10-fpm

**How to reproduce**  
Just get the container running and require the package.

**Possible Solution**  
There is still the conflict 7.4.0-7.4.1 in the composer.json. In the last release there was this (https://github.com/php-amqplib/php-amqplib/pull/800) pull request which says "PHP 7.4 as fully supported minro version, on linux and windows.".

**Additional context**  
None

**Comment by andrew-demb** [comment]
Do you have a `config.platform.php` section in composer.json?

**Comment by dodo1708** [comment]
Oooh, my bad! I didn't know about this property. Changing this to 7.4.10 fixed the issue. 
I'm still curious: What's the issue with 7.4.0-7.4.1?
