### ISSUE TITLE
getDeliveryTag and basic_ack type missmatch

### ISSUE THREAD

**Issue by autowp** [php-amqplib/php-amqplib#835]
**Version(s) affected**: v2.12.0

**Description**  
[getDeliveryTag](https://github.com/php-amqplib/php-amqplib/blob/31c6ec8425e7bcbde1f649b5296b00de9e6c86eb/PhpAmqpLib/Message/AMQPMessage.php#L363) and [basic_ack](https://github.com/php-amqplib/php-amqplib/blob/1711e420195bd8d8df9a6aa7183d13c6475c1791/PhpAmqpLib/Channel/AMQPChannel.php#L781) type missmatch

```
PhanTypeMismatchArgument Argument 1 ($delivery_tag) is $msg->getDeliveryTag() of type int but \PhpAmqpLib\Channel\AMQPChannel::basic_ack() takes string defined at vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:781
PhanTypeMismatchArgument Argument 1 ($delivery_tag) is $msg->getDeliveryTag() of type int but \PhpAmqpLib\Channel\AMQPChannel::basic_nack() takes string defined at vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:886
```

**How to reproduce**  
Check with static analyzer like phan/psalm
```
$channel->basic_nack($msg->getDeliveryTag());
```

**Possible Solution**  
```
$channel->basic_nack((string) $msg->getDeliveryTag());
```

**Comment by ramunasd** [comment]
This is not real issue rather outdated and incorrect doc block which causes nothing except static analysis warnings.
BTW, `delivery-tag`[1] should be integer as originally it is defined as `longlong`. Conversion to string may lead to weird issues.

[1] https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.delivery-tag

**Comment by autowp** [comment]
Confused.
Ok, low priority, not critical etc. But you can't say "not issue" and close it with "invalid" tag.

> static analysis warnings
Errors

**Comment by lukebakken** [comment]
> But you can't say "not issue" and close it with "invalid" tag.

We would gladly review a pull request to address this. Tests are required for non-doc changes. Thanks.
