### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with message 'The connection timed out after 3 sec while awaiting incoming data'

### ISSUE THREAD

**Issue by rakesh1510** [php-amqplib/php-amqplib#839]
Hello,

while connecting to the cloud server it is showing me the below error.
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with message 'The connection timed out after 3 sec while awaiting incoming data'

$connection = new AMQPStreamConnection('host',port, 'username','password','VHOST');

"AMQPStreamConnection" function throwing error.

php-amqplib/php-amqplib : 2.7
RabbitMQ 3.8.7
Erlang 23.0.3
PHP version : PHP 5.3.29

Below is the script.

require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('host',port, 'username','password','VHOST');

**Comment by lukebakken** [comment]
My guess is that you're not really connecting to the "cloud server". Please follow this guide to troubleshoot your connection:

https://www.rabbitmq.com/troubleshooting-networking.html

**Comment by rakesh1510** [comment]
But 3rd party provided me RabbitMQ details which are located on the cloud server.
My job is to send a message to Queue and it is working via Ip and port 5672.
But when I am trying to send a message to the RMQ using the hostname and port 5671 it is showing above error.

**Comment by lukebakken** [comment]
The fact that you are using port `5671` is an important detail you should have included. More than likely RabbitMQ is configured to use TLS on that port - 

https://github.com/php-amqplib/php-amqplib/blob/master/demo/ssl_connection.php
https://www.rabbitmq.com/ssl.html
https://www.rabbitmq.com/troubleshooting-ssl.html

**Comment by lukebakken** [comment]
You need to connect using TLS. Please see the demo code to which I linked:

https://github.com/php-amqplib/php-amqplib/blob/master/demo/ssl_connection.php

**Comment by rakesh1510** [comment]
Thanks for your response.
As per code, I have to add the below details in $sslOption. 

$sslOptions = array(
    'cafile' => CERTS_PATH . '/ca_certificate.pem',
    'local_cert' => CERTS_PATH . '/client_certificate.pem',
    'local_pk' => CERTS_PATH . '/client_key.pem',
    'verify_peer' => true,
    'verify_peer_name' => false,
);

$connection = new AMQPSSLConnection(HOST, 5671, USER, PASS, VHOST, $sslOptions);

But is it possible to dens a message to queue without adding SSl detail in $sslOptions.
Because my client will not provide all certificates to me.
Is there anyway to just enable SSl or TLS connection?

**Comment by lukebakken** [comment]
You need _at minimum_ the CA certificate. If RabbitMQ is configured to require a client certificate, you need the other files as well. I strongly suggest you take the time to read the links I provided and teach yourself how TLS/SSL works.

**Comment by lukebakken** [comment]
If you continue to have questions, ask them on the mailing list so that other people can learn from them:

https://groups.google.com/forum/?oldui=1#!forum/rabbitmq-users
