### ISSUE TITLE
fwrite(): send of 19 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by yeoman-chen** [php-amqplib/php-amqplib#841]
**Version(s) affected**: v2.8.1

**Description**  
The consumer throws an exception after running for about 1 minute：

> PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: fwrite(): send of 19 bytes failed with errno=32 Broken pipe in /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:314
Stack trace:
#0 /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(349): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#1 /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(470): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#2 /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(240): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(167): PhpAmqpLib\Channel\AbstractChannel in /opt/www/squeue/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 314

**How to reproduce**  
`$consumerTag = 'consumer';
        $connection = $this->getConnection();
        $channel = $connection->channel();

        $channel->queue_declare($queue, false, true, false, false);
        $channel->exchange_declare($exchange, 'direct', false, true, false);

        $channel->queue_bind($queue, $exchange, $routingKey);
        $channel->basic_qos(null, 1, null);
        $channel->basic_consume($queue, $consumerTag, false, true, false, false, $callback);
        // 注册shutdown 函数
        register_shutdown_function($this->shutdown, $channel, $connection);

        try {
            while (count($channel->callbacks)) {
                $channel->wait(null, false, 65);
            }
        } catch (\Exception $e) {
            Log::info('【rabbitmq】进程等待时间超过限制，正常退出。' . $e->getCode() . '-' . $e->getMessage()."\n".$e);
        }`

**Possible Solution**  

**Additional context**

**Comment by ramunasd** [comment]
From Your example is unclear how connection was created and what are defined timeouts. I guess they are less than `wait()` timeout, so this is expected behaviour.

Also, please upgrade to latest version before submitting issues. For any questions about timeouts and general usage please use mailling list instead of github issues.

https://groups.google.com/g/php-amqplib-devel
