### ISSUE TITLE
Too many publishers produce many messages In an hour, occasionally cause an exception: "stream_socket_client(): unable to connect to tcp://RABBITMQ-***amazonaws.com:5672 (Connection timed out)"

### ISSUE THREAD

**Issue by yjj353373397** [php-amqplib/php-amqplib#842]
**php-amqplib: 2.10.0**
**php version: 7.0**

Recently, we added too many producers, as a result,we discovered the following exception thrown occasionally.

`stream_socket_client(): unable to connect to tcp://RABBITMQ-***amazonaws.com:5672 (Connection timed out)`

### Part of the code

```
// create connection and channel
$this->connection = new AMQPStreamConnection(
    $host,
    $port,
    $user,
    $password,
    $vhost,
    $insist = false,
    $login_method = 'AMQPLAIN',
    $locale_response = null,
    $locale = 'en_US',
    $connection_timeout = 3,
    $read_write_timeout = 3,
    $context = null,
    $keepalive = false,
    $heartbeat = 120
);
$this->channel = $this->connection->channel();

...

// publish msg
$properties = [
    'delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT,
    'content_type'  => 'application/json',
];
$msg = new AMQPMessage($body, $properties);
$this->channel->basic_publish($msg, $this->exchange_name, $msg_type);


// close channel and connection
$this->channel->close();
$this->connection->close();
```

Because of Connection timed out, we Lost a few messages. Of course, most of messages can be published normally.

Does anyone have a similar problem? 

How to solve this problem? Thanks.

**Comment by kanidjar** [comment]
Hello, we face the same issue in my team.

We are running a microservices platform and have around 100 connections.

3 or 4 times per day, we get the following error when trying to publish.

```php
[2020-10-24 18:17:28] release.ERROR: stream_socket_client(): unable to connect to ssl://***.rmq.cloudamqp.com:5671 (Unknown error) {"exception":"[object] 
(PhpAmqpLib\\Exception\\AMQPIOException(code: 0): stream_socket_client(): unable to connect to ssl://***.rmq.cloudamqp.com:5671 (Unknown error) at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:110)
```

I already asked the Cloudamqp support to investigate but they did not find any network issue on their side...

**Comment by ramunasd** [comment]
Your client failed on one of the firsts TCP connection functions. `stream_socket_client()` is a low level wrapper for C function, which directly works with TCP stack, so this error comes from operating system(OS). If OS cannot open connection to specific endpoint then PHP can do nothing about it. It's a network problem.

I see You use DNS names. Maybe the problem is DNS server timeouts?
I would siggest to use IP addresses or use some kind of DNS lookup cache, either network or system based.
Anyways, the problem is not in the library.
