### ISSUE TITLE
Multiple consumers at one connection

### ISSUE THREAD

**Issue by andrey-tech** [php-amqplib/php-amqplib#843]
Hello,

Is there any correct way to use multiple consumers at one connection?
I'm trying this code, but is this correct way?

```php
$connection = new AMQPStreamConnection($host, $port, $uer, $pass);
$channel1 = $connection->channel(1);
$channel2 = $connection->channel(2);
$channel1->basic_consume($query1, '', false, false, false, false, $callback1);
$channel2->basic_consume($query2, '', false, false, false, false, $callback2);

while (true) {
    if ($channel1->is_consuming()) {
        $channel1->wait(null, true);
    }
    if ($channel2->is_consuming()) {
        $channel2->wait(null, true);
    }
    usleep(500000);
}
```

**Comment by ramunasd** [comment]
Hi @andrey-tech, it would be better to ask all "how to use" questions in mailing list[1], user chat chat[2] or read official documentation [3]. Github issues are for library bugs and other issues only.

[1] https://groups.google.com/forum/#!forum/php-amqplib-devel
[2] https://gitter.im/php-amqplib/RabbitMqBundle
[3] https://www.rabbitmq.com/getstarted.html
