### ISSUE TITLE
PHP 8: Required parameter $io follows optional parameter $vhost

### ISSUE THREAD

**Issue by dakujem** [php-amqplib/php-amqplib#846]
**Version(s) affected**: current
**PHP version**: 8.0 (RC3)

**Description**  
![image](https://user-images.githubusercontent.com/443067/98666432-51fe3400-234d-11eb-9385-ec16accf6051.png)

Here is info about this deprecation in PHP 8.\
https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Possible Solution**  
```php
    public function __construct(
        $user,
        $password,
        $vhost = '/',
        $insist = false,
        $login_method = 'AMQPLAIN',
        $login_response = null,
        $locale = 'en_US',
        AbstractIO $io = null,
        $heartbeat = 0,
        $connection_timeout = 0
    ) {
        if($io === null){
            throw new InvalidArgumentException('$io is compulsory');
        }
```

**Comment by ramunasd** [comment]
We do not support PHP8 yet. It is too difficult to support 3 different major versions.

Also, this constructor will be refactored as more parameters might and are optional.

**Comment by dakujem** [comment]
Would you welcome a PR with the change I proposed above?
PHP 8 should be released **in 2 weeks**, I suppose all libs should update ASAP.

@ramunasd

**Comment by dakujem** [comment]
AFAIK the change is backward compatible and would not break existing working code.

**Comment by ramunasd** [comment]
I would strongly not recommend to use this library with PHP8. There might be more and bigger issues with it. As a example I can show incompatibilities with PHP7.4[1], which is far less changed version.

You can disable deprecation errors easily:
```
$level = error_reporting(E_ERROR);
$connection = new AMQPConnection();
error_reporting($level);
```

[1] https://github.com/php-amqplib/php-amqplib/pull/765

**Comment by dakujem** [comment]
I'm confused. What is the alternative then? All the other libs for AMPQ/RabbitMQ I found only wrap this one.

I'm currently using this lib with the latest PHP 7.4 and will try migrate to 8 on multiple projects soon. I'm not getting any errors described in the linked issue.

Furthermore,  the PHP bug referenced in the issue (https://bugs.php.net/bug.php?id=79000) has been closed almost an year ago.

**Comment by dgafka** [comment]
@ramunasd is there work in progress to introduce PHP 8 compatibility? 
If so, is there any chance for it to be available before the release?

**Comment by ramunasd** [comment]
@dgafka AFAIK nobody works on PHP8 compatibility. IMHO we will drop PHP5 support first.

**Comment by dgafka** [comment]
@ramunasd ok, thanks for answer :)

**Comment by dakujem** [comment]
I believe you can safely drop support for anything below 7.4 for new version(s) of the lib, since 7.3's active support is ending in a couple of weeks. Legacy PHP soft can keep running on legacy lib versions. A working lib for PHP 7.4 (and 8.0), the current PHP versions, should IMHO be prioritized.

**Comment by thepercival** [comment]
hello,

is there an alternative for this package when using php 8? I would like to move our projects to php 8, but we need a amqp-lib. Thanks to all the contributors by the way for making this nice package!

**Comment by dgafka** [comment]
@thepercival you may try native PHP extension for php-amqp. It recently got support for PHP8.

**Comment by robo2bobo** [comment]
I've tested php-amqplib with PHP8 and created a patch to fix the deprecation warnings: https://github.com/php-amqplib/php-amqplib/issues/860#issuecomment-752139275

**Comment by thepercival** [comment]
great, thnx for the work
