### ISSUE TITLE
Why is the client disconnecting automatically with no errors nor Exceptions?

### ISSUE THREAD

**Issue by achetronic** [php-amqplib/php-amqplib#847]
**Edited**
Deleted because I finally did it with Python Pika library

**Comment by ramunasd** [comment]
Please report library version and other required information. Also, please enable debug mode with `define('AMQP_DEBUG', true)`. Also, it makes no sense to register heartbeat sender with connection param `heartbeat=0`.

**Comment by achetronic** [comment]
> Please report library version and other required information. Also, please enable debug mode with `define('AMQP_DEBUG', true)`. Also, it makes no sense to register heartbeat sender with connection param `heartbeat=0`.

Library version is the last one and using with Laravel. According to the heardbeats you are right and they are both defined because of a lot of tests done right now. This happens in both cases individually (=0 and defined).

If I define AMPQ_DEBUG, the channel-wait() will throw something? because i thing there is the problem, the rest of code acts well untill everything hangs, Am i mistaken? :)
