### ISSUE TITLE
About message body string "quit"

### ISSUE THREAD

**Issue by haozige90** [php-amqplib/php-amqplib#848]
Description:
In consumer demo, there is a line as below:

```
// Send a message with the string "quit" to cancel the consumer.
if ($message->body === 'quit') {
    $message->getChannel()->basic_cancel($message->getConsumerTag());
}
```

Question:
Why do we need a "quit" signal to cancel consumer?

**Comment by lukebakken** [comment]
https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_consumer.php#L52-L55
