### ISSUE TITLE
The connection would lost on some environment and cause destruct failed

### ISSUE THREAD

**Issue by JasonCatShi** [php-amqplib/php-amqplib#849]
**Version(s) affected**: From 2.7.3 to 2.12.1 (maybe, since I saw no code change about the point I found the bug)

**Description**  
Rabbitmq connection lost when destruct on a weak socket connection server, then fatal error raised
Fatal error: 
<br /><b>Fatal error</b>:  Call to a member function wait_channel() on a non-object in <b>/ramdisk/epgweb/public/dists_epgweb/R2010-20201027-1028_webroot/sites/all/modules/cimsmq/php-amqplib-2.7.3/PhpAmqpLib/Channel/AbstractChannel.php</b> on line <b>225</b><br

**How to reproduce**  

Need a server that config weak socket connection

**Possible Solution**  

Firstly just avoid the fatal error, then you may gave me more information about why connection would lost, I have weak knowledge about socket

**Additional context**  

The avoid workaround is
On file 
PhpAmqpLib/Channel/AbstractChannel.php

Function   public function next_frame($timeout = 0) one line (225)

    public function next_frame($timeout = 0)
    {
        $this->debug->debug_msg('waiting for a new frame');

        if (!empty($this->frame_queue)) {
            return array_shift($this->frame_queue);
        }

        if (!isset($this->connection) || !$this->connection) {
            throw new AMQPRuntimeException('Channel connection is closed.');
        }

        return $this->connection->wait_channel($this->channel_id, $timeout);
    }

**Comment by ramunasd** [comment]
It would be very helpful if You could provide Your configuration, library info from `tests/phpinfo.php` and the way how to reproduce this error message.
BTW, You can change this file locally just for debug purposes.

**Comment by JasonCatShi** [comment]
The php info page is long:
[phpinfo.txt](https://github.com/php-amqplib/php-amqplib/files/5634407/phpinfo.txt)

We are refactoring the old consumers...

**Comment by ramunasd** [comment]
@JasonCatShi Your last comment was removed because it had sensitive information about Your environment. Please be carefull before posting such things publicly. Also, that info came not from special file I mentioned before.

From what i seen You are using pretty old PHP5.5 version. We do not support it anymore.

You didn't provide any other usefull info for debug purposes - connection configuration, stack trace, constants from `tests/phpinfo.php`, sample script. Therefore we cannot help You.

**Comment by JasonCatShi** [comment]
Ok, thanks for the answer anyway.
We have avoid this issue by the ITTE support.
And sorry for the late update...

Best Regards
