### ISSUE TITLE
Is a support of PHP 8 planned yet?

### ISSUE THREAD

**Issue by cougargit** [php-amqplib/php-amqplib#853]
**Description**  
At the moment php-amqplib does not support PHP 8.
Is there any support planned?

**Comment by sbacelic** [comment]
This has already been discussed in #851

**Comment by lukebakken** [comment]
@cougargit @sbacelic 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2

The above should ship as `3.0.0` this week.
