### ISSUE TITLE
PHP 8.0.0 Deprecated: Required parameter ... follows optional parameter ... in 

### ISSUE THREAD

**Issue by sergiula** [php-amqplib/php-amqplib#856]
**Description**  
As of PHP 8.0.0, passing mandatory arguments after optional arguments is deprecated. This can generally be resolved by dropping the default value. One exception to this rule are arguments of the form Type $param = null, where the null default makes the type implicitly nullable. This usage remains allowed, though it is recommended to use an explicit nullable type instead.

see: https://www.php.net/manual/en/functions.arguments.php

**Example**  

`Deprecated: Required parameter $io follows optional parameter $vhost in ...vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 175`
and other, for example:
`php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 20`

**Comment by sergiula** [comment]
duplicate

**Comment by lukebakken** [comment]
@sergiula 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2

The above should ship as `3.0.0` this week.
