### ISSUE TITLE
The dependency phpseclib needs an update to version 3.*

### ISSUE THREAD

**Issue by r-simlinger** [php-amqplib/php-amqplib#867]
**Description**

The dependency phpseclib needs an update to version 3.*

https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md

It's not critical, but it's blocking updating other projects which want to use the version 3.* as composer does not allow to install the version 2.* and 3.*at the same time.

**Comment by r-simlinger** [comment]
As an alternative to upgrading to version 3.* it's also possible to use https://github.com/phpseclib/phpseclib2_compat .

**Comment by ramunasd** [comment]
Looking from another side, higher requirement on our side would enforce everyone to upgrade even if they don't want to? @r-simlinger

**Comment by hotrush** [comment]
@ramunasd better to force to upgrade than to force to use outdated software...

**Comment by r-simlinger** [comment]
@ramunasd you could also support both versions :)

As you are only using this BigInteger class from this dependency will will not have any trouble I guess.

Just use [class_exists](https://www.php.net/manual/en/function.class-exists.php) to check which version was installed  [phpseclib3\Math\BigInteger](https://github.com/phpseclib/phpseclib/blob/3.0/phpseclib/Math/BigInteger.php) or [phpseclib\Math\BigInteger](https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Math/BigInteger.php).

**Comment by ooing** [comment]
@r-simlinger   How to do it in  phpseclib3.*
