### ISSUE TITLE
PHP 8 Deprecate required parameters after optional parameters issue

### ISSUE THREAD

**Issue by semalley** [php-amqplib/php-amqplib#870]
**Version(s) affected**: v2.12.1

**Description**  
PHP 8 deprecates the required parameters after optional. So now we got Exception in `PhpAmqpLib\Connection\AbstractConnection::_construct()` because of `AbstractIO $io` parameter goes after optional.

**How to reproduce**  
Run code on PHP 8 version

**Possible Solution**  
Change position of this parameter, to move it before optional

**Additional context**  
https://php.watch/versions/8.0/deprecate-required-param-after-optional
https://www.php.net/manual/en/functions.arguments.php#functions.arguments.default

**Comment by AratKruglik** [comment]
Confirm issue. The same for me.

**Comment by lukebakken** [comment]
Please see #858

**Comment by lukebakken** [comment]
@AratKruglik @semalley 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by AratKruglik** [comment]
@lukebakken 
I was testing `v3.0.0-rc1` tag on my local environment. Seem like now it works with PHP8.

**Comment by semalley** [comment]
@lukebakken 
For me RC worked as well. Thanks for notifying

**Comment by AratKruglik** [comment]
RC2 works for me, thanks!
One last question: when do you plan to release stable v.3.0.0 version?

**Comment by lukebakken** [comment]
Thanks @AratKruglik you're the first person to report back testing RC2. I can get version 3 today.

**Comment by semalley** [comment]
@lukebakken It would be really great. Already want to try in on production with php8

**Comment by lukebakken** [comment]
https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0
