### ISSUE TITLE
PHP8 issues - PHP Deprecated:  Required parameter $io follows optional

### ISSUE THREAD

**Issue by 3kbest** [php-amqplib/php-amqplib#872]
**Version(s) affected**: 2.12.1

**Description**  
PHP Deprecated:  Required parameter $io follows optional parameter $vhost in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 175

Deprecated: Required parameter $exchange follows optional parameter $redelivered in /vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 662

**How to reproduce**  
Usage of php8.
PHP 8.0.1 (cli) (built: Jan 13 2021 08:21:37) ( NTS

**Possible Solution**  
Reorder optional params to end?

**Additional context**  
![image](https://user-images.githubusercontent.com/25566931/106900487-dff07d80-66f6-11eb-8769-04aa4a2a7697.png)

**Comment by lukebakken** [comment]
This is a duplicate of many other issues. See #858

**Comment by lukebakken** [comment]
@3kbest 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
@3kbest 

Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2
