### ISSUE TITLE
Provide AMQPTable to exchange_declare

### ISSUE THREAD

**Issue by Patrick-Remy** [php-amqplib/php-amqplib#873]
At https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L356 for `exchange_declare` it isn't typed/annotated that $arguments can be of type `AMQPTable`, but it is at https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L640 for `queue_declare`.

Is this just a bug or is there a reason not to pass the `AMQPTable` there?

Thanke for your investigation!

**Comment by ramunasd** [comment]
fixed #874
