### ISSUE TITLE
Type definition delivery tag differs

### ISSUE THREAD

**Issue by Patrick-Remy** [php-amqplib/php-amqplib#876]
**Version(s) affected**: 2.12.0

**Description**  
Using linters like [psalm](https://github.com/vimeo/psalm), you'll notified that 
```
/** 
 * @var \PhpAmqpLib\Channel\AMQPChannel $channel
 * @var \PhpAmqpLib\Message\AMQPMessage $message
 */
$channel->basic_ack($message->getDeliveryTag());
```
results in `Argument 1 of PhpAmqpLib\Channel\AMQPChannel::basic_ack expects string, int provided`.

References: 
- https://github.com/php-amqplib/php-amqplib/blob/v2.12.0/PhpAmqpLib/Message/AMQPMessage.php#L359
- https://github.com/php-amqplib/php-amqplib/blob/v2.12.0/PhpAmqpLib/Channel/AMQPChannel.php#L778
- https://github.com/php-amqplib/php-amqplib/blob/v2.12.0/PhpAmqpLib/Message/AMQPMessage.php#L343
- https://github.com/php-amqplib/php-amqplib/blob/v2.12.0/PhpAmqpLib/Message/AMQPMessage.php#L187

Which type is required/should be passed? `int`, `string` or `int|string`?

**Comment by andrew-demb** [comment]
See discussion in PR #838
Maybe we should specify `int` in every place, where a delivery tag is mentioned?

**Comment by ramunasd** [comment]
@Patrick-Remy Can You check master branch and reopen this issue if it still exists?

**Comment by Patrick-Remy** [comment]
Thank's it was resolved by https://github.com/php-amqplib/php-amqplib/commit/d718b0fe536fc295b5cb72c97cca47a9fb3b1d5d#diff-3b3272c2802b1c5758a7cf0539fe4e1db13ca02ceb959ede81694a934fc38955. 
Shame on me ;)
