### ISSUE TITLE
Remove support for PHP 5.X

### ISSUE THREAD

**Issue by lukebakken** [php-amqplib/php-amqplib#877]
All support for 5.X should be removed. See #858.

**Comment by lukebakken** [comment]
@ramunasd do you have an account on packagist.org? If so I would like to add you as an owner of `php-amqplib` there.

**Comment by ramunasd** [comment]
@lukebakken should be same username as here, `ramunasd`

**Comment by lukebakken** [comment]
Done!

**Comment by ramunasd** [comment]
fix in #884
