### ISSUE TITLE
BigInteger breaks authoritative class maps

### ISSUE THREAD

**Issue by AegirLeet** [php-amqplib/php-amqplib#885]
**Version(s) affected**: 2.12.2 / current master branch

**Description**  
https://github.com/php-amqplib/php-amqplib/pull/875 broke [authoritative class maps](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps) because the `\PhpAmqpLib\Helper\BigInteger` class is only aliased at runtime.

**How to reproduce**  
1. Clone this repo
2. `composer install -a`
3. `php -r "require __DIR__ . '/vendor/autoload.php'; var_dump(new \PhpAmqpLib\Helper\BigInteger());"`

> Fatal error: Uncaught Error: Class 'PhpAmqpLib\Helper\BigInteger' not found in Command line code on line 1

To verify it works without authoritative class maps, run `composer install -o` and try the command in step 3 again.

**Possible Solution**  
Revert or refactor https://github.com/php-amqplib/php-amqplib/pull/875.

**Additional context**  
N/A

I'm not sure if the usual SemVer rules apply in this case, but this broke one of our applications after going from 2.12.1 to 2.12.2.

**Comment by ramunasd** [comment]
@AegirLeet can You provide more info how it broke Your application? It's just because You use composer optimizations?

**Comment by AegirLeet** [comment]
@ramunasd Yes, our deployments use `composer install -a`. We fixed it by using `composer install -o` for now. Definitely not something we expected from a patch-level upgrade though.

**Comment by ramunasd** [comment]
Released as v2.12.3
