### ISSUE TITLE
Required parameter $io follows optional parameter $vhost

### ISSUE THREAD

**Issue by ddarrko** [php-amqplib/php-amqplib#886]
**Version(s) affected**: Latest version with PHP8

**Description**  
The required parameter currently follows an optional one in AbstractConnection.php. This has been deprecated in PHP8

**How to reproduce**  

**Possible Solution**  
Reorder the parameters

**Comment by keywinf** [comment]
Already on https://github.com/php-amqplib/php-amqplib/pull/858

**Comment by ddarrko** [comment]
> Already on #858

Yes sorry. I didnt see it included as was looking at issue names only. Thanks
