### ISSUE TITLE
Support for php 8 version 2.12.2

### ISSUE THREAD

**Issue by surendra-17** [php-amqplib/php-amqplib#887]
amqplib 2.12.2 support php 8 or not?

**Comment by liborm85** [comment]
https://github.com/php-amqplib/php-amqplib/blob/2.12.2/composer.json#L32

**Comment by lukebakken** [comment]
@keywinf @liborm85 @surendra-17 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
@keywinf @liborm85 @surendra-17

Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2
