### ISSUE TITLE
Always allow to set a timeout

### ISSUE THREAD

**Issue by mschirmacher** [php-amqplib/php-amqplib#89]
We ran into a problem with rabbitmq: due to a bug the broker occasionally wouldn't answer to tx.commit and amqpChannel->tx_commit() hangs indefinitly as the tx.commit-ok never arrives.
So we need a timeout for tx_commit and all other methods, which currently do not provide this parameter

**Comment by xlight** [comment]
+1

**Comment by lukebakken** [comment]
I'll check to see how other RabbitMQ client handle methods like commit.

**Comment by mszabo-wikia** [comment]
I believe this was resolved by #609 : `tx_commit` will now respect the configured `$channel_rpc_timeout` value.

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L1354

**Comment by ramunasd** [comment]
I can confirm, almost all wait() has set timeout, either `$channel_rpc_timeout` or `$connection_timeout` or user provided.

**Comment by lukebakken** [comment]
Assuming addressed by #609 and by @ramunasd 's testing. Thanks!
