### ISSUE TITLE
application_headers vs headers

### ISSUE THREAD

**Issue by greg0ire** [php-amqplib/php-amqplib#890]
Hi! I have a question about `application_headers` vs `headers`: It says here that application_headers is AMQP 1.0, while headers is AMQP 0.9: https://github.com/rabbitmq/rabbitmq-amqp1.0 … but in the README of this repo, one can read:

> This library is a pure PHP implementation of the AMQP 0-9-1 protocol.

And then in https://github.com/php-amqplib/php-amqplib/blob/master/doc/AMQPMessage.md, it's stated that it only accepts `application_headers` . And finally, when I send a message with application_headers, the consumer receives a message with these headers, but in a `headers` property. Does anyone know about this?

**Comment by ramunasd** [comment]
@greg0ire Could You explain where the problem is? It's just naming or something else?

Also, please check examples in:
demo/amqp_message_headers_snd.php
demo/amqp_message_headers_recv.php

**Comment by greg0ire** [comment]
The problem is, I would expect this: https://github.com/php-amqplib/php-amqplib/blob/85da8ec7cd2181c2e8b33a290ce72db051609854/demo/amqp_message_headers_snd.php#L65

to actually be `$message->set('headers', $headers);`.

It would make more sense to me, especially since:
- `application_headers` seem to be an AMQP 1.0 thing, and this repo says it is an implementation of AMQP 0.9
- what I see in the RabbitMQ UI is my headers under "Headers", not "Application headers"

So to be clear, I know how to use this package to make my code work, I just don't understand how it works… Note that this also complexifies other packages, that use phpamqplib and need to do a conversion: https://github.com/swarrot/swarrot/blob/4ae0d5c5fe5b0c2a73fe513d594d6f3ba1fcdda2/src/Swarrot/Broker/MessagePublisher/PhpAmqpLibMessagePublisher.php#L47-L62

**Comment by ramunasd** [comment]
This project is open-source and welcomes bug fixes and improvements. Complains and expectations does not help. We would like to review PR with all changes, tests and documentation improvements. IMHO this change would be considered as backwards incompatible, so version 3.0 is good opportunity to release it fast ;)

**Comment by greg0ire** [comment]
Sorry if I appeared bossy, what I really meant is to ask for additional context that you might know about. If you don't know that's fine: I too maintain big projects, and there is a lot of decisions that I can't explain because they were made a long time  ago in a different context.
