### ISSUE TITLE
Required parameter $io follows optional parameter $vhost in php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php"

### ISSUE THREAD

**Issue by dannyrossouxxtract** [php-amqplib/php-amqplib#896]
**Version(s) affected**: 2.12.1 (2.12.2 ?)

**Description**  
Required parameter $io follows optional parameter $vhost 
in php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures
(https://php.watch/versions/8.0/deprecate-required-param-after-optional)

**How to reproduce**  
Use the php-amqplib with php 8.0

**Possible Solution**  
Change the parameter order or make parameter $io optional

**Comment by ramunasd** [comment]
See #851 #853 #856 #860 #870 #872 #887 & #858

**Comment by lukebakken** [comment]
@dannyrossouxxtract 

Please take the time to test `v3.0.0-rc1` in your environment and report back if issues are found:

https://groups.google.com/g/rabbitmq-users/c/ktkiQ9slrME

https://packagist.org/packages/php-amqplib/php-amqplib#3.0.0-rc1

**Comment by lukebakken** [comment]
Latest RC is https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2
