### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by hvanoch** [php-amqplib/php-amqplib#902]
I was wondering what the status is about the PHP 8.0 support. I see there has been work on it lately and it looks that the only thing that is blocking composer to update is the version constraint defined in the composer.json.

Not trying to push or anything. Just wanted to know if this is something that is going to be done in the coming days.

Thanks for the effort!

**Comment by ramunasd** [comment]
not an issue, duplicated discussion https://github.com/php-amqplib/php-amqplib/discussions/901
