### ISSUE TITLE
stream_select does not detect dropped connections

### ISSUE THREAD

**Issue by Bill-ColeUS** [php-amqplib/php-amqplib#906]
**Version(s) affected**: 3.0.0

**Description**  
If I reboot the rabbitmq server, all my PHP consumers stop receiving messages and never recover once the rabbitmq server is back online. This issue only affects my PHP consumers using the php-amqplib library.

Upon further investigation, I traced the problem to the file `Wire/IO/StreamIO.php`, function `do_select` calls `stream_select`:

```php
    /**
     * @inheritdoc
     */
    protected function do_select($sec, $usec)
    {
        if ($this->sock === null || !is_resource($this->sock)) {
            $this->sock = null;
            throw new AMQPConnectionClosedException('Broken pipe or closed connection', 0);
        }

        $read = array($this->sock);
        $write = null;
        $except = null;

        return stream_select($read, $write, $except, $sec, $usec);
    }
```

The problem in this case, is that `$sec` is null and `$usec` is 0. This causes stream_select is sit there indefinitely, never detecting that the rabbitmq server has gone away and never re-trying to recreate the connection. An undead consumer... 

As you can see from my connection below, I'm using a heartbeat with 4 seconds timeout, that does absolutely nothing when stream_select is blocking.

I am also using connection_timeout with 2 seconds timeout, thinking that this would be passed down to stream_select, apparently I am wrong.

Is this a bug? or am I missing some other timeout value that I should be using?

Thank you.

**How to reproduce**  
```php
$connection = new AMQPSSLConnection(
	$server,
	$port,
	$user,
	$password,
	$vhost,
	array(
		'cafile'		=> "cafile.pem",
		'verify_peer'		=> true,
		'verify_peer_name'	=> true
	),
	array(
		'connection_timeout'	=> 2,
		'heartbeat'		=> 4
	)
);

$channel = $connection->channel();

$channel->exchange_declare($name, "fanout", false, false, false);

list($randomQueue, ,) = $channel->queue_declare("", false, true, true, false);

$channel->queue_bind($randomQueue, $name);

$channel->basic_consume($randomQueue, "", false, true, false, false, "process"));

while($channel->is_consuming())
	$channel->wait();
```

**Possible Solution**  
Temporarily, I've manually set `$usec = 2;` just above the call to stream_select and that solved my problems.

**Comment by Bill-ColeUS** [comment]
I think I've narrowed down the problem...

Apparently, `next_frame($timeout)` starts fine and has my 2 second timeout as set by connection_timeout. But this only happens for the first 3 loops! Weird... the 4th loop calls `next_frame()` with no timeout, which automatically forces it to reset my timeout to 0, which results in undead consumers.

**Comment by Bill-ColeUS** [comment]
While tracing the calls to next_frame and who sets the timeout parameter, I came upon the following calls to `function setTimeout($timeout)`:

```
[Wire/AMQPReader.php] setTimeout: 2
[Wire/AMQPReader.php] setTimeout: 0
[Wire/AMQPReader.php] setTimeout: 2
[Wire/AMQPReader.php] setTimeout: 0
[Wire/AMQPReader.php] setTimeout: 2
[Wire/AMQPReader.php] setTimeout: 0
[Wire/AMQPReader.php] setTimeout: 0
...etc...
```

When my consumers start, the timeout is correctly set to 2 seconds, then switched to 0 seconds, then again back to 2 seconds, again to 0 seconds, back to 2 seconds and finally set to 0 seconds permanently which flows down to `next_frame($timeout)` and further down to `stream_select` which results in undead consumers.

Not sure if that is how it's supposed to work or if this is a bug...

**Comment by ramunasd** [comment]
The problem lies in those lines:
```
while($channel->is_consuming())
	$channel->wait();
```

By default `wait()` is blocking and there is no internal mechanism which could perform connection probing. So this code sample is very optimistic and aren't prone to various connection problems.

What You could do is to set wait timeout. Then You will have very high chances to detect dropped connection.
```
while($channel->is_consuming()) {
    try {
        $channel->wait(null, false, 10);
    } catch (AMQPTimeoutException $exception) {
        continue;
    } catch (AMQPConnectionClosedException $exception) {
        // stop and reconnect
    }
}
```

**Comment by Bill-ColeUS** [comment]
You are right, if I use `wait(null, false, 2)` then things work fine and setTimeout does not reset to 0 permanently after a few loops.

- So heatbeat is utterly useless in this case?

- And connection_timeout is used at first, but ignored eventually?

- Maybe these things could be documented a little better? :)

**Comment by ramunasd** [comment]
> * So heatbeat is utterly useless in this case?
Not really. You can use unix signals based heartbeat checker as described here https://github.com/php-amqplib/php-amqplib#signal-based-heartbeat

Connection timeout(or RPC timeout) can be used for 

> 
> * Maybe these things could be documented a little better? :)

Please don't hesitate, we would will gladly review a PR :) Separate section about connection issues would be very nice to have.

**Comment by Bill-ColeUS** [comment]
I wish I could write something, but my lack of understanding is a problem. Maybe once I've learned a bit more I can write a useful document. The current documentation is good enough to play around, but once you apply the library into a real world application, things don't go as planned.

I tried your suggestion and used `wait(null, false, 10)` which had an interesting result... every 10 seconds (or whatever timeout I set), it throws AMQPTimeoutException. Even if there is no rabbitmq server running... it never throws AMQPConnectionClosedException or any other exception. Thus, the consumer never recovers from a dropped connection, even when the rabbitmq server has recovered.

I'd appreciate your help.

Thank you.

**Comment by ramunasd** [comment]
Well, it does detect dropped connection if heartbeats are enabled. This is most reliable way.

PHP itself does not provide any `detect_broken_connection()` function. If You know how to do it - please let me know, we will consider it really seriously.
