### ISSUE TITLE
PHP 8.0 deprecation, required parameters following optional parameters 

### ISSUE THREAD

**Issue by mtedv** [php-amqplib/php-amqplib#907]
**Version(s) affected**: v3.0.0 (latest by now)

**Description**  
I receive deprecation notices when using php-amqplib:

**How to reproduce**  
Deprecated: Required parameter $routing_key follows optional parameter $redelivered in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 721

Deprecated: Required parameter $exchange follows optional parameter $redelivered in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 721

Deprecated: Required parameter $routing_key follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 703

Deprecated: Required parameter $exchange follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 703

Deprecated: Required parameter $exchange follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 562

Deprecated: Required parameter $exchange follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 472

Deprecated: Required parameter $source follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 393

Deprecated: Required parameter $destination follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 393

Deprecated: Required parameter $source follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 356

Deprecated: Required parameter $destination follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 356

Deprecated: Required parameter $exchange follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 328

Deprecated: Required parameter $exchange follows optional parameter $ticket in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 291

Deprecated: Required parameter $method_id follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 225

Deprecated: Required parameter $class_id follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 225

Deprecated: Required parameter $method_id follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 133

Deprecated: Required parameter $class_id follows optional parameter $reply_text in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 133

Deprecated: Required parameter $server_properties follows optional parameter $version_major in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php on line 20

Deprecated: Required parameter $io follows optional parameter $vhost in /www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 176 

**Possible Solution**  
Change the order of parameters / make them non-optional :)

**Comment by ramunasd** [comment]
This was already fixed. You can check latest version here on github.
Something is wrong on Your end. Please double check which version You actually use.
