### ISSUE TITLE
consumer_tag: Consumer identifier

### ISSUE THREAD

**Issue by 449134904** [php-amqplib/php-amqplib#909]
这个用户标识的具体作用是什么?可以指点迷津吗

**Comment by ramunasd** [comment]
Sorry, we speak english only.

**Comment by 449134904** [comment]
So I just want to ask what exactly does consumer_tag do

**Comment by ramunasd** [comment]
Please check documentation before asking:

https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.consumer-tag
