### ISSUE TITLE
README - Non-existant code of conduct file

### ISSUE THREAD

**Issue by RyanFarrah67** [php-amqplib/php-amqplib#913]
**Version(s) affected**: 3.0.0 and since v2.10.0-rc1

**Description**  
The `README.md` file make a link to a non-existant code of conduct file in this text : 
`Please note that this project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.`

In fact this file was moved from `CODE_OF_CONDUCT.md` to `.github/CODE_OF_CONDUCT.md` since the merge request of this issue https://github.com/php-amqplib/php-amqplib/pull/717/commits/97e873341720126054cc7a6986f3ff012b871455 but the README was not updated.

**Comment by ramunasd** [comment]
Thanks
