### ISSUE TITLE
Updating "phpseclib/phpseclib" is necessary!

### ISSUE THREAD

**Issue by wajdijurry** [php-amqplib/php-amqplib#914]
As been reported by Github, the "phpseclib/phpseclib" has a vulnerability:
```
phpseclib before 2.0.31 and 3.x before 3.0.7 mishandles RSA PKCS#1 v1.5 signature verification.
```
![Screenshot from 2021-05-01 12-27-13](https://user-images.githubusercontent.com/25797257/116778170-0cf3c880-aa79-11eb-97d8-d5d4a39476a2.png)

It's recommended to update the dependency to patched version: 2.0.31

**Comment by ramunasd** [comment]
Already explained in #911
