### ISSUE TITLE
Can't connect to ssl amqp hosts.

### ISSUE THREAD

**Issue by alexbumbacea** [php-amqplib/php-amqplib#918]
**Version(s) affected**: 2.7.0

**Description**  
Can't connect to ssl amqp hosts. Trying to do it, results in broken pipe exception.

**How to reproduce**  
Try to consume from a connection with this dsn: amqps://guest:guest@host.docker.internal:5671/%2f.
This will result in broken pipe failure.

**Possible Solution**  
\OldSound\RabbitMqBundle\RabbitMq\AMQPConnectionFactory should send info about ssl/non-ssl cnnection to create_connection call.
\PhpAmqpLib\Connection\AMQPStreamConnection::try_create_connection should be passing to the constructor the ssl_protocol.

**Additional context**  
# General info
phpinfo()
PHP Version => 7.4.19

System => Linux 150f2552a38e 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64
Build Date => May  6 2021 22:26:07
Configure Command =>  './configure'  '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pear' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-musl'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /usr/local/etc/php
Loaded Configuration File => /usr/local/etc/php/php-cli.ini
Scan this dir for additional .ini files => /usr/local/etc/php/conf.d
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-amqp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sockets.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini

PHP API => 20190902
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,NTS
PHP Extension Build => API20190902,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => zlib.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies

# Extensions
Array
(
    [16] => mbstring
    [38] => sockets
)

PHP_INT_SIZE=8
PHP_INT_MAX=9223372036854775807
# Constants
AF_INET                       2
AF_INET6                      10
AF_UNIX                       1
AI_ADDRCONFIG                 32
AI_ALL                        16
AI_CANONNAME                  2
AI_NUMERICHOST                4
AI_NUMERICSERV                1024
AI_PASSIVE                    1
AI_V4MAPPED                   8
IPPROTO_IP                    0
IPPROTO_IPV6                  41
IPV6_HOPLIMIT                 52
IPV6_MULTICAST_HOPS           18
IPV6_MULTICAST_IF             17
IPV6_MULTICAST_LOOP           19
IPV6_PKTINFO                  50
IPV6_RECVHOPLIMIT             51
IPV6_RECVPKTINFO              49
IPV6_RECVTCLASS               66
IPV6_TCLASS                   67
IPV6_UNICAST_HOPS             16
IPV6_V6ONLY                   26
IP_MULTICAST_IF               32
IP_MULTICAST_LOOP             34
IP_MULTICAST_TTL              33
MCAST_BLOCK_SOURCE            43
MCAST_JOIN_GROUP              42
MCAST_JOIN_SOURCE_GROUP       46
MCAST_LEAVE_GROUP             45
MCAST_LEAVE_SOURCE_GROUP      47
MCAST_UNBLOCK_SOURCE          44
MSG_CMSG_CLOEXEC              1073741824
MSG_CONFIRM                   2048
MSG_CTRUNC                    8
MSG_DONTROUTE                 4
MSG_DONTWAIT                  64
MSG_EOF                       512
MSG_EOR                       128
MSG_ERRQUEUE                  8192
MSG_MORE                      32768
MSG_NOSIGNAL                  16384
MSG_OOB                       1
MSG_PEEK                      2
MSG_TRUNC                     32
MSG_WAITALL                   256
MSG_WAITFORONE                65536
PHP_BINARY_READ               2
PHP_NORMAL_READ               1
SCM_CREDENTIALS               2
SCM_RIGHTS                    1
SOCKET_E2BIG                  7
SOCKET_EACCES                 13
SOCKET_EADDRINUSE             98
SOCKET_EADDRNOTAVAIL          99
SOCKET_EADV                   68
SOCKET_EAFNOSUPPORT           97
SOCKET_EAGAIN                 11
SOCKET_EALREADY               114
SOCKET_EBADE                  52
SOCKET_EBADF                  9
SOCKET_EBADFD                 77
SOCKET_EBADMSG                74
SOCKET_EBADR                  53
SOCKET_EBADRQC                56
SOCKET_EBADSLT                57
SOCKET_EBUSY                  16
SOCKET_ECHRNG                 44
SOCKET_ECOMM                  70
SOCKET_ECONNABORTED           103
SOCKET_ECONNREFUSED           111
SOCKET_ECONNRESET             104
SOCKET_EDESTADDRREQ           89
SOCKET_EDQUOT                 122
SOCKET_EEXIST                 17
SOCKET_EFAULT                 14
SOCKET_EHOSTDOWN              112
SOCKET_EHOSTUNREACH           113
SOCKET_EIDRM                  43
SOCKET_EINPROGRESS            115
SOCKET_EINTR                  4
SOCKET_EINVAL                 22
SOCKET_EIO                    5
SOCKET_EISCONN                106
SOCKET_EISDIR                 21
SOCKET_EISNAM                 120
SOCKET_EL2HLT                 51
SOCKET_EL2NSYNC               45
SOCKET_EL3HLT                 46
SOCKET_EL3RST                 47
SOCKET_ELNRNG                 48
SOCKET_ELOOP                  40
SOCKET_EMEDIUMTYPE            124
SOCKET_EMFILE                 24
SOCKET_EMLINK                 31
SOCKET_EMSGSIZE               90
SOCKET_EMULTIHOP              72
SOCKET_ENAMETOOLONG           36
SOCKET_ENETDOWN               100
SOCKET_ENETRESET              102
SOCKET_ENETUNREACH            101
SOCKET_ENFILE                 23
SOCKET_ENOANO                 55
SOCKET_ENOBUFS                105
SOCKET_ENOCSI                 50
SOCKET_ENODATA                61
SOCKET_ENODEV                 19
SOCKET_ENOENT                 2
SOCKET_ENOLCK                 37
SOCKET_ENOLINK                67
SOCKET_ENOMEDIUM              123
SOCKET_ENOMEM                 12
SOCKET_ENOMSG                 42
SOCKET_ENONET                 64
SOCKET_ENOPROTOOPT            92
SOCKET_ENOSPC                 28
SOCKET_ENOSR                  63
SOCKET_ENOSTR                 60
SOCKET_ENOSYS                 38
SOCKET_ENOTBLK                15
SOCKET_ENOTCONN               107
SOCKET_ENOTDIR                20
SOCKET_ENOTEMPTY              39
SOCKET_ENOTSOCK               88
SOCKET_ENOTTY                 25
SOCKET_ENOTUNIQ               76
SOCKET_ENXIO                  6
SOCKET_EOPNOTSUPP             95
SOCKET_EPERM                  1
SOCKET_EPFNOSUPPORT           96
SOCKET_EPIPE                  32
SOCKET_EPROTO                 71
SOCKET_EPROTONOSUPPORT        93
SOCKET_EPROTOTYPE             91
SOCKET_EREMCHG                78
SOCKET_EREMOTE                66
SOCKET_EREMOTEIO              121
SOCKET_ERESTART               85
SOCKET_EROFS                  30
SOCKET_ESHUTDOWN              108
SOCKET_ESOCKTNOSUPPORT        94
SOCKET_ESPIPE                 29
SOCKET_ESRMNT                 69
SOCKET_ESTRPIPE               86
SOCKET_ETIME                  62
SOCKET_ETIMEDOUT              110
SOCKET_ETOOMANYREFS           109
SOCKET_EUNATCH                49
SOCKET_EUSERS                 87
SOCKET_EWOULDBLOCK            11
SOCKET_EXDEV                  18
SOCKET_EXFULL                 54
SOCK_DGRAM                    2
SOCK_RAW                      3
SOCK_RDM                      4
SOCK_SEQPACKET                5
SOCK_STREAM                   1
SOL_SOCKET                    1
SOL_TCP                       6
SOL_UDP                       17
SOMAXCONN                     128
SO_BINDTODEVICE               25
SO_BROADCAST                  6
SO_DEBUG                      1
SO_DONTROUTE                  5
SO_ERROR                      4
SO_KEEPALIVE                  9
SO_LINGER                     13
SO_OOBINLINE                  10
SO_PASSCRED                   16
SO_RCVBUF                     8
SO_RCVLOWAT                   18
SO_RCVTIMEO                   20
SO_REUSEADDR                  2
SO_REUSEPORT                  15
SO_SNDBUF                     7
SO_SNDLOWAT                   19
SO_SNDTIMEO                   21
SO_TYPE                       3
TCP_NODELAY                   1

**Comment by alexbumbacea** [comment]
The problem is with the bundle.

**Comment by alexbumbacea** [comment]
But what about offering a ConnectionFactory for url based config directly in the base lib?

**Comment by ramunasd** [comment]
Please submit issue in bundle repo. Thanks
