### ISSUE TITLE
Getting Unrecoverable error: PreconditionFailed 406, PRECONDITION_FAILED 

### ISSUE THREAD

**Issue by imaithal** [php-amqplib/php-amqplib#925]
**Version(s) affected**: v2.5.2

**Description**  
Getting error 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out

**How to reproduce**  
After Adding 'delivery_mode' => 2 started to get this error.

**Additional context**  
Getting error: Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '').
Getting this intermittently and pod gets restarted.

**Comment by ramunasd** [comment]
Error message is self explanatory - timeout during ack. Check your broker log, there should more info about this issue. Nothing to do with library itself.

**Comment by KinaneD** [comment]
Hi @ramunasd yes the error is self explanatory, but how to programmatically change the default 30 mins timeout?
The [docs](https://www.rabbitmq.com/confirms.html#consumer-acknowledgements) point to `basic_consume` but i fail to find a param for that.
I know that taping into the config file could [do](https://www.rabbitmq.com/consumers.html#acknowledgement-timeout), but i;d rather avoid that.

**Comment by lukebakken** [comment]
> Hi @ramunasd yes the error is self explanatory, but how to programmatically change the default 30 mins timeout?

You must change the value in the RabbitMQ configuration.
