### ISSUE TITLE
Heartbeat after upgrade to 3.0

### ISSUE THREAD

**Issue by pbabilas** [php-amqplib/php-amqplib#926]
Hi, I'd like to upgrade my amqp lib to v3, but it seams that heartbeat has changed, and now it checks it on consumer side also.
Now my consumer is running all the time in loop with hb ping, and new tasks are running at forks. All was working fine at v2, but in v3, hb is validate on consumer itself. So when I start fork but ping is running only at master process my last hb ping is not updating at child. And when I'm trying to send ack at fork it gets Heartbeet missing exception.

Is there any way to skip hb check at forks? Only one idea I've got is to move ack and any rabbit communication to master process, but my way has an advantage because I can decide how to react to rabbit depending at excepion etc. When I move it to master I can react only by child status code.

**Comment by ramunasd** [comment]
Support for forks is not possible by design. This library can work properly only in single process/thread mode.
