### ISSUE TITLE
composer Namescpace error

### ISSUE THREAD

**Issue by TimoFrenzel** [php-amqplib/php-amqplib#927]
Class PhpAmqpLib\Tests\Unit\Helper\Writer\Protocol091Test located in ./vendor/php-amqplib/php-amqplib/PhpAmqpLib/Tests/Unit/Helper/Protocol/Protocol091Test.php does not comply with psr-0 autoloading standard. Skipping.
Class PhpAmqpLib\Tests\Unit\AMQPWriterTest located in ./vendor/php-amqplib/php-amqplib/PhpAmqpLib/Tests/Unit/Wire/AMQPWriterTest.php does not comply with psr-0 autoloading standard. Skipping.

**Comment by andrew-demb** [comment]
Namespace was fixed 4 years ago (2.7.1+ versions) in commit https://github.com/php-amqplib/php-amqplib/commit/af88829c47900c6ae02064d67efb9edaaf331e14#diff-c5db975a4f54e6eacacd98df2dc7cac3e84bcd5ae094e13baa19e2c53e634ada

What library version do you use?

**Comment by ramunasd** [comment]
Latest version is compatible with all autoloading standards.
