### ISSUE TITLE
php5.6.9  Unable to use AMQPStreamConnection to connect RabbitServer but AMQPSocketConnection is normal 

### ISSUE THREAD

**Issue by fengahan** [php-amqplib/php-amqplib#928]
**Version(s) affected**: x.y.z
SystemOs: windows
PHP:5.6.9
RabbitServer:3.8.16 (windows)
**Description**  
php error:
-----------------
Exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with message 'The connection timed out after 3 sec while awaiting incoming data'

in D:\phpstudy_pro\WWW\api\apiCenterYii2\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Wire\AMQPReader.php:134
-------------------
rabbitmq log:
----------------
2021-07-21 20:05:40.015 [info] <0.20516.0> accepting AMQP connection <0.20516.0> ([::1]:56339 -> [::1]:5672)
2021-07-21 20:05:40.031 [warning] <0.20516.0> closing AMQP connection <0.20516.0> ([::1]:56339 -> [::1]:5672):
client unexpectedly closed TCP connection
2021-07-21 20:05:40.031 [info] <0.20518.0> Closing all channels from connection '[::1]:56339 -> [::1]:5672' because it has been closed
-----------------

**Comment by ramunasd** [comment]
We do not support PHP versions below 7.0
Also, You did not provide library version, debug info and how to reproduce the issue.

**Comment by fengahan** [comment]
> We do not support PHP versions below 7.0
> Also, You did not provide library version, debug info and how to reproduce the issue.

1.Install PHP5.6.9 on windos and then composer PHP-AMqplib

2.I used the sample code from the official website documentation, but its does‘t work when PHP turns on the OpenSSL extension

3.I tried php5.6.8 and it worked but 5.6.9 didn't work
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();

$channel->queue_declare('hello', false, false, false, false);

$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'hello');

echo " [x] Sent 'Hello World!'\n";

$channel->close();
$connection->close();
?>
```

**Comment by fengahan** [comment]
I hope you can help me find out the specific reasons @ramunasd . thanks
