### ISSUE TITLE
Can i customize the protocol from 'tcp' to anything!

### ISSUE THREAD

**Issue by magdi14** [php-amqplib/php-amqplib#936]
Hi there,
I'm trying to use the package and create a basic connection with Stream and SSL but in both cases it always appends 'tcp:/' protocol to host while i want to use 'ampqs:/' i tried both kind of connections i navigated to the source code and i saw that in the stream class there's a variable protocol equals to 'tcp' hardcoded and the ssl extend stream.

So is there anything to do to overwrite this and make the host something like 'amqps:/host'?

**Comment by ramunasd** [comment]
Just use last constructor parameter and set `$ssl_protocol` equal to `amqps`.
Please bear in mind that keep alive wont work with secure connections.
