### ISSUE TITLE
stream_socket_client(): unable to connect to ssl: connection time out

### ISSUE THREAD

**Issue by Navdeep-Jethwa** [php-amqplib/php-amqplib#937]
**Version(s) affected**: 2.0

**Description**  
I'm working on this library in my localhost it working perfect with SSL , but in the live server it will show below error.
**My server is also have SSL**

**Exception: stream_socket_client(): unable to connect to ssl://b-3fbb67d2-99cd-4109-83bf-9f0509bdab66.mq.us-east-1.amazonaws.com:5671:5671 (Connection timed out) /data/sites/web/hvheymans-vanhovebe/subsites/mmd.heymans-vanhove.be/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php 111**

```
use PhpAmqpLib\Connection\AMQPSSLConnection;
use PhpAmqpLib\Connection\AMQPSocketConnection;
use PhpAmqpLib\Exchange\AMQPExchangeType;
use PhpAmqpLib\Message\AMQPMessage;

$this->ci =& get_instance();
$this->ci->load->config('aws_config');
$this->ci->load->config('sync_community');
$config = $this->ci->config->item('aws_mq_config');
	
$exchange = $this->ci->config->item('exchange_name');
		
$queue = $this->ci->config->item('queue');
$consumerTag = $this->ci->config->item('consumer_tag');
$route_key = $this->ci->config->item('routing_key');

		
$connection = new AMQPSSLConnection($config['aws_host'], $config['aws_port'], $config['aws_user'], $config['aws_password'],'/',['verify_peer_name' => false], ['connection_timeout'=>60, 'heartbeat'=>30], 'ssl');
```
Thanks In advance

**Comment by ramunasd** [comment]
This isn't libarary issue likely. PHP itself cannot connect to secure endpoint using Your credentials and context.
Make sure You use latest library version and provide all neccessary SSL info - it depends on environment, that's why it works locally.
https://github.com/php-amqplib/php-amqplib/blob/master/demo/ssl_connection.php

**Comment by Navdeep-Jethwa** [comment]
but my endpoint is amqps url , so replace ssl with amqps still its not working and throwing below error

`Exception: stream_socket_client(): unable to connect to amqps://b-3fbb67d2-99cd-4109-83bf-9f0509bdab66.mq.us-east-1.amazonaws.com:5671 (Unable to find the socket transport "amqps" - did you forget to enable it when you configured PHP?) /opt/lampp/htdocs/mmd/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php 111`
