### ISSUE TITLE
Severity: error --> Exception: stream_socket_client(): unable to connect to

### ISSUE THREAD

**Issue by rajjagani021** [php-amqplib/php-amqplib#938]
I am trying to connect RabbitMQ using Amazon MQ. I have installed the php-amqplib and I have successfully installed the AMQP extension (Please see the attached screenshot)

![image](https://user-images.githubusercontent.com/4434991/132976351-ca8e23df-e43f-402f-9dc6-d847220b842a.png)

But when I run the command, I am getting the below error

```
Severity: error --> Exception: stream_socket_client(): unable to connect to amqps://XXXXX.mq.us-east-1.amazonaws.com:5671 (Unable to find the socket transport "amqps" - did you forget to enable it when you configured PHP?) 
/Applications/MAMP/htdocs/joris/community/mmd/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php 111
``` 

Any Idea after installing AMQP why it still not allow to connect with it. 

Any help would be appreciated. 

Thank you

**Comment by ramunasd** [comment]
This library does not require amqp extension. It's is pure PHP implementation for AMQP protocols.

**Comment by rajjagani021** [comment]
@ramunasd 

If the library doesn't require amqp extensions then why it's unable to open socket for amqp protocol while doing a connection.
Do you have any workaround for this? How can I resolve this error?

**Comment by seokman-hong** [comment]
Hi bro...
Have you resolved this issue? 

I am currently struggling with this problem...
If you did, Can you tell me how??

**Comment by coooperify** [comment]
almost 2025 an the package still doesn't allow amqps. Any solution so far? Thanks.

**Comment by lukebakken** [comment]
> almost 2025 an the package still doesn't allow amqps.

Of course it does. People can't seem to be bothered to provide _CODE_ that demonstrates the issues they are having, so we can't assist.
