### ISSUE TITLE
Auto close channels on connection close

### ISSUE THREAD

**Issue by saem** [php-amqplib/php-amqplib#94]
If I understand things correctly channels in Rabbit are a way to multiplex connections. It's my understanding that a channel without a connection doesn't really make sense.

Here https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L49 there is definitely thought given to cleaning up channels.

I think the reason why the code never got written is that the Connection itself should iterate over its channel array and close them off, since it's the aggregate and has sufficient knowledge of lifetimes.

**Comment by lukebakken** [comment]
This appears to be implemented [here](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AbstractConnection.php#L642). Closing.
