### ISSUE TITLE
RabbitMQ Consumer receives Message with empty payload/NULL from HTML POST.

### ISSUE THREAD

**Issue by ksoz** [php-amqplib/php-amqplib#947]
So, I have two different publishers, one with a simple "Hello World!" preset in a variable. The other receives from POST through html form. In PHP I'll use implode() to connect the POST array into a string, then encode and send it as a message. The backend consumes it and decodes it, only to show nothing. 

My backend says it received SOMETHING. But the text or string value isn't shown and doing a var_dump just says NULL.

The one that ends up sending nothing:
```
$connection = new AMQPStreamConnection($address, 5672, $user, $pass);
$channel = $connection->channel();
$channel->queue_Declare('login', false, false, false, false);

$data;
function setMessage($arr) {
    $data = implode('', array_slice($arr));
    json_encode($data);
    var_dump($data);
    if (empty($data)) {
        echo 'Please input your email and/or password.';
        return;       
    }
    return;
}
$msg = new AMQPMessage($msg);
$channel->basic_publish($msg, '', 'login');

echo 'Validating Login....';

$channel->close();
$connection->close();

```

And this is the one that works fine:
```
$connection = new AMQPStreamConnection($address, 5672, $user, $pass);
$channel = $connection->channel();
$channel->queue_declare('login', false, false, false, false);

$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'login');

echo " [x] Sent 'Hello World!'\n";

$channel->close();
$connection->close();
```

**Comment by ramunasd** [comment]
So You prove that library works fine and the bug is in the code which handles form? :) Then there is nothing to do with the library.
