### ISSUE TITLE
stream_select(): unable to select [9]: Bad file descriptor (max_fd=444)

### ISSUE THREAD

**Issue by liuyong888** [php-amqplib/php-amqplib#955]
Environments
  
  I encountered an error when using php-amqplib v2.9.1:
  `stream_select(): unable to select [9]: Bad file descriptor (max_fd=484)`
   OS: windows10
   php: 5.6.9
   php-amqplib: v2.9.1
![image](https://user-images.githubusercontent.com/45752479/139592656-884aa545-8c04-40ce-9d9d-21fee68f456a.png)
![image](https://user-images.githubusercontent.com/45752479/139592893-49b4e996-dddc-4701-9b1a-9b2de154cb1e.png)

It worked when I lowered the version to 2.7.0.
help
@ramunasd @lukebakken

**Comment by ramunasd** [comment]
We do not support PHP versions 7.0 and below.
