### ISSUE TITLE
Error: Uncaught Error: Call to a member function send_channel_method_frame

### ISSUE THREAD

**Issue by akang1** [php-amqplib/php-amqplib#956]
Hello,

We currently have a RabbitMQ cluster of 3 nodes. 

On each node, we have php consumers that run in the background and consumes messages from specific queues as messages come in to the queues. For example, we have 3 queues called `external_post.pserver`, `external_post.xxxx`, and `external_post.yyyy` and we have 3 consumers for each queue. The consumers send out emails if the consumers fail to start or get killed.

One of the nodes had an issue on the host side and ungracefully got shut down (around 12:30am) and then came back up and rejoined the cluster (around 12:40am). The consumers on node3 got automatically started on boot up as we have it set to start them automatically.

We did not get any email alerts regarding the consumers on node3 after the reboot. 

However, out of nowhere starting 4:40am on node3, we started getting the following email alerts about consumers getting killed for `external_post.pserver`. This caused all the messages for this specific queue to get backed up and not get consumed.

```
Error: Uncaught Error: Call to a member function send_channel_method_frame() on null in /var/iForm-MQ/composer/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:126
Stack trace:
#0 /var/composer/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(446): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#1 /var/connection/RabbitMq.php(72): PhpAmqpLib\Channel\AMQPChannel->queue_declare('aliveness-test', true)
#2 /var/connection/Connection.php(59): RabbitMq->validateConnection()
#3 /var/connection/RabbitMq.php(84): Connection->validateAndRetryConnection(true)
#4 /var/record_post.php(173): RabbitMq->queueDeclare('external_post.p...', 'external_post.b...', 'pserver.1800', Array)
#5 [internal function]: {closure}(Object(PhpAmqpLib\Message\AMQPMessage))
#6 /var/composer/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(720): call_user_func(Object
```

Around 8:00am, when trying to debug and fix this issue, every time I would start the consumers for `external_post.pserver`, the consumers would continue fail with the same error as above.

I noticed that none of the other consumers for other queues were having this issue.

I thought maybe the queue itself was corrupted somehow, so I decided to delete and recreate the queue (after I shoveled the messages to a temp queue first).

After that, I was able to successfully start the consumers for `external_post.pserver` while the queue was empty but after shoveling the messages back to the queue, it caused the consumers to get killed with the same error.

As a last report, I decided to eventually create a a whole new queue and start consumers on that new queue instead. Interestingly the consumers for the new queue did not get killed with the same error when the same messages were shoveled to the new one.

Since I am completely out of ideas, I thought I'd post the error here to see if anyone could help at all.

**Comment by ramunasd** [comment]
@akang1 thanks, but all that info is unuseable and useless. Sorry, but we cannot provide any help having only that info.
Please, next time fill issue template properly or ask for help in mailing list.
