### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by sartor** [php-amqplib/php-amqplib#959]
There is version limit in composer.json now  (^7.0|~8.0.0) and probably deprecations and notices in code.

**Comment by ramunasd** [comment]
All known issues were fixed in #953
Please report exact issues if You know. Meanwhile PHP8.1 is not released yet.

**Comment by sartor** [comment]
Thank you, waiting for release!

**Comment by dshemin** [comment]
PHP 8.1 is released. Are there any plans to support it?

**Comment by pottertech** [comment]
PHP 8.2 is released. Are there any plans to support it?

**Comment by liborm85** [comment]
PHP 8.2 is supported.
