### ISSUE TITLE
Got an error when using php-amqplib with rabbitmq-bundle

### ISSUE THREAD

**Issue by scourgen** [php-amqplib/php-amqplib#96]
my php-amqplib version is v2.1.0

I was running a command that send message to a queue. but I've got this error:

PHP Notice:  fwrite(): send of 19 bytes failed with errno=32 Broken pipe in /var/www/www.test.com/shared/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 61

**Comment by lukebakken** [comment]
Closing, see @gjuric's [comment](https://github.com/php-amqplib/php-amqplib/issues/96#issuecomment-66489212).
