### ISSUE TITLE
Huge disk space and memory usage in using the library

### ISSUE THREAD

**Issue by mathewvp** [php-amqplib/php-amqplib#962]
When using phpamqp library and using persistent mode for delivery of messages, the messages are getting written under "msg_store_persistent" folder but the size is huge, around 3.8 GB for 4800 messages. When using golang library and using persistent mode, using the same payload, the messages are getting written to "queues" folder (still persistent, I restarted AMQP server and tested) and the file size is relatively very small, 49MB for 43000 messages. Why is php amqp library writing to a different folder with such huge size?

**Comment by ramunasd** [comment]
Client cannot affect configuration of broker somehow, neither folders for storage. Looks like there is something wrong either with broker/exchange/queue configuration or another library.
You consume as much storage as message payload weight.

**Comment by mathewvp** [comment]
Payload is around 1.1 KB . 1.1 KB x 43000 messages is 47 MB which is correct when using golang library. But when using php library 1.1 KB x 4800 messages  takes 3.8 GB when it should be around 5.28 MB

**Comment by ramunasd** [comment]
@mathewvp why do You think it's a library issue? Please prove it before submitting an issue. Also, we need all steps to reproduce that issue, otherwise nobody can help You.

**Comment by mathewvp** [comment]
Php code

```
$exchange = new \AMQPExchange($this->_channel);
$exchange->setName('xxx.push-notification.exg');
$exchange->setType(AMQP_EX_TYPE_DIRECT);
$exchange->setFlags(AMQP_DURABLE);
// declare method deprecated. ref http://php.net/manual/fa/amqpexchange.declare.php
$exchange->declareExchange();
$this->_exchange = $exchange;

$queue = new \AMQPQueue($this->_channel);
$queue->setName('xxx.push-notification.que');
$queue->setFlags(AMQP_DURABLE);
$args = array('x-ha-policy' => 'all');
if ($hasDeadLetter) {
$args['x-dead-letter-exchange'] = 'xxx.err.exg';
$args['x-dead-letter-routing-key'] = $queueName;
}
$queue->setArguments($args);
$queue->declareQueue();
$queue->bind('xxx.push-notification.exg', $routingKey);

$params = array('content_type' => 'text/json', 'delivery_mode'=>2);
$exchange->publish($msg, $routingKey, false, $params);
```

Golang code

```
conn, err := amqp.Dial(fmt.Sprintf("amqp://%s:%s@%s:%s/", "guest", "guest", "xx.xx.xx.xx", "5672"))
if err != nil {
fmt.Println(err)
return
}

ch, err := conn.Channel()
if err != nil {
fmt.Println(err)
return
}

out = []byte(`{"command":"sendPushNotification","data":{"userId":"0","profileId":"2701","message":"xxx xxx xxx","section":"general","extraParams":[{"key":"img","val":"aHR0cHM6Ly9zdGWLm00bWFycnkuaW4vdWkvaW1hZ2VzL2xvZ28uZGVza3RvcE5vdGlmaWNhdGlvbi5wbmc="},{"key":"webUrl","val":"https:\/\/lens.xxx.in\/click?evt_id=14d9edf5-7268-463e-8141-03aacf536e65&evt_nm=Clicked+Desktop+Notification&evt_typ=generic&app_id=xxx-jobs&eml_sub=&usr_did=2701&cpg_sc=&cpg_md=&cpg_nm=&cpg_cnt=&cpg_tm=&link_txt=expo+notification+link+clicked&em_type=&cpg_subcode=2021-11-25&cpg_dt=&url=https%3A%2F%2Fstag-fe.xxx.in%2Fsubscription%2FchoosePackage%3Futm_source%3D%26utm_medium%3D%26utm_campaign%3D%26utm_content%3D%26utm_term%3D%26utm_subcode%3D2021-11-25%26evt_typ%3Dgeneric"}],"customFields":[{"key":"pixelTrackerUrl","val":"https:\/\/lens.xxx.in\/i?evt_id=60b675c8-f16d-4224-b3c1-a0b92dccb011&evt_nm=Viewed+Desktop+Notification&evt_typ=generic&app_id=xxx-jobs&eml_sub=&usr_did=2701&cpg_sc=&cpg_md=&cpg_nm=&cpg_cnt=&cpg_tm=&link_txt=&em_type=&cpg_subcode=2021-11-25&cpg_dt="},{"key":"title","val":"xxx team is here in xxx!"}]}}`)

err = ch.Publish("xxx.push-notification.exg", "*", false, false, amqp.Publishing{
ContentType: "text/json",
Body: out,
DeliveryMode: amqp.Persistent,
})
```

same payload used in both cases.

**Comment by mathewvp** [comment]
> why do You think it's a library issue? 

Because using the same code and configuration using two different libraries produces two outputs.

**Comment by ramunasd** [comment]
Why do You think those snippets produces same messages? Have You tried to debug actual data frames? BTW, it's not enough to reproduce the issue. Please prepare whole environment. Can You setup docker images?

**Comment by ramunasd** [comment]
Also, this library does not have such classes as `\AMPQQueue` and `\AMQPExchange`.
Perhaps You are using PHP extension? That's completely another library. Please report issues there.

**Comment by mathewvp** [comment]
> Why do You think those snippets produces same messages? 

The consumer is stopped, I can retrieve the message from rabbitmq console and see the payload. And the payload submitted is copy pasted in both scripts.

> That's completely another library. Please report issues there.

Sorry about that.

**Comment by lukebakken** [comment]
This issue turned out to be an error in the user's code - https://github.com/rabbitmq/amqp091-go/discussions/28#discussioncomment-1743665
