### ISSUE TITLE
StreamIO.php line 181: Error receiving data

### ISSUE THREAD

**Issue by Satheez** [php-amqplib/php-amqplib#964]
**Version(s) affected**: 3.1.1

**Description**  
In StreamIO.php line 181: Error receiving data

I've tried with "Amazon MQ" & "cloudamqp" but all the time, TCP connection is failing with the above error.

**How to reproduce**  
php artisan queue:work or php artisan rabbitmq:consume
<img width="236" alt="messaging_service –  env 2021-12-13 12 PM-18-57" src="https://user-images.githubusercontent.com/11453046/145765471-bb0e4832-a9ca-49b0-8b84-b7124d54c322.png">

**Additional context**  
Used ub Laravel/Lumen version: 8.3.2
Note: I've added the queue configuration as per the document and added the correct credentials to the .env file

**Comment by ramunasd** [comment]
So this exception happens when `fread()` returns failure. We cannot tell the reason why it happens from provided information.
Please report PHP version, stack trace and steps how we could reproduce this issue.

**Comment by Satheez** [comment]
Thanks @ramunasd 
With further investigation, it fails due to 'AWS MQ' SSL key
