### ISSUE TITLE
PhpAmqpLib\Exception\AMQPInvalidFrameException  Invalid frame type 21

### ISSUE THREAD

**Issue by tijanidevit** [php-amqplib/php-amqplib#999]
An uncaught Exception was encountered
Type: PhpAmqpLib\Exception\AMQPInvalidFrameException

Message: Invalid frame type 21

Filename: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php

Line Number: 600

Backtrace:

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
Line: 651
Function: wait_frame

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php
Line: 235
Function: wait_channel

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php
Line: 352
Function: next_frame

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
Line: 264
Function: wait

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php
Line: 236
Function: connect

File: /home/vagrant/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php
Line: 63
Function: __construct

**Comment by ramunasd** [comment]
Any tips how to reproduce? @tijanidevit 
Connection settings, library, php version, debug info?

**Comment by PAG-Erik** [comment]
Hey, I'm with the same problem. I'm using the PHP 8.1.3, latest version of php-amqplib and trying to do the Hello World tutorial from:
https://www.rabbitmq.com/tutorials/tutorial-one-php.html

**Comment by ramunasd** [comment]
apparently wrong connection options, either unsupported protocol or wrong port.

**Comment by wweaver** [comment]
What were the invalid connection options? I'm trying to upgrade from an old version of rabbitmq from 2015 to the latest Amazon MQ RabbitMQ implementation and getting this error. Haven't found a solution.

**Comment by kinjalpadhiyar7** [comment]
Is there any solution for this yet ? Looks like this issue still occurs after I tried to update "php": from "7.3  to 8.0" and  "laravel/framework" from "8.75 to 9.0" and had to user RABBITMQ_PROTOCOL=ssl instead of RABBITMQ_CONNECTION_CLASS=\PhpAmqpLib\Connection\AMQPStreamConnection as in the older version of Laravel it does not exist anymore.
